### ISSUE TITLE
Progress bar detail gets lost with quality

### ISSUE THREAD

**Issue by duarteframos** [NickeManarin/ScreenToGif#1]
Heard you were trying to move away from Codeplex to Github so I'll try to post issue here.

Not sure if this is something solvable without increasing file size or save quality, but see the GIF recorded [here](http://blender.stackexchange.com/a/60349/19307)
My guess is the GIF compression ate away the detail of the progress bar, making it look fragmented or broken. It looked fine in the preview before saving

This release is great so far :)

**Comment by NickeManarin** [comment]
Your guess is right. The neural quantizer (NeuQuant) algorithm transforms 24 bits images to 8 bits images (256 colors).

Since the bar increase it self piece by piece, the algorithm only takes into account a few number of pixels per frame. The other pixels that are changing take more "space" than the piece of the bar.

So the bar color information os lost when there's too much info per frame. :(

**Comment by duarteframos** [comment]
Ah that's too bad, but I suspected as much.
I use ScreentoGif mainly to help users out over Blender Stack exchange and upload sizes are limited to 2Mb there, so file sizes already very tight without increasing image quality.

Anyway thanks for the reply, keep up the great work.

**Comment by NickeManarin** [comment]
I created from scratch a new encoder that avoids this bug. This new encoder lacks the current NeuQuant (color quantitizer) but I plan to improve with other color quantization algorithms.

**Comment by duarteframos** [comment]
Wow you are tireless. That is great news, curious to see how it preforms.
I'll be keeping an eye on this :+1:

**Comment by sirtet** [comment]
Could a solution be to first add a background stripe, and let the progressbar run on that?

**Comment by NickeManarin** [comment]
No, the problem starts with gif encoder (the color quantization).

**Comment by NickeManarin** [comment]
I fixed a bug related to this issue, #79

**Comment by NickeManarin** [comment]
#79

**Comment by NickeManarin** [comment]
There's a new color quantization algorithm almost ready for the encoder 2.0.

**Comment by duarteframos** [comment]
Yeah, cool! Looking forward to seeing it in action

**Comment by NickeManarin** [comment]
Previous (1.5 MB):
![taurm](https://user-images.githubusercontent.com/14798947/28759783-a4bfc474-7577-11e7-9fc5-2bd71c62f8a1.gif)


New (1.11 MB):
![256](https://user-images.githubusercontent.com/14798947/28759770-71b0adfa-7577-11e7-9177-c9e6306802c9.gif)

I noticed the color banding, but at least the progress bar is alright.

**Comment by duarteframos** [comment]
Wow this is absolutely fantastic, both improved image quality and reduced file size!
Banding is barely noticeable at all, and quite an acceptable compromise for the quality gains.

This will make long GIFs a lot easier to watch. Thanks a lot! :)
