### ISSUE TITLE
[Feature request] 2.5 version small feature requests

### ISSUE THREAD

**Issue by Kristinita** [NickeManarin/ScreenToGif#100]
### 1. Folder for project saving

**Actual behavior**: I record my video → `Save as project` → GIF save to Desktop by default. I need manually select another location for projects files each time.

**Expected behavior**:
1. Projects save to `ScreenToGIF/Project` folder by default.
2. User can set in `Options` location for project files.

### 2. Hotkey for Discard command

**Actual behavior**: I record video → `Pause` → I need to click to `Discard` use mouse.

**Expected behavior**: I record video → `Pause` → I may click to `Discard` use hotkey.

### 3. More keys for hotkeys

**Actual behavior**: `Options` → `Keyboard Shortcuts` → I may select <kbd>F1—F12</kbd> hotkeys for ScreenToGIF commands.

**Expected behavior**: `Options` → `Keyboard Shortcuts` → I may select more hotkeys. I have <kbd>F1—F12</kbd> shortcuts in applications, which I record, so I get conflicts. It would be nice, if would be possible use <kbd>Super</kbd> key for hotkeys, because shortcuts with <kbd>Super</kbd> key seldom used in applications.

### 4. Optional time for pre start countdown

**Actual behavior**: if I check `Use a pre start countdown` in Options, I have 3 seconds for pre start, I don't can change pre start time. But I do not always have time to prepare my workspace in 3 seconds. For example, [**KeypressOSD**](https://autohotkey.com/boards/viewtopic.php?t=225) keys display more than 3 seconds, and I need edit my first frames, that remove unexpected KeypressOSD displayed keys into GIF.

**Expected behavior**: for example, I want 5 seconds for pre start. `Options` → `pre start countdown time` → I can select 5 seconds.

Thanks.

**Comment by NickeManarin** [comment]
**1)** That's a nice idea. Maybe I should expand that to all kinds of file types? Remember each location individually for gifs, videos, projects, images...

**2)** and **3)** Ready for the next release :D

![image](https://cloud.githubusercontent.com/assets/14798947/23827504/2274a194-0694-11e7-8070-69a3e7c418dc.png)

**4)** Working on it ;)

**Comment by Kristinita** [comment]
> That's a nice idea. Maybe I should expand that to all kinds of file types? Remember each location individually for gifs, videos, projects, images...

Yes, it's a nice idea!

We wait a new release.

Thanks.

**Comment by NickeManarin** [comment]
**1)** Done. The app will remember the latest selected location/filename/extension for each kind of **Save As** type.

Ready for v2.8 when released.

**Comment by K0media** [comment]
> **1)** Done. The app will remember the latest selected location/filename/extension for each kind of **Save As** type.
> 
> Ready for v2.8 when released.

Can we have more hotkeys for editor tools too?

Like these:
## Image
R for Resize
C for Crop
M to Spin/Mirror
S for Subtitles
O for Outlined text
F for Geometric forms
P for Progress indicator
B for Mouse clicks
D for Drop shadow
H for Hide/Blur
W for Watermark

T for Transitions

## Edit
**I for Replace (time interval)**
PgUp/PgDn for moving left/right
Ctrl+I to Invert
Ctrl+G to go to

And to report a small "bug"... When you delete some frames or apply effects to them, it jumps back to the beginning of the recording. Would you fix that?

And, at last but not the least... I'd like the feature to view those keyboard shortcuts next to each item (faded, if possible).
