### ISSUE TITLE
[Suggestion] Insert recording to an existing record.

### ISSUE THREAD

**Issue by edwinyzh** [NickeManarin/ScreenToGif#1008]
Assume I have recorded and edited a recording of several minutes, than I found something is missing, but I don't want to re-record and re-edit everything.

It'll be great if I can just start a recording without closing the current project and insert the newly recorded frames into the current position of the current project. 

I hope it makes sense, this is really a great project and I appreciate your excellent work!

**Comment by NickeManarin** [comment]
Hi, if I understood correctly, this feature already exists.

![image](https://user-images.githubusercontent.com/14798947/143791303-2df7c3a4-06da-4c66-b130-c28c37a3c4db.png)

**Comment by edwinyzh** [comment]
> Hi, if I understood correctly, this feature already exists.
> 
> ![image](https://user-images.githubusercontent.com/14798947/143791303-2df7c3a4-06da-4c66-b130-c28c37a3c4db.png)

Oh my bad! It's so obvious but I didn't even notice it! Thank you!
