### ISSUE TITLE
[Feature Request] Upload to X instead of having to  save as

### ISSUE THREAD

**Issue by Partixel** [NickeManarin/ScreenToGif#101]
Would encode to a temp directory or whatever and then remove it once uploaded.

Would be nice if it supported Imgur, gfycat, etc

**Comment by SoftwUser** [comment]
We don't need another ShareX, IMHO.

**Comment by Partixel** [comment]
Pretty much every gif I make goes straight on imgur, it's the only thing missing from this great app :(

**Comment by SoftwUser** [comment]
Not that I do not understand this request. But see: It starts with Imgur, than the next one comes and wants GDrive, AS3, DropBox, Sendspace.... and so on and so on...
Just my vote: Let's keep that out.
But it is of course up to @NickeManarin to decide where he wants to go...

**Comment by NickeManarin** [comment]
@SoftwUser I understand that I should focus on some other primary feature requests and bug fixes.

@Partixel Your feature request is valid and it's on my personal to-do list, on the other hand, there's some key features that I need to implement first.

**Comment by positr0nic** [comment]
My +1 to this idea, I like what **[pastebinit](https://github.com/skorokithakis/pastebinit)** does but for image upload services instead.

The problem for my case where this would be helpful because some gifs of 1.5MB and larger cant be attached to most forum boards, so getting a capture saved/uploaded and a direct link returned to clipboard would be ideal and a time saver.

**Comment by Partixel** [comment]
Yeah, that's what I use i for. :)

**Comment by lafe** [comment]
In my opinion, this would be a great addition if it can be implemented using a plugin infrastructure. In this case, users can install the desired uploaders if they need one. The community can provide the necessary uploaders (I am thinking about an upload directly into our TFS to help with bug reports).

**Comment by NickeManarin** [comment]
This feature was implemented with v2.11, but it's not mature yet (it only supports Imgur and Gfycat). 

With time, I'll implement more type of services with the help of comunity.
