### ISSUE TITLE
[Bug] Region command line option doesn't work

### ISSUE THREAD

**Issue by highend** [NickeManarin/ScreenToGif#1010]
Hi,

I'm on v2.34.1 (portable) on Windows Server 2019

The region option (/r, -r, etc.) doesn't work (here).

```
ScreenToGif.exe -r 2198,64,1281,929
```

Should open ScreenToGif on my second monitor (both monitors use a 1920x1200 resolution) to be able to capture the content of a VMware machine.

Instead ScreenToGif opens on the last remembered position (if the option under Recorder - Other is ticked) or centered on the first monitor (if that option is unticked).

**Comment by NickeManarin** [comment]
Hi, the issue here is that this option is only working when you set up with along with the option `-open`.
I'm going to remove that requirement.
