### ISSUE TITLE
macOS version

### ISSUE THREAD

**Issue by rogeriotaques** [NickeManarin/ScreenToGif#1011]
Hey! Any plans for releasing a macOS version of ScreenToGif?

**Comment by NickeManarin** [comment]
Yes, but I need to get a macOS device first. ;) 
Not cheap where I live.

If you known somebody wishing to help me during the start phase of the implementation, just message me.
I'm thinking in using Xamarin.mac or similar tech stack.

**Comment by rogeriotaques** [comment]
Sounds good, @NickeManarin! Thank you for getting back to me.

I'll check around and suggest people contribute to your project. 😉
