### ISSUE TITLE
UI is invisible (but interactable) if RDP session is open. 

### ISSUE THREAD

**Issue by HYBRID-BEING** [NickeManarin/ScreenToGif#1015]
For some reason, when i open RDP session, UI starts behaving really weird. For example, this is how it looks when i start STG:
![изображение](https://user-images.githubusercontent.com/1691231/144023919-a4517f8a-6c50-41dd-b767-8b0d7f830264.png)
Here i hold mouse over the record button, showing tooltip. I can click all buttons, and even record stuff, but when editor opens it looks like this:
![изображение](https://user-images.githubusercontent.com/1691231/144024116-66d39cff-7748-453d-b47d-e997d98f7eef.png)
As soon as i close RDP session and refresh STG window (by maximizing/minimizing, for example), UI gets displayed normaly.

**Comment by NickeManarin** [comment]
That's strange. Try disabling hardware acceleration in Options > Application.

**Comment by HYBRID-BEING** [comment]
That helped, everything seems to be in order now. Oh, forgot to mention, but just in case, i'm using https://github.com/stascorp/rdpwrap.
