### ISSUE TITLE
Korean Translation

### ISSUE THREAD

**Issue by daanta-real** [NickeManarin/ScreenToGif#1017]
I found there is no Korean translation in this loved software.
Can I help your software to get many Korean users use easily with Korean translation?

I'm a Korean so I can translate the english menus, buttons, etc all of things to Korean.
But I don't know how, so I need to know how to do that first.

If anyone is interested in this please notify me how to do translation and submit the results.
Sorry for my short Enligsh.

**Comment by NickeManarin** [comment]
Hi, there is a Korean translation for this app, but it's not complete (it was not updated).

The website and installer are missing the translation.
To help visit these links:

https://github.com/NickeManarin/ScreenToGif/wiki/Localization
https://github.com/NickeManarin/ScreenToGif/wiki/Localization-(Website)
https://github.com/NickeManarin/ScreenToGif/wiki/Localization-(Installer)

Thanks!
