### ISSUE TITLE
Previous versions support overwriting. New versions do not support overwriting files with the same name.

### ISSUE THREAD

**Issue by 1015770492** [NickeManarin/ScreenToGif#1018]
Can you add a default option to allow overwriting files of the same name for users to open manually?

**Comment by NickeManarin** [comment]
Do you have the option to overwrite file enabled?

**Comment by NickeManarin** [comment]
![image](https://user-images.githubusercontent.com/14798947/145403417-b33ee573-ad61-4b07-9229-cff6fae5cf7b.png)

**Comment by NickeManarin** [comment]
Hi @1015770492, do you still have the issue?

**Comment by 1015770492** [comment]
well,it is good.
