### ISSUE TITLE
ScreenToGif crashes when importing an animated GIF file into the Editor

### ISSUE THREAD

**Issue by jonathanlinat** [NickeManarin/ScreenToGif#102]
Just opened the ScreenToGif's Editor, clicked on _Load_ icon, picked up an animated GIF image downloaded from Google Images and then finally crashes.

![ScreenToGif's Editor crashes](https://image.ibb.co/jepNfa/screentogif_editor_crashes.gif)

Here, my log file: [17_03_11.txt](https://github.com/NickeManarin/ScreenToGif/files/836257/17_03_11.txt)

**Comment by NickeManarin** [comment]
Apparently, the property "TemporaryFolder" was/is empty. Is this the first time that you open the app?

Could you just open and close the Recorder window? This setting is set to a default value if not present or empty when you open the recorder (screen, webcam or board recorder).

Anyway, thanks for the feedback. I fixed this by adding the same check to the initialization of the Editor.

    #region Temporary folder
    
    //If never configurated.
    if (string.IsNullOrWhiteSpace(UserSettings.All.TemporaryFolder))
        UserSettings.All.TemporaryFolder = Path.GetTempPath();
    
    #endregion

**Comment by NickeManarin** [comment]
You can also pick a custom location to store the temporary files by opening `Options > Temporary Files > Location Folder`.
