### ISSUE TITLE
Crop dimensions incorrectly scaled when windows UI scaling set

### ISSUE THREAD

**Issue by kavika13** [NickeManarin/ScreenToGif#103]
When I have my Windows scale settings set to 150%, the crop dimensions show up as 1.5x the value they are supposed to be.

Repro steps (Windows 10):
1. Open Cortana/Search (Windows key)
2. Type "Display Settings" and open the first result
3. "Change the size of text, apps, and other items:" - change to 150%
4. Reboot (could just log off and log back on supposedly)
5. Launch ScreenToGif
6. Open the editor
7. Drag/drop a gif onto the editor
8. Switch to the "Image" tab
9. Click "Crop"
10. Drag corners of crop tool to upper left and lower right of image

Expected:
- Image extents should be the width & height of the original gif (in my case 367x255)
- The image should fill the entire crop extents in the "Preview" (WYSIWYG) area
- The entire image should show in the "preview" (text entry) area

![here's a picture of "expected"](https://cloud.githubusercontent.com/assets/439185/23876637/b064d7fe-07fb-11e7-9b7f-b74071006551.png)

Actual:
- Image extents are the width & height of the original gif times 1.5 (in my case, 551x383)
- The image shows up as ~2/3 the crop extents in the "Preview" (WYSIWYG) area
- The entire image shows up in the "preview" (text entry) area - note: this matches expected behavior

![Here's a picture of "actual"](https://cloud.githubusercontent.com/assets/439185/23871717/d19982d4-07e8-11e7-92e9-9add85bc2d42.png)

**Comment by NickeManarin** [comment]
Thanks for the feedback.

The viewer is not fully synced with the visual aid (drag elements) and the numerical boxes of the crop feature.

Working on it.

**Comment by NickeManarin** [comment]
Done, fixed.

Now I need to test if I didn't break anything else. Would you kindly help me out with this task?

I have a 1080p monitor in a 15' screen, it is quite hard for me to work with that DPI factor.

Anyways, I'll attach the executable with this bug fix. (also there's two features ready for the next release)

[ScreenToGif 2.7 Preview.zip](https://github.com/NickeManarin/ScreenToGif/files/840036/ScreenToGif.2.7.Preview.zip)

**Comment by NickeManarin** [comment]
It looks like all other features that touch the image got broken with this fix for the crop. It should be easy to fix all.
