### ISSUE TITLE
2.35.2 issue

### ISSUE THREAD

**Issue by szmabcd** [NickeManarin/ScreenToGif#1031]
2.35.2 open issue

![QQ截图20211226102832](https://user-images.githubusercontent.com/38176269/147397425-0182f8de-f45c-4b87-9664-3d6bfa5a4346.png)

**Comment by NickeManarin** [comment]
You should download the .NET 6 Desktop Runtime.

![image](https://user-images.githubusercontent.com/14798947/147424342-00a9f637-9ea7-4780-b411-72e79f552ddd.png)

Did you download that one?

**Comment by szmabcd** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NickeManarin/ScreenToGif"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月27日(星期一) 上午8:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NickeManarin/ScreenToGif] 2.35.2 issue (Issue #1031)





 
You should download the .NET 6 Desktop Runtime.
 

 
Did you download that one?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NickeManarin** [comment]
Hi, your answer is broken.

**Comment by szmabcd** [comment]
screentogif如何录制全屏，thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NickeManarin/ScreenToGif"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月27日(星期一) 晚上11:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NickeManarin/ScreenToGif] 2.35.2 issue (Issue #1031)





 
Hi, your answer is broken.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by szmabcd** [comment]
hi，


&nbsp; &nbsp; 有两个问题请改进下，谢谢！
&nbsp; &nbsp; 1、录像看起来很模糊

&nbsp; &nbsp; &nbsp;


&nbsp; &nbsp; 2、制作gif动画时请支持多尺寸图片

&nbsp; &nbsp; &nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NickeManarin/ScreenToGif"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月31日(星期一) 中午12:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NickeManarin/ScreenToGif] 2.35.2 issue (Issue #1031)





 
Closed #1031.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
