### ISSUE TITLE
[Bug] 2.35.2 ScreenToGif (.stg) saving error

### ISSUE THREAD

**Issue by tony** [NickeManarin/ScreenToGif#1035]
**Describe the bug**
Saving project files has an error after 2.35 update.

Normal encoding of video (e.g. .webm, .mp4) works as anticipated.

**To Reproduce**
1. Create a recording
2. Save As
3. Project
4. Default (.stg)
5. Click Save

"Could not find file 'DriveLetter:\Users\username\APpData\Local\Temp\ScreenToGif\Recording\<date>\Project.json'."

**Expected behavior**
Should save project files at it did before

**Screenshots**

![image](https://user-images.githubusercontent.com/26336/147518018-3750aaa3-385d-4a3c-8347-b5ffd3afd02a.png)

Temp directory
![image](https://user-images.githubusercontent.com/26336/147518198-a79ef362-dd1b-49c0-b7c5-494418c7ce84.png)
![image](https://user-images.githubusercontent.com/26336/147518215-c966c359-1cdb-40d1-bfc2-91c3ef2f917c.png)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Version 2.35.2
 

**Additional context**
- 2.34 worked
- Fails with both No compression
- Fails with .zip and .stg
- The directory for `Recording/<datetime>` exists and it has images and `Encode <>` folders, but no `Project.json`
- I've only tried 2.35.2, not 2.35.0 or 2.35.1

**Comment by NickeManarin** [comment]
Hi, just tested in here and it worked normally.

Before trying to export as a project, what steps did you take?

**Comment by tony** [comment]
@NickeManarin It was my first attempt after upgrade

I'm not recreating it now either...

Perhaps it's overcome by evens on my system?  Can I close? (I can recreate/reopen if I bump into again?)

P.S. Thank you for checking into this!  I hope things are going well!

**Comment by NickeManarin** [comment]
Any anti-virus triggering some false positive and removing the file?
Usually that file is only removed by discarding the whole project, manually or via the cleaning task.

Yes, you can close it and if it ever appears again, you can just reopen this ticket.

Thank you for the detailed feedback! Have a nice day.

**Comment by tony** [comment]
No antivirus that I can see

I am not sure why it happened 🤷 

If I get it happening again I will try to geta recreation

Have a good evening. I will donate again some time also. I am no longer on Patreon (due to leaving the platform, not dissatisfaction with the ScreenToGif or you)

**Comment by tony** [comment]
Actually, nevermind it happened again

**Comment by tony** [comment]
😆

**Comment by NickeManarin** [comment]
:O

**Comment by NickeManarin** [comment]
Ok, let's check, were did you get the a from? Github/Website, Store, chocolatey?

**Comment by tony** [comment]
Is there a way I can collect a debug report?  

FIle: `C:\Users\username\Documents\ScreenToGif`
My filename is like `?yyyy-MM-dd HH-mm-ss? - PR 1993- master @ 712eabc`

**Comment by tony** [comment]
via Updater.

**Comment by tony** [comment]
Before that from the website, .msi file.  

2.34

Then I upgraded via the updater

**Comment by NickeManarin** [comment]
If some error was triggered, it would be located at AppDirectory / ScreenToGif / Logs

**Comment by tony** [comment]
Do you skype or telegram? I can screenshare with you

**Comment by NickeManarin** [comment]
Yes, that or discord.

**Comment by NickeManarin** [comment]
Thanks for the help.
A new version should be available tomorrow.

**Comment by tony** [comment]
Thank you for looking into this on short notice. Looking forward to it
