### ISSUE TITLE
[Feature request] Transition length and delay parameters

### ISSUE THREAD

**Issue by Kristinita** [NickeManarin/ScreenToGif#104]
### 1. Summary

It would be nice, if would be possible set `Transition length` and `Transition delay` parameters.

### 2. Actual behavior

I record any GIF → I edit GIF → <kbd>Ctrl+Alt+T</kbd> → I set `Transition length` value is `10x` for me → <kbd>Alt+E</kbd> → I get 10 new frames by length `66ms`.

I close and reopen ScreenToGIF → I record any GIF → I edit GIF → <kbd>Ctrl+Alt+T</kbd> → I must set `Transition length` value is `10x` again.

### 3. Expected behavior

In `settings.xaml` file I set `Transition length = 10`, `Transition delay = 150`.

I record any GIF → I edit GIF → <kbd>Ctrl+Alt+T</kbd> → `Transition length` value is `10x` for me → <kbd>Alt+E</kbd> → I get 10 new frames by length `150ms`.

I close and reopen ScreenToGIF → I record any GIF → I edit GIF → <kbd>Ctrl+Alt+T</kbd> → my `Transition length` value is `10x`.

Thanks.

**Comment by NickeManarin** [comment]
Thank you for the ideas :D

Done! Ready for the next release.
Here are the settings:

    <s:Int32 x:Key="FadeTransitionLength">2</s:Int32>
    <s:Int32 x:Key="FadeTransitionDelay">66</s:Int32>
    <s:Int32 x:Key="SlideTransitionLength">2</s:Int32>
    <s:Int32 x:Key="SlideTransitionDelay">66</s:Int32>
