### ISSUE TITLE
[Feature Request] Make it more portable

### ISSUE THREAD

**Issue by stla** [NickeManarin/ScreenToGif#1044]
Hello,

  I wanted to upgrade **ScreenToGif** (my favorite GIF recorder) but now it requires **NET**. I don't have admin rights on my laptop so I'm using **ScreenToGif** portable, but **NET** requires admin rights. That is sad.

**Comment by NickeManarin** [comment]
Hi, ScreenToGif was never truly portable.
Older versions required .NET Framework 4.8, which was installed by default.

In order for it to be truly portable, the download size will go up to 78MB.
I could add that download option in future releases.

**Comment by SoftwUser** [comment]
@NickeManarin 

That would be cool. I don't care much about portability - but bundling ScreenToGif with the needed .NET6 files insetad of requiring a systemwide .NET6 install would be very welcome. Other popular software (such as paint.net) already go this way.

**Comment by NikolajPagh** [comment]
I am here to second that motion. Was quite surprised to see that I needed to install some additional .net software in order to use ScreenToGif. This is soo sad.
From a developer point of view, WHY do you need the newer .Net framework - What part of it, is it that you need ?

**Comment by NickeManarin** [comment]
Right. 
Let's use the right terms here, it's not sad, it's inconvenient for you guys (and I got your points). :)
I'll make it more convenient, not an issue.

Also, I don't need to explain myself as to why I did something with my project (but it's easy to guess why).

**Comment by NickeManarin** [comment]
Next version (v2.36) will be distributed with a Full and Light package types.
The updater will know how to handle each installation mode.
Also, I'll distribute the app as an msix package.
