### ISSUE TITLE
[Bug] Starting the app creates a log saying error in CheckForUpdates

### ISSUE THREAD

**Issue by tw0517tw** [NickeManarin/ScreenToGif#1045]
**Describe the bug**
After starting the app, it creates a log file saying there is an error in `ScreenToGif.Util.LocalizationHelper.CheckForUpdates`

**To Reproduce**
1. Download portable exe
2. start exe
3. see `ScreenToGif\Logs` showing

**Expected behavior**
No error logs

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2.35.3

**Additional context**
The error log says below.

```
► Title - 
	Check for an updated localization recource
▬ Message - 
	The path is empty. (Parameter 'path')
○ Type - 
	System.ArgumentException
♦ [Version] Date/Hour - 
	[2.35.3] 01/09/2022 01:00:23
▲ Source - 
	System.Private.CoreLib
▼ TargetSite - 
	System.String GetFullPath(System.String)
♠ StackTrace - 
   at System.IO.Path.GetFullPath(String path)
   at System.IO.File.GetLastWriteTime(String path)
   at ScreenToGif.Util.LocalizationHelper.CheckForUpdates(String culture) in C:\Users\nicke\source\repos\ScreenToGif\ScreenToGif.Util\LocalizationHelper.cs:line 146
```

Maybe this was cause by the behavior change in `Assembly.Location` after .NET 5?
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.location?view=net-6.0#remarks

**Comment by NickeManarin** [comment]
> Maybe this was cause by the behavior change in Assembly.Location after .NET 5?

Yes, that was it. I was able to fix it.
Thanks.
