### ISSUE TITLE
I was never able to create a smooth loop.

### ISSUE THREAD

**Issue by wvxwxvw** [NickeManarin/ScreenToGif#1053]
**Describe the bug**
Added different sets images, including two identical sets of images and set the minimum possible match threshold. Always the same thing, can't create, he says. But I know there's 100% identical footage. :)

**Desktop (please complete the following information):**
 - OS: Windows 7 x64
 - Version 2.35.4

**Comment by NickeManarin** [comment]
How did you position the frames?

Use the same number for 100% equal frames, like so:
1 2 3 4 5 1

Also, which options did you use?

**Comment by wvxwxvw** [comment]
I arranged them in order.
Frame-1.bmp
Frame-2.bmp
Frame-3.bmp
...
This is how it was extracted from the original gif. And duplicated one of the first frames by placing it closer to the end, while maintaining the numbering order.

And just exported another gif with two identical sequences.

But that's all after I tried a lot of other options and never got a result.
============

The question is a little off topic. windowsdesktop-runtime-6.0.1 what bit depth (x86 or x64) should I install? I put both, maybe that's the problem? ScreenToGif portable x64 version, but I tried x86 as well.

**Comment by NickeManarin** [comment]
The algorithm tries to find the first similar enough frame from end-to-start or start-to-end depending on settings.
For example:

![image](https://user-images.githubusercontent.com/14798947/149022403-f0b3fdf1-e9c6-4ac4-9b07-2f87c78c746a.png)

In this project, the algorithm wil find the frame $4 as the 100% similar as the first one and will delete all next frames ($5).

**Comment by wvxwxvw** [comment]
I thought so.
sp1 and all major (non-junk) updates are worth it.

Since you show it works, but on more complex images, such as a video series, it does not.
In general, it is clear that the simplest images are needed to use the opportunity. If you want, you can close the thread.

**Comment by NickeManarin** [comment]
I want to leave this issue ticket open, as I need to improve the UX of the tool.
Right now it's not clear how it works and why it fails.

**Comment by NickeManarin** [comment]
As for the runtime, I'm thinking about embbeding .NET 6 along with the app, it just going to increase the file size by a lot.
I may also distribute as a msix (maybe with support for MSIX Core, for Windows 7 and above).

**Comment by wvxwxvw** [comment]
Yeah, that's better. This is what most developers with portable versions of software do. And nothing that will increase the size, it's better than insnalling it in the OS.

**Comment by NickeManarin** [comment]
Fixed a couple of issues with the Smooth Loop feature.
The frames were not being correctly compared, skipping some.
And the warning message was not that great.

![image](https://user-images.githubusercontent.com/14798947/151266196-326cdf5c-6af0-4d81-9dc7-2663551a16c0.png)
