### ISSUE TITLE
2.35.4 error

### ISSUE THREAD

**Issue by szmabcd** [NickeManarin/ScreenToGif#1054]
![QQ截图20220111212815](https://user-images.githubusercontent.com/38176269/148952771-c4cb815e-f247-4289-b9be-f054b2c40afa.png)

**Comment by NickeManarin** [comment]
That's not an error.
That warning appears because you tried to import multiple images and at least one of them had a different resolution.

**Comment by NickeManarin** [comment]
The solution is to import them separately.

**Comment by szmabcd** [comment]
image1:&nbsp; 782x591
image2:&nbsp; 782x591
image3:&nbsp; 781x588


issue:


1.When taking screenshots, we cannot guarantee that each picture has the same size. Can it be improved?
2.How to record in full screen？


thanks!




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "NickeManarin/ScreenToGif"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月11日(星期二) 晚上10:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NickeManarin/ScreenToGif] 2.35.4 error (Issue #1054)





 
The solution is to import them separately.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NickeManarin** [comment]
I'm reworking the editor, adding support for multiple layers, multiple objects, etc.
Multiple sized image imports will be supported.

But right now you can take multiple screenshots of the same window using Alt + Ptrscr. 

----

What do you mean by recording in fullscreen? With ScreenToGif? 
You need to use the new screen recorder interface in Options > Recorder.

**Comment by szmabcd** [comment]
thanks!


I mean to record the entire computer screen, now screentogif seems to be impossible, or I don't know how to record full screen.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NickeManarin/ScreenToGif"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月12日(星期三) 凌晨5:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NickeManarin/ScreenToGif] Warning when importing multiple images with different size (Issue #1054)





 
I'm reworking the editor, adding support for multiple layers, multiple objects, etc.
 Multiple sized image imports will be supported.
 
But right now you can take multiple screenshots of the same window using Alt + Ptrscr.
 
 
What do you mean by recording in fullscreen? With ScreenToGif?
 You need to use the new screen recorder interface in Options &gt; Recorder.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NickeManarin** [comment]
Go here:

![image](https://user-images.githubusercontent.com/14798947/149042006-b00b16b8-61ed-49ec-ac8d-f2d8927f6fa3.png)

![image](https://user-images.githubusercontent.com/14798947/149041957-82da456f-c0be-4ec7-84fd-fb21cec5fdea.png)

**Comment by szmabcd** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NickeManarin/ScreenToGif"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月12日(星期三) 上午8:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NickeManarin/ScreenToGif] Warning when importing multiple images with different size (Issue #1054)





 
Go here:
 

 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
