### ISSUE TITLE
Windows 11 support

### ISSUE THREAD

**Issue by nbabanov** [NickeManarin/ScreenToGif#1056]
I love this app. Sadly on Windows 11 it keeps insisting that I don't have .NET Core installed, which I did install. :(

![image](https://user-images.githubusercontent.com/8811188/149153241-aabb8e13-7b78-4411-816c-9b75220df6f6.png)

**Comment by NickeManarin** [comment]
Download .NET 6 Desktop Runtime.
It should work.

**Comment by nbabanov** [comment]
@NickeManarin That did the trick! Thanks a lot! Maybe you could list in this window, which are the missing frameworks?

Keep up the good work!
