### ISSUE TITLE
Make it work on .NET 5.x as well

### ISSUE THREAD

**Issue by thany** [NickeManarin/ScreenToGif#1057]
**Describe the bug**
I'm not sure requiring .NET 6 is a good idea for me, as my pc is a development pc for (among others) .NET applications. I don't do .NET development myself, but I do have to compile and run stuff. Long story short, I don't want to bollocks up my installation.

On top of that, it doesn't feel right to be installing a .NET version, esp one that doesn't come with Windows, for one program.

**To Reproduce**
1. Download the latest version
2. Run it

**Expected behavior**
Works on .NET 5.x just like the previous(-ish) versions. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - Version: 2.35.4

**Comment by thany** [comment]
For those encountering this issue: Latest working version for me is [2.34.1](https://github.com/NickeManarin/ScreenToGif/releases/tag/2.34.1). Reverting to that for the time being. Improvements on newer version don't seem to be super important on the surface (no offense) so this will work for me until hopefully this issue can be resolved.

**Comment by NickeManarin** [comment]
If you don't want to install .NET 6 Desktop Runtime, download the Microsoft Store version, it doesn't need a .NET 6 install.

But, installing .NET 6 desktop runtime should be fine and quick.
I'm thinking about alternatives for true portable versions, but it will end up increase the file size a lot.

**Comment by NickeManarin** [comment]
Well, it still requires .NET 6, it just comes along with the downloaded files.
But with the Store version, you only download what's needed.

As for the installer and portable versions, I would need to always ship the 120MB file everytime an update was released.

Btw, I can publish in two ways the software: as a single .exe file (ScreenToGif.exe with all .NET 6 files inside) or as separated files (ScreenToGif.exe + 100s of .NET 6 files).

**Comment by thany** [comment]
Alright, well that explain why. But you skipped my last question.

**Comment by UnicodeTreason** [comment]
As someone who just runs this as a portable .exe off a USB drive the sudden requirement to install .NET v6 was a surprise.
I will remain using v2.34.1 for now.

Use Case if curious, very handy to quickly record a screen when replicating an odd issue on a random PC.

**Comment by ElMay0r** [comment]
I have the  same issue with last update on Win 11

**Comment by thany** [comment]
> We can also look at this from a different angle: why does it need .NET 6 in the first place? What was wrong with or lacking in .NET 5?

Can we have an answer this this please?

**Comment by NickeManarin** [comment]
ScreenToGif never had a .NET 5 requirement and .NET 6 is LTS.

**Comment by NickeManarin** [comment]
Next version will be distributed without the requirement for installing .NET 6 desktop runtime (except if you download the Light package).
