### ISSUE TITLE
[Bug] cannot change startup mode

### ISSUE THREAD

**Issue by AndreaBorgia-Abo** [NickeManarin/ScreenToGif#1059]
**How to reproduce**
1. install
2. start up
2. open settings
3. click "start with windows"

**Expected behavior**
Startup mode is changed

**Screenshots**
![impossibletoalternate](https://user-images.githubusercontent.com/25269970/149618759-81e1c565-f7a7-47bf-9246-4e6d4b602dab.gif)

**Desktop**
 - OS: Windows 10 (
 - Version 2.35.4

I searched for "impossible", "alternate" and "startup" but no luck.

**Comment by NickeManarin** [comment]
Hi, this issue is new to me.
Can you check the logs to see if there's anything written in there?

Same folder where the ScreenToGif.exe is located > ScreenToGif > Logs.
OR
User > Documents > ScreenToGif > Logs

**Comment by AndreaBorgia-Abo** [comment]
Here is the log, hope it helps. I am now trying out another sw, but I could always reinstall it to test a new version, in case.
[22_01_15.txt](https://github.com/NickeManarin/ScreenToGif/files/7876601/22_01_15.txt)
.

**Comment by NickeManarin** [comment]
Thank, I was able to reproduce it and I'll fix it.
A new version should be available in 1 week.

**Comment by NickeManarin** [comment]
Fixed
