### ISSUE TITLE
[Bug] App won't start although required framework is installed

### ISSUE THREAD

**Issue by jesuscc1993** [NickeManarin/ScreenToGif#1060]
**Describe the bug**
App fails to start, complaining about a missing .NET install that is actually present.

**To Reproduce**
1. Run version 2.35.4 on Windows 10 with .NET 6.0.1 installed

**Expected behavior**
App should start up when the required frameworks are installed.

**Screenshots**
![image](https://user-images.githubusercontent.com/8211197/150644699-c3efac92-f647-432a-8d71-96c017b713de.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2.35.4

**Comment by NickeManarin** [comment]
Download .NET 6 Desktop Runtime.
Or download the installer version of the app.

**Comment by jesuscc1993** [comment]
Running the installer fixed the issue, but I don't understand why.
Does it require exactly version 6.0 of the .NET runtime? Was that why 6.0.1 wasn't working?

**Comment by NickeManarin** [comment]
It requires the **Desktop** Runtime, not just the Runtime, for now.

**Comment by jesuscc1993** [comment]
I see, I didn't know those were two different things. Thanks for the clarification and apologies for the confusion.
