### ISSUE TITLE
File size increased significantly after some update

### ISSUE THREAD

**Issue by luansepultura** [NickeManarin/ScreenToGif#1064]
After 20/01/2022, without modifying any settings, the file size jumped from ~300Kb to ~9Mb, other larger files that were ~2.2Mb now have ~21Mb, as reported I didn't change any settings, attached prints with the settings I use.
After that I tested other settings, none resulted in a good size.
Thank you very much for your attention.

APP version: 2.35.4
S.O.: Windows 11 x64 (10.0.22000 Comp. 22000)
Device: Dell inspiron 5537
![msinfo32_iJAcdFOCJY](https://user-images.githubusercontent.com/98748733/151794981-d4005e25-00d7-4f57-8463-86e22ddfb3ea.png)
![ScreenToGif_SJs4mlLpU3](https://user-images.githubusercontent.com/98748733/151794986-82e66274-fc29-4365-a41d-41581f1178b8.png)
![ScreenToGif_UGM5zT2OHO](https://user-images.githubusercontent.com/98748733/151794989-85d77548-386d-434e-a061-c1ddacb0dc13.png)

**Comment by luansepultura** [comment]
File size comparison, all have variable sizes (50-1000 screens), size after day 20 much bigger than previous ones.
![explorer_z1OBEKhUgh](https://user-images.githubusercontent.com/98748733/151795314-9a6777c6-9397-433b-86cb-17125812ef7b.png)

**Comment by NickeManarin** [comment]
![image](https://user-images.githubusercontent.com/14798947/151795313-980803b0-3b4b-4ee7-ad36-3b6d1e641f96.png)

This property is not the default for the given preset.
Click reset to undo all changes to the preset settings.

**Comment by luansepultura** [comment]
Thanks for replying, actually, going back to default the same 20Mb file went to ~4.5Mb...
In this range I can perform the process without problems.

Thank you very much
