### ISSUE TITLE
[Bug] Version 2.35.4 does not save application settings

### ISSUE THREAD

**Issue by SudoCerb** [NickeManarin/ScreenToGif#1067]
**Describe the bug**
Application settings are not preserved and must be reconfigured with every app launch.

**To Reproduce**
1. Install ScreenToGif.2.35.4.Setup.x64.msi
2. Run it and change Application theme to Dark or whatever

(OPTIONAL)
3. Configure following of mouse - which requires a shortcut to be defined.
4. Record a GIF and export it.

5. Close the application
6. Re-open the application and observe that Dark mode is not on.

**Expected behavior**
Settings should be saved and should persist after the application has been closed.

**Desktop:**
 - OS: Windows 10 Enterprise
 - Version: 21H2 (19044.1466)

**Comment by kiririn39** [comment]
Same problem. Tried dark theme and ffmpeg location string

**Comment by NickeManarin** [comment]
Fixed.
Fix will be available for v2.36.
