### ISSUE TITLE
[Feature Request] Yet another GIF Encoder

### ISSUE THREAD

**Issue by koszeggy** [NickeManarin/ScreenToGif#1069]
I've been actually [working](https://github.com/koszeggy/ScreenToGif/tree/KGySoftGifEncoder) on this already, but I didn't want to introduce an unwanted pull request without any notification.

**Motivation**

I really like ScreenToGif and it is very useful in a lot of cases. However, the built-in GIF Encoders have some weaknesses, especially with alpha images. Additionally, the built-in encoders do not support dithering and have only a few quantizers (eg. there is no B&W one), etc. To address these issues I included my [GIF Encoder](https://github.com/koszeggy/KGySoft.Drawing#advanced-gif-encoder-with-high-color-support) in ScreenToGif but so far it was meant for private usage only. As it proved to be quite useful for me now I ask if you are also interested in it.

> 📝 _Note:_ I know about the external 3rd party GIF Encoders but I don't cover them in this issue. KGy SOFT Drawing Libraries are built for .NET, providing a direct, in-proc solution with good integration, supporting async-await, progress reporting, cancellation, etc.

**Comparisons:**

> ⚠️ _Disclaimer:_ The new encoder does not aim to replace the existing ones. Sometimes the built-in encoders can be faster, more compact or better in other ways so it would be just a new option. The images below do _not_ reflect the general quality difference of the encoders. It is intentionally a special example where the new encoder might be a better choice.

|Animation|Description|Size
|--|--|--|
| Original APNG image | ![APNG Balls](https://davidmz.github.io/apng-canvas/images/pyani.png) | 363.1K |
| System Encoder | ![Balls by System GIF Encoder](https://user-images.githubusercontent.com/27336165/152840198-2de55a61-a280-4cfe-8a6b-4a6eda3c6990.gif) | 288.4K |
| STG Encoder (Default Preset) | ![Balls by STG/Default GIF Encoder](https://user-images.githubusercontent.com/27336165/152840644-105dfcfd-894e-44cc-8c7a-73e69f31a6e5.gif) | 341.9K |
| STG Encoder (High Quality Preset) | ![STGHigh](https://user-images.githubusercontent.com/27336165/152841076-6501a236-3817-4292-8ce9-26694ed771bd.gif) | 347.1K |
| STG Encoder (High Quality • Graphics Preset) | ![STGHighGraphics](https://user-images.githubusercontent.com/27336165/152841467-795475fb-a2df-4288-b19d-bfc5b530fa8b.gif) | 256.6K |
| STG Encoder (High Quality • Transparent Background Preset) | ![STGHighTr](https://user-images.githubusercontent.com/27336165/152841668-82885f19-28fa-47b6-bb82-883072c9eb38.gif) | 320.8K |
| KGy SOFT Encoder (Balanced Preset) | ![KGyBalanced](https://user-images.githubusercontent.com/27336165/152842099-607b4fcb-c46c-43d0-af2b-a7ba6d9cbe42.gif) | 151.2K |
| KGy SOFT Encoder (High Quality Preset) | ![KGyHigh](https://user-images.githubusercontent.com/27336165/152842544-6c962c4c-ccd1-41f1-95f2-61aa92ed3739.gif) | 158.1K |
| KGy SOFT Encoder (Low Quality Preset) | ![KGyLow](https://user-images.githubusercontent.com/27336165/152842858-1af3f3e7-10e3-4947-92d5-0c03c14a7549.gif) | 102.7K |
| KGy SOFT Encoder (custom preset: Wu quantizer, white background, no alpha) | ![KGyCustomWhite](https://user-images.githubusercontent.com/27336165/152860205-c71d6a39-efa2-4052-a385-5c5d8810bc18.gif) | 276.1K |

**Preview:**

Still under development but now it looks like this (it also shows some of the supported quantizers and ditherers):

![KGy SOFT GIF Encoder Features Preview](https://user-images.githubusercontent.com/27336165/152844903-b60c82c0-9fab-4ae8-93f7-b168308c2117.gif)

**Bonus (offtopic):**

During development I bumped into some issues regarding user settings deserialization, where I noticed the [comment](https://github.com/NickeManarin/ScreenToGif/blob/9cfdf56f3538277a4dfcf556535207031ac9f25a/ScreenToGif.Util/Settings/UserSettings.cs#L194) about looking for a better solution. As a matter of fact, I addressed the problem on a separate branch. The refactored version is 253 lines shorter than the original, and it doesn't need adjustments when using new types in user settings (such as new enums, nullables, etc). Its branch was created from the new encoder's feature branch rather than master (not published yet), and as it uses some features from the same [library](https://github.com/koszeggy/KGySoft.CoreLibraries) referenced also by KGy SOFT Drawing Libraries maybe it makes sense if I create a pull request only if the new encoder is accepted along with its dependencies.

----

So what do you think? Will you accept a pull request for the new encoder? If so, I could improve the user experience a bit (more tooltips/hints, etc.), and maybe I can add some localization, too. Maybe I could finish it in a week or two.

**Comment by NickeManarin** [comment]
Hi @koszeggy, this looks great!

I'm yet to look at your branch (next weekend when I have more time). 
If I understood correctly, you want to make your encoder available with ScreenToGif, not as an external download, right?

Also, I'm interested in knowing how you solved my issue with the settings parsing. :)

**Comment by koszeggy** [comment]
> If I understood correctly, you want to make your encoder available with ScreenToGif, not as an external download, right?

That's correct. It is downloaded at compile time from NuGet.

In the meantime I finished the polishing and added some localization so I can create the pull request for review.

> Also, I'm interested in knowing how you solved my issue with the settings parsing. :)

In the meantime I updated and published the [refactoring branch](https://github.com/koszeggy/ScreenToGif/tree/UserSettingsRefactoring) so [here](https://github.com/koszeggy/ScreenToGif/blob/f80a05c951c1311e267be703cd066f538126c6d1/ScreenToGif.Util/Settings/UserSettings.cs#L189) you can see the new version. I tried to generate the largest possible settings file to test it (I just opened all the possible menus and clicked randomly here and there 😁) and now it seems alright to me but maybe it needs some more throughout testing.

**Comment by koszeggy** [comment]
I added the [pull request](https://github.com/NickeManarin/ScreenToGif/pull/1073) for the new encoder so you can review it.

It does _not_ contain the settings parsing refactoring but feel free to create a separate issue for it. As I mentioned it has a dependency on the same library the new encoder also references so it seems reasonable to create a pull request for that after this one is accepted.

**Comment by NickeManarin** [comment]
Thank you!

**Comment by NickeManarin** [comment]
Btw, do you have an ARM64 device to test out this new feature?
Looks like the DLLs are 32 bits (when the project is exported as ARM64). Not sure if this will cause some problems with ARM64 computers.

![image](https://user-images.githubusercontent.com/14798947/159191463-f2a9c4d0-a1c0-4b18-9d42-f82c085e1b00.png)

**Comment by koszeggy** [comment]
The .dlls are AnyCPU .NET assemblies so they must be able to referenced by both 32 and 64 bit .NET applications.

From .NET Reflector:
![image](https://user-images.githubusercontent.com/27336165/159229511-c2ceb20f-ed60-4bc1-9b08-5651c735ac51.png)

However, I don't really know how .NET is realized on an ARM64 system, but I would be really surprised if it didn't work because it would be a serious issue for almost every other packages, too. But let me know if any issue occurs on an ARM platform.

If anything, possible big endianness might be a problem because I have never tested the libraries on big endian systems. But AFAIK the ARM64 CPUs supports both mode so hopefully a Windows uses the little endian mode on ARM, too...

**Comment by NickeManarin** [comment]
Hi @koszeggy, I'm receiving some feedback about the "Save As" panel closing and not opening anymore after selecting the KGySoft encoder.

I'm unable to reproduce that, but from what I could see in someone's else computer, selecting the encoder will simply close the panel. Trying to click in "Save As" to expand the panel again will give no result.

Also, there's no error messages or logs, not even in Windows Events.

**Comment by koszeggy** [comment]
Hmm... I've never encountered this issue but I will pull the latest sources and play with it a bit. Let's see if I find something.
