### ISSUE TITLE
[Bug] I can not run ScreenToGif.2.35.4.Portable.x64

### ISSUE THREAD

**Issue by 7K-K-H** [NickeManarin/ScreenToGif#1071]
**Describe the bug**

I can not run ScreenToGif.2.35.4.Portable.x64

**To Reproduce**

1. I install "dotnet-runtime-6.0.2-win-x64.exe"   
2. I try to insall .net framework.    
   ![image](https://user-images.githubusercontent.com/96602947/153120224-e87449ca-8a3c-4487-9b1a-e6120cdcdc9e.png)

3. try to run "ScreenToGif.2.35.4.Portable.x64"
   ![image](https://user-images.githubusercontent.com/96602947/153120275-285f7fb1-d587-4ef5-a617-476f61e8e497.png)
   

**Desktop (please complete the following information):**
OS: Win11 21H2
Version: OS build 22000.469
![image](https://user-images.githubusercontent.com/96602947/153120358-fe5ce380-1001-4ebf-be9f-f8c62ef818de.png)

**Comment by NickeManarin** [comment]
Hi, you need to download **.NET 6 Desktop Runtime** in order to run the app.

**Comment by 7K-K-H** [comment]
Thanks, 
After install .NET 6 Desktop Runtime, software run well.
