### ISSUE TITLE
[Bug] Don't save setting of last recorded

### ISSUE THREAD

**Issue by Bitmanyga** [NickeManarin/ScreenToGif#1074]
Hello, could you advise me? When i setting up the program, after exiting all setting changes to default. Could i fix it somehow?

![try](https://user-images.githubusercontent.com/59740338/153592415-7d5edcc4-57ac-4008-8ec6-fa43e279e4b8.png)

**Comment by NickeManarin** [comment]
This is an issue with the latest version. 
It was fixed and the fix will be available this weekend.
