### ISSUE TITLE
[Feature Request] Custom name FFmpeg.dll

### ISSUE THREAD

**Issue by wvxwxvw** [NickeManarin/ScreenToGif#1079]
When specifying a file FFmpeg.dll overview ScreenToGif only sees files with the name - FFmpeg.dll . This is not right. I don't need to download FFmpeg for every program that needs it, I have it lying quietly on the disk under the name FFmpeg64.dll and it is with this name that it works in several programs. The ScreenToGif overview should see all the dll's, not just those with a specific name. A trifle, of course, but it is desirable to fix it.

**Comment by NickeManarin** [comment]
ScreenToGif uses an ffmpeg executable, not a dll.
And you should be able to select a custom file, with a different name with no problem.

**Comment by wvxwxvw** [comment]
Exactly. And I tried to slip a dll and thought that it didn’t work because of the name. I'm sorry.
