### ISSUE TITLE
Apply keystrokes only in some frames

### ISSUE THREAD

**Issue by daniloalonso** [NickeManarin/ScreenToGif#108]
Is there an option to apply keystrokes only to some frames? It would be nice if you could remove the keystrokes where you type too much text, and leave only frames that contains ENTER, SHIFT+KEY, TAB, and others.
This tool is great, congratulations!

**Comment by NickeManarin** [comment]
I started working with the keystrokes editor (to add or remove key presses), but I had to postpone it.

Thank you, btw :D

**Comment by NickeManarin** [comment]
A few more proposed enhancements:

- Let the keystroke be shown X ms in advance. 
- Allow customization of key strokes text. Example: Change the text for 'Ctrl' key from 'Control' to 'Ctrl' and from 'Return' to 'Enter' or even an arrow icon that is on 'Return' key. 
- Allow to display icons instead of keys.

**Comment by vatterspun** [comment]
@NickeManarin Just a note that this is a hard problem -- I appreciate you putting so much energy into it.

**Comment by NickeManarin** [comment]
Done!

![keys](https://user-images.githubusercontent.com/14798947/35358852-326e95a4-013f-11e8-8f68-c263bc70c5b8.JPG)

Basically, you can add/remove/edit the detected key strokes:  

![image](https://user-images.githubusercontent.com/14798947/35358779-ef324e66-013e-11e8-9d57-40e5eee5c447.png)

**Comment by vatterspun** [comment]
> Basically, you can add/remove/edit the detected key strokes

Oh HELL yeah.

That's not just a great program addition, that's a really smart solution.
