### ISSUE TITLE
Translator.exe weird behavior ??

### ISSUE THREAD

**Issue by Regmos** [NickeManarin/ScreenToGif#1083]
Hi.
I´ve noticed a weird little thing.
I download the translator tool and unzip to a folder on my desktop:
**C:\Users\Regmos5\Desktop\STG)**.
When I start the tool, it creates this folder:
**C:\Users\Regmos5\Documents\Scripts\Autohotkey\ScreenToGif**
It doesn't affect the program, but it just seems odd.
Shouldn't the location be in the STG folder ?

Kind regards 
Regmos

![Translator](https://user-images.githubusercontent.com/811857/153825159-5611e99b-2903-45af-8ec4-ee3222e3668e.png)

**Comment by NickeManarin** [comment]
Yes, what's happening is that the translator is using the startup folder instead of the base folder.
So, if the app was opened by the autohotkey, the translator is going to use that folder.

I'll fix this, so that the translator uses the correct base folder instead.
