### ISSUE TITLE
[Feature Request] Highlight mouse cursor even when no buttons are pressed

### ISSUE THREAD

**Issue by zsee** [NickeManarin/ScreenToGif#1086]
**Is your feature request related to a problem? Please describe.**
When presenting a software demo on a big screen (people looking at it from a distance), the mouse cursor in the demo can be hard to follow. The same can happen when looking at recordings on a phone.

**Describe the solution you'd like**
Add an option to highlight the mouse cursor without any buttons being pressed.
The existing mouse click feature already has all the mouse positions available, and can be extended with a new option for the highlight color. :)

**Describe alternatives you've considered**
Longer demos with more explanations. :(

**Additional context**
See pull request:
https://github.com/NickeManarin/ScreenToGif/pull/1046
![image](https://user-images.githubusercontent.com/4281365/156877532-b991b0de-4463-45aa-b0c4-4f78299aee51.png)

**Comment by NickeManarin** [comment]
Thank you :)
