### ISSUE TITLE
Would like to record 100px width

### ISSUE THREAD

**Issue by kwinz** [NickeManarin/ScreenToGif#109]
I tried to record a small section of the screen with a width of arround 100px. However I can not select an area thinner than 328px.
Even when I manually enter a width of 100px it still records 328px.

Crosspost: https://www.reddit.com/r/screentogif/comments/5zxq78/would_like_to_record_100px_width/

**Comment by NickeManarin** [comment]
The minimum size of the recorder window is 164x34, yet you can record smaller regions by typing lower sizes.

Also you can crop the image later.

What's your setup? screen DPI? I'm asking this because it can be a problem with a high DPI screen.

**Comment by kwinz** [comment]
Thanks, MickeManarin!

The screen is 4K/UHD at 15' inch size. The scaling is set to 200% in Windows 10.
It could be possible that the window won't allow lower areas because the title bar can't get any smaller.
I would strongly prefer if ScreenToGif provided an option to record smaller regions than 164x34.
As a workaround how can  I crop the image later?

**Comment by NickeManarin** [comment]
Done, you can use the new recorder by enabling it on Options > Application.
