### ISSUE TITLE
[Bug] can't install ffmpeg with admin rights win 11

### ISSUE THREAD

**Issue by fusionneur** [NickeManarin/ScreenToGif#1097]
Info: === Logging started: 13 April 2022  15:47:44 ===
CommonData: Message type: 0, Argument: 1033
CommonData: Message type: 1, Argument: ScreenToGif
ActionStart: Action 15:47:44: INSTALL. 
Info: Action start 15:47:44: INSTALL.
CommonData: 1: 0 2: 1033 3: 1252 
CommonData: 1: 0 2: 1033 3: 1252 
CommonData: 1: ScreenToGif
Info: === Logging started: 13 April 2022  15:47:52 ===
CommonData: Message type: 0, Argument: 1033
CommonData: Message type: 1, Argument: ScreenToGif
ActionStart: Action 15:47:52: INSTALL. 
Info: Action start 15:47:52: INSTALL.
InstallStart: 1: ScreenToGif 2: {F1E8D877-932A-42ED-B6EC-B2366CD88A63} 
ActionStart: Action 15:47:52: FindRelatedProducts. Searching for related applications
Info: Action start 15:47:52: FindRelatedProducts.
Info: Action ended 15:47:52: FindRelatedProducts. Return value 1.
ActionStart: Action 15:47:52: WixSharp_InitRuntime_Action. 
Info: Action start 15:47:52: WixSharp_InitRuntime_Action.
Info: SFXCA: Extracting custom action to temporary directory: C:\Users\Fusion\AppData\Local\Temp\MSIB65E.tmp-\
Info: SFXCA: Binding to CLR version v4.0.30319
Info: Calling custom action WixSharp!WixSharp.ManagedProjectActions.WixSharp_InitRuntime_Action
Info: Action ended 15:47:52: WixSharp_InitRuntime_Action. Return value 1.
ActionStart: Action 15:47:52: AppSearch. Searching for installed applications
Info: Action start 15:47:52: AppSearch.
ActionData: Property: NETFRAMEWORK45, Signature: NetFramework45
Info: Action ended 15:47:52: AppSearch. Return value 1.
ActionStart: Action 15:47:52: LaunchConditions. Evaluating launch conditions
Info: Action start 15:47:52: LaunchConditions.
Info: Action ended 15:47:52: LaunchConditions. Return value 1.
ActionStart: Action 15:47:52: ValidateProductID. 
Info: Action start 15:47:52: ValidateProductID.
Info: Action ended 15:47:52: ValidateProductID. Return value 1.
ActionStart: Action 15:47:52: CostInitialize. Computing space requirements
Info: Action start 15:47:52: CostInitialize.
Info: Action ended 15:47:52: CostInitialize. Return value 1.
ActionStart: Action 15:47:52: FileCost. Computing space requirements
Info: Action start 15:47:52: FileCost.
Info: Action ended 15:47:52: FileCost. Return value 1.
ActionStart: Action 15:47:52: CostFinalize. Computing space requirements
Info: Action start 15:47:52: CostFinalize.
Info: Action ended 15:47:52: CostFinalize. Return value 1.
ActionStart: Action 15:47:52: InstallValidate. Validating install
Info: Action start 15:47:52: InstallValidate.
Info: Action ended 15:47:52: InstallValidate. Return value 1.
ActionStart: Action 15:47:52: InstallInitialize. 
Info: Action start 15:47:52: InstallInitialize.
Info: Action ended 15:47:52: InstallInitialize. Return value 1.
ActionStart: Action 15:47:52: RemoveExistingProducts. Removing applications
Info: Action start 15:47:52: RemoveExistingProducts.
Info: Action ended 15:47:52: RemoveExistingProducts. Return value 1.
ActionStart: Action 15:47:52: ProcessComponents. Updating component registration
Info: Action start 15:47:52: ProcessComponents.
ActionStart: Action 15:47:52: GenerateScript. Generating script operations for action:
ActionData: Updating component registration
Info: Action ended 15:47:52: ProcessComponents. Return value 1.
ActionStart: Action 15:47:52: UnpublishFeatures. Unpublishing Product Features
Info: Action start 15:47:52: UnpublishFeatures.
Info: Action ended 15:47:52: UnpublishFeatures. Return value 1.
ActionStart: Action 15:47:52: SchedSecureObjectsRollback. 
Info: Action start 15:47:52: SchedSecureObjectsRollback.
Info: Action ended 15:47:52: SchedSecureObjectsRollback. Return value 1.
ActionStart: Action 15:47:52: RemoveRegistryValues. Removing system registry values
Info: Action start 15:47:52: RemoveRegistryValues.
Info: Action ended 15:47:52: RemoveRegistryValues. Return value 1.
ActionStart: Action 15:47:52: RemoveFiles. Removing files
Info: Action start 15:47:52: RemoveFiles.
Info: Action ended 15:47:52: RemoveFiles. Return value 1.
ActionStart: Action 15:47:52: RemoveFolders. Removing folders
Info: Action start 15:47:52: RemoveFolders.
Info: Action ended 15:47:52: RemoveFolders. Return value 1.
ActionStart: Action 15:47:52: CreateFolders. Creating folders
Info: Action start 15:47:52: CreateFolders.
ActionData: Folder: Creating folders
Info: Action ended 15:47:52: CreateFolders. Return value 1.
ActionStart: Action 15:47:52: InstallFiles. Copying new files
Info: Action start 15:47:52: InstallFiles.
ActionData: File: Copying new files, Directory: , Size: 
Info: Action ended 15:47:52: InstallFiles. Return value 1.
ActionStart: Action 15:47:52: CreateShortcuts. Creating shortcuts
Info: Action start 15:47:52: CreateShortcuts.
ActionData: Shortcut: Creating shortcuts
Info: Action ended 15:47:52: CreateShortcuts. Return value 1.
ActionStart: Action 15:47:52: WriteRegistryValues. Writing system registry values
Info: Action start 15:47:52: WriteRegistryValues.
ActionData: Key: Writing system registry values, Name: , Value: 
Info: Action ended 15:47:52: WriteRegistryValues. Return value 1.
ActionStart: Action 15:47:52: InstallServices. Installing new services
Info: Action start 15:47:52: InstallServices.
Info: Action ended 15:47:52: InstallServices. Return value 1.
ActionStart: Action 15:47:52: SchedSecureObjects. 
Info: Action start 15:47:52: SchedSecureObjects.
Info: Action ended 15:47:52: SchedSecureObjects. Return value 1.
ActionStart: Action 15:47:52: RegisterUser. Registering user
Info: Action start 15:47:52: RegisterUser.
Info: Action ended 15:47:52: RegisterUser. Return value 1.
ActionStart: Action 15:47:52: RegisterProduct. Registering product
Info: Action start 15:47:52: RegisterProduct.
ActionData: Registering product
Info: Action ended 15:47:52: RegisterProduct. Return value 1.
ActionStart: Action 15:47:52: PublishFeatures. Publishing Product Features
Info: Action start 15:47:52: PublishFeatures.
ActionData: Feature: Publishing Product Features
Info: Action ended 15:47:52: PublishFeatures. Return value 1.
ActionStart: Action 15:47:52: PublishProduct. Publishing product information
Info: Action start 15:47:52: PublishProduct.
ActionData: 1: Publishing product information 
Info: Action ended 15:47:52: PublishProduct. Return value 1.
ActionStart: Action 15:47:52: Set_CancelRequestHandler_Props. 
Info: Action start 15:47:52: Set_CancelRequestHandler_Props.
Info: Action ended 15:47:52: Set_CancelRequestHandler_Props. Return value 1.
ActionStart: Action 15:47:52: CancelRequestHandler. 
Info: Action start 15:47:52: CancelRequestHandler.
ActionData: 
Info: Action ended 15:47:52: CancelRequestHandler. Return value 1.
ActionStart: Action 15:47:52: InstallFinalize. 
Info: Action start 15:47:52: InstallFinalize.
CommonData: Message type: 0, Argument: 1033
CommonData: Message type: 1, Argument: ScreenToGif
ActionStart: Action 15:47:52: ProcessComponents. Updating component registration
ActionData: 1: {F1E8D877-932A-42ED-B6EC-B2366CD88A63} 2: {F1E8D877-932A-42ED-B6EC-B2369F030686} 3: C:\Program Files\ScreenToGif\ 
ActionData: 1: {F1E8D877-932A-42ED-B6EC-B2366CD88A63} 2: {F1E8D877-932A-42ED-B6EC-B2363298F448} 3: C:\Program Files\ScreenToGif\ScreenToGif.exe 
ActionData: 1: {F1E8D877-932A-42ED-B6EC-B2366CD88A63} 2: {F1E8D877-932A-42ED-B6EC-B2366F935F8E} 3: C:\Program Files\ScreenToGif\ScreenToGif.150x150.png 
ActionData: 1: {F1E8D877-932A-42ED-B6EC-B2366CD88A63} 2: {F1E8D877-932A-42ED-B6EC-B236E77521A1} 3: C:\Program Files\ScreenToGif\ScreenToGif.70x70.png 
ActionData: 1: {F1E8D877-932A-42ED-B6EC-B2366CD88A63} 2: {F1E8D877-932A-42ED-B6EC-B23667950016} 3: C:\Program Files\ScreenToGif\ScreenToGif.visualelementsmanifest.xml 
ActionData: 1: {F1E8D877-932A-42ED-B6EC-B2366CD88A63} 2: {F1E8D877-932A-42ED-B6EC-B2368DB36AC7} 3: C:\Program Files\ScreenToGif\gifski.dll 
ActionData: 1: {F1E8D877-932A-42ED-B6EC-B2366CD88A63} 2: {F1E8D877-932A-42ED-B6EC-B236B05417FF} 3: 21:\Software\WixSharp\Used\ 
ActionData: 1: {F1E8D877-932A-42ED-B6EC-B2366CD88A63} 2: {F1E8D877-932A-42ED-B6EC-B2363582FAFF} 3: C:\Program Files\ScreenToGif\ 
ActionData: 1: {F1E8D877-932A-42ED-B6EC-B2366CD88A63} 2: {F1E8D877-932A-42ED-B6EC-B23651C041A1} 3: 21:\Software\WixSharp\Used\ 
ActionData: 1: {F1E8D877-932A-42ED-B6EC-B2366CD88A63} 2: {F1E8D877-932A-42ED-B6EC-B236CB8A0958} 
ActionData: 1: {F1E8D877-932A-42ED-B6EC-B2366CD88A63} 2: {F1E8D877-932A-42ED-B6EC-B236DFA8FAD6} 3: F:\ 
ActionStart: Action 15:47:52: CreateFolders. Creating folders
ActionData: Folder: C:\Program Files\ScreenToGif\
ActionData: Folder: C:\Program Files\ScreenToGif\
ActionData: Folder: C:\Program Files\ScreenToGif\
ActionData: Folder: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\
ActionStart: Action 15:47:52: InstallFiles. Copying new files
ActionData: File: gifski.dll, Directory: C:\Program Files\ScreenToGif\, Size: 524752
ActionData: File: ScreenToGif.150x150.png, Directory: C:\Program Files\ScreenToGif\, Size: 20793
ActionData: File: ScreenToGif.70x70.png, Directory: C:\Program Files\ScreenToGif\, Size: 18917
ActionData: File: ScreenToGif.exe, Directory: C:\Program Files\ScreenToGif\, Size: 166561560
ActionData: File: ScreenToGif.visualelementsmanifest.xml, Directory: C:\Program Files\ScreenToGif\, Size: 389
ActionStart: Action 15:47:53: CreateShortcuts. Creating shortcuts
ActionData: Shortcut: app_icon.ico
ActionData: Shortcut: zrwsrv93.lnk|Uninstall ScreenToGif.lnk
ActionData: Shortcut: p1bl2slt.lnk|ScreenToGif.lnk
ActionStart: Action 15:47:54: WriteRegistryValues. Writing system registry values
ActionData: Key: \Software\WixSharp\Used, Name: , Value: 0
ActionData: Key: \Software\WixSharp\Used, Name: , Value: 0
ActionStart: Action 15:47:54: RegisterProduct. Registering product
ActionData: {F1E8D877-932A-42ED-B6EC-B2366CD88A63}
ActionStart: Action 15:47:54: PublishFeatures. Publishing Product Features
ActionData: Feature: Binary
ActionData: Feature: Auxiliar
ActionData: Feature: Gifski
ActionStart: Action 15:47:54: PublishProduct. Publishing product information
ActionData: 1: {F1E8D877-932A-42ED-B6EC-B2366CD88A63} 
ActionStart: Action 15:47:54: CancelRequestHandler. 
Info: SFXCA: Extracting custom action to temporary directory: C:\WINDOWS\Installer\MSIBE90.tmp-\
Info: SFXCA: Binding to CLR version v4.0.30319
Info: Calling custom action WixSharp!WixSharp.ManagedProjectActions.CancelRequestHandler
CommonData: Message type: 2, Argument: 0
ActionStart: Action 15:47:54: RollbackCleanup. Removing backup files
CommonData: Message type: 2, Argument: 1
Info: Action ended 15:47:54: InstallFinalize. Return value 1.
Info: Action ended 15:47:54: INSTALL. Return value 1.
InstallEnd: 1: ScreenToGif 2: {F1E8D877-932A-42ED-B6EC-B2366CD88A63} 3: 1 
CommonData: 1: 2 2: 0 
CommonData: 1: 2 2: 1 
Info: Action ended 15:47:54: INSTALL. Return value 1.

▬ Message - 
	Access to the path 'C:\Program Files\ScreenToGif\ffmpeg.exe' is denied.
♦ Date/Hour - 
	4/13/2022 3:47:57 PM
▲ Source - 
	mscorlib
▼ TargetSite - 
	Void WinIOError(Int32, System.String)
♠ StackTrace - 
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at ScreenToGif_Installer.UserControls.Progress.<DownloadFfmpeg>d__36.MoveNext()

**Comment by NickeManarin** [comment]
The file will be downloaded to the ProgramData folder instead.
