### ISSUE TITLE
[Feature Request] Support default AV1 output option, take 2

### ISSUE THREAD

**Issue by saschanaz** [NickeManarin/ScreenToGif#1099]
**Is your feature request related to a problem? Please describe.**
It has been a few years since I opened #547. It seems it's now supported well.

**Describe the solution you'd like**
```
-vsync passthrough 
-hwaccel auto 
{I} 
-c:v librav1e 
-preset fast 
-pix_fmt yuv420p 
-vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" 
-crf 30 
-b:v 0 
-f webm 
{O}
```

**Describe alternatives you've considered**
`libaom-av1` also exists but `librav1e` was over 2 times faster and generated smaller file with the above options.

**Additional context**

**Comment by NickeManarin** [comment]
I'll add support for 3 new encoders (`libaom (libaom-av1), SVT-AV1 (libsvtav1), and rav1e (librav1e)`), but the correct version of `ffmpeg.exe` needs to be used. 

I'll update the ffmpeg downloader to get version 4.4.1.
