### ISSUE TITLE
[Feature Request] Pressing enter on text boxes commits changes

### ISSUE THREAD

**Issue by duarteframos** [NickeManarin/ScreenToGif#11]
For example pressing <kbd>Enter</kbd> on the _Save as_ file name text box will save the file (same as pressing the save button bellow)
Pressing <kbd>Enter</kbd> on the _Editor > Playback > Delay Between Frames_ value box will commit it to selected frames, or using the _Override Delay_ or _Change Delay_ dialog pressing enter will 'Apply' the values as the button bellow.

**Comment by NickeManarin** [comment]
I'll keep working with keyboard improvements. :)

**Comment by duarteframos** [comment]
Lovely, thanks a lot for the great support :)

**Comment by NickeManarin** [comment]
I had to change this a bit. Enter already changes focus to the next element.

To apply or cancel the action of an open panel, you can press Alt + E or Esc.

**Comment by duarteframos** [comment]
Hum, could it be Tab to focus next element instead, and leave enter for committing values?

It seems more predictable and closer to standard behaviour this way.

**Comment by NickeManarin** [comment]
Sorry, I got confused, haha. Other app that I'm developing have this behavior (from my work place).

That's right, Tab focus to the next element and Alt + E to apply or Esc to cancel. I'll add Enter as apply too.

**Comment by duarteframos** [comment]
Hehe no problem, quickly  switching between multiple multiple applications can get confusing at times!

Sounds awesome this way, looking forward to trying it out in the next release
