### ISSUE TITLE
[Bug] Reduce frame count Delay Adjustment "Don't adjust" option is not working 

### ISSUE THREAD

**Issue by kHellstr** [NickeManarin/ScreenToGif#1102]
Reduce Frame Count Delay Adjustment "Don't adjust" option is not working. 
The Delay is adjusted even if "Don't Adjust" is selected.

1. Go to Edit Tab
2. Click on 'Reduce Frame Count '
3. Set Delay adjustment to "Don't Adjust" 
--> The Delays of frames are adjusted after reducing frame count 

Expected behavior:
Delays should not be adjusted when "Don't Adjust" is selected.

Windows 11

**Additional context**
Thank you for the great app

**Comment by NickeManarin** [comment]
Thank you for the feedback. 

It happened when the removal factor was set to 1.
Version 2.37 is not going to have this bug anymore.
