### ISSUE TITLE
[Bug] Breakage

### ISSUE THREAD

**Issue by dcxstq2** [NickeManarin/ScreenToGif#1103]
**Describe the bug**

Breakage occurs in the elements that the mouse comes into touch with. It's hard to explain in words, so here's a gif

https://ibb.co/XZCbnsc

How can I fix this breakage?

**To Reproduce**

**Expected behavior**

**Screenshot**
 https://ibb.co/xLCdGZF

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 21H2]
 - Version [e.g. 2.36 x64 light version]

**Comment by NickeManarin** [comment]
This is caused by temporal compression.
You can use other encoders (FFmpeg or Gifski) or disable the option "Detect unchanged pixels", but that's going to increase the size of the gif.
