### ISSUE TITLE
Install screentogif with ffmpeg.exe got permission problem on windows 11

### ISSUE THREAD

**Issue by hiepxanh** [NickeManarin/ScreenToGif#1104]
**Describe the bug**
Cannot install ffmpeg.exe on windows 11
"Access to the path 'C:\Program Files\ScreenToGif\ffmpeg.exe' is denied."
**To Reproduce**
1) install
2) select includes ffmpeg
3) get error

**Expected behavior**

**Screenshots**
![Animation](https://user-images.githubusercontent.com/16970990/164363417-1bcfc956-b33b-4a05-bc9a-b5e3dba107b1.gif)

log file here

[ScreenToGif.log](https://github.com/NickeManarin/ScreenToGif/files/8526919/ScreenToGif.log)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Version [e.g. 2.35.2]

**Additional context**
work around, download manually

**Comment by hiepxanh** [comment]
lol I'm using ScreenToGif to record ScreenToGif error. So awesome. You are the best <3 1000 loves to you

**Comment by NickeManarin** [comment]
Hello, thank you for the feedback. This issue was fixed and the installer for the next version should not have this problem anymore.
