### ISSUE TITLE
[Error] To run this application you must install .NET runtime 6.0.1

### ISSUE THREAD

**Issue by nmnithinkrishna** [NickeManarin/ScreenToGif#1105]
The error comes as soon as the application is opened. I also installed the Runtime in my system but still the error persists.

![image](https://user-images.githubusercontent.com/26877977/164383258-330ef697-9ef9-4efb-9704-0fc8b8a59192.png)

I'm using this on Winx64 machine

Thanks

**Comment by NickeManarin** [comment]
Hi, which version are you using?
Also, which version of the .NET **desktop** runtime (**NOT** .NET runtime) did you install?

With the latest version, you can use the full version instead, as it doesn't require a .NET 6 installation.

**Comment by nmnithinkrishna** [comment]
Here you go...

![image](https://user-images.githubusercontent.com/26877977/165036801-6d53c183-780d-4f08-89f0-38aab6614f03.png)

I downloaded it from the Microsoft Store. .NET Desktop Runtime 6.0.1 already installed from the link given by the tool itself.

**Comment by NickeManarin** [comment]
Try downloading v2.36 and it should work with the latest .NET Desktop Runtime version.

**Comment by nmnithinkrishna** [comment]
Thanks man @NickeManarin 

Working perfectly fine with the latest version :)

**Comment by tmssngr** [comment]
Would it be possible to compile the application in that way, that it does not need any installed .NET Desktop Runtime?
I reckon, if you download a different application and it rejects to start because no or the wrong Java Runtime Environment is installed, you would be unhappy, too.

**Comment by NickeManarin** [comment]
@tmssngr Yes, just avoid downloading the version labeled as "Light":

![image](https://user-images.githubusercontent.com/14798947/208131031-12a634c1-47c3-4bda-8357-5d88e808ad16.png)

The other versions should work without having to instal .NET 6

**Comment by tmssngr** [comment]
Out of curiosity: are these large bundles ahead-of-time compiled or - expressed with my Java knowledge - bytecode with VM?
