### ISSUE TITLE
[Feature Request] PNG-export for single screenshots

### ISSUE THREAD

**Issue by panther2** [NickeManarin/ScreenToGif#111]
@NickeManarin 
I am aware that adding a PNG-export to a software called ScreenTo**Gif** is sort of blasphemous, so I fully understand if this will be declined.

But the recent resurrection of #62 brought my attention to the possibility to take single screenshots using ScreenToGif, that I had not realized before. 

So what about adding PNG-support to this feature? That would make an alternative screenshot-software obsolete (at least for my needs)?

**Comment by panther2** [comment]
Ok ignore me... I now realized that it is already there...

**Comment by NickeManarin** [comment]
Yes, all selected frames will be saved as PNGs when saving as Images.

This feature was present since 2.4 (I believe), but it was hidden (you had to right-click on the list of frames to see a context menu with an "Export" option).

:)
