### ISSUE TITLE
[Feature Request] if fail to install, show download link 

### ISSUE THREAD

**Issue by 7K-K-H** [NickeManarin/ScreenToGif#1119]
**Is your feature request related to a problem? Please describe.**

------
i use potable version. (2.3.4)
when i click update button,  window installer show error message box. 
(i guess ... because potable version)

I suggest to ....
if fail to install like me,  show download url .
![image](https://user-images.githubusercontent.com/96602947/173266609-bc93f063-d5c6-42cb-ad8e-dd0cd5b82764.png)

**Comment by NickeManarin** [comment]
I cannot add any information to that error message as it's part of the Microsoft Installer UI.
Your version is failing to install because the app had some substantial changes between v.2.34 and 2.35 and newer versions.
