### ISSUE TITLE
Which GIF encoder to be used in which situation

### ISSUE THREAD

**Issue by panther2** [NickeManarin/ScreenToGif#112]
There are three GIF encoders to select from: 2.0 - 1.0 - System

Are there any hints, pros, cons about when to use which encoder?

**Comment by NickeManarin** [comment]
2.0 = Only good if there's not so many colors on your recording.
1.0 = General use.
System = Compatibility reasons.

My idea was to completely replace v.10 with v2.0, but I couldn't finish to develop that encoder (with more customizations).

**Comment by panther2** [comment]
Thanks a lot!

**Comment by panther2** [comment]
@NickeManarin 

I am reopening this issue as I noticed a change with the new version 2.8:

Encoder choice is now:

![stg](https://user-images.githubusercontent.com/20812775/27263430-1f26a1ae-5469-11e7-881c-674e5173dd30.PNG)

So again my question: Which encoder do you now recommend for which purpose?

Thanks a lot :smiley:

**Comment by EMLVIRUS** [comment]
@NickeManarin Why not add them to the tool tips. Now I see only 2.0 has tool tips.

**Comment by panther2** [comment]
I was under the impression that - because of the renaiming from "2.0" to "ScreenToGif" - the "new" encoder  was no longer "experimental", that's why I asked - but there still appears "experimental" in the tool tip.

@NickeManarin  would you please explain the actual status/use cases?

Thank you again :smiley:

**Comment by NickeManarin** [comment]
@panther2 Sorry, the translation (German, I believe) still uses the old naming scheme. It should be v1.0 and v2.0 as the English version says.

I'll replace when I get home. Thanks.

**Comment by panther2** [comment]
Oh, we had v2 and v1 in prior versions, even in German... that's why I thought things have changed...
Thank you, @NickeManarin  ...

So the Wiki description is still up to date?

**Comment by NickeManarin** [comment]
@panther2 Yes. :)

Next big update I'll focus on the encoding process.
