### ISSUE TITLE
[Bug] Single quote shown as comma when applying keystrokes

### ISSUE THREAD

**Issue by reduckted** [NickeManarin/ScreenToGif#1122]
**Describe the bug**
When showing keystrokes, if you press the single quote key ( `'` ) key, it is shown as a comma ( `,` ).

**To Reproduce**
1. Start recording
2. Press `'`
3. Stop the recording
4. Apply keystrokes

**Expected behavior**
The key `'` is shown as `'`.

**Screenshots**
![keystrokes](https://user-images.githubusercontent.com/10321525/174504284-67bbf931-10dd-4d05-888d-0496cc9d7e28.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 (10.0.19044 N/A Build 19044)
 - Version 2.37

**Additional context**
N/A

**Comment by jfbueno** [comment]
@reduckted What keyboard layout are you using? I'm not able to reproduce this using my configuration. I'm also in Windows 10 build 19044

**Comment by reduckted** [comment]
"English (United States)" (the QWERTY layout). I'm not sure if it helps, but [`GetKeyboardLayoutName()`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getkeyboardlayoutnamew) reports it as `00000409`.

**Comment by reduckted** [comment]
I just tried a few other things. I can also reproduce it with the the on-screen keyboard in Windows.
![osk](https://user-images.githubusercontent.com/10321525/174954495-5c4a2193-e88e-4172-b228-b17c62c73b8b.gif)

And it also occurs when editing the key strokes. Here's a gif of me pressing `;` then `'` then `.` then `,`:
![edit](https://user-images.githubusercontent.com/10321525/174955308-8fd5fd66-d04e-421b-b106-8be5c219da81.gif)

**Comment by NickeManarin** [comment]
Hi, that's weird.
For me, it's displaying correctly the `'` and `,` chars.

![112](https://user-images.githubusercontent.com/14798947/175033123-5d5e2d36-0c7f-4a8c-a20b-06b48a3fd5bc.png)

**Comment by jfbueno** [comment]
@NickeManarin I just found out what's happening and opened a PR with the fix. We can discuss further details there.

@reduckted Can you build ScreenToGif using that branch, repeat your test cases and get back in this thread?
