### ISSUE TITLE
Records accurate mouse movements but no actual content?

### ISSUE THREAD

**Issue by Kelptic183** [NickeManarin/ScreenToGif#113]
![garbage_example](https://cloud.githubusercontent.com/assets/26589908/24182936/0b17090e-0e93-11e7-8620-d7f140009597.gif)
Anything I record results in a black screen. Mouse movements are tracked accurately. I've tried messing around in the options but can't find anything that seems amiss. Any suggestions?

**Comment by NickeManarin** [comment]
Lets see, could you share your system info?

Windows version/build
Laptop or desktop?
If laptop, contains GPU?

If you have a laptop with GPU, you can try switching the settings to make the app use only the CPU or to use the GPU.

**Comment by Kelptic183** [comment]
Windows 10, Lenovo Desktop.

**Comment by NickeManarin** [comment]
I guessed that a video setting could be the culprit. I'll keep searching for answers.

**Comment by NickeManarin** [comment]
Sorry for taking so long, there's a new capture method incoming, in v2.20:
Would you like to try it? #551

**Comment by NickeManarin** [comment]
Also, the content that you tried to record could be blocked by DRM.

**Comment by NickeManarin** [comment]
Closing as inactive.
