### ISSUE TITLE
[Bug] Windows Installer: Gifski & FFmpeg installed but still needs manual configuration for app to find files

### ISSUE THREAD

**Issue by JeffJacobson** [NickeManarin/ScreenToGif#1133]
# Windows installer issue

When I use the Windows installer and select the options to install **Gifski** and **FFMpeg**, the required files are installed, but I still need to go into the *Extras* section of the application's configuration menu and tell it where the files are.

## Steps to reproduce

1. Download and run installer on Windows.
     * Download MSI installer and select options to install *FFmpeg* and *Gifski*.
     * If using `winget` to install, it doesn't let you customize installation options, so you must...
       1. Go to *Add / Remove Programs* and then *Modify*, and choose FFmpeg. (Gifski is chosen by default and already installed).
2. Open ScreenToGif *Options*.
3. Click on *Extras* in the list to the left. The *Available external tools*, *FFmpeg* and *Gifski*, are not available.
4. User must manually locate the files that the installer installed.

    | File         | Location                     |
    | ------------ | ---------------------------- |
    | `ffmpeg.exe` | `%ProgramData%\ScreenToGif`  |
    | `gifski.dll` | `%ProgramFiles%\ScreenToGif` |

## Desktop (please complete the following information)

* OS Microsoft Windows 11 Home
* Version 10.0.22000 Build 22000

## Additional context

See attached video for post-installation *Extras* configuration.

[ScreenToGif Extras.webm](https://user-images.githubusercontent.com/713754/181805573-5e97b79f-0e4e-4395-8917-9c13a2016bbb.webm)

**Comment by NickeManarin** [comment]
The app will end up datecting the files when you want to use them, it was just not detecting when in the Settings window.
I changed that.
