### ISSUE TITLE
New version creates monochrome output

### ISSUE THREAD

**Issue by Grisgram** [NickeManarin/ScreenToGif#1140]
Hi, never had to change many settings so far, always used "all at default".
Now that i upgraded to the new version, the output gif is monochrome/greyscale only.

What did change... or asked the other way round: Is this a bug, that the new default settings create a monochrome gif (for whatever reason)?
How can i get the same output as in the previous version?

Reverting back to older version now, because this is not usable.

**Comment by NickeManarin** [comment]
![image](https://user-images.githubusercontent.com/14798947/188272941-50cbd489-1167-4f3b-8b54-3686e105fe50.png)

Hi, did you select the quantizer "Grayscale"?
Can you take a screenshot of this panel for me?

After that, you could just click on reset and it should go back to the original settings.

**Comment by Grisgram** [comment]
after clicking reset the output was colored. i am not dumb, i know it was NOT set on grayscale - developer myself, i am able to configure output settings.
Can it be, that on the first launch of the version, something got messed up with the settings from the previous version? something that was not reflected in this output dialog?

tried again with the old version, the launched the .1 - same effect.
i removed settings.xaml from my roaming profile and launched. all worked ok.

maybe there has something changed, a new flag, an unlucky default value?

**Comment by Grisgram** [comment]
no longer reproducible
