### ISSUE TITLE
Ideal settings for optimum gif file size

### ISSUE THREAD

**Issue by kapooramit** [NickeManarin/ScreenToGif#1152]
Hi,

I have using screentogif for a long time now, but suddenly after the updates in the last couple of months, the output gif size has gone from 500KB to 4-5MB. And this is huge difference. I assumed it was some setting I did unintentionally so I uninstalled, deleted all traces and reinstalled. Still ditto issue. What am doing wrong? 30secon gif should not be 3-4MB!! It was not like this earlier. 

How can i fix it?

**Comment by NormandoHall** [comment]
Use mp4 with standard settings (ffmpeg) and you will get a file size below 500KB

**Comment by kapooramit** [comment]
Thank you @NormandoHall . But why is the gif size and time it takes to create gif has gone exponentially up and not like it was a few releases before? What changes and why.

The problem is I need to use gif and not mp4 or any other format - the way Microsoft does in their docs these days.

**Comment by NickeManarin** [comment]
Hello @kapooramit 

Usually when that happens, those two options at the bottom are unchecked.

![image](https://user-images.githubusercontent.com/14798947/196491862-57c29bf5-20e3-416a-834f-eed406231066.png)

Anyway, if in doubt, just press the "reset" button at the top to return to the default settings.

**Comment by kapooramit** [comment]
Thank GOD! and Thank you @NickeManarin . Finally! I am so relieved! It is working now like it used to - size and speed - both :-)
