### ISSUE TITLE
Gif speed

### ISSUE THREAD

**Issue by Frankusky** [NickeManarin/ScreenToGif#116]
I was trying to make a lighter by making it smaller since actually weights 30mb, I wonder if there is a way I can make the gif reproduce faster. Example: saying my gif has 300 frames that takes 4 seconds to reproduce it totally, I would like that the same gif would be completely reproduced at 2 seconds.

I saw that I can edit the frame speed but only of 1 frame at a time, so its kinda tedious to change the frame speed of the 300 frames.

Regards

**Comment by NickeManarin** [comment]
Making the gif to go faster will not reduce the file size, only if you remove frames or decrease the amount of changes among frames.

There's a function called "Edit > Reduce frame rate" that allows you to remove frames and update the framerate to make up for the frames being removed.

But if you just want to decrease de frame speed (also known as frame delay) to make the gif go faster, you can select multiple frames by Ctrl + A and open the "Edit > Increase or Decrease" to adjust the delay/speed of the frames.

**Comment by Frankusky** [comment]
Oh, nvm, I was still using version 2, thats why I didnt saw that options. Thanks!
