### ISSUE TITLE
[Bug] Unable to import frames from video using ffmpeg

### ISSUE THREAD

**Issue by NormanMises** [NickeManarin/ScreenToGif#1165]
**Describe the bug**
Unable to import frames from video using ffmpeg
I have configured ffmpeg, it is the latest version of the build that I downloaded. But when I use ffmpeg to import video frames, it doesn't work and the progress bar stays at 0 without change.

**To Reproduce**
Just use ffmpeg to import video frames

**Expected behavior**
Video frames can be successfully imported

**Screenshots**
![image](https://user-images.githubusercontent.com/38835726/215727944-1bc0f2e4-f4f0-44f9-9a8a-3af13fa2a205.png)

**Desktop (please complete the following information):**
版本	Windows 11 家庭中文版
版本	22H2
安装日期	‎2022/‎05/‎12
操作系统版本	22623.1245
体验	Windows Feature Experience Pack 1000.22638.1000.0

**Additional context**
might be the log
► Title - 
	Purging cache
♦ [Version] Date/Hour - 
	[2.37.1] 01/31/2023 17:55:40
▬ Message - 
	The process cannot access the file '0a207526-6eb8-4d6b-969a-5ca6aa0c8a53.tmp' because it is being used by another process.
○ Type - 
	System.IO.IOException
▲ Source - 
	System.Private.CoreLib
▼ TargetSite - 
	Void RemoveDirectoryRecursive(System.String, WIN32_FIND_DATA ByRef, Boolean)
♠ StackTrace - 
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at ScreenToGif.Util.StorageUtils.PurgeCache() in C:\Users\nicke\source\ScreenToGif\ScreenToGif\Util\StorageUtils.cs:line 19

----------------------------------

**Comment by NormanMises** [comment]
Even though I changed the cache location, it still doesn't work

**Comment by 7peanuts** [comment]
> Even though I changed the cache location, it still doesn't work

换一个 ffmpeg 版本，或者使用 STG 下载的 ffmpeg

**Comment by cherinyy** [comment]
I had the same problem with FFmpeg from [gyan.dev](https://www.gyan.dev/ffmpeg/builds/).

FFmpeg version: 2023-08-30-git-7aa71ab5c0

**Comment by cherinyy** [comment]
[FFmpeg 5.1.2](https://github.com/GyanD/codexffmpeg/releases/tag/5.1.2) works fine.

**Comment by NickeManarin** [comment]
Fixed, it will be available with the next version of the app.
