### ISSUE TITLE
[bug]clear temp folder doesn't work

### ISSUE THREAD

**Issue by EMLVIRUS** [NickeManarin/ScreenToGif#117]
[v2.7 on Windows 10.15063.13]

![5b5d540f-fc57-4db8-9ab9-891db33ad25f](https://cloud.githubusercontent.com/assets/16912240/24905186/a5206cd6-1ee5-11e7-81bb-45e217223995.gif)

**Comment by EMLVIRUS** [comment]
Note: In that recording, the third folder is actually the gif I pasted here, aka my recording mistake.

**Comment by NickeManarin** [comment]
As it looks like, you answered **Yes** to keep all recent project (Less than 5 days old). You should answer **No** if you want to erase every project. :)

**Comment by EMLVIRUS** [comment]
This can be reallt embarassing. Sorry for that. 🤐
