### ISSUE TITLE
[Bug] Keystroke editing does not update content

### ISSUE THREAD

**Issue by JudyLipinski** [NickeManarin/ScreenToGif#1175]
**Describe the bug**
I have edited keystrokes, removing them, and hit apply. They are still in the frames.

**To Reproduce**
1. Go to Edit Your Keystrokes
2. Remove the keystrokes from the frames
3. Click Ok, then apply to all
4. See they are still there.

**Expected behavior**
That teh keystrokes removed from Edit Your Keystrokes would be removed.

**Screenshots**

![keystroke-removed](https://user-images.githubusercontent.com/1499472/221433602-52d0f072-0df7-4d80-aad1-512310c5bbff.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version I dont see where to get this, though I downloaded two days ago

**Additional context**
Just wanted to say - loving your software and will be donating soon.

**Comment by NickeManarin** [comment]
Hi, did you apply the keystrokes before editing them?

When you hit Apply, the keystrokes are merged with the frame.
So, to be able to edit the keystrokes, do it so before applying them.

Next major version (v3) will work differently, you'll be able to edit the content on the go, working as a separated layer.

**Comment by JudyLipinski** [comment]
Thanks NickeManarin 

Looking forward to seeing the next version. 

I did hit Apply first - as I could not see the keystrokes until I did that.

I see now it is in the Edit menu.

Hope the next version makes it easy to remove keystrokes for most of the frames, rather than one by one. 

This is my most favorite app as of late.

Once I finish this project - I am donating. **Thank you!!!**
