### ISSUE TITLE
[Feature Request] Quickly seek frames through shortcut or rather control button in Playback/Frame controls.

### ISSUE THREAD

**Issue by JergenRoss** [NickeManarin/ScreenToGif#1176]
**Is your feature request related to a problem? Please describe.**
I don't like every next one frame seek using `arrow` or rather `pageup , pagedown` because I tried holding to next frame but there's 5000 over frames that too much precise seek frames. I need quickly seek like next 10 frames via shortcut keyboard for Playback/frame controls.

**Describe the solution you'd like**
I'd like add slow/fast or next `#` step seek frames through shortcut keyboard or control button. most app existing quickly. there is `Ctrl` + `arrow` or rather `pagedown` was not bound, so could be add this default.

**Comment by NickeManarin** [comment]
Done, PageUp/Down are already bound to the list, so I added some keyboard modifiers to it.

PageUp/Down + Control = 5 frames.
PageUp/Down + Alt = 10 frames.
PageUp/Down + Control + Alt = 20 frames.
