### ISSUE TITLE
Avast says maybe risk in 2.7.1

### ISSUE THREAD

**Issue by LiangWei88** [NickeManarin/ScreenToGif#118]
I download version 2.7.1
Avast says maybe risk, and ScreenToGif crash when I open again.
But then I try 2.7
Everything is ok.

**Comment by NickeManarin** [comment]
Maybe because v2.7.1 is a recently created binary. Try adding it to the avast exception list.

**Comment by NickeManarin** [comment]
Did it work out?

**Comment by LiangWei88** [comment]
Hi, I didn't try the 2.7.1
Because the 2.7 is all ok, so I used the version 2.7.
Thank for create this amazing app ^_^

**Comment by NickeManarin** [comment]
Oh, ok. Thank you. :)
