### ISSUE TITLE
"Detect Mouse Click" only detect left click

### ISSUE THREAD

**Issue by byzod** [NickeManarin/ScreenToGif#119]
Demo
![Left Click Only](https://i.giphy.com/3ohzdTWFd5EwwWhTkQ.gif)

**Comment by NickeManarin** [comment]
It's by design, but I can include the other buttons as an enhancement.

**Comment by byzod** [comment]
YES! Please make that happen!

**Comment by Kristinita** [comment]
@byzod , [**this my AutoHotkey script**](https://www.pastery.net/wesknr/) detect all mouse buttons click + mouse click with modifiers, for example, <kbd>Ctrl+Left_Click</kbd>.

Thanks.

**Comment by NickeManarin** [comment]
Done. It will detect all types of buttons (Left, Right, Middle, X1, X2).
