### ISSUE TITLE
Snap to Window, doesnt capture whole windows or dialogs

### ISSUE THREAD

**Issue by positr0nic** [NickeManarin/ScreenToGif#120]
This has been a problem for many versions, Snap is essentially broken you cant select a whole Window or dialog only the inner portions of either, so if capture involves these parts they are left out.

Only way to get the whole area is by manually expanding ScreenToGif capture area.

ScreenToGif version: 2.7.1
OS: Windows 7 Ultimate Sp1 / Windows 10 1607 / 1703

## Captures of problem.

**Snap to whole dialog - Mission impossible 1**
![solve](https://cloud.githubusercontent.com/assets/25669462/25085149/90f56d98-2358-11e7-9d22-b84a98374422.gif)

**Snap to whole Window - Mission Impossible 2**
![solve2](https://cloud.githubusercontent.com/assets/25669462/25085232/fedce23c-2358-11e7-81cd-fcb7ce9baaec.gif)

## Good capture examples - Expected area snap should snap to.
These were captured with Snipping tool to illustrate the expected  areas of dialogs / windows to be captured by snap.

**Dialog**
![solve](https://cloud.githubusercontent.com/assets/25669462/25085322/74168094-2359-11e7-9150-dc707dfbd8e9.PNG)

**Window**
![solve2](https://cloud.githubusercontent.com/assets/25669462/25085332/805bdcfa-2359-11e7-9454-2c4c1c02007a.PNG)

**Comment by NickeManarin** [comment]
Oh, it's a problem with the rectangle that for some reason fails to be painted on top of the window chrome/border.

I tested with W10 1607, the app snaps to the entire window, just the rectangle that does not show.

But I realized that I can improve the snapping region, expand a little bit to fit the whole window + border.

![lol](https://cloud.githubusercontent.com/assets/14798947/25087879/76150dfe-2348-11e7-882d-62e2a6696810.gif)

**Comment by positr0nic** [comment]
Ah right you are, so that is the actual issue, because I didnt see a painted area around the desired Windows/Dialog complete area, naturally assumed that it wasnt being selected.

As an offtopic: see https://www.windows10forums.com/threads/screentogif-if-a-picture-speaks-1000-words-a-sequence-speaks-volumes.12790/

**Comment by positr0nic** [comment]
Actually there seems to be a bigger issue at least here.

I was just trying to capture my NIC properties dialog via snap and it will definetly not snap.

![ugh](https://cloud.githubusercontent.com/assets/25669462/25092424/89249d78-2385-11e7-94b7-e03f160bb352.gif)

the only way was manually

![pattermatch](https://cloud.githubusercontent.com/assets/25669462/25092430/923c1008-2385-11e7-85b5-a035686ae786.gif)

**Comment by NickeManarin** [comment]
Indeed, just tested. 
Is it a window opened with admin rights? It looks like it's not working with any window like that.

**Comment by positr0nic** [comment]
No admin rights on that one, there wasnt even UAC prompt.

**Comment by NickeManarin** [comment]
Alright, it looks like I'm not able to get any MouseUp/MouseDown events while the cursor is on top of windows opened with admin rights (the adapter properties window follows the same rule, it just doesn't show any UAC dialog, you can see by the shield icon of the context menu)

![image](https://cloud.githubusercontent.com/assets/14798947/25262599/6a94bdf0-262f-11e7-9821-79b5ce75c4bf.png)

So, in order to work, I had to make a little hack. For that kind of window, the Snap To Window will only work after you release the mouse button AND move the cursor after that.

Also I adjusted the region of snap, it will show the border of the window.

This fix will be available for v2.7.2 or v2.8.0.

Thanks for the feedback.

**Comment by positr0nic** [comment]
No problem, and thank you for the fix. will be looking forward to see it.

**Comment by Partixel** [comment]
@NickeManarin 
Still happening ( Doesn't have admin privileges ):
![gif 1](https://cloud.githubusercontent.com/assets/2728862/26000061/5a94dba0-371f-11e7-98c8-37d2e1a73ea9.gif)

**Comment by NickeManarin** [comment]
Looks alright. The small offset will not be recorded.

**Comment by Partixel** [comment]
Sorry, I mean it doesn't show around the edge of the window when I hover over the top bar

**Comment by NickeManarin** [comment]
Oh, that I could not fix... I'm not sure why. I'm using the a Windows API to draw the rectangle.

**Comment by Partixel** [comment]
Very weird :(

**Comment by Partixel** [comment]
I think I figured out what's going on.

You're creating it in the context of the window the mouse is over, which has a clipping zone around itself, not including the title bar.

Maybe create the rectangles in the context of the screen2gif window so it isn't clipped?

( I've never used VS before, this was just from a quick look around and google )

**Comment by Partixel** [comment]
Working code snippet:
Line 769 of Native:
`var hdc = GetWindowDC(IntPtr.Zero);`
Remote line 775 of Native

Seems to cause a lot of lag when moving the mouse around though, No idea if that's because I'm running it from VS?

**Comment by Partixel** [comment]
Also thanks to that fix I noticed you can select Screen2Gifs window.. Not sure if that's a bug?

**Comment by NickeManarin** [comment]
Awesome, thanks.

Yeah, it lags because of the MouseHook, the listener that capture mouse inputs outside the app. When running from the VS, it will lag a lot.

**Comment by Partixel** [comment]
The ``OffsetRect(ref rect, -rect.Left, -rect.Top);`` line as it's now being drawn from the edge of the screen
