### ISSUE TITLE
Error in StringResources.en

### ISSUE THREAD

**Issue by Regmos** [NickeManarin/ScreenToGif#1200]
While working on a StringResources.da update, I noticed this.
When hovering over Image Tab => Mouse Events the tooltip is wrong.

![MouseEvents](https://github.com/NickeManarin/ScreenToGif/assets/811857/0af5d119-2d9a-48f1-a08e-b6a94c3cf932)

If 
**line 126**    <s:String x:Key="S.Command.**_MouseClicks_**">Mouse clicks</s:String>
Is changed to
**line 126**    <s:String x:Key="S.Command.**_MouseEvents_**">Mouse clicks</s:String>
Everything is OK.

Kind regards 
Regmos

**Comment by NickeManarin** [comment]
Fixed by @matthew-e-brown
