### ISSUE TITLE
None of the Github links work to download exe packages

### ISSUE THREAD

**Issue by rkelbel** [NickeManarin/ScreenToGif#1212]
I'm unable to use any of the listed links on the .exe downloads and Chocolatey fails because of the same issue.

I don't know if this is a Github issue or a maintainer issue, but something that likely you'd want to be aware of so the app is available for download.

**Comment by NickeManarin** [comment]
Github had an outage a few hours ago.

https://www.githubstatus.com/incidents/gqx5l06jjxhp
