### ISSUE TITLE
Add a way to indicate which frame will be used for the printed version of an animated gif

### ISSUE THREAD

**Issue by marclaporte** [NickeManarin/ScreenToGif#1220]
An animated gif can be great in a web browser. For example:
![728x90-banner](https://github.com/NickeManarin/ScreenToGif/assets/1004261/258827c5-9f4e-4902-ad64-e9d8bb1dc6c5)

However, when printed, it uses this frame (yuck):
![2023-08-04_004236](https://github.com/NickeManarin/ScreenToGif/assets/1004261/490f2561-ce06-4ec6-a509-9173eb164077)

**Comment by NickeManarin** [comment]
It will use the first frame of the gif.
We can't control this.

What you can do is to make a frame at the beggining to be the frame that you want to use in print.
