### ISSUE TITLE
Menu bar labels impossible to read when focus on window is set.

### ISSUE THREAD

**Issue by positr0nic** [NickeManarin/ScreenToGif#123]
![focusunreadabletxt](https://cloud.githubusercontent.com/assets/25669462/25305758/04572bc2-2779-11e7-9513-c262d16f262f.gif)

That example starts without focus on ScreenToGif Editor windows i.e. clicked desktop area, label text is dark and easy to read on Menu Bar area.

As soon as you click into ScreenToGif Window, the labels go very pale and hard to read both on mouse over and normal text on Menu Bar Area.

ScreenToGif 2.7.1
Windows 10 Pro 1607 14393.1066
Creators Update 1703 15063.138
Windows 7 Ultimate Sp1

**Comment by NickeManarin** [comment]
Just to check, under **Windows Settings > Personalization > Colors**

![image](https://cloud.githubusercontent.com/assets/14798947/25305998/8de8e8d0-275b-11e7-8f18-8ce3e0b86d21.png)

Do you have the second option unchecked?

If so, as a workaround, go to **ScreenToGif Option > Interface** and uncheck the "Extend titlebar/chrome"

As a bug fix, I need to find the registry entry that defines that property (if > W10) and always display black as the foreground color of that text.

**Comment by positr0nic** [comment]
I have neither of those options enabled

![capture](https://cloud.githubusercontent.com/assets/25669462/25314739/7c0e5b54-2841-11e7-848b-042cbebca128.PNG)

> If so, as a workaround, go to ScreenToGif Option > Interface and uncheck the "Extend titlebar/chrome"

Excellent that indeed does the trick :D

> As a bug fix, I need to find the registry entry that defines that property (if > W10) and always display black as the foreground color of that text.

Ill have a look around and see if I find it and report back if I do.

In meanwhile thx for that tidbit.

**Comment by NickeManarin** [comment]
Just to explain what's happening, the app looks for the current accent color in the registry, so if "Show colour on title bar" isn't checked, the app will still find the accent color.

It`s fixed now. Wait for the next release. Thanks for the feedback.
