### ISSUE TITLE
[Easy discard button] Easy discard current recording button

### ISSUE THREAD

**Issue by EdwinHauspie** [NickeManarin/ScreenToGif#1231]
A button on this interface to quickly discard current recording, would really come in handy for me personally.

![image](https://github.com/NickeManarin/ScreenToGif/assets/2393930/0b826b10-9bb5-4084-b4ed-7c06798b0cce)

**Comment by AmanKumarxxx** [comment]
Hello

**Comment by AmanKumarxxx** [comment]
Rawdyboy

**Comment by AmanKumarxxx** [comment]
https://user-images.githubusercontent.com/2393930/269266853-0b826b10-9bb5-4084-b4ed-7c06798b0cce.png

**Comment by NickeManarin** [comment]
You can do that already, near the place where you activated compact mode:

![image](https://github.com/NickeManarin/ScreenToGif/assets/14798947/e8f61e50-1beb-4a80-a09e-98571d9148ec)

Then it would appear like this:

![image](https://github.com/NickeManarin/ScreenToGif/assets/14798947/a90d74dc-1228-4102-bd74-5950ca3177d2)
