### ISSUE TITLE
Palette Quantizer in C#

### ISSUE THREAD

**Issue by positr0nic** [NickeManarin/ScreenToGif#124]
https://www.codeproject.com/articles/66341/a-simple-yet-quite-powerful-palette-quantizer-in-c

This maybe help.

**Comment by NickeManarin** [comment]
Yes, I'm aware of that project. I found something more simple with a few color quantization examples as well.

**Comment by positr0nic** [comment]
Ah sure, I had read in another ticket you were looking for something along those lines.

Have you implemented it yet or is that on your no doubt large todo list? ;)

**Comment by NickeManarin** [comment]
I started working with a new color quantizer, but it looks like it will take some time to finish.

**Comment by positr0nic** [comment]
Ah nice...

Ill close this, feel free to reopen if you feel it serves some purpose.... Have a nice rest of Sunday ;)

**Comment by NickeManarin** [comment]
Thank you :) Have a nice day you too.
