### ISSUE TITLE
[Feature request] Save project if save file

### ISSUE THREAD

**Issue by Kristinita** [NickeManarin/ScreenToGif#125]
### 1. Request

It would be nice, if you add option: `Save project, when file save`.

### 2. Justification

I always save projects, because I can make errors, and I may need edit my projects. If you add option, it may save users time.

### 3. Steps to reproduce

I record and edit any GIF → `File` → `Save As` → `GIF` → I wrote file name → `Save`.

### 4. Actual behavior

To save a project, each time I need `File` → `Save As` → `Project` → I wrote project name → `Save`.

### 5. Expected behavior

If `Save project, when save file = True`, when I create a file, project with the same name create for me.

Thanks.

**Comment by NickeManarin** [comment]
Done. 

![saveas](https://user-images.githubusercontent.com/14798947/31041467-532f57f8-a56c-11e7-9559-e228929dd230.PNG)
