### ISSUE TITLE
.NET 8.0 has Windows Arm64 Installer

### ISSUE THREAD

**Issue by iKineticate** [NickeManarin/ScreenToGif#1259]
**Describe the bug**
Windows on arm must install .NET 8.0(x64) 

**Expected behavior**
.NET 8.0 has Windows Arm64 Installer

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11 on ARM]
 - Version [e.g. 2.40]

**Comment by NickeManarin** [comment]
The installer calls this WinAPI method to get the OS architecture:

        [DllImport("kernel32.dll", SetLastError = true)]
        private static extern bool IsWow64Process2(IntPtr process, out ushort processMachine, out ushort nativeMachine);
        
I don't have access to a Arm64 machine right now to be able to test it properly.
