### ISSUE TITLE
Bugs(Incorrect hot key & unstable free text & watermark flaws)

### ISSUE THREAD

**Issue by byzod** [NickeManarin/ScreenToGif#126]
- `Free Text` said its hotkey is `Alt+F` however `Flip` popped up when press alt+f
![Incorrect hotkey](http://i.imgur.com/va0rnGL.gif)
---
- `Free Text` is unstable when you try to drag it. This won't happen to the dragging of `Watermark`.
![Unstable free text](http://i.imgur.com/82YCn6d.gif)
---
- You can not 'reset' image source to it's original resolution without restarting the application.
- The `scale` thing is confusing because change the shape/size of watermark image is irrelevant to the value of `scale`. The value of `scale` can't change the height/width ratio of image neither.
![Cannot reset image source](http://i.imgur.com/1ZvRnxG.gif)
---
- Weird things happened if you try to place the watermark image to the boarder: it became 'fatter' or 'taller'...lol
![Edge glitch](http://i.imgur.com/atqnNtP.gif)

**Comment by NickeManarin** [comment]
1) Fixed.

**Comment by NickeManarin** [comment]
All done. Thanks.
