### ISSUE TITLE
[Bug] Can no longer use user interaction as trigger in newer version

### ISSUE THREAD

**Issue by MichaelWoodc** [NickeManarin/ScreenToGif#1263]
**Describe the bug**
I was able to capture all user interaction inside a VM previously.  I had to redo my PC, and it doesn't work anymore.  I want to make instructionals but can't because it doesn't capture on every mouse click.  Microsoft problem recorder has no problem, but I don't understand what changed in screentogif for this problem to happen.  

**To Reproduce**
1. Open VMware pro
2. Click anywhere

**Expected behavior**
I would love for it to capture the events as it did previously

**Screenshots**
If applicable, add screenshots to help explain your problem.  (Please notice how clicks inside the VM don't do anything, but if I click on the taskbar it does)

https://github.com/NickeManarin/ScreenToGif/assets/51295010/0766c572-411e-43db-852a-4192b3179e6c

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version 22H2

**Additional context**
It worked only days ago, not sure what happened :(

**Comment by MichaelWoodc** [comment]
In multiple acts of hopeless desperation, as I had to complete everything quickly, I enabled developer mode.  This seems to have made it work for my use case.  

Can anybody confirm this is the only required change to capture user events inside vms and protected windows?  If not I'll go over everything I tried

**Comment by MichaelWoodc** [comment]
Ok I just updated to vmware 17.5 and I now have the same issue.  One thing I had done on my previous VM was I enabled hyperv after having vmware installed.  When I updatd, I was greeted with tthe following screen:
![vmware install question](https://github.com/NickeManarin/ScreenToGif/assets/51295010/48481193-b7cb-4654-8cb1-237c1a16b77b)

I think that this feature is what disables it from being able to detect the clicks.  Not sure though.

**Comment by NickeManarin** [comment]
Hello Michael! 

ScreenToGif needs the OS to report the clicks or else nothing can be done.

If the clicks are not being registered (or are being done in a admin-run window, I simply won’t receive them).

**Comment by MichaelWoodc** [comment]
> Hello Michael!
> 
> ScreenToGif needs the OS to report the clicks or else nothing can be done.
> 
> If the clicks are not being registered (or are being done in a admin-run window, I simply won’t receive them).

Thanks for the response!  I am not sure what I did, but somehow, I got it to work again.  I had to downgrade vmware, and I did so many things but it wasn't working.  After restarting my PC it worked fine.  

So it's obvious to me it's not a bug at this point.  I love the program!  If only I knew enough about this kindof programming to contrubute and make it seamless for these very rare use cases lol.  Thank you!!

**Comment by MichaelWoodc** [comment]
I think the trick is to actually run screenToGif as admin, AND for some reason the other app had to be run as an administrator, then it could capture mouse clicks.  Hope this helps anyone trying to grab user events from inside a "protected" app!  (You won't be able to capture keystrokes though a VM, clicks only, there's lots of VM isolation going on)

https://github.com/NickeManarin/ScreenToGif/assets/51295010/fa846f11-506d-4a91-9c8d-5920cdb11c6d
