### ISSUE TITLE
Crowdstrike antivirus flags ScreenToGif.dll as virus

### ISSUE THREAD

**Issue by richardsjogren** [NickeManarin/ScreenToGif#1264]
Crowdstrike antivirus flags ScreenToGif as virus
(Sorry, not sure if it´s ok to report this as a "bug")

1. Try to install ScreedToGif on computer with Crowdstrike

https://www.virustotal.com/gui/file/95542221c818831363148465643614273f819c08065a0870dade8ddba6edb1ad

**Comment by Vincent-FundApps** [comment]
+1

**Comment by TrevisanGMW** [comment]
+1

**Comment by mattspierce** [comment]
I've had a few user experiencing this.  Here are the details of the detection.

DETECT TIME
Dec. 17, 2023 12:48:24
HOSTNAME
computername
HOST TYPE
Workstation
USER NAME
place\user
ACTIONS TAKEN
Process blocked
File quarantined
SEVERITY
Low
OBJECTIVE
[Falcon Detection Method](https://falcon.laggar.gcw.crowdstrike.com/documentation/detections/objective/falcon-detection-method)
TACTIC & TECHNIQUE
[Malware ](https://falcon.laggar.gcw.crowdstrike.com/documentation/detections/tactic/malware-csta0001)via [PUP](https://falcon.laggar.gcw.crowdstrike.com/documentation/detections/technique/pup-cst0013)
TECHNIQUE ID
CST0013
SPECIFIC TO THIS DETECTION
This file is classified as Adware/PUP based on its SHA256 hash.
TRIGGERING INDICATOR
Associated IOC (SHA256 on library/DLL loaded)
ad17b9409ac2b46f54c5fbd220d48d091ca7a1b8d91c20f15b00b93c6f6ca69d
GLOBAL PREVALENCE
Common
LOCAL PREVALENCE
Low
IOC MANAGEMENT ACTION
None

Associated File
\Device\HarddiskVolume6\Program Files\ScreenToGif\ScreenToGif.exe
GROUPING TAGS
None
LOCAL PROCESS ID
26000
COMMAND LINE
"C:\Program Files\ScreenToGif\ScreenToGif.exe"
FILE PATH
\Device\HarddiskVolume6\Program Files\ScreenToGif\ScreenToGif.exe
EXECUTABLE SHA256
ad17b9409ac2b46f54c5fbd220d48d091ca7a1b8d91c20f15b00b93c6f6ca69d
GLOBAL PREVALENCE
Common
LOCAL PREVALENCE
Low
IOC MANAGEMENT ACTION
None

EXECUTABLE MD5
ce227688fe0d35e6b5381666dc1cd7db
RUN PERIOD
START TIME
Dec. 17, 2023 12:47:14
END TIME
Dec. 17, 2023 12:47:15
DURATION
Terminated

**Comment by jduke-halls** [comment]
Just had a trigger with the new version

## Steps to reproduce detection:
* Download ScreenToGif Portable from link at screentogif.com
  * https://github.com/NickeManarin/ScreenToGif/releases/download/2.40.1/ScreenToGif.2.40.1.Portable.x64.zip
* Extract ScreenToGif.exe
* Run ScreenToGif.exe

## Metadata from Crowdstrike Detection
```
ACTIONS TAKEN
Process blocked
File quarantined

SEVERITY
Low

OBJECTIVE
Falcon Detection Method

TACTIC & TECHNIQUE
Malware via PUP

TECHNIQUE ID
CST0013

SPECIFIC TO THIS DETECTION
This file is classified as Adware/PUP based on its SHA256 hash.

TRIGGERING INDICATOR
Associated IOC (SHA256 on library/DLL loaded)
fe13f363f2c5940eb7010eeee25763575b86d945fa7d70f54c2cce9c4c6f54c6

GLOBAL PREVALENCE
Common

LOCAL PREVALENCE
Unique

IOC MANAGEMENT ACTION
None

Associated File
\Device\HarddiskVolume3\Apps\ScreenToGif.exe
```

VirusTotal has no detections https://www.virustotal.com/gui/file/fe13f363f2c5940eb7010eeee25763575b86d945fa7d70f54c2cce9c4c6f54c6/detection

HybridAnalysis doesn't have a sample: https://www.hybrid-analysis.com/sample/fe13f363f2c5940eb7010eeee25763575b86d945fa7d70f54c2cce9c4c6f54c6

## What we did
We created a group in Falcon for those who can run ScreenToGif and tagged the computers to allow an exception to `*\ScreenToGif.exe`

**Comment by NickeManarin** [comment]
I sent a message to the company, let's see if they give me a reply.

**Comment by mcd92** [comment]
Same thing here. Antivirus McAfee.

**Comment by elliottttttttt** [comment]
> I sent a message to the company, let's see if they give me a reply.

We have the same issue and have asked our CrowdStrike TAM to assist. Hoping that you receive some assistance back from the vendor. In case it's helpful we've raised support case # 01326126 on our end for misidentification as a PUP.

**Comment by DavidMulder0** [comment]
Tip: When you install through the Microsoft Store it actually works just fine... 😕 No idea what that says about CrowdStrike, but at least a workaround for those who want to use ScreenToGif 👍.

**Comment by captainhunt** [comment]
Well just as long as your company does not block MS store, too 😕.

**Comment by chrispy-snps** [comment]
@NickeManarin - I hope we are able to resolve this. I am impacted too.

**Comment by NickeManarin** [comment]
![image](https://github.com/NickeManarin/ScreenToGif/assets/14798947/8afaa482-4256-4ae5-8281-a6bec7a17cd4)

**Comment by mattspierce** [comment]
I would love for this issue to be resolved.  The detection was heuristic.  I am curious if this FP submission works with the AI engines or just a hash check.   Do we know what was added to the code in mid December that triggered the alerts?

**Comment by mattspierce** [comment]
Also, I did a test with the current version against my CS client and did not get blocked.  I will remove the IOC exception and see if my users are impacted.

**Comment by NickeManarin** [comment]
I got this details from some other company:

```
YARA signature "Bolonyokte" matched file "sample.bin" as "UnknownDotNet RAT - Bolonyokte" (Author: Jean-Philippe Teissier / @Jipe_) YARA
 signature "MALWARE_Win_AgentTeslaV3" matched file "sample.bin" as "AgentTeslaV3 infostealer payload" (Author: ditekSHen)
 ```

and

```
 "ScreenToGif.exe" wrote 00000FB8 bytes to a remote process "C:\Windows\System32\WindowsPowerShe l\v1.0\powershe l.exe" (Handle: 1728)
```

YARA Bolonyokte is a really generic rule-set as for example, it matches apps with "CaptureScreen" and "CaptureCursor" which of course this app would have. 🙄

**Comment by NickeManarin** [comment]
> mid December that triggered the alerts?

I can check, but the code base was mostly unchanged during the last 2 quarters of 2023.

**Comment by NickeManarin** [comment]
This should no longer be a problem, as the company removed the false-positive.

**Comment by p1r473** [comment]
@NickeManarin Nope its still flagging for me here as of May 5
