### ISSUE TITLE
Startup crash on win11(.msix package)

### ISSUE THREAD

**Issue by SineObama** [NickeManarin/ScreenToGif#1268]
**Describe the bug**
Crashed after inatall ScreenToGif.2.40.Package.x64.msix

**To Reproduce**
run ScreenToGif.2.40.Package.x64.msix(download by windows), autostart failed.

**Screenshots**
nothing happend

**Desktop (please complete the following information):**
 - OS: Windows 11 (21H2  22000.2538)
 - Version 2.40

[ScreenToGif.exe.3940.dmp](https://github.com/NickeManarin/ScreenToGif/files/13691169/ScreenToGif.exe.3940.dmp)

**Comment by DocMoebiuz** [comment]
<img width="938" alt="image" src="https://github.com/NickeManarin/ScreenToGif/assets/86157512/1c490a54-91df-4bac-a160-7ee10ea5e13a">

Not 100% sure if it is the same issue, but it looks like on my Win11 there is no .NET8.0 installed yet.

**Comment by FiniteLooper** [comment]
Just updated to the latest version via the in-app updater, now it won't launch for me either.  Went to the website to manually install via the installer, no change.

```
Fault bucket 1379558355639503474, type 5
Event Name: MoAppCrash
Response: Not available
Cab Id: 0

Problem signature:
P1: 33823Nicke.ScreenToGif_2.40.0.0_x64__s0jv9ksk6a4w4
P2: praid:ScreenToGif
P3: 2.40.0.0
P4: 65410000
P5: KERNELBASE.dll
P6: 10.0.22621.2792
P7: 3091b6fb
P8: e0434352
P9: 000000000006567c
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.21491135-346a-44a2-853c-1ded7d430b70.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.320d28a4-c606-46dc-8c9d-54dec305b4cb.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.2dee75c8-d73f-4f31-8eef-dce87de59096.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.1ec85279-a5bc-4b70-97bd-2209d4c011b6.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.19ed66d8-78da-455e-b11d-35f83755e4f1.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_33823Nicke.Scree_cd7c2428632c41f6d8f5f9df2e2e5314ab56df5_4f74e92c_1de37d68-f326-4e8d-901f-54f6327e1181

Analysis symbol: 
Rechecking for solution: 0
Report Id: fec80c5b-7c90-4d1b-9e35-71a1dbe78b17
Report Status: 268435456
Hashed bucket: 12092b981b7ca30d93252d03e6d08a72
Cab Guid: 0
```

**Comment by DocMoebiuz** [comment]
i uninstalled the old version and downloaded the MSI package from the website. This solved the issue for me.

**Comment by NickeManarin** [comment]
Hi, there's a fix coming in a few minutes.
The package was missing some files.

**Comment by FiniteLooper** [comment]
Had to downgrade to the previous version (v2.39) to get it to work last night. But just updated to the latest version (v2.40.1) and it now works again. That was a quick response - thanks!
