### ISSUE TITLE
[Feature Request] Option to show reason of fail of coding

### ISSUE THREAD

**Issue by inoyakaigor** [NickeManarin/ScreenToGif#1278]
I tried to save as webm but got error and  can't see why there was an error? 
<img width="310" alt="image" src="https://github.com/NickeManarin/ScreenToGif/assets/1235286/c845da93-4035-49fd-bc54-355105c61f6d">
It would be great if there was a button «Show log» in case of error

**Comment by pawlos** [comment]
@inoyakaigor clicking on the Window icon (on the right) actually show the error dialog. If you hover over it it should say "Show details"

![image](https://github.com/NickeManarin/ScreenToGif/assets/1296768/ed0b69ee-f991-4caf-bc85-94491174f8f8)

**Comment by inoyakaigor** [comment]
@pawlos Thank you! I didn't see tha button on the corner. I just tried to repeat export and get an error:
<img width="799" alt="image" src="https://github.com/NickeManarin/ScreenToGif/assets/1235286/93736df4-6834-41f2-bda6-d42736cc88de">
<details><summary>Result from screen in text</summary>
<p>

   at ScreenToGif.Util.EncodingManager.EncodeWithFfmpeg(ExportPreset preset, List`1 listFrames, Int32 id, CancellationTokenSource tokenSource, String processing) in C:\Users\nicke\source\ScreenToGif\ScreenToGif\Util\EncodingManager.cs:line 1774
   at ScreenToGif.Util.EncodingManager.Encode(ExportProject project, ExportPreset preset, Int32 id, CancellationTokenSource tokenSource) in C:\Users\nicke\source\ScreenToGif\ScreenToGif\Util\EncodingManager.cs:line 1038

Command:

-hwaccel auto -safe 0 -f concat -i "file:C:\Users\InoY\AppData\Local\Temp\ScreenToGif\Recording\2024-01-18 20-31-43\Encode 2024-01-18 08-33-20-15\concat.txt" -c:v libvpx -preset medium -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -crf 30 -q:v 5 -f webm -vsync auto -y "C:\Users\InoY\Videos\Captures\test2.webm"


Result:


ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.1 (GCC) 20200726
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --enable-librav1e --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Expected number for vsync but found: auto

</p>
</details> 

Maybe the option "auto" should be disabled for webm encoding?

**Comment by NickeManarin** [comment]
@inoyakaigor You are using FFmpeg v4, check if you have the correct version selected here:

![image](https://github.com/NickeManarin/ScreenToGif/assets/14798947/2097d3c1-ad2b-424d-a94e-7644a7ed8a1a)
(Options > Extras)

**Comment by inoyakaigor** [comment]
Oh, thank you so much! Today I learned.
