### ISSUE TITLE
[Bug] The coding progress rate exceeds 100%

### ISSUE THREAD

**Issue by inoyakaigor** [NickeManarin/ScreenToGif#1279]
**Describe the bug**
Often percenatge of encoding process exceed 100%

**To Reproduce**
Just tryed to save a video with these config
![screen to gif](https://github.com/NickeManarin/ScreenToGif/assets/1235286/c9682ff2-4e91-4cb1-b0ed-721af5fef607)

**Expected behavior**
Progress must not exceed 100%

**Screenshots**
[Link to video](https://inoy.dev/files/video_2024-02-07_15-36-07.mp4) (Can't attach because it exceed GH file size limit)
But there is most important frame:
![videoframe_70020](https://github.com/NickeManarin/ScreenToGif/assets/1235286/65ec122a-2866-4dbc-a566-7b8886651be3)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Version 2.40.1
 - ffmpeg 6.1.1

**Additional context**
The video was shot when I set the latest version of ffmpeg 6.1.1 but I've met this bug with in box ffmpeg 4

**Comment by pawlos** [comment]
Ok, this is a bit more interesting that initially anticipated.

One of the output lines from ffmpeg:

> frame=    1 fps=0.0 q=32.7 size=       0kB time=-00:00:00.04 bitrate=N/A dup=12 drop=0 speed=N/A

So it's not just a matter of removing the dup's as that would produce problems on the other end. Values below 0%. Investigating.
