### ISSUE TITLE
[Feature Request] please add guidance to tell the user how insert Date/Time in Name of file

### ISSUE THREAD

**Issue by Dr-Kaisa** [NickeManarin/ScreenToGif#1286]
**Is your feature request related to a problem? Please describe.**
it just indicate insert Date/Time in "??",but didnt tell use which word
i try many times,and find that:
- D:Date with the day of week
- HH:hour
- FF: seconds
- MM:month
but..where is mins?or day of month

**Comment by pawlos** [comment]
@Dr-Kaisa Didn't check the code but I would assume it uses the standard .NET DateTime custom formats. So mins would be 'mm', day of the month would be "dd" would be the day of the month. 'ff' - I is the fraction of a second (in this case 1/100th). Seconds would be 'ss'.

See: https://learn.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings

**Comment by pawlos** [comment]
@NickeManarin I think it would be nice addition to for example this page https://github.com/NickeManarin/ScreenToGif/wiki/Help-%E2%96%AA-Editor-%E2%9C%8F%EF%B8%8F-%E2%96%AA-Exporting-your-project-%F0%9F%92%BE#-basic-workflow-for-exporting-our-project to include info about the possible options.

**Comment by yuyeqianxun** [comment]
Insert the DateTime between ?, for example: ?yyyy-MM-dd?.
