### ISSUE TITLE
[Feature Request] Highlight mouse buttons 4 and 5

### ISSUE THREAD

**Issue by muzikbike** [NickeManarin/ScreenToGif#1292]
**Is your feature request related to a problem? Please describe.**
Currently, left clicks are highlighted in yellow, right clicks in red and middle clicks in cyan. However, using the fourth and fifth mouse buttons does not cause any colored circles to appear, despite these also being mouse buttons.

To this day, Windows does not account for the existence of mouse buttons 6 and above (unlike Mac or Linux), and since this utility appears to be designed only for Windows we don't need to account for any higher buttons at this point.

**Describe the solution you'd like**
Add some colored circles to indicate when the fourth or fifth buttons are pressed, like how #374 added support for the right click.

**Describe alternatives you've considered**
Coping with not having them show up at all? That sounds a bit depressing.

**Additional context**
All five mouse buttons are used here, in order: left, right, left, middle, fourth, fifth. The last two aren't visually shown, hence the long period of nothing happening at the end of this gif.
![mousebuttonsdemo](https://github.com/NickeManarin/ScreenToGif/assets/52297970/22533972-4c3c-40d2-b32e-ce61514ee106)

**Comment by pawlos** [comment]
Not sure if those are 4th & 5th button but there's already some info in the application about FirstExtra & SecondExtra mouse button. They just don't appear on the recording with visual indicator. I'll see if that's possible to expose.

**Comment by muzikbike** [comment]
I wonder if visual indicators for scrolling up and down would also be relevant.

**Comment by pawlos** [comment]
Well, there's also some info about scroll delta, but not sure how that would be represented on the recording

**Comment by NickeManarin** [comment]
Yes, it's possible to update the current code to add support for the extra buttons.
I just did that, but I can't test it properly as my mouse doesn't have extra buttons.

![image](https://github.com/NickeManarin/ScreenToGif/assets/14798947/0a98d176-728c-4cae-8223-305b5f492475)
