### ISSUE TITLE
[Bug] Mouse button 5 appears to be displayed as mouse button 3 in recordings

### ISSUE THREAD

**Issue by muzikbike** [NickeManarin/ScreenToGif#1296]
**Describe the bug**
When checking the fix for #1292, I noticed that mouse button 4 is correctly reported as expected, but mouse button 5 uses the middle mouse button colour instead of the mouse 5 colour.

**To Reproduce**
1. Have a mouse with five or more buttons (in this case, a Logitech G402)
2. Click using the fifth button
3. Look at the recorded frames

**Expected behavior**
It'd use the fifth button colour - orange by default.

**Screenshots**
In order: left, right, middle, fourth, fifth
![fifthismiddle](https://github.com/NickeManarin/ScreenToGif/assets/52297970/dcda34b1-3c35-4030-8e2f-14c0d85e01c4)
![image](https://github.com/NickeManarin/ScreenToGif/assets/52297970/b0eec1dd-19a5-4882-aacc-5994bda0520e)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 2.41.0

**Additional context**
Other programs recognise buttons 4 and 5 fine, so I can confirm the mouse in question is not misconfigured.
![2024-03-25_10 39 31](https://github.com/NickeManarin/ScreenToGif/assets/52297970/fc7389b9-2289-445c-9df2-ea8cb1e8870d)

**Comment by NickeManarin** [comment]
Fixed
