### ISSUE TITLE
Incorrect recording offset and size when Windows font size is above 100%

### ISSUE THREAD

**Issue by adbre** [NickeManarin/ScreenToGif#13]
I have a laptop in a multi-monitor setup. The laptop monitor is configured to 2880x1620. It's placed in a docking station and thus a bit far away as would otherwise be normal if I would have the laptop in my lap, the "size of text, apps and other items" is set to quite high 175%.

The other screen resolutions is 2560x1440 and 1200x1920, both at 100%. Recording on them works fine.
Decreasing the font size on the laptop display to 100% resolves the issue.
Increasing the font size on the other displays reproduces the issue on those displays too.

**Update**: Using version 2.2

I have attached two screenshots showing this.

![screentogif-recordingoffsetissue-1-small](https://cloud.githubusercontent.com/assets/1292956/18699838/0f555794-7fd4-11e6-8078-6841750adff4.png)
![screentogif-recordingoffsetissue-2-small](https://cloud.githubusercontent.com/assets/1292956/18699839/0f5a409c-7fd4-11e6-9361-2a436f0b7f39.png)

**Comment by NickeManarin** [comment]
Thank you for your feedback, this is a known bug.

[StackOverflow](http://stackoverflow.com/questions/36818964/dealing-with-multiple-dpi-screens)

I currently have no fix for this bug. :/

**Comment by adbre** [comment]
Even if there's no fix, is the scenario detectable?
I spent a lot of time troubleshooting, when I *just wanted to record*. Then I discovered it worked if I just dragged what I wanted to record and the recorder to the other screen... A warning/tip would have been extremely helpful at that point.

**Comment by NickeManarin** [comment]
Detecting this kind of issue is hard. It took me some time to understand it too. :/

I had a warning tagged as [Bug] before migrating to GitHub. I'll update the release notes. :)

**Comment by NickeManarin** [comment]
I believe this bug is fixed. Tested with two monitors with different dpi.
