### ISSUE TITLE
Detect Mouse Click is Broken

### ISSUE THREAD

**Issue by byzod** [NickeManarin/ScreenToGif#130]
Version: 2.7.2

Only clicking on ScreenToGif itself (border or toolbar) is detected XD

In the following gif, I clicked 6 times: 3 times on the right border of this application itself, 3 times on the webpage in Firefox.
![a 1](https://cloud.githubusercontent.com/assets/848607/25742397/e1da6700-31c1-11e7-8726-3cce5f9e3baa.gif)

**Comment by NickeManarin** [comment]
OH NO, tonight I'll make a quick fix!

**Comment by NickeManarin** [comment]
Strange, it's working here. Do you have that option enabled?

**Comment by NickeManarin** [comment]
Fixed. Download again v2.7.2
