### ISSUE TITLE
[Bug] Custom Cursor Size Not Reflected in ScreenToGif Recording

### ISSUE THREAD

**Issue by NazCodeland** [NickeManarin/ScreenToGif#1309]
**Describe the bug**
When I change my cursor size in Windows and use ScreenToGif to record, the cursor size in the recording is the default size and not the custom size I set it to.

**To Reproduce**
1. Change the cursor size in Windows settings.
2. Open ScreenToGif and start a new recording.
3. In the recording, observe that the cursor size is the default size and not the custom size.

**Expected behavior**
I expected the cursor size in the ScreenToGif recording to reflect the custom cursor size I set in Windows settings.
The following video is recorded in a different software to show the expected behaviour.
https://github.com/NickeManarin/ScreenToGif/assets/113494366/d5587eea-1a45-477a-b24f-478f55dfdcd0

**Screenshots**
![Custom cursor size resetting to default size](https://github.com/NickeManarin/ScreenToGif/assets/113494366/f06c8b6c-3c9f-4e9e-80f0-c6989729e430)

**Desktop**
 - OS: Windows 11 23H2
 - Version: 2.41

**Comment by ericchase** [comment]
Change your method capture to DirectX:
![2024-05-29_03 28 01](https://github.com/NickeManarin/ScreenToGif/assets/30473157/10f00f14-1dda-4f3c-ba45-6bc48efbb03e)

**Comment by NazCodeland** [comment]
You are the best! Thank you so much!

**Comment by danielschenk** [comment]
> Change your capture method to DirectX:

I tried this, but with DirectX my mouse doesn't appear at all. :-(
