### ISSUE TITLE
Program does not start at all (Win10)

### ISSUE THREAD

**Issue by 2090886l** [NickeManarin/ScreenToGif#131]
Running Windows 10 Anniversary Edition (x64), opening the executable does not do anything on any of the latest versions (2.5, 2.6 or 2.7). No error, just doesn't open. I might be missing some libraries perhaps? 

NOTE: I already have .NET Framework 4.6.1+

**Comment by NickeManarin** [comment]
I have PC's with the Creators Update, but I recently had the Anniversary update too, both using (x64). Everything running as expected.

Are you running directly from the Zip file? Do you have an antivirus?

**Comment by 2090886l** [comment]
Tried running from zip and extracting it, I only have Windows Defender, but it hasn't said it's blocking the program or anything.

**Comment by NickeManarin** [comment]
While running outside the zip, did you notice if the app creates a folder on the same location of the executable?

**Comment by 2090886l** [comment]
Does not create anything.

**Comment by tychoid** [comment]
Same issue here.  screentogif.exe service runs for a second. werfault.exe then runs for a moment.  Mouse cursor hangs a bit for about a second, then nothing.  No error message.  Worked a month or two ago on the same machine with the same version (2.5).  2.7.2 also doesn't launch.  Trying to identify any other changes since it last worked on my machine... can't think of any besides Anniversary and nvidia graphics drivers.

**Comment by NickeManarin** [comment]
Where exactly are you running the app? (from which folder, desktop? Program files?)

**Comment by tychoid** [comment]
When it worked, It was in a directory off the desktop.  I already tried dropping it in a few other directories, including program files x86 on my startup disk with no change in launch behaviour.

**Comment by TheCell** [comment]
Does it show up if you run it as administrator? (rightclick the exe -> run as administrator)

**Comment by tychoid** [comment]
Nope. Was the first thing I tried.

**Comment by 2090886l** [comment]
Not sure what changed, but it suddenly started working. The only two major changes I can think of that I've done is move it to a different HDD and updating to the latest NVidia drivers.

**Comment by NickeManarin** [comment]
@tychoid Do you have a similar program installed (RivaTuner)?

**Comment by tychoid** [comment]
I do have RivaTuner/MSIAfterburner installed.  I already tried closing those processes before with no change, but I have not tried stopping them from hooking during startup.  Let me try fiddling around with that.
