### ISSUE TITLE
[Feature Request] Don't override existing files

### ISSUE THREAD

**Issue by aaronshenhao** [NickeManarin/ScreenToGif#1310]
**Is your feature request related to a problem? Please describe.**
I noticed that the software actually overwrites files without warning, and the overwritten files are deleted permanently. This is really unexpected, and led to the loss of a file I made previously.

**Describe the solution you'd like**
If the file exists, prompt the user on whether they want to override the original file, or rename the new file. If the user chooses to override the original file, move the original file to the recycle bin.

**Additional context**
This is for the Windows app (hence the recycle bin).

**Comment by pawlos** [comment]
@aaronshenhao you mean the output files? 
You have an option to choose how the application behave in this case
![image](https://github.com/NickeManarin/ScreenToGif/assets/1296768/3290cb06-e566-4a1b-97fa-7f78db4a505d)
With the options other than "allow", you will be notified when you try to overwrite the file.
