### ISSUE TITLE
[Bug] Can't launch app.

### ISSUE THREAD

**Issue by leozzyzheng** [NickeManarin/ScreenToGif#1312]
**Describe the bug**
Application doesn't appear after launched, also not see it in task manager.

**To Reproduce**
1. Just double click exe to launch it.
2. Nothing happens.

**Expected behavior**
Application should show up.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - Version 22631.3593

**Additional context**
Attachment is the log file I found.
[24_05_31.txt](https://github.com/user-attachments/files/15509215/24_05_31.txt)

I can run application a few days ago, and I'm working on developing windows drivers for virtual box, so there might be many .net version installed on my machine, may be that's the root cause, but I'm not familiar with the .net environment, so I need a help, thanks!

**Comment by leozzyzheng** [comment]
@pawlos Thanks for the quick reply. I tried to remove Settings.xaml but still can't launch application, I'm going to build from source to debug it.

**Comment by pawlos** [comment]
@leozzyzheng do you have the log file from that run too? There are some local settings also - that could be the issue. I don't remember the location - maybe the app folder?

**Comment by leozzyzheng** [comment]
Here is the log
[24_05_31.txt](https://github.com/user-attachments/files/15510743/24_05_31.txt)

I can run application from visual studio, that's strange that I can't run the standalone one.

**Comment by leozzyzheng** [comment]
Is there any special steps to pack the standalone file? Providing the pack CLI would be much appreciated.

**Comment by leozzyzheng** [comment]
@pawlos I found the problem is caused by single file mode, will try to finger it out.

**Comment by leozzyzheng** [comment]
After debugging the dotnet, I think it's runtime mismatch, the problem is using the wrong libray(Baml2006) to load GUI, but I can't find why it use wrong host. Now I'm using no-self-contained version and everything works well, if I found the root cause someday, I will post here.
