### ISSUE TITLE
Mouse animation only captured the first frame

### ISSUE THREAD

**Issue by byzod** [NickeManarin/ScreenToGif#132]
# What I captured with ScreenToGif
![a 1](https://cloud.githubusercontent.com/assets/848607/25744129/cf40948a-31ca-11e7-8e58-001d2a6bd1e4.gif)

# What it actually looks like
(Have to capture via a screen recorder so it's a little blurry)
![a 2](https://cloud.githubusercontent.com/assets/848607/25744128/cf20fb02-31ca-11e7-81dd-43ce4fff8369.gif)

# Test page
https://developer.mozilla.org/en-US/docs/Web/CSS/cursor?v=example#Values

**Comment by NickeManarin** [comment]
Done! It will be available with the next version, v2.20.
The animation speed is currently bound to the recording FPS, since I can't know for sure how fast it should be.

![Animated Cursor](https://user-images.githubusercontent.com/14798947/68080906-d5548380-fde3-11e9-88a9-2ce0e1e42446.gif)
