### ISSUE TITLE
[Bug] The CTRL+SHFT+Left and CTRL+SHFT+Right do not behave as indicated

### ISSUE THREAD

**Issue by raindropsfromsky** [NickeManarin/ScreenToGif#1324]
**Describe the bug**
In the Editor, the tooltip on the **Move Left** button shows that its shortcut is CTRL+SHFT+Left.
![image](https://github.com/user-attachments/assets/05131a04-41c8-4899-805e-a0ef406b7920)
However, instead of moving the selected frame to the left, this shortcut actually extends the selection to the left.

Similarly, the CTRL+SHFT+Right contracts the selection toward the right.

**To Reproduce**
1. Open a multi-frame GIF in the Editor.
2. Select a frame in the middle of the sequence
3. Now press CTRL+SHFT+Left.
4. The selection extends to the left of the originally selected frame. **[BUG#1]**
5. Press CTRL+SHFT+Right. The selection contracts toward the right. **[BUG#2]**

**Expected behavior**

CTRL+SHFT+Left and CTRL+SHFT+Right should move the selected frame to left/right.
It should not change the selection.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version	10.0.22631 Build 22631

**Additional context**
Actually, extending and contracting the selection is a useful function.
While I have only pointed out the inconsistency between the tooltip and the actual behavior, this function should be retained.

So instead of removing the functionality altogether, other shortcuts should be assigned.

(In other words, let us have shortcuts to actually move the selection, and also to extend/contract the selection.)

**Comment by NickeManarin** [comment]
Thanks for the feedback.
Command changed to <kbd>Ctrl + Alt + Arrow</kbd>
