### ISSUE TITLE
[Bug] In the Editor UI, the tooltip on Move Left/Right buttons state "selected frame" instead of "selected frames" (plural) 

### ISSUE THREAD

**Issue by raindropsfromsky** [NickeManarin/ScreenToGif#1326]
**Describe the bug**
 In the Editor UI, the tooltip on Move Left/Right buttons state "selected frame" instead of "selected frames" 

**To Reproduce**
1. Hover the nmouse on the Move Left and Move right buttons.
2. Check the tooltip
![image](https://github.com/user-attachments/assets/145821dd-d7be-4df1-aa97-448a0701c15f)

**Expected behavior**
The tooltip should state "selected frames" (plural)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 2.35.2]

**Additional context**

**Comment by NickeManarin** [comment]
Fixed
