### ISSUE TITLE
Slow play back

### ISSUE THREAD

**Issue by gitmegitme** [NickeManarin/ScreenToGif#134]
Hi there,

Thanks for a great product.
The playback in both record and cam, is a little slower than real time.  Have I done something wrong, or is there a setting I should change please?

Thanks again.

**Comment by NickeManarin** [comment]
Unfortunately that's a heavy IO operation (that reads the images/frames from the disk). If your disk is being used by other apps, it will take more and more to load the next image/frame.

**Comment by strich** [comment]
Surely during editing the recording should sit in memory, not disk?

**Comment by NickeManarin** [comment]
Yep. :/

**Comment by LovCAPONE** [comment]
I might have found a solution to this issue. At first, I wanted to do a pull request but later I realized that not only did the solution involved a lot of code, but also that making a separate project for it would be better as some other projects might benefit from the component.

So, my solution is in this [repo](https://github.com/LovCAPONE/SharpDXFP). The major down side to it is that it has a lot of dependencies, so if you decide not to integrate it to your project, I hope that it can give you insights on how to solve this issue. If you have any questions it will be my pleasure to try to answer them as best as I can.

**Comment by mabakay** [comment]
#878 just include it here as a suggestion.

**Comment by NickeManarin** [comment]
Closing this as the performance was improved in recent releases.
