### ISSUE TITLE
Snap To Window works incorrectly when the window is not on the main monitor

### ISSUE THREAD

**Issue by cypressious** [NickeManarin/ScreenToGif#135]
I have two monitors, the right one being the main one. When the to-be-recorded window is on the left (secondary) monitor and I use the Snap to window feature, it moves to the wrong location.

**Comment by NickeManarin** [comment]
Are your monitors using different DPI's?

**Comment by cypressious** [comment]
No, two identical monitors-

**Comment by NickeManarin** [comment]
Fixed. Thanks.
