### ISSUE TITLE
[Bug] Hover shows in the top left corner

### ISSUE THREAD

**Issue by Askhento** [NickeManarin/ScreenToGif#1353]
**Describe the bug**
Hover info (or whatever it called) shows in the top left corner of the screen, which says ScreenToGif!

**To Reproduce**
Not sure, it happening at random. But when the hover appears I can remove it by hovering over tray icon of ScreenToGif.
**Screenshots**
![image](https://github.com/user-attachments/assets/f00b99fb-f956-4fc5-b195-a22c2788a30e)

**Desktop (please complete the following information):**
 - OS: Windows11, but also was happening on Windows 10

**Comment by NickeManarin** [comment]
It's called "Tooltip".

The position is relative to the cursor position.

```
tt = new ToolTip
{
    Placement = PlacementMode.Mouse,
    //...
};
```

I was doing manually the creation of the tooltip.
I now changed to using the native way.

**Comment by NickeManarin** [comment]
![image](https://github.com/user-attachments/assets/5c092255-eb5c-4023-a659-d16c1b8236df)
