### ISSUE TITLE
[Bug] 编辑器内显示的总帧数与实际导出的gif总帧数出现巨大差距 A huge gap about the total number of frames

### ISSUE THREAD

**Issue by forcyan** [NickeManarin/ScreenToGif#1354]
**Describe the bug**
编辑器内显示的总帧数与实际导出的gif总帧数出现巨大差距，编辑器内显示一共91帧，导出结果只有44帧，且每帧持续时间差距很大。
There is a huge gap between the total number of frames displayed in the editor and the total number of frames actually exported, a total of 91 frames are displayed in the editor, but the exported result has only 44 frames, and the duration of each frame varies greatly.

**Screenshots**
![image](https://github.com/user-attachments/assets/90a46fdb-229c-452e-a3e5-7894ddc5150e)
![image](https://github.com/user-attachments/assets/df8c21cb-45fb-44b2-b136-1d4b5a8655d1)

**Desktop (please complete the following information):**
 - OS:  Windows 11
 - Version 10.0.22631 版本 22631

 - ScreenToGif.2.41.1.Portable.x64

**Comment by NickeManarin** [comment]
The encoding is only exporting the frames that have changes.
You can disable compression in the encoder settings:

![image](https://github.com/user-attachments/assets/b0da1016-2ba1-49f7-8f7b-fcf0ea63ee1e)

But be aware that the filesize will increase a lot.
