### ISSUE TITLE
Suspicious code fragments

### ISSUE THREAD

**Issue by Lokiori** [NickeManarin/ScreenToGif#1357]
Hello!
I have checked ScreenToGif using the PVS-Studio static code analyzer and highlighted the most curious issues in my [article](https://pvs-studio.com/en/blog/posts/csharp/1194/). You may take a look at it if you're interested. I also identified a few problematic code sections that may require consideration:
### Fragment 1
```
public object ConvertBack(object value, Type targetType,
                          object parameter, CultureInfo culture)
{
  if (value is not int index)
    return DependencyProperty.UnsetValue;

  switch (index)
  {
    case 0:
      return Key.F1;
    case 1:
      return Key.F2;
    case 2:
      return Key.F3;
    case 13:            // <=
      return Key.F4;
    case 4:
      return Key.F5;
    case 5:
      return Key.F6;
    case 6:
      return Key.F7;
    case 7:
      return Key.F8;
    case 8:
      return Key.F9;
    case 9:
      return Key.F10;
    case 10:
      return Key.F11;
    case 11:
      return Key.F11;  // <=
  }

  return Key.F1;
}
```

There are probably two typos here, `case 13` instead of `case 3` and `Key.F11` instead of `Key.F12`.

Link to this place in the code:
https://github.com/NickeManarin/ScreenToGif/blob/22a10b445c1aea1c5ca011a542a3454e42b9123c/ScreenToGif.Util/Converters/ShortcutSelection.cs#L64

https://github.com/NickeManarin/ScreenToGif/blob/22a10b445c1aea1c5ca011a542a3454e42b9123c/ScreenToGif.Util/Converters/ShortcutSelection.cs#L81

### Fragment 2
```
private void UpdateMarkerPosition(Color theColor)
{
  ....
  var hsv = ColorExtensions.ConvertRgbToHsv( theColor.R, theColor.G, theColor.B);
  ....
}
```

```
public static HsvColor ConvertRgbToHsv( int r, int b, int g)
{
  ....
}
```

The `ConvertRgbToHsv( int r, int b, int g)` method has a strange order of parameters: r, b, g. At the same time, the code uses: R, G, B. Most likely, the parameters are mixed up.

Link to this place in the code:
https://github.com/NickeManarin/ScreenToGif/blob/22a10b445c1aea1c5ca011a542a3454e42b9123c/ScreenToGif/Util/ColorExtensions.cs#L305
### Fragment 3
```
public static readonly DependencyProperty IsReversedProperty =
DependencyProperty
   .Register("IsReversed",
             typeof(bool),
             typeof(DynamicGrid),
             new FrameworkPropertyMetadata(false,
                        FrameworkPropertyMetadataOptions.AffectsMeasure 
                      | FrameworkPropertyMetadataOptions.AffectsMeasure));
```

The analyzer detected a strange code snippet where the '|' operator has identical left and right operands.

Link to this place in the code:
https://github.com/NickeManarin/ScreenToGif/blob/22a10b445c1aea1c5ca011a542a3454e42b9123c/ScreenToGif/Controls/DynamicGrid.cs#L21

### Fragment 4
```
private void Window_Loaded(object sender, RoutedEventArgs e)
{
  ....
  CanvasSizeTextBlock.Text = $"{right.PixelWidth} × " +
                             $"{right.PixelHeight} • " +
                             $"{Math.Round(left.DpiX, 0)} " +            // <=
                             $"{LocalizationHelper.Get("S.Resize.Dpi")}";

  LeftImageSizeTextBlock.Text = $"{left.PixelWidth} × " +
                                $"{left.PixelHeight} • " +
                                $"{Math.Round(left.DpiX, 0)} " +
                                $"{LocalizationHelper.Get("S.Resize.Dpi")}";    
  ....
}
```

The analyzer assumes that the specified string should contain `right.DpiX` instead of `left.DpiX`.

Link to this place in the code:
https://github.com/NickeManarin/ScreenToGif/blob/22a10b445c1aea1c5ca011a542a3454e42b9123c/ScreenToGif/Windows/Other/Insert.xaml.cs#L303

### Fragment 5
```
var properties = doc.Root?.Elements().Select(GetProperty).ToList();
....
var version = properties?.FirstOrDefault(f => f.Key == "Version")   // <=
                                         ?.Value ?? "0.0";

Migration.Migrate(properties, version);

var resource = new ResourceDictionary {{"Version", All.VersionText}};

foreach (var property in properties)                                 // <=
{
  var value = ParseProperty(property);

  if (value != null && !resource.Contains(property.Key))
    resource.Add(property.Key, value);
}
```

In this fragment, you can see that the `properties` variable is assigned a value obtained via the '?.' operator, which indicates that this value can be null.
Next, `properties` is used with a check for null: `var version = properties?.FirstOrDefault`. However, just a few lines down, the `properties` are used as an enumerated expression in foreach without any check. Such use may result in the NullReferenceException being thrown.

Link to this place in the code:
https://github.com/NickeManarin/ScreenToGif/blob/22a10b445c1aea1c5ca011a542a3454e42b9123c/ScreenToGif.Util/Settings/UserSettings.cs#L125

### Fragment 6
```
if (File.Exists(Path.Combine(pathTemp, "Project.json")))
{
  ....
  using (var ms = new MemoryStream(Encoding.UTF8.GetBytes(json)))
  {
    var ser = new DataContractJsonSerializer(typeof(ProjectInfo));
    var project = ser.ReadObject(ms) as ProjectInfo;

    list = project?.Frames;                                      // <=
  }
}
....
//Shows the ProgressBar
ShowProgress(LocalizationHelper.Get("S.Editor.ImportingFrames"),
                                     list.Count);                // <=
```

After a possible assignment of null to the `list` variable, it's further used without any check.

Link to this place in the code:
https://github.com/NickeManarin/ScreenToGif/blob/22a10b445c1aea1c5ca011a542a3454e42b9123c/ScreenToGif/Windows/Editor.xaml.cs#L4121

### Fragment 7
```
protected override void OnPreviewKeyDown(KeyEventArgs e)
{
  ....
  if (   (e.Key == Key.OemQuestion || e.Key == Key.OemPeriod) 
      && (Keyboard.Modifiers & ModifierKeys.Control) == 0)
  {
    if (Text.Length > 8)              // <=
    {
      e.Handled = true;
      return;
    }
    if (Text.Length == 1){....}
    else if (Text.Length == 4) {....}
    else if (Text.Length == 7) {....}
    else if (Text.Length == 10)       // <=
       Text = Text.Substring(0, 9) + Text.Substring(6, 1).PadLeft(3, '0');

    SelectionStart = Text.Length;
    e.Handled = true;
    return;
  }
  ....
}
```

The analyzer warns that `Text.Length == 10` always returns false, and this is indeed true. There's the `if(Text.Length > 8)` check with return a bit higher up the code, which makes it impossible to pass the `Text.Length` values greater than 8 into the subsequent conditions. So, the `if(Text.Length == 10)` check is pointless, or there's an error in the `Text.Length > 8` condition.

Link to this place in the code:
https://github.com/NickeManarin/ScreenToGif/blob/22a10b445c1aea1c5ca011a542a3454e42b9123c/ScreenToGif/Controls/TimeBox.cs#L338

### Fragment 8
```
if (monitor.NativeBounds.Top > top)
  top = monitor.NativeBounds.Top;

if (monitor.Bounds.Left > left)                 // <=
  left = monitor.NativeBounds.Left;

if (monitor.NativeBounds.Bottom < top + height)
  top = monitor.NativeBounds.Bottom - height;

if (monitor.NativeBounds.Right < left + width)
  left = monitor.NativeBounds.Right - width;
```

In this fragment, the analyzer reports a mismatch between `Bounds` in the if condition and `NativeBounds` in the then body. There are three more checks for top, bottom, and right nearby, which shows the similarity of these checks. However, only the left check in question has `Bounds` instead of `NativeBounds`.

Link to this place in the code:
https://github.com/NickeManarin/ScreenToGif/blob/22a10b445c1aea1c5ca011a542a3454e42b9123c/ScreenToGif/Windows/Other/Troubleshoot.xaml.cs#L85C25-L85C31

### Fragment 9
```
....
using (var process = new Process())
{
  process.StartInfo = procStartInfo;
  process.Start();

  var message = await process.StandardOutput.ReadToEndAsync();
  var error = await process.StandardError.ReadToEndAsync();

  if (!string.IsNullOrWhiteSpace(message))
      output += message + Environment.NewLine;

  if (!string.IsNullOrWhiteSpace(message))
      output += message + Environment.NewLine;

  process.WaitForExit(1000);
}
....
SetCommand(id, true, command, output);
```

The analyzer has detected two identical checks. Probably, the `error` variable declared above should be used instead of `message` in one of the code blocks.

Link to this place in the code:
https://github.com/NickeManarin/ScreenToGif/blob/22a10b445c1aea1c5ca011a542a3454e42b9123c/ScreenToGif/Util/EncodingManager.cs#L1264

### Fragment 10
```
public static string ReplaceRegexInName(string name)
{
  const string dateTimeFileNameRegEx = @"[?]([ymdhsfzgkt]+[-_ ]*)+[?]";    // <=

  if (!Regex.IsMatch(name, dateTimeFileNameRegEx, RegexOptions.IgnoreCase))
    return name;

  var match = Regex.Match(name, dateTimeFileNameRegEx, RegexOptions.IgnoreCase);
  var date = DateTime.Now.ToString(Regex.Replace(match.Value, "[?]", ""));

  return name.Replace(match.ToString(), date);
}
```

This fragment has an unusual issue: the regular expression used is vulnerable and could potentially freeze the application. In my [article](https://pvs-studio.com/en/blog/posts/csharp/1194/), I explored this problem in greater detail and even reproduced it in a sample application. While this vulnerability is harmless in your case, it may still be worth exploring.

Link to this place in the code:
https://github.com/NickeManarin/ScreenToGif/blob/22a10b445c1aea1c5ca011a542a3454e42b9123c/ScreenToGif.Util/PathHelper.cs#L17

**Comment by NickeManarin** [comment]
Thanks for the detailed report. I fixed most issues.
