### ISSUE TITLE
Cannot import video in windows10-16193

### ISSUE THREAD

**Issue by huoshan12345** [NickeManarin/ScreenToGif#136]
When i try to  import frames from a video file(whatever which type of video file), a exception is thrown.
![qq 20170515211002](https://cloud.githubusercontent.com/assets/3745918/26059171/564b7f0e-39b3-11e7-9962-a613c7af6ddb.png)

It happened in  windows10-16193, and it's normal(no exception thrown) in win10 of earlier version before 16193 and win7.

**Comment by NickeManarin** [comment]
Do you have the codecs to load that video?

By the looks of it, the app is failing to load the video, returning 0 as the size, thus crashing.

**Comment by NickeManarin** [comment]
I added a new method for importing frames from video, using FFmpeg.
https://github.com/NickeManarin/ScreenToGif/issues/551
