### ISSUE TITLE
[Bug] Running ARM64 installer on ARM64 Windows shows "There's a better suited package for your OS architecture"

### ISSUE THREAD

**Issue by saschanaz** [NickeManarin/ScreenToGif#1362]
**Describe the bug**
(As the title says)

**To Reproduce**
1. On Surface Pro 11 (with Snapdragon X1E80100)
2. Download ScreenToGif.2.41.1.Setup.Arm64.msi from https://github.com/NickeManarin/ScreenToGif/releases/tag/2.41.1
3. Click Next
4. See the recommendation to install "64 bits" binary instead (ARM64 is also "64 bits" btw)

**Expected behavior**
No warning, this is the right installer for my machine

**Screenshots**
![image](https://github.com/user-attachments/assets/37062906-28f2-419d-ace5-8b57a69b2393)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 2.41.1

**Comment by NickeManarin** [comment]
Thanks.
If Arm64, I wont show this step, since it doesn't make sense anyway.

**Comment by saschanaz** [comment]
Is installer code also open source? 👀
