### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by felixfbecker** [NickeManarin/ScreenToGif#137]
Would be great to have an MSI for a proper link in start menu and uninstaller. Or put it in the Windows store with Project Centennial?

**Comment by NickeManarin** [comment]
I'm currently starting to work with Project Centennial. :)

**Comment by NickeManarin** [comment]
Looks like I'll not be able to use Centennial, I would need to buy a $ 300/year digital certificate. That's a big 'no' unfortunately. :(

**Comment by SuperDOS** [comment]
Since it's so few files you can pretty easy build an installare with insted.

**Comment by taspeotis** [comment]
I would like an installer too, ideally with some facility to automatically update ScreenToGif. Your application is very useful to me, but I use it infrequently, so my workflow is something like:

* Download ScreenToGif.zip
* Run it out of the zip
* (Weeks pass)
* (Purge Downloads folder)
* Where did I download ScreenToGif to?
* Download it again

Some thoughts on installer toolkits, for your consideration:

* [Wix](https://marketplace.visualstudio.com/items?itemName=RobMensching.WiXToolset)
* [Visual Studio Installer Projects](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.MicrosoftVisualStudio2017InstallerProjects)

I do not think these make automatic updates very easy, you could do it with [Squirrel](https://github.com/Squirrel/Squirrel.Windows) after-the-fact (i.e. use MSI to get the files on a user's computer, then Squirrel to keep it up-to-date). Squirrel can be used to do it all, however, installation plus updates.

ClickOnce is a bit old but it also works pretty well for simple apps. It will work with applications that aren't digitally signed (with the security consequences of unsigned applications.)

As much as I'd like to see this installer + updater, I know it's also a bit of a time commitment. I had my own application that was kept automatically up-to-date on macOS with Sparkle.framework, and the rigmarole of building/signing*/deploying was a time drain.

*Signing is free: you self-generated public/private keys, the public key is pinned in the app bundle. Squirrel is similar, I think.

**Comment by felixfbecker** [comment]
Don't like that Squirrel forces you to install to `%LOCALAPPDATA%` with no way to customize that (at least that was my experience with Squirrel-based apps like Atom). Visual Studio Code used Squirrel in the past but switched to something else (all I know is it's an MSI) because the experience for Windows users is just not the best (and this project is Windows-only...).

**Comment by SuperDOS** [comment]
NSIS could be an alternative as well https://sourceforge.net/projects/nsis/

**Comment by felixfbecker** [comment]
I think NSIS doesn't produce MSIs. I would always prefer MSIs because the declarative approach (in opposite to a script-based imperative approach) ensures an installation and uninstallation can be cancelled and rolled back at any stage of the (un)installation.

**Comment by SuperDOS** [comment]
Correct and I'm with you on using MSI. have you looked at WIX? http://wixtoolset.org/

**Comment by NickeManarin** [comment]
I'm familiar with InnoSetup, Wix (via WixSharp) and the Visual Studio Installer Projects. 
It looks like the later is the easiest.

**Comment by NickeManarin** [comment]
@SuperDOS So, I'm currently creating the installer with Wix#. It will produce a MSI file as requested.

**Comment by NickeManarin** [comment]
Here's what I got, not the final version: [ScreenToGif 2.8.1 Setup.zip](https://github.com/NickeManarin/ScreenToGif/files/1117217/ScreenToGif.2.8.1.Setup.zip)

**Comment by felixfbecker** [comment]
Tried it, works great (besides a a security warning)!

**Comment by NickeManarin** [comment]
@felixfbecker Nice, but what kind of security earning? Maybe because it's not signed?

**Comment by felixfbecker** [comment]
![image](https://user-images.githubusercontent.com/10532611/27765270-740abf18-5ead-11e7-83df-f5fe6858afe8.png)

**Comment by NickeManarin** [comment]
Oh, this dialog appears because it's a file that Windows does not trust yet. The only way to make it disappear is to have a certificate.

**Comment by SuperDOS** [comment]
You need to right click and choose properties and then unblock it.

**Comment by bramborman** [comment]
@NickeManarin Where did you read about the $300/year certificate? [Here][docs] they say that Centennial could generate the certificate for you. And above it, there's an paragraph about packaging apps without an installer. But no words about $300/year certificate.

[docs]: https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-run-desktop-app-converter#package-an-app-sign-the-app-and-run-validation-checks-on-the-package

**Comment by NickeManarin** [comment]
@bramborman 
From https://www.thawte.com/code-signing/

But I managed to buy one from KSoftware for way less money. I just pass the validation process to get the certificate.

**Comment by NickeManarin** [comment]
@bramborman 
About the generated certificate, it only works if you install, it's not a valid global certificate. Only work if the CA is installed on the machine. It's a fake certificate.

**Comment by bramborman** [comment]
@NickeManarin  Windows Store doesn't create one for you? For UWP apps it's all done automatically and for free.

**Comment by NickeManarin** [comment]
@bramborman Apparently not with Project Centennial.

**Comment by bramborman** [comment]
@NickeManarin just downloaded Visual Studio 15.4 that adds a new project type - [Windows Application Packaging Project][1] - which simplifies creating Centennial apps. Just tested it and it generated a temporary certificate and I was also able to get the Store certificate that's generated by Microsoft and is used to publish the app to Windows Store.

Could you look at it? I think I'm not the only one who'd prefer downloading ScreenToGif from the Windows Store.

[1]: https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes#WAPPtemplate

**Comment by NickeManarin** [comment]
@bramborman I'm downloading... :)
Btw, I got a code signing certificate.

**Comment by vatterspun** [comment]
> I think I'm not the only one who'd prefer downloading ScreenToGif from the Windows Store.

I definitely don't prefer Windows Store and can name various problems with the App Store model in general, but I acknowledge some devices are locked down to only allow Apps from the Windows Store.

Thanks for looking into that.

**Comment by NickeManarin** [comment]
@vatterspun I'm still going to distribute the app via the current available options (no install, installer, Chocolatey). 
;)

**Comment by bramborman** [comment]
@NickeManarin I know you have the certificate, but the app still isn't on Windows Store, so not sure if you're planning to add it later or what :)

**Comment by vatterspun** [comment]
> I'm still going to distribute the app via the current available options (no install, installer, Chocolatey).

Thanks for that.
