### ISSUE TITLE
Bug on overriding a gif

### ISSUE THREAD

**Issue by maxgomes92** [NickeManarin/ScreenToGif#138]
Hi, I might have found a bug.

I recorded my screen, generated a gif a saved it on my hard drive.
Then, I realized it was too big, so I used the tool on EDIT tab to reduce the number of slides.
I did it a couple times, always overriding my previous gif saved before. 
(I had the override option checked)
Nothing was happening with the file size, it always kept the same. Although it was reducing the number of frames per second.
So I deleted the file on my hard drive, and save again. Magically the file reduced the size, which was expected to happen.
So, there might be a problem there, on overring previous gif files.

Thanks, nice software, by the way.

**Comment by NickeManarin** [comment]
This bug was supposedly fixed a few releases ago. I tested here and it looks like the 3 gif encoders are working as expected. (I recorded 36 frames, saved, reduced to 11 frames, saved again, overriding it) 

![image](https://cloud.githubusercontent.com/assets/14798947/26181107/f08b4c8e-3b43-11e7-9aa5-561f7f184ccf.png)

**Comment by NickeManarin** [comment]
Could you check if this bug happens with the latest release (v2.7.3)?

**Comment by maxgomes92** [comment]
Fiz o teste aqui, está corrigido!


Depois que fui ver que você era brasileiro. 😅


Nice work on this!


Max

________________________________
De: Nicke Manarin <notifications@github.com>
Enviado: quinta-feira, 25 de maio de 2017 16:57
Para: NickeManarin/ScreenToGif
Cc: Max Gomes; Author
Assunto: Re: [NickeManarin/ScreenToGif] Bug on overriding a gif (#138)


Could you check if this bug happens with the latest release (v2.7.3)?

**Comment by NickeManarin** [comment]
Ótimo.

----

Great
