### ISSUE TITLE
Importing from MP4 & Extreme Memory Usage

### ISSUE THREAD

**Issue by changbowen** [NickeManarin/ScreenToGif#139]
First of all thanks for the great app.
Something I find is that when importing an mp4 file (720p), if i set scale to 25%, and set the start and end time, then start importing, the program would consume over 6 out of 8GB of RAM and OS starts to write to the page file like crazy.
After loading, under Statistics the size shows something really large like 5124 * 6841.
Bug?

And some of the imported frames shares the same content. When played the gif looks as if some frames are dropped.

Also I tried using the feedback directly from the app but it prompts me that I'm running from source code which I'm not.

**Comment by NickeManarin** [comment]
OHHHHH, sorry for that. :/
The scaling and the feedback bugs are fixed. About the memory usage, I'm not able to fix it yet.

Thank you.
