### ISSUE TITLE
[Feature Request] Fade effect video

### ISSUE THREAD

**Issue by Kristinita** [NickeManarin/ScreenToGif#14]
### Request

I want adding fade effect for GIF or any other effect that people who are view cyclic GIF can to see where the beginning and at the end on the GIF.
### Example

I want at the end of GIF became darker, darker, and finally became completely black. Example effect on Adobe Premier:

![Adobe Premier](http://i.imgur.com/pw1kEBq.gif)
### Cause

In some videos is very difficult from the first or the second time to see where it starts and where the video ends. This is important if a video sequence of certain actions. Example.

![MultiEditUtils](https://camo.githubusercontent.com/f6d6f92018eeacec852de7957647e076c6183e5e/687474703a2f2f7068696c6970706f74746f2e6769746875622e696f2f5375626c696d652d4d756c7469456469745574696c732f73637265656e732f303725323072656d6f7665253230656d70747925323073656c656374696f6e732e676966)

Yes, I understand that ScreenToGif - it's not a huge expensive video editor with lots of features, but I think the effect will be beneficial for many users, not only for me.

Thank you for a great program!

**Comment by NickeManarin** [comment]
Hi @Kristinita!

The fade effect is available inside the **Transitions** tab, but it only fades into the next frame.
So, there's no official way to fade to black (right now).

But you could use a temporary hack:

Insert a **Title Frame** (Edit > Title Frame), select a dark color as background (and remove the text), move this frame to the last position, select the previous frame, insert the fade transition (pick the duration of the transition using the slider).

**Comment by Kristinita** [comment]
Thank you very much! It's work!

![MultiUtilsEdit](http://i.imgur.com/sA5Kr9h.gif)

But how I can edit multiple frames? `Transition` → `Fade` → I select 4 `Transition Length` → I get 4 new frames, that last 66 ms:

![66 ms frames](http://i.imgur.com/EWYoNa6.png)

I want increase length frames 46—49 to 200 ms. Yes, I can change the length of each frame separately, but is it possible to change the length of the four frames at once?

Thanks.

**Comment by NickeManarin** [comment]
You can select multiple frames by <kbd>Ctrl</kbd> + *Click* or <kbd>Shift</kbd> + *Click*

To edit the length/delay/duration of multiple frames, head over to the tab **Playback**, there's two buttons with a clock as an image. *(Ignore the label of these buttons, it's a little bit wrong, I already replaced with a better description)*

![clock](https://cloud.githubusercontent.com/assets/14798947/18808367/7efe5be0-8236-11e6-8be3-3f511ebeee2a.PNG)

- The button to the left (the one with a yellow star) will **replace** the length/delay/duration of each selected frame by the new value.

- The button to the right (the one with a + and - sign) will **increase/decrease** the length/delay/duration of each selected frame by the given value.

**Comment by Kristinita** [comment]
Thank you very much!

 1. When I make last frame as `Title Frame`, creates another frame duration of 10 ms.  
![Last frame](http://i.imgur.com/7uyaeHd.gif)  
How I can automatically disable the creation of the last frame? 

 2. Length of `Title frame` by default is 500 ms. Length of `Fade Transition` frames by default is 66 ms. How I can change for me this values on, for example, 1000 ms and 150 ms just one time that I did not have to change the values ​​each time I apply an effect?

---

Where I can read documentation to ScreenToGIF, so I would not bother you with such questions? I can not find documentation in Internet 😟 .

Thanks.

**Comment by NickeManarin** [comment]
1. That's not an extra frame, the Title Frame option inserts the frame before the selected frame. You can simply move the frame to right/left by clicking on the Edit>Move Left/Right. I should make available an option to choose exactly where to put this new frame, like I do with the Paste operation.

2. Title Frame gives you the option to change the delay (duration), you can see that option inside the Title Frame options panel. There's an UI overhaul planned for the transitions options, to make more personalized effects.

@Kristinita, the help will be available [here (wiki)](https://github.com/NickeManarin/ScreenToGif/wiki/Help), but there's nothing yet. I'm sorry. :/

**Comment by Kristinita** [comment]
1. Thanks. So, I have to do my `Title Frame` at the beginning GIF, then <kbd>Ctrl+End</kbd> and make `Transitions` → `Fade` in last frame. But to the last frame is highlighted in blue, I additionally need press <kbd>←</kbd> and <kbd>→</kbd>. Otherwise, the new frames are created after the first frame.

![Ctrl+End](http://i.imgur.com/5i8PA1j.gif)

Can I go to the last frame without pressing <kbd>←</kbd> and <kbd>→</kbd>?

2.1. Perhaps the bug. I set a value of 1000 ms, but still 500 ms.

![500 ms](http://i.imgur.com/aSMoaEa.gif)

2.2. We are waiting ⌚ 😄  .

**Comment by NickeManarin** [comment]
Alpha version here: https://1drv.ms/u/s!Atz6mWWOy6N8mesZWt5pBgYZvCoFdw

With some bug fixes and the new encoder (named as ScreenToGif).

**Comment by Kristinita** [comment]
@NickeManarin , bad encoding in alpha version — <http://jmp.sh/KsSdKl4>.

![Bad encoding in Alpha](http://i.imgur.com/4ZnSIJo.gif)

**Comment by NickeManarin** [comment]
Version 2.3 adds an option to fade to a specific color.

**Comment by Kristinita** [comment]
@NickeManarin, shortcut for Fade 😺? Thanks.

**Comment by NickeManarin** [comment]
Not yet :/

**Comment by Kristinita** [comment]
Thank you very much! We waiting hotkeys — #22.
