### ISSUE TITLE
Capturing on mouse or key event only?

### ISSUE THREAD

**Issue by ArjangAssadi** [NickeManarin/ScreenToGif#142]
Is it possible to screen capture on mouse or key events only? looking to use this as an alternative to PSR, do not need to have to edit large chunks of nothing happening afterwards.

**Comment by EMLVIRUS** [comment]
> screen capture on mouse or key events only

As far as key events, I recommend you [KeyCastOW](https://brookhong.github.io/2014/04/28/keycast-on-windows.html)

For mouse, what do you mean precisely?

**Comment by NickeManarin** [comment]
With current version, no it's not possible. It would require me to write an additional recorder to take screenshots everytime an user press something (keys or buttons). 

To simply take a screenshot by key/button presses is easy. To emulate ever feature of the Step Recorder (PSR), it will require more work.

**Comment by ArjangAssadi** [comment]
Hello 

@EMLVIRUS : Yes, PSR is problem step recorder, it does more than is needed, just taking screen shots on mouse clicks would be sufficient. Thanks for the KeyCastOW link, but I think I was not clear, I am after taking screen shots on mouse events. similar to PSR, and while nothing is happening not to record.

@NickeManarin  : No need to take as much as PSR does, There is already two parts there:
1.Detect Mouse Clicks and
2.Enable snapshot mode.

now if there was a mode to take a snap shot on mouse click and be able to save the snapshots separately that would be perfect. Maybe it is already there, I try to play around see what I find.

Thank you both for your response.

**Comment by EMLVIRUS** [comment]
Can't agree with owner more. And keycastow is really a good choice for keyboard activity now

**Comment by EMLVIRUS** [comment]
Hey. Do you mean to screen shot the windows where user press the mouse with mouse click detection enable meantime?

**Comment by ArjangAssadi** [comment]
@EMLVIRUS : Yes, only take screen shot when mouse is clicked, that is all is needed.

**Comment by EMLVIRUS** [comment]
@ArjangAssadi I think there is certain hardness:
- different windows sizes
- high process priority for certain windows such as Windows store. That will cause UAC warning popup

**Comment by ArjangAssadi** [comment]
@EMLVIRUS : Thank you
How is using pressing F7 /F8 to start and stop different to starting and stopping on mouse click?

**Comment by EMLVIRUS** [comment]
> How is using pressing F7 /F8 to start and stop different to starting and stopping on mouse click?

Could you reorganzie your sentence? It is really confusing to read through

**Comment by ArjangAssadi** [comment]
Updated the previous sentence, also assume one can run ScreenToGif as administrator, so no worries about UAC etc. Just what is now being accomplished by pressing F7/F8 will be replaced by mouse click.

**Comment by NickeManarin** [comment]
@EMLVIRUS The PSR takes full screen screenshots, so the only problem would be to detect clicks/keys made on windows opened using admin rights (the detector fails to detect any event from those windows).

**Comment by NickeManarin** [comment]
@ArjangAssadi Currently that's not possible.

**Comment by ArjangAssadi** [comment]
@NickeManarin  Cool, thank you :)

**Comment by vatterspun** [comment]
As with #169 this seems out of scope.  Although I've been looking for something for a long time to replace PSR, I wonder if Screentogif can help without some pretty major changes.

Although they have similar use cases, PSR and similar programs are more for bug submission, bug testing, and documentation.  With those programs, you capture what's clicked on and where on the screen it's located.  It's almost always full screen images with emphasis on what was selected/clicked, a little text describing what was done e.g. Click on "OK".  

ScreentoGif seems to focus on being more dynamic, easier to pull from place to place, and easy to edit/tweak for additional detail.

Anyway, some recommended PSR freeware alternatives include:

* Active Presenter, which is free for personal use, but my testing so far has resulted in some BSOD so your mileage may vary.
* StepsToReproduce - great but avoid the included editor program.
* Imago - simple and great, but some of the customizations are a bit of a pain, no longer developed, not sure if it works in Win10.

**Comment by NickeManarin** [comment]
I implemented an event-triggered capture mode.

![image](https://user-images.githubusercontent.com/14798947/89808835-1e72fa00-db11-11ea-8681-048ae6026e78.png)

It's treated as a capture frequency type, along with the manual and time-based modes.
It will capture a frame each time a mouse event (click or scroll) or keyboard event is triggered by the user.

![image](https://user-images.githubusercontent.com/14798947/89816244-94309300-db1c-11ea-9033-f7dbfd9db0c2.png)

It will ignore those events if they are directed to the recorder UI, so you can click and type normally without an accidental capture.

![InputCapture](https://user-images.githubusercontent.com/14798947/89816760-829bbb00-db1d-11ea-8c2d-0052f89f0487.gif)

I'm also improving the mouse event detection system. It will be possible to differentiate a click from one button to the other, scroll up/down/left/right, etc.
