### ISSUE TITLE
Can't run in virtual machine

### ISSUE THREAD

**Issue by woxinwuchen** [NickeManarin/ScreenToGif#145]
I am using macOS sierra, parallels desktop 12, window 7 ultimate, .net frame work 4.6.0., when I try to run screentogif. I got an error message.

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	ScreenToGif.exe
  Application Version:	2.7.3.0
  Application Timestamp:	591e4ac2
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.17514
  Fault Module Timestamp:	4ce7c78c
  Exception Code:	e0434352
  Exception Offset:	000000000000a49d
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	2052
  Additional Information 1:	152d
  Additional Information 2:	152d49a18dcb45231bb1c1efff527c4d
  Additional Information 3:	6d7c
  Additional Information 4:	6d7c784962d941895e03c517875503b1

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by NickeManarin** [comment]
The minimum required .Net framework version is 4.6.1, yet I believe it should at least open the app (because of the small difference between framework versions).

[Would you like to install the a newer version of the framework?](https://www.microsoft.com/en-us/download/details.aspx?id=49982)

**Comment by woxinwuchen** [comment]
Thank you so much! I have just tested with 4.6.1 . It worked!!
