### ISSUE TITLE
Framerate option ignored during ffmpeg saving?

### ISSUE THREAD

**Issue by MeatyChunks** [NickeManarin/ScreenToGif#146]
While testing some settings it looks like the framerate option is ignored during ffmpeg saving? Adding -report to the ffmpeg command line shows there's always an "-r 30" at the end, regardless of whatever I set it to in the area above the ffmpeg command line. Is it meant to be this way?

I could also use some help if possible; While saving as a GIF plays at the correct speed, ffmpeg always seems to play it slightly faster, I was wondering if setting it to a lower fps would fix the issue which led me to discovering not being able to change the framerate. This is while using constant framerate so the delay between frames shows as 33ms, does ffmpeg ignore that or something?

Many thanks!

**Comment by NickeManarin** [comment]
Indeed, there's a bug in here. The value is locked to a hidden value. I just need to set the proper variable.

Currently, FFmpeg ignores the delay between frames of the source recording. I still need to implement variable framerate and remove the Framerate option.

Thanks.

**Comment by NickeManarin** [comment]
I removed the **output fps** parameter from my code (you can still set via the Extras box) in order to favor variable framerate from the current recording.

Ready for v2.8.
