### ISSUE TITLE
https://screentogif.codeplex.com/ has TLS certificate issues

### ISSUE THREAD

**Issue by movermeyer** [NickeManarin/ScreenToGif#147]
Searching 'gif screen capture' in both Google and [Duck Duck Go](https://duckduckgo.com/) returns https://screentogif.codeplex.com/ as the first result.

However, that link is broken, since the TLS certificate has issues (expired?)

[Here is a screenshot of what users see in Firefox](http://imgur.com/a/nGurq).

Just thought you'd want to know so people stop getting a bad first impression.

**Comment by NickeManarin** [comment]
My idea for letting that page alive was to redirect everyone here and to [ScreenToGif.com](http://www.screentogif.com/).

I'll delete the project tonight. Not sure how long does it take to stop appearing in a web search.
