### ISSUE TITLE
[Bug] Skipped keystrokes

### ISSUE THREAD

**Issue by vatterspun** [NickeManarin/ScreenToGif#148]
Setup: Win7x86, ScreenToGif 2.7.3

I've been testing the awesome Keystrokes feature and tried creating a quick tutorial on it's use.  In going through a menu system (ALT, F, A) to select File - Save As, for some reason the program skipped the "A" key:

https://s12.postimg.org/anpqe3lfx/show_keyboard.gif

Workaround: go in and add text manually.

Thanks SO much for adding this functionality, which I've seen in no other screen capture program, much less an open source tool.

**Comment by NickeManarin** [comment]
I'm using a different language (pt-BR) so my sequence is Alt + F, V to "Save as". Still, it shows the correct keys.

Maybe this is a race problem, the key was pressed too quickly to be recorded. Not sure.

**Comment by vatterspun** [comment]
@NickeManarin Great suggestion.  I think it was actually the "Reduce Frame Count" and the speed that caused this.  Closing the case.
