### ISSUE TITLE
Notes for improvements of the Key Strokes feature

### ISSUE THREAD

**Issue by NickeManarin** [NickeManarin/ScreenToGif#149]
### Notes
1. Holding a key should not add multiple key entries.
2. Differentiate lower and upper case letters. Detect Shift and Capslock and print the respective character. _(optional)_
3. Somehow the entry "LeftAlt + Alt" was recorded. Also "LeftShift + Shift". Maybe it's related to **note 1**.
4. "Capital" should actually be called "Capslock".

### Example
![animation](https://cloud.githubusercontent.com/assets/14798947/26594062/a4ed3b22-453c-11e7-9337-75819acb8ecf.gif)

**Comment by vatterspun** [comment]
By way of possible alternative implementations:

* QiPress - small window that changes according to buttons pressed.  May run into the issue of someone typing too fast (as with my recently [closed issue](https://github.com/NickeManarin/ScreenToGif/issues/148))
* Carnac - individual boxes that rise up from the lower left (this is customizable)

**Comment by NickeManarin** [comment]
![keys](https://user-images.githubusercontent.com/14798947/27518346-2d86b892-59b4-11e7-8865-e2b8e194b135.gif)

Done.
