### ISSUE TITLE
Mouse click detection indicator is persistent if mouse is not moving

### ISSUE THREAD

**Issue by byzod** [NickeManarin/ScreenToGif#151]
It this a bug or feature?

![](http://i.imgur.com/O9eUCDO.gif)

In the screencast above, I clicked 6 times

First 3 clicks: `LMB down > 50~100ms > LMB up > move pointer away > next click`
Later 3 clicks: `LMB down > 50~100ms > LMB up > wait ~2 seconds > move pointer away > next click`

## Expect result
Same recording result for all 6 clicks: mouse click indicator disappeared after mouse button released

## Actual result
First 3 clicks recording: mouse click indicator disappeared quickly
Later 3 clicks recording: mouse click indicator persist until mouse moves

**Comment by EMLVIRUS** [comment]
FF论坛的百左兄。。。

**Comment by NickeManarin** [comment]
Fixed.
