### ISSUE TITLE
Snap to window

### ISSUE THREAD

**Issue by Tekbr** [NickeManarin/ScreenToGif#154]
-- Sorry for the English, I used Google Translator --

In my view the most current version 2.7.3 leaves more borders than version 2.7.0. It has a greater distance between the border of the ScreenToGif with the border of the program that I want to capture.

![screentogif](https://user-images.githubusercontent.com/19866231/27089514-f4cfe2d0-5030-11e7-9d4d-534df5a870fb.gif)

Or is it some new configuration I have to do?

Thanks for the attention and congratulations to the ScreenToGif. 👏 👏 👏

**Comment by NickeManarin** [comment]
O gravador tem uma borda interna de 1 pixel, para todos os lados. A versão 2.7.3 vai gravar a janela corretamente, sem deixar espaços em branco e sem cortar algo. A não ser que eu esteja esquecendo de algo.

----

The recorder has an internal border of 1 pixel, for all sides. The version 2.7.3 will record the window correctly, without leaving any space left and without clipping anything. Unless I'm missing something.

![aaa 0](https://user-images.githubusercontent.com/14798947/27095465-1b433d6e-5044-11e7-9205-886f6ff89ece.png)

Como você pode ver, a janela se encaixa exatamente onde deveria. No entanto, se você precisa ignorar a borda da janela, eu poderia criar uma configuração para suportar isso.

----

As you can see, the window fits exactly where it should. Yet, if you need to ignore the window border, I could make a setting to support this.

**Comment by Tekbr** [comment]
Você está certo. Fiz mais alguns teste, funcionou perfeitamente. Foi falta de atenção minha. No momento não preciso retirar a borda. Obrigado por atenção e pela resposta rápida.

**Uma pergunta em off:** sei que o modo tela cheia está no modo experimental, mas há algumas situações que gostaria de tentar lhe mostrar o que acontece, com alguns passos a ser seguidos. Existe algum caso especifico para ele?

Parabéns pelo ótimo trabalho. 👏 👏 👏 👏 👏 

-------------------------------------------------------------------------------------------------------------

You're right. I did some more testing, it worked perfectly. It was my lack of attention. At the moment I do not need to remove the border. Thank you for your attention and quick response.

**An off question:** I know fullscreen mode is in experimental mode, but there are some situations I would like to try to show you what happens, with a few steps to be followed. Is there any specific case for it?

Congratulations on the great work. 👏 👏 👏 👏 👏

**Comment by samizzo** [comment]
Sorry for necroing an old issue but I'm not sure this is working right in 2.37. When recording is in progress I can see a gap and whatever is behind the window that I'm recording:
![image](https://user-images.githubusercontent.com/1753040/178096067-83caaa28-82cc-4fe7-a172-ca4501191a37.png)

and in the final recorded clip it shows up (although not as much as when recording is in progress):
![image](https://user-images.githubusercontent.com/1753040/178096085-17be6a9f-2a07-4291-b898-b59cce64c725.png)

This is in Windows 10 if that makes a difference!
