### ISSUE TITLE
Project managerment request

### ISSUE THREAD

**Issue by EMLVIRUS** [NickeManarin/ScreenToGif#156]
Sorry that I didn't review wiki throughout. Could you add any guideline about contributing translation via PRs on GitHub?

I guess another independent repo can help you manage strings files better.

**Comment by NickeManarin** [comment]
I added a small tutorial of how to PR, by linking to GitHub help page.

**Comment by EMLVIRUS** [comment]
@NickeManarin Maybe I missed something before. I mean on this repository, I can't see a folder containing all locale files.
So I request a new repository which has only locale files so that:
1. people can update and track translation better
2. you can be free up a little from emails
