### ISSUE TITLE
Suggestion for new recorder UI

### ISSUE THREAD

**Issue by byzod** [NickeManarin/ScreenToGif#157]
## Things that can be improved
The new record UI is cool and easy to use, no longer need to drag the window over and over to cover the area you want to record, very intuitive.

But there are still space to improve!

- When you selected a region to record, you need to move your mouse a long way to click the small confirming icon in the center, every time. I think there's no need to do this. 
**Suggestion**: smart confirm/reselect/cancel icon postion like what shown in the gif below, or double click to quick confirm region selection (you can quick cancel region selection by right click now, that's very cool)

  > ![a 1](https://user-images.githubusercontent.com/848607/27282305-f8745498-5521-11e7-955f-039b331eb42c.gif)
This is a screenshot application from Tencent TIM, it's very intuitive to use. Once you finished a region selection, the action bar appear in the button or the region (or top if not possible), moreover the confirm button (the green `√`) is extremely close to your cursor in most situation. Not to mention it even has a magnifier to help aligning in pixel precision, with RGB color display.

- With old UI, ctrl+N in editor will start a new recording, with default recorder window size & position. However new UI can't remember that, with every ctrl+N, you need to select the region again.
This makes same-position-recording nearly impossible as it's extremely difficult to recreate a region with exact same position and dimension for a human.
  Besides, the `Region` button in the toolbar is actually a 'drop menu', you need to click twice to really start selecting a region, not so convenient
  > ![2](https://user-images.githubusercontent.com/848607/27282779-083ec410-5524-11e7-99d9-4eb8306d2030.png)

  **Suggestion**: 
  - Region position & dimension is remembered when start a new recording, like before
  - Click `Region` icon on toolbar start region selecting directly, add a drop arrow to access other functions (or show all icon on the toolbar if you're not adding more select methods

    > ![2](https://user-images.githubusercontent.com/848607/27283165-9f1e7258-5525-11e7-9b16-12fe2e161a7f.png)
   ~~I know my drawing is awful lol~~

**Comment by duarteframos** [comment]
Was about to comment mostly the same things.
First and foremost I haven't commented here in awhile, ScreenToGif has been progressing well, congrats!

I'dd also suggest adding final size feedback while drawing the recording area, as illustrated in the above GIF, and if possible also keep the same dimension input fields in the recorder window to allow more precise value adjustment.

A quick way to toggle between the two without entering the preferences dialog would also be great, or if possible make both coexist in the same window, though I understand it may not be trivial to do.

One last quick suggestion. Make the *Snapshot Mode* entry in the menu either have a tick (✓) or different icon while active; or when active change menu entry to read  *Record Mode* or Video Mode* or whatever the regular way is called instead, and change the camera icon to the regular "red circle" to better reflect what that menu entry will currently do.

Again thanks for this wonderful little application, and keep up the great work

**Comment by positr0nic** [comment]
I have a commnet and suggestion:

Accessing settings is somewhat convoluted with this new UI and it could be more user friendly.

* Please make the new UI at least carry all basic controls and consider making this more intuitive.

* The text "Please press escape to cancel" over a dark interface its hard to see.
![capture](https://user-images.githubusercontent.com/25669462/28488328-1cc4ce68-6e9f-11e7-93ec-338a1f146113.PNG)

**Comment by NickeManarin** [comment]
Sharing some progress... How about this?

![test](https://user-images.githubusercontent.com/14798947/31040356-dc97777e-a55c-11e7-97c5-820ed377c3f9.gif)

![test 2](https://user-images.githubusercontent.com/14798947/31040460-00b53cbc-a55e-11e7-83be-3ac635f6dc96.gif)

Btw, I still need to improve this window:

![window](https://user-images.githubusercontent.com/14798947/31040464-09ed18d6-a55e-11e7-933a-b95ea48dc5f2.png)

**Comment by duarteframos** [comment]
Wow that is absolutely perfect, excellent work,
Last thing missing would be a "follow mouse cursor" option for the region mode 

Looking forward to the next version, congrats on the progress! :)

**Comment by NickeManarin** [comment]
> follow mouse cursor

I'm thinking about this... I have some questions:

- This could be activated via a menu/button or maybe by holding a key?
- If activated by a menu/button, how could the user stop the recording? A key press would be needed, right?

**Comment by duarteframos** [comment]
Hum, good question! I'd go with the second option, via a hotkey press.

The "Follow Cursor" option could be available from that recording mode dropdown menu just like "Region" "Window" and "Screen".  It would then behave similar to the region option, with a resizeable region, or pre-defined area.
Then a hot key to start/stop, and if possible always keep an additional "New Interface" floating window somewhere out of the way.

BTW that magnifier looks awesome for pixel perfect alignment ;)

**Comment by byzod** [comment]
I just played with v2.10 (the new UI landed), it just works exactly as what I expected
The confirm/cancel buttons transform to a column when there's no enough space to place them under the region to provide quicker access, this is even more convenient than I thought :D

Well done!

**Comment by NickeManarin** [comment]
@HansWaider It's available in v2.19.
