### ISSUE TITLE
[Bug] How to disable «Clipboard» pane?

### ISSUE THREAD

**Issue by Kristinita** [NickeManarin/ScreenToGif#16]
When I edit my GIF, appears `Clipboard` pane, although I do not want it. `Clipboard` pane just prevents me.

![Clipboard pane](http://i.imgur.com/MYxdhf5.gif)

What should I do to `Clipboard` pane does not always appear, but only when I want it: `Edit` → `Show Clipboard`. I did not find in the settings, how can I disable `Clipboard` pane.

+ Windows 10.0.14393
+ ScreenToGif 2.2.160907

Thanks.

**Comment by NickeManarin** [comment]
That's strange. :O

This panel should only appear when clicking <kbd>Ctrl + C</kbd> or <kbd>Cltr + X</kbd>

**Comment by Kristinita** [comment]
@NickeManarin, thanks for comment! In mouse mode of [QTranslate](https://quest-app.appspot.com/) program are [emulated pressing <kbd>Ctrl+C</kbd>](http://forum.ru-board.com/topic.cgi?forum=5&topic=35038&start=2540#14). 

![Mouse mode](http://i.imgur.com/PMahNqk.gif)

I disable mouse mode, and the problem no longer for me.

**Comment by NickeManarin** [comment]
Oh!

That explains it. Thanks for the feedback, even so I should make an option to show (or not) the panel when copy/cut.
