### ISSUE TITLE
[Feature request] Once export has completed, provide a link to the clipboard

### ISSUE THREAD

**Issue by AlexFielder** [NickeManarin/ScreenToGif#160]
I've been using greenshot a LOT recently and one of the features I've come to rely upon is that when you save a file from the screengrab tool (either directly or via the built-in editor) you get a link to the saved file available in the clipboard. I guess this is related in-part to #101 in so far as somebody there mentioned the clipboard.

**Comment by NickeManarin** [comment]
You can right click on the finished image and copy to the clipboard. Is this what you have in mind? 

I understand that it's difficult to find this feature. I'll make some changes to improve it.

**Comment by AlexFielder** [comment]
I just need the path to the exported file dumped onto the clipboard for pasting into (amongst other things) Skype and/or slack's upload/share function

**Comment by NickeManarin** [comment]
Just for reference:

![clipboard](https://user-images.githubusercontent.com/14798947/27699879-273123f8-5cd2-11e7-9d4a-143d4e772ad1.png)

Still, I got a feedback about this a while ago. The idea was to have an option to automatically copy the path to the clipboard. A similar feature (already available), copies the gif image to the clipboard without the need to pick a folder.

**Comment by NickeManarin** [comment]
Done. I implemented an option to copy the file, folder path or file path while still letting you pick a folder where to save.

![clip](https://user-images.githubusercontent.com/14798947/33506981-4e36f866-d6d9-11e7-98fe-8774e0bc1aff.png)
