### ISSUE TITLE
Switch from "Editor Window" to "StartUp Window"

### ISSUE THREAD

**Issue by smaragdus** [NickeManarin/ScreenToGif#161]
Hello,

I don't find a way to switch from "Editor Window" to "StartUp Window" without restarting **Screen To Gif**-it is the only window which lacks the "back arrow" button. I can use the context menu but it lacks an item for "Board Recorder".

**Comment by NickeManarin** [comment]
Hi,
Indeed, there's no way to go back to the startup window after entering the editor. (And there's no need to, since every action is also available on the Editor).

About the context menu: you are right, I forgot to add the Board Recorder item.

**Comment by NickeManarin** [comment]
Added the "New Board Recording" context menu on the Editor window.

**Comment by smaragdus** [comment]
Thanks.
