### ISSUE TITLE
The new recorder UI does not support multi-screen

### ISSUE THREAD

**Issue by walterlv** [NickeManarin/ScreenToGif#164]
When the new recorder UI is enabled (just as the setting item below) , I find that it does not support multi-screen.
![the new recorder ui](https://user-images.githubusercontent.com/9959623/28295859-9389dac2-6b96-11e7-9e94-b6059a4c865f.png)

In details:
- When the editor UI shows in the extended screen, the new recorder UI will no longer show any pixel.
- But even when the editor UI shows on the main screen, the new recorder UI still show half when it is dragged to the edge.
![image](https://user-images.githubusercontent.com/9959623/28295954-70ee2b84-6b97-11e7-8fd9-edd3d97b993a.png)![image](https://user-images.githubusercontent.com/9959623/28296001-bbfde5ba-6b97-11e7-80eb-1bc5b0b559fb.png)
(Normal on the left and clipped on the right)
- When `Area` is activated, the `Area selection` window only shows on the main screen. Then I can't record on the extended screen.

**Comment by NickeManarin** [comment]
I need a few details about this bug:

Are you using a high DPI monitor?
Did you connect the external/second monitor after opening the recorder?

**Comment by walterlv** [comment]
I have two monitors connecting to my PC.
- Both use 96Dpi.
- Neither of them connect or disconnect during the Recorder Window displaying.
- I can reproduce this issue everytime with normal procedure.

---

To solve this issue, we could not create a maximized window and put a recorder UI onto it. These may help:
- Use multi-window and display each of them in one screen.
- Use a single window with non-maximized state and cover it to all screens.

Maybe I can find out and solve this issue this weekend. After that, I will create a new pull request.

**Comment by NickeManarin** [comment]
Oh, I think that I understand what's happening.

Is your secondary screen to the left of your primary screen?

**Comment by NickeManarin** [comment]
I just tested In here... I was assuming that no monitor would use a negative position (> 0;0/Left;Top), but if the secondary display is set to the left side, the app won't cover that screen.

![image](https://user-images.githubusercontent.com/14798947/28487207-83a40f28-6e62-11e7-81aa-25ec24d633fb.png)

**Comment by NickeManarin** [comment]
To solve this, it's pretty simple, just set Left and Top to the VirtualScreen coordinates:

![image](https://user-images.githubusercontent.com/14798947/28487216-e904f2c4-6e62-11e7-9ffd-5ac66e0b46f7.png)

Of course, there's a few adjustments to make, but nothing big.

**Comment by walterlv** [comment]
You'are right!
My secondary screen is on the left.

**Comment by walterlv** [comment]
It's not that simple.
It is possible that your coordinate will be incorrect when your window location changes.

**Comment by NickeManarin** [comment]
When the window location changes, it's possible to detect the new arrangement by listening to this event:

`SystemEvents.DisplaySettingsChanged += (sender, args) => { Dialog.Ok("a", "b", "c"); };`

**Comment by walterlv** [comment]
Solved. See #166 .
