### ISSUE TITLE
[Exception] The calling thread cannot access this object because a different thread owns it.

### ISSUE THREAD

**Issue by walterlv** [NickeManarin/ScreenToGif#165]
## Exception
System.InvalidOperationException:"The calling thread cannot access this object because a different thread owns it."

## Reproduce
Open the new recorder UI.

## StackTrace
![image](https://user-images.githubusercontent.com/9959623/28487096-a0ef0b32-6ebc-11e7-9dd6-b1bcfe6ab11e.png)

**Comment by NickeManarin** [comment]
Delete that **IF** inside the event **GarbageTimer_Tick**.
