### ISSUE TITLE
Getting a "deceptive site ahead" error when trying to download zip release

### ISSUE THREAD

**Issue by SvenLauterbach** [NickeManarin/ScreenToGif#167]
As a chrome user i get the following error message when clicking on the [download link](https://github.com/NickeManarin/ScreenToGif/releases/download/2.8.1/ScreenToGif.2.8.1.zip):

![image](https://user-images.githubusercontent.com/1760777/28560933-c130d9d6-711c-11e7-9c58-5925160564fd.png)

Chrome reports these details: "Google Safe Browsing recently detected phishing on github-production-release-asset-2e65be.s3.amazonaws.com. Phishing sites pretend to be other websites to trick you."

**Comment by NickeManarin** [comment]
Apparently, this a problem with GitHub. I can't do anything. :/
Thanks for letting me know about that.

**Comment by SvenLauterbach** [comment]
I already contacted github and they resolved the issue.
