### ISSUE TITLE
[Feature request]  `ctrl + s`  popup save dialog

### ISSUE THREAD

**Issue by eromoe** [NickeManarin/ScreenToGif#168]
Hi,

`ScreenToGif` is amazing ! Very easy to use.  Just one thing I think a little inconvenient ,  press `ctrl + s` show a right window, I have to click the `folder ico` to select where to save. Directly popup a save dialog to choose save path would be better I think.

**Comment by NickeManarin** [comment]
Hi, thank you :D

I understand the inconvenience, but it's currently necessary.

The panel that opens when you hit `Ctrl + S` or when you click `Save As` lets you choose between 4 types of output files, each one of them has its own `Output Folder` and `Filename`.

So, there's a need for it to happen like that. :/
