### ISSUE TITLE
No option to make gif transparent

### ISSUE THREAD

**Issue by kylelamse** [NickeManarin/ScreenToGif#169]
This seems like it should be a basic feature.  Is there any plan to implement this?

**Comment by NickeManarin** [comment]
There's currently no plan for this feature. The main purpose of the app is to make small recordings and save as gif or video. So, a transparent background is not so common (I think).

**Comment by vatterspun** [comment]
> The main purpose of the app is to make small recordings and save as gif or video. So, a transparent background is not so common (I think).

Yeah that's what I'd expect the program would focus on.  Transparency makes sense as out of scope.

**Comment by NickeManarin** [comment]
Btw, since ScreenToGif 2.26, it's possible to work with gifs with transparency.

If you animation is not transparent, you can select one color to be treated as transparent (like a background).
