### ISSUE TITLE
Editor issues

### ISSUE THREAD

**Issue by lammbert5** [NickeManarin/ScreenToGif#175]
i'm having problems with the editor
>it won't open after i press f8 to stop recording
>it won't open on startup
Everything else seems to work, however.

**Comment by NickeManarin** [comment]
Less see, I need more details:

Which version of windows are you using?
Can you open the Editor by opening the StartUp window first?
Are you using the latest version of the app (v2.9)?
After trying to open the Editor, can you see it on the taskbar?

**Comment by lammbert5** [comment]
windows 7
You can't get to the editor at all, i am using 2.9
it does show it on the taskbar, even showing the preview window, but clicking on it doesn't open it

**Comment by lammbert5** [comment]
problem fixed, no idea what i did to fix it

**Comment by NickeManarin** [comment]
Hmm, maybe it was outside the screen. If this happens again, use `Windows + Left Arrow` or `Window + Right Arrow` to move the window.
