### ISSUE TITLE
Request for improvement

### ISSUE THREAD

**Issue by lefty06** [NickeManarin/ScreenToGif#177]
Hi all,

i've checked the existing posts and could not find the suggestions i'm bringing forward.

It would be very useful to have some additional picture editing tools to allow:
-To draw an area to get viewer's attention on a particular zone
-To draw lines to get viewer's attention on a sequence of events occurring in the animation.

A possible example of what it could look like would be Irfanview:
-Press c and enter
-Press crtl +  F11 => The screenshot will appear
-Press F12 => Basic image editing tool bar shows up

Tools:
Arrow Line tool
Line Tool
Rectangle tool
Elipse tool
Background/Foreground color, thickness of lines

![image](https://user-images.githubusercontent.com/31104194/29419727-c42f7450-8367-11e7-8d98-2d1d04590145.png)

**Comment by NickeManarin** [comment]
You can add shapes to your frames and with the next version, v2.27, you'll be able to show focus on some part of the frames by using the obfuscation tool.

**Comment by NickeManarin** [comment]
I still need to improve the UX, add more shapes, btw.
