### ISSUE TITLE
[Bug] Bad GIF compilation

### ISSUE THREAD

**Issue by Kristinita** [NickeManarin/ScreenToGif#18]
### Summary

I get GIF bad quality.

### Expected behavior

I make video in ScreenToGIF editor panel use [LICEcap](http://www.cockos.com/licecap/) program.

![LICEcap output](http://i.imgur.com/64PoeV3.gif)

### Actual behavior

![ScreenToGIF output](http://i.imgur.com/SXHixOn.gif)

### Steps to reproduce

I make and edit GIF → `Save as` → my parameters:

![Parameters](http://i.imgur.com/GILbpk9.png) 

But I get bad file in output.

### Additional information

But other GIF, when I make use ScreenToGIF, is good:

![Additional GIF](http://i.imgur.com/KosnXsO.gif)

### Attached Files

[Project file](http://jmp.sh/rJmwiGw)
[Output file](http://jmp.sh/lQprVkm)

### Environment

**Operating system and version:**
Windows 10.0.14393
**ScreenToGif**
Version 2.2.160907

Thanks.

**Comment by Kristinita** [comment]
Also bad compilation. If need, I wrote steps to reproduce:

### Expected behavior

![Expected behavior](http://i.imgur.com/IjsP5yD.gif)

### Actual behavior

![Actual behavior](http://i.imgur.com/NAt1bsS.gif)

### Project file

![Autocomplete.stg](http://jmp.sh/7faKhfH)

Thanks.

**Comment by NickeManarin** [comment]
Hi @Kristinita :)

During the last month, I developed a **new encoder** that suits this kind of animations. I believe it will be ready for release 2.3.

Here's the results with the new encoder:

### First animation
![comparison 1](https://cloud.githubusercontent.com/assets/14798947/18859037/f179d57a-8446-11e6-9ba9-9f82d77c16cc.png)

_The first animation was encoded with the new encoder. You can see the reduced file size._

![auto 1](https://cloud.githubusercontent.com/assets/14798947/18859068/341f7b8c-8447-11e6-9664-41077e7e9d0f.gif)


### Second animation
![comparison](https://cloud.githubusercontent.com/assets/14798947/18858890/dd9d7972-8445-11e6-8f12-fdc11c7a4016.png)

_Again, the first animations was encoded with the new encoder._

![auto 2](https://cloud.githubusercontent.com/assets/14798947/18858915/124161de-8446-11e6-9186-9b7eb451d1b5.gif)

Thank you so much for your detailed feedback. 👍

**Comment by Kristinita** [comment]
In second example my avatar is dark:

![Dark avatar](http://i.imgur.com/NZopZjT.png)

We are waiting a new release. Do not forget to update your package in [Chocolatey](https://chocolatey.org/packages/screentogif).

Thanks.

**Comment by Kristinita** [comment]
@NickeManarin, another bad encoding of file <http://jmp.sh/NQlPWRE>.

![Bad encoding](http://i.imgur.com/fWDEGnU.gif)

Maybe you make pre-release 2.3 version?

Thanks.
