### ISSUE TITLE
Inconsistencies between the various windows' styles and the back button position

### ISSUE THREAD

**Issue by mlaily** [NickeManarin/ScreenToGif#186]
Any reason why the webcam window has the default window style and a back button in the bottom left corner, while the recorder and board windows have a custom style and their back button in the top left corner?

I think it would be better if the back button position was consistent between windows.

I'm also not sure if there is a technical reason for the custom window style or not, but I miss some features of the native windows. (For example the ability to maximize the window, either with the maximize button, or by dragging a window to the top of the screen. More generally, I miss [Aero Snap](https://blogs.windows.com/windowsexperience/2015/06/04/arrange-your-windows-in-a-snap/).)

What's your opinion about this?

Anyway this tool is great, thank you!

**Comment by NickeManarin** [comment]
There's a technical reason for the screen recorder and board recorder to have custom windows.

It's possible to use the default window style for the board recorder, but that requires some kind of big changes (that I'm planning to do by the end of the year).

**Comment by NickeManarin** [comment]
The back button will be removed following version 2.13.
