### ISSUE TITLE
[Feature request] Warn on exit

### ISSUE THREAD

**Issue by vatterspun** [NickeManarin/ScreenToGif#188]
This is really a feature request but I'm submitting this as a bug just because I lost a bunch of work.  It's not critical.

Steps:
1. Launch program
2. Goto editor
3. Record something or open a GIF file and make some changes
4. (Not thinking) click X in the top-right corner

**Defect**: Program closes, changes lost

**Expected behavior**: Prompt user to save changes before shutdown or at minimum ask "are you sure?".  Note that this doesn't make much sense unless there's something recorded or changes have been made to a given file.

**Comment by NickeManarin** [comment]
You are right 😊

I implemented this behavior soon after the release of v2.9, so it will be available with v2.10.

It only asks yo close if there's really something being edited.

Btw, I think that you can recover your work by clicking on "Recent Projects" and selecting a project from the list.

**Comment by vatterspun** [comment]
> You are right 😊 ... I implemented this behavior soon after the release of v2.9, so it will be available with v2.10.

Awesome :)

> Btw, I think that you can recover your work by clicking on "Recent Projects" and selecting a project from the list.

Very cool, thanks

**Comment by saucesome** [comment]
> Btw, I think that you can recover your work by clicking on "Recent Projects" and selecting a project from the list.

This saved me. I just had a crash with a longish recording (pressed Up arrow while focused on the timeline images and the app locked up -- I was using left/right arrows to navigate via press-and-hold).

Windows 10 on latest version (updated today).
