### ISSUE TITLE
Overwritten files don't decrease in size

### ISSUE THREAD

**Issue by duarteframos** [NickeManarin/ScreenToGif#19]
One thing I have noticed in the past and has continued happening for several versions now is that if a file is saved overwriting an existing GIF recorded in a previous session it's file size never really decreases even if the new recording is smaller than the original.

Say I record a capture and save it has gif (henceforth called Capture_A.gif) with a file size of 2.5Mb, then close ScreenToGif . I then proceed to open a new session and make a second recording which is considerably shorter than the previous one.

If I save it as Capture_B.gif it has 1.3Mb, but if I turn on the _Overwrite_ option and save it over Capture_A.gif it will still save with 2.5Mb file regardless of the actual size.

If I go back to the file browser and erase Capture_A.gif and save it again it will correctly present it's 1.3Mb file size.

Is this intended behavior or some sort of bug?

**Comment by NickeManarin** [comment]
It was a silly bug and it's fixed.

During the creation of the gif file, I was opening the file and overwriting instead of creating a new one.

It had to do with a wrong flag during a FileStream call. 

:)

**Comment by duarteframos** [comment]
Wow that was quick, you must have beaten some record of shortest time between a bug report and a bug fix in the history of man kind! :)

Thanks for the fix!

**Comment by NickeManarin** [comment]
It was a very silly bug. :D
