### ISSUE TITLE
Error with msvcr120_clr0400.dll

### ISSUE THREAD

**Issue by peter-mw** [NickeManarin/ScreenToGif#190]
Screentogif stopped working today with some error of msvcr120_clr0400.dll

![image](https://user-images.githubusercontent.com/5698247/30484385-e5cb6ace-9a32-11e7-8307-32173da7e032.png)

**Comment by Rictusempra** [comment]
I suppose that's the problem with your .net framework. Have you reinstalled [it](http://www.microsoft.com/en-us/download/details.aspx?id=49982)?

**Comment by peter-mw** [comment]
I just installed 4.7 i had 4.6 and still get the error. 

Probably its something on my PC because it was working fine yesterday
