### ISSUE TITLE
monetize this

### ISSUE THREAD

**Issue by brandonmp** [NickeManarin/ScreenToGif#191]
This is far & away the best app of its kind, and it's one I miss every time I'm on linux.

Donations is a broken model for FOSS sw & you deserve to make a living on an app this good, so imo consider monetizing.

**Comment by vatterspun** [comment]
>consider monetizing

Everyone has a different reason for this kind of work, but @brandonmp is not wrong that this sort of thing could be monetized.  I hope you avoid adware/bundleware route however.  If you haven't been contacted by someone trying to get you to bundle your software, it should be coming soon.  I'd be happy to suggest some possible tricks to make some dough but remain in the freeware camp.

Then again if you just feel generous and want people to have great screen recording tools like this one, that's awesome too :)

**Comment by NickeManarin** [comment]
@brandonmp Thank you for your kind words.

I want to keep this app alive without any ads or bundles, but I also want to stay free.

@vatterspun I was only contacted by people wanting to add ads to my webpage, but I always refuse :)

So, the only way to monetize this app that I can think right now is to create some sort of commercial license or something like that.

**Comment by DeathRowRecords** [comment]
If ScreenToGif made a BIG impact on people, I feel like this project should grow naturally without any interference by greasy hands ( my 2¢ ). Azz stupid as it be from FOSS Camp perspectives or Life in general ( spiritual or scientific ) we are absolutely connected, there's no question about it. How will you serve the world? What do they need that your talent can provide, That's all you have to figure out. I can tell you from experience the effect you have on others is the most valuable currency there is. Your need for acceptance can make you invisible in this world, and the decisions we make in this moment, which are based in either love or fear. So many of us choose our path out of fear disguised as practicality.

**Comment by 0x53A** [comment]
You could gate new features behind donation targets and/or encourage pull-requests.

People may be more inclined to pay if they see a shiny new feature the donation pays for. The other way around, if someone files a feature request, you could explicitly ask for a payment.

--------------------

Also, the donation option is really hidden :-)

On github, I always go directly to the release tab; inside the program I would expect that almost no-one opens the settings.

I have no idea if such a thing would make any difference (there is probably some research out there), but you could show a splash-screen once on start after the app has been used for a combined duration of half an hour or so.

That way the user gets prompted _after_ having already used it multiple times and maybe appreciates it more.

**Comment by DeathRowRecords** [comment]
@0x53A [With all due respect](https://media.tenor.co/images/2dc3992bb2ba3ef62551c6cdb2bc82f7/raw). I don't know what kind of social engineering is dat but I think u r a blast from the past, big bang was the proof of that. This incantation sorcery ( implementation ) can cause more to the project, than the importance of delivering a great User Experience.
