### ISSUE TITLE
Save As Gif Should Default to Project Name.gif

### ISSUE THREAD

**Issue by spottedmahn** [NickeManarin/ScreenToGif#193]
When I save my project and then go to save a gif, I end up having to retype the filename again.  IMHO, it should use the project name as the default.  Thoughts?

How feasible would this be in the current code base?  I'm open to submitting a PR for this.

**Comment by NickeManarin** [comment]
Do you mean that if you open a project file named "Example.stg", the suggested filename of the gif (and other output types) should be "Example.xxx"?

Also, do you think that it should use the same output folder?

This could be implemented, but it needs to be optional.

**Comment by spottedmahn** [comment]
No, but that is another valid scenario where it should probably apply.  My use case is: record -> save prj -> save gif.  After I save the prj, I have to re-type the filename for gif.

Yes, same output folder.

Copy that.

I happy to assist with this request 😄

**Comment by NickeManarin** [comment]
Oh, for that behavior there's a similar ticket open.
#125

**Comment by spottedmahn** [comment]
thanks Nicke
