### ISSUE TITLE
Gaussain Blur

### ISSUE THREAD

**Issue by spottedmahn** [NickeManarin/ScreenToGif#194]
It would be very handy to have a gaussian blur for hiding parts of the gif.  I currently hide parts of the gif by drawing but it doesn't look professional imho.

![vsts markdown for linking work items](https://user-images.githubusercontent.com/14079228/30864042-8fcbc710-a2a0-11e7-9b3f-d2add3c6c57d.gif)

vs

![gaussian blur](https://user-images.githubusercontent.com/14079228/30864317-363a7a9c-a2a1-11e7-97f6-9fce05d044d6.png)

Thoughts?

**Comment by NickeManarin** [comment]
#48

**Comment by spottedmahn** [comment]
thanks Nick!
