### ISSUE TITLE
crash when incorrectly specifying save location

### ISSUE THREAD

**Issue by kodonnell** [NickeManarin/ScreenToGif#196]
Recorded a gif and went to save ... in the 'location' I picked a file, and didn't specify anything for the filename. It crashed repeatedly. It only worked when I realised I was meant to pick a folder in 'location', and specify a name, etc. My mistake, but this should be handled?

**Comment by NickeManarin** [comment]
Hmm, could you take a screenshot of the "Save As" panel?

I tried to reproduce this issue by typing the full filename on the "Destination folder" text field.
The app gave me a warning, saying that I needed to select a folder that exists, but no crash.

**Comment by kodonnell** [comment]
OK, now I can't reproduce, though I managed to twice previously. However, I have rebooted, and the system was also under high load before.

Closing as I can't reproduce.

**Comment by NickeManarin** [comment]
Oh, that's interesting...

I would like to take a look at the log files (if there's any), to try to understand if it's possible to avoid this kind of issue.

There should be a folder called Logs (it's possible to change the location of this folder, so it varies based on your settings). It's understandable if you don't want to share those files.

**Comment by kodonnell** [comment]
Sorry, I can't find the log files ... the location is set to the default ('.'), and I don't know where that points. I checked e.g.  `%AppData%\Local\Temp\ScreenToGif\Recording`

**Comment by NickeManarin** [comment]
'.' is a relative path, so it points to the same location as the executable.

**Comment by kodonnell** [comment]
Nothing in `C:\Program Files (x86)\ScreenToGif` sorry ...

**Comment by NickeManarin** [comment]
Oh, okay. Thanks anyway :)
