### ISSUE TITLE
Record/convert directly to WebM format

### ISSUE THREAD

**Issue by BoQsc** [NickeManarin/ScreenToGif#199]
Introduction to WebM: https://www.youtube.com/watch?v=IETReChj4Xk
More old news about WebM: http://blog.johnmuellerbooks.com/2014/07/11/webm-replacing-the-animated-gif/

I recorded Gif that weighted 4.5mb, converted it into 2.2mb WebM
Using this project: https://compressify.herokuapp.com/
I was able to compress 2.2mb WebM into 400kb WebM that works and looks the same as 4.5mb Gif.

Was unable to do so with any kind of Gif compression.

**Comment by vatterspun** [comment]
Related: #129   Ultimately I think it comes down to the fact that WEBM is a video format and should be compared to other video tools.  The reason GIF has been around for so long is it's (mostly) not a lossy format and can be easily modified and changed.  One person can share an initial GIF that others can then add stuff to (such as any number of JCVD gifs: https://giphy.com/search/bloodsport).

**Comment by BoQsc** [comment]
> Animation is an art of drawing sketches of object and then showing them in a series of frames so that it looks like a moving and living thing to us while a video is a recording of either still or moving objects. 

[Source of definitions](http://www.differencebetween.com/difference-between-animation-and-vs-video/)
**Animated** GIF and WebM **Video** format is very similar thing.
 Animations are drawn by hand on a multiple sheets and put together and finally ends up recorded as a Video. 
The only difference is that GIF are interpreted differently on the web browsers, than any kind of video format.
Video formats are given a player interface by default, while GIF's are only rendered without any additional control except for well known "stop repeating this GIF" function.

**Comment by NickeManarin** [comment]
Hmm, [you can try using the FFmpeg option to export to WebM.](https://github.com/NickeManarin/ScreenToGif/wiki/FAQ-%28Frequently-Asked-Questions%29#how-can-i-export-the-project-to-a-video-mp4webmaviwmv)

**Comment by vatterspun** [comment]
> Animated GIF and WebM Video format is very similar thing.  Animations are drawn by hand on a multiple sheets and put together and finally ends up recorded as a Video.

I can't think of a way to consisely explain this, but modern video functions as a series of objects rather than a series of sequential images.  GIF files are so substantially larger because (most of them) behave as 100 (or whatever) individual images.  Really you can test this by creating a WebM file, editing it, and then compressing it again.  If it loses quality over time, it's not a replacement for GIF.

**Comment by vatterspun** [comment]
Related thread: #252

**Comment by NickeManarin** [comment]
I'm closing this issue, since it's possible to export as WebM via FFmpeg.
