### ISSUE TITLE
[Feature Request] Add Save to Clipboard

### ISSUE THREAD

**Issue by 0x53A** [NickeManarin/ScreenToGif#20]
Most of the time (99%) when I record something with this great tool, I want to directly paste it somewhere.

It would be cool if there was an option to save the gif directly to the clipboard.

I think internally it should save it to a temporary file in %temp%, and then copy that.

**Comment by NickeManarin** [comment]
The encoder now has a "Copy" context menu.

**Comment by sirtet** [comment]
Where is this context-menu to be found?

**Comment by NickeManarin** [comment]
I'm sorry, I forgot to write that it's available for version 2.4 (still not released).

**Comment by sirtet** [comment]
I see... do you have an idea about how soon you want to release that 2.4?

**Comment by NickeManarin** [comment]
This weekend, if nothing bad happens.

**Comment by sirtet** [comment]
I see now, there's only a copy to clipboard AFTER SAVING.
Well, that's a helpful feature in some situations too, i think.
But i was hoping for a button "Render to clipboard". This is nice if i only paste the gif to a forum, no need for a saved version.

PS:
The context menu options do not all work, and paths are inconsistent:
COPY
[nothing happens] 
Should this remember the last copy-action? Or what is it?
COPY NAME
C:/Users/toro/Desktop\test.gif
COPY PATH
C:\Users\toro\Desktop

**Comment by NickeManarin** [comment]
I understand, that's why this ticket is still open. I'm planning to add an option that will encode to a file stored inside the temp folder and automatically copy that file to the clipboard as image or file.

To clarify:
**Copy:** Copies the file to the clipboard, so you can paste in other folder.
**Copy as image:** Loads the gif into the clipboard, allowing you to paste on Paint for example. 
**Copy filename:** Copies the entire path, with the filename and the extension.
**Copy folder path:** Copies only the folder path where the file is located.

**Comment by sirtet** [comment]
I see... maybe also call it Copy AS FILE

PS:
Note the different slashes:
COPY NAME
C:/Users/toro/Desktop\test.gif
COPY PATH
C:\Users\toro\Desktop

**Comment by NickeManarin** [comment]
Yes.

That's strange, maybe it's some sort of language or system configuration. Mine returns:

C:\Users\Nicke\Desktop\a.gif  
C:\Users\Nicke\Desktop

**Comment by EMLVIRUS** [comment]
This request seems really popular but also perhaps severe burden to RAM.

**Comment by sirtet** [comment]
Burden to RAM? Why would it? 
Unless there is a constant copying happening in Background, it would not produce any more load on anything.

**Comment by NickeManarin** [comment]
Done. _(Ready for release 2.5)_

There's a check box in the **Save As** panel, when enabled, the file will be saved inside the temp folder (You can change that folder on the Options window) and after the encoding completes, will be copied into the clipboard.

**Comment by johnknoop** [comment]
It seems to be copied as a file, rather then just the contents itself, which makes it impossible to paste it into applications like Slack.

**Comment by NickeManarin** [comment]
> It seems to be copied as a file, rather then just the contents itself, which makes it impossible to paste it into applications like Slack.

Yes, this is a limitation of Windows. It's not possible to copy a gif file without losing data. So now, it only allows to copy as file instead of as image.
