### ISSUE TITLE
Windows position not properly saved when have more monitors than 1

### ISSUE THREAD

**Issue by shoter** [NickeManarin/ScreenToGif#205]
When I close SreenToGif on monitor which is not my primary monitor then after restarting my application it is being opened on the wrong display.

Video showcasing bug:
https://www.youtube.com/watch?v=A2rkuI32sf4&feature=youtu.be

**Comment by NickeManarin** [comment]
Fixed. It will be available with the next release. v2.11.1 or 2.12
