### ISSUE TITLE
ScreenToGif Translator is not working in Windows10

### ISSUE THREAD

**Issue by svatas** [NickeManarin/ScreenToGif#206]
Hi all,

as my native language is Czech and it is not available in ScreenToGif I decided to create a translation. However, it is not possible to start the translator application under my Windows10.

Can you please make Translator app compatible with Windows 10?

Have a nice day.

Svatopluk
Prague, Czech Republic

**Comment by NickeManarin** [comment]
It works alright on my Windows 10 machine.

Is there any error message?

The translator needs to create a folder (and download some files) at the same folder where it's located, maybe could be related to that.

**Comment by svatas** [comment]
the original message was, that Win10 can not start the app without any special error message. I created new special folder and from this moment this app is working. So you were right with the folder creation as it was not possible to create a new one. Now it is working.

Thanks for quick reply. I will provide the translation.

**Comment by NickeManarin** [comment]
Great, I'll add a warning on the wiki about this issue.
