### ISSUE TITLE
gif green screen

### ISSUE THREAD

**Issue by ghost** [NickeManarin/ScreenToGif#208]
In the use of 2.9 / 10 version generated gif green screen phenomenon, the video format is not, how is the problem going on?
https://img.vim-cn.com/72/361146bf7b31f862858762aefea7e0fee02e60.png

**Comment by ABrandau** [comment]
Same issue, guess I will have to grab an old version
https://imgur.com/a/ycfj8

**Comment by NickeManarin** [comment]
Try changing the dummy color to magenta or use the other gif encoder (v1.0).

**Comment by ABrandau** [comment]
Version 2.2 seems to work fine, been using the software for some time, thanks!

**Comment by NickeManarin** [comment]
Hmm, did you try changing the dummy color to magenta or using encoder v1.0?
