### ISSUE TITLE
[Feature Request] Add drag/drop functionality to file window

### ISSUE THREAD

**Issue by 0x53A** [NickeManarin/ScreenToGif#21]
![image](https://cloud.githubusercontent.com/assets/4236651/18993648/8c67a8d4-8724-11e6-9c4d-cec566b4a494.png)

I would like to be able to drag a file from this window and drop it somewhere else.

Also, a context menu with "Copy to clipboard" would be awesome. (ref https://github.com/NickeManarin/ScreenToGif/issues/20)

**Comment by NickeManarin** [comment]
Noted :)

**Comment by NickeManarin** [comment]
Drag to move enabled. Also, a context menu with copy operations, such as: Copy, Copy as image, Copy filename and Copy folder path.

Release 2.4, when available.
