### ISSUE TITLE
Feature Request - implement an option to "Clean TEMP folder right after closing ScreenToGif"

### ISSUE THREAD

**Issue by user3323** [NickeManarin/ScreenToGif#212]
I make a lot of gifs, all gifs in HQ with a lot of frames, so my TEMP folder for only 1 day can raise up to 1 GB or more. That's too much. I think it would be great if there would be an option "Clean TEMP folder right after closing program".

Thanks!

**Comment by NickeManarin** [comment]
It's a little bit tricky to implement this. ScreenToGif accepts multiple instances and even if the Editor window is closed, the Encoder can stay opened (if there's any active encoding).

**Comment by mabakay** [comment]
This feature is already in Windows 10. It is called "Storage Sense" ;-)

**Comment by NickeManarin** [comment]
I added the option for automatically erasing projects, with a configurable maximum age in days. For example, you can set to erase projects older than 1 day.

Also, the app will warn about the free space.
