### ISSUE TITLE
[Feature request] Add more hotkeys support

### ISSUE THREAD

**Issue by Kristinita** [NickeManarin/ScreenToGif#22]
<del>
### Request

Added hotkeys for all operations, when I make on my GIF. I want to ScreenToGif users can do all the operations, never using the mouse. GIF of my macros:

![ScreenToGIF Macros](http://i.imgur.com/Wucz4YD.gif) 

### Justification

**You greatly simplify record macros in ScreenToGif.**

I make AutoHotkey macros for operations, I often do — <https://gist.github.com/a7e71ef8c6778f86a047ca105c3025dc>. But I've been doing it a long time. I have problem: if window ScreenToGif bit shift, macros not will work. Do not recommended make macros using the mouse, because it requires very accurate hitting.

If the only record macros to hotkeys, macros are always well run, no matter what the size of ScreenToGIF window and wherever ScreenToGif window was not.

### Environment

**Operating system and version:**
Windows 10.0.14393
**ScreenToGIF:**
2.3 Alpha b

Thanks.
</del>

**Comment by Kristinita** [comment]
@NickeManarin , I update my request. Thanks.

### Request

1. Add hotkeys for switching between panels.
2. Add hotkeys for panels items.
3. Add documentation or tooltips for hotkeys.

### Justification

I record [macro](https://gist.github.com/40d9c25ed7ad6213e7e1c115016c60a5) for fade effect for stable release ScreenToGIF. 

![FadeEffectMacro](http://i.imgur.com/LcBAfNK.gif)

But I have 2 problems.

1. In some cases, the macro does not work, because the number of pressed <kbd>Tab</kbd> is different for different screencasts.
2. I need many times press <kbd>Tab</kbd> or <kbd>Shift+Tab</kbd>.

If you add a hotkeys, your users will be easier.

Thanks.

**Comment by NickeManarin** [comment]
How about the idea of ScreenToGif supporting macros?

Like simple commands such as:

`Select>2>1 (index, selection lenght)`
`Fade>2 (lenght)`

**Comment by Kristinita** [comment]
> How about the idea of ScreenToGif supporting macros?

Oppose, because for macros now there many good programs including open source. For example, AutoHotkey → [PuloversMacroCreator](https://github.com/Pulover/PuloversMacroCreator).

Of course, if you add the macro support, it would be good, but I would prefer if you spend time on other tasks to improve the ScreenToGIF, which can be solved using other programs.

Thanks.

**Comment by duarteframos** [comment]
Macros would be great, especially if one could directly define keyboard shortcuts for them from the UI :)

**Comment by Kristinita** [comment]
@NickeManarin , status?

**Comment by NickeManarin** [comment]
Not yet, I just fixed some bugs but I had no time to work with the shortcuts. I should work with this issue this week.

**Comment by Kristinita** [comment]
We wait 😺 .

**Comment by NickeManarin** [comment]
I added shortcuts to the transitions.
I also added to the Apply/Cancel actions of the panels. To apply <kbd>Alt + E</kbd> or  to cancel <kbd>Esc</kbd>.

So nº 2 is done. I'm still doing the number 3º of the list.

**Comment by Kristinita** [comment]
@NickeManarin, thanks, nice work! But after I apply my fade transition, how I can move without mouse to my selected frame — active frame, when I press <kbd>Ctrl+Alt+T</kbd> — to continue editing?

![Apply transition](http://i.imgur.com/cbpn7k2.png)

ScreenToGIF 2.3.161201.

Thanks.

**Comment by NickeManarin** [comment]
Without the mouse there's no way, currently. 

I should put the focus on the list after closing the panels. Got it. ;)

**Comment by NickeManarin** [comment]
Ready for release 2.4: After clicking "Apply", the focus will be set to the selected frame.

**Comment by Kristinita** [comment]
@NickeManarin , we wait release 2.4 version in Chocolatey.

Thanks.

**Comment by Kristinita** [comment]
@NickeManarin , <kbd>Ctrl+Alt+T</kbd> → `Apply` → what I do press, to continue editing my frames in version 2.4?

**Comment by NickeManarin** [comment]
@Kristinita Strange, the focus is there, you can see by pressing <kbd>Tab</kbd> and <kbd>Shift+Tab</kbd>.

Something new must be breaking the tab flow. :/

**Comment by Kristinita** [comment]
Nothing occurs.

![Tab switch](http://i.imgur.com/bNdFxSY.gif)

**Comment by Kristinita** [comment]
@NickeManarin , and why <kbd>Alt+E+Enter?</kbd> In Windows, we can use only one non-modifier key for shortcuts, but no 2 — <kbd>Alt</kbd> and <kbd>Enter</kbd>. Isn't it?

Thanks.

**Comment by NickeManarin** [comment]
Well, I have to fix this, because I do apply focus on the frame after closing the panel.

https://github.com/NickeManarin/ScreenToGif/blob/master/ScreenToGif/Windows/Editor.xaml.cs#L3911  
and
https://github.com/NickeManarin/ScreenToGif/blob/master/ScreenToGif/Windows/Editor.xaml.cs#L4777

But it looks like it fails somehow.

Btw, It's <kbd>Alt+E</kbd> or <kbd>Enter</kbd> not both together.

**Comment by NickeManarin** [comment]
Fixed. 
When applying the effect, the focus was lost.
When cancelling, the focus worked as expected.
