### ISSUE TITLE
Implementing gifski?

### ISSUE THREAD

**Issue by marcsyp** [NickeManarin/ScreenToGif#220]
First, thanks for this great tool!  I use it all the time to make quick work-in-progress GIFs to share with my team.

That said -- I'm struggling to find the best encoder for my purposes -- System is super fast, has good file sizes, and provides the best quality on my new Win 10 machine, but doesn't translate well to mobile _at all_ (very slow playback, crashes, bad color rendition).  "1.0" translates well to mobile (smooth playback, no additional artifacts) and offers far better  quality than "2.0" but often results in pretty bad banding, and is significantly slower to encode.

I saw that there is a high-quality gif encoder out there that is available for integration in OS projects -- called gifski -- have you taken a look, any plans to integrate into Screen2Gif???  Would love a new option, and it looks like it uses some trickery to get beyond the 256 color limit (or at least appear to). I would go for a longer encode process if I could get very high quality across devices...  thoughts?

Thanks,
Marc

**Comment by marcsyp** [comment]
forgot to provide a link:

https://gif.ski

**Comment by NickeManarin** [comment]
Hi, thanks for the kind words :)

I just implemented the option to use FFmpeg as a gif encoder, so it should be easy to add gifski.

One question, does it support variable framerate (such as FFmpeg)?

**Comment by vatterspun** [comment]
I guess the main question is whether or not gifski generates files that are compatible with older players (part of the reason for the ongoing success of Animated GIF).  In some testing I did like a year ago I know FFmpeg worked well.

> looks like it uses some trickery to get beyond the 256 color limit (or at least appear to)

For something that's essentially a GIF with support for more than 256 colors, you might want to look into APNG: https://github.com/NickeManarin/ScreenToGif/issues/129

**Comment by NickeManarin** [comment]
Done, it will be available with v2.11.

>  I know FFmpeg worked well.

Indeed, it works well enough, it even supports variable framerate. Gifski CLI does not.
