### ISSUE TITLE
Persistent hints for image editing tools

### ISSUE THREAD

**Issue by byzod** [NickeManarin/ScreenToGif#224]
Currently when active a editing tool, the affecting scope hints will display at the bottom for few seconds (something like "this will apply to selected frame" or "this will apply to all frame")

The hints disappear too fast for me. Often, when I finished tweak the settings, then I remembered that I should check the affecting scope but the hint is no longer there, I have to cancel the current session then active the same tool again.

The good side is that StG remembers every settings I changed so at least I don't have to tweak them again.

**Suggestion:**
- The hints stay there for ever until you submit/cancel the current edition.
- Or, add an area to show the scope of current tool (selected frame or all frames)

I think this is an important information of a tool, it's worth giving it an area to let the user be able to understand which frames their edition will apply to.

**Comment by NickeManarin** [comment]
Done.
For now, the hints triggered by the action panel will stay visible until the panel gets closed.

It will be available with v2.13
