### ISSUE TITLE
Problem with Gifski

### ISSUE THREAD

**Issue by tpkn** [NickeManarin/ScreenToGif#225]
![34457437-3f0de3e6-edc1-11e7-9d3f-7a560ccde201](https://user-images.githubusercontent.com/18248992/34458349-22e6bf12-eddf-11e7-9304-53040cbec718.jpg)

Bare Gifski works fine. Any idea why this happens?

v2.11 with all default settings
Gifski v0.7.0
Win7 x64

**Comment by NickeManarin** [comment]
Sorry, it works with Gifski v0.6 but not v0.6.2 or v0.7.
The next release of ScreenToGif should take care of this bug.

**Comment by alphestdev** [comment]
Is the release date in sight?

**Comment by NickeManarin** [comment]
Unfortunately, no. Try using Gifski v.0.6.

**Comment by NickeManarin** [comment]
I fixed this bug, but I also changed the dependency to a .dll. 

For the next version of ScreenToGif, if you want to use Gifski, you'll need to enter Options > Extras and click to download the Gifski dll.

**Comment by winterlaite** [comment]
Hi, thanks for the great program. Just wanted to let you know that the link for Gifski in Options->Extras downloads gifski.exe, and not gifski.dll. 
Regards,
Winter

**Comment by NickeManarin** [comment]
If the download button isn't working for you, here's the link to download Gifksi:

http://screentogif.com/downloads/Gifski.zip

**Comment by NickeManarin** [comment]
Sigh, It was working when I was implementing the integration, but it's not working now. I'll have to fix this during this week.

**Comment by user3323** [comment]
@NickeManarin  

can I ask you, where do you get the Gifski DLL ? There is no DLLs on the official gif.ski website

**Comment by NickeManarin** [comment]
@user3323 I downloaded the source and compiled it into a dll.

**Comment by BobVul** [comment]
@NickeManarin Maybe a more descriptive error message for people who mistakenly use the exe? I had one left over from a previous version that was auto-detected, and it only came up as `Error` in the encoding output.

**Comment by vintproykt** [comment]
Windows 10 says that _this DLL is not supposed to be run on Windows_. How to fix this error?

`gifski.dll` is not blocked and placed in `C:/gifski`.

**Comment by edwinyzh** [comment]
Here I could't download the gifski dll inside the program, and I downloaded it manually using the link you provided below, and error when exporting to GIF, with the latest version:
  at ScreenToGif.Windows.Other.Encoder.<Encode>d__24.MoveNext()

Result:

2
