### ISSUE TITLE
Can't open clipboard.

### ISSUE THREAD

**Issue by DropsOfSerenity** [NickeManarin/ScreenToGif#228]
![image](https://user-images.githubusercontent.com/2287977/34509879-01bc6fea-f004-11e7-9965-d8215d4edf2a.png)

Getting this error any time I try to copy to the clipboard. Using version 2.11

**Comment by NickeManarin** [comment]
Do you have any clipboard manager? (apps that listen to clipboard changes)

**Comment by NickeManarin** [comment]
The apparent solution to this bug is just to wait and try to copy the file again. This fix will be ready for the next release.

**Comment by DropsOfSerenity** [comment]
@NickeManarin in order to reproduce this problem, download [HaxeDevelop](https://haxedevelop.org/). While this program is open, I get that error from ScreenToGif. All other programs are to be able to copy things fine.
