### ISSUE TITLE
How to scale during export as video using FFmpeg?

### ISSUE THREAD

**Issue by alphestdev** [NickeManarin/ScreenToGif#229]
It seems like you have created a possibility to pass parameters to FFmpeg while exporting as video. But I cant set them up properly to add `scale`. 

We start out with:

    -c:v libx264 -pix_fmt yuv420p -vf "pad=width={W}:height={H}:x=0:y=0:color=black"

I've tried to add `scale=560:356` in random places, but none these attempts didn't work.

    -c:v libx264 -pix_fmt yuv420p -vf "pad=width={W}:height={H}:x=0:y=0:color=black scale=560:356"
    -c:v libx264 -pix_fmt yuv420p -vf "pad=width={W}:height={H}:x=0:y=0:color=black;scale=560:356"
    -c:v libx264 -pix_fmt yuv420p -vf "pad=width=560:height=356:x=0:y=0:color=black"

You have no UI for this or docs on your website, and to get the docs on FFmpeg.org look like I need PhD in video editing. So could you help?

Thanks in advance.

**Comment by alphestdev** [comment]
Found it. 

    -c:v libx264 -pix_fmt yuv420p -vf "pad=width={W}:height={H}:x=0:y=0:color=black,scale=560:356"

**Comment by NickeManarin** [comment]
Awesome. Yeah, understanding FFmpeg docs is nearly impossible. 😁

**Comment by imeltemi** [comment]
-c:v h264_nvenc -pixel_format yuv420p -preset default
have a try，its faster！
