### ISSUE TITLE
Encoding progress bar

### ISSUE THREAD

**Issue by divyang8842** [NickeManarin/ScreenToGif#231]
Some times while saving the project as GIF, the encoding window shows process from  100 to 0, i.e. Reverse. Its random and I don't have steps to reproduce but it happens a lot time.

**Comment by NickeManarin** [comment]
During the "Analyzing Unchanged Pixels" stage? It means that the process is analyzing from the end to the start.

**Comment by divyang8842** [comment]
Oh, but it looks confusing as the progress bar is going from 100% to 0%.

**Comment by NickeManarin** [comment]
Indeed. I need to fix that.

**Comment by divyang8842** [comment]
Thanks.

**Comment by NickeManarin** [comment]
Done. It will be available with the next release.
