### ISSUE TITLE
[Feature request] Save size of slides after adding title frame

### ISSUE THREAD

**Issue by Kristinita** [NickeManarin/ScreenToGif#232]
### 1. Request

It would be nice, if preview size will be saved after adding title frame.

### 2. Justification

I preferred preview my recorded videos without vertical scrollbar. I think, that this is usually convenient for most users. In 2.11 version after recording I see slides without vertical scrollbar. Thank you!

**But** if I add title frame, size of preview slides is 100%. I need to set size of slides manually.

### 3. Steps to reproduce

I record video → `Stop` → `Edit` → I see, that slide size is 84%.

![84%](https://i.imgur.com/MPrGWoN.png)

`Image` → `Title frame` → I create title frame → `Apply`.

### 4. Actual behavior

100% size and vertical scrollbar.

![100%](https://i.imgur.com/LzSNRsZ.png)

### 5. Expected behavior

Size of preview slides remains 84%.

Thanks.

**Comment by NickeManarin** [comment]
Done.
It will be available with v2.13.
