### ISSUE TITLE
[Feature request] Preview speed

### ISSUE THREAD

**Issue by Kristinita** [NickeManarin/ScreenToGif#233]
### 1. Request

It would be nice, if would be possible preview slides faster.

### 2. Justification

1. Usually I use preview slides, for quick view my future videos and GIFs, that check, they contain bugs or not.
1. It would be nice, if would be possible view, how GIF or video looks at the speed as in output GIF or video before conversion.

At the time preview takes 2 times longer than the output video. It may take a lot of time of ScreenToGIF users.

### 3. Files

+ [**ScreenToGIF project file**](https://www.dropbox.com/s/b6b20bxwq2hmspe/KristinitaLuckyLinkProject.stg?dl=0),
+ [**Output ffmpeg video of this project**](https://streamable.com/bj22k) — 1 minute 49 seconds.

### 4. Steps to reproduce

I open project from section above → `Playback` → `Play`.

At the same time I start the timer.

### 5. Actual behavior

All slides show for me in 4 minutes 20 seconds. More than 2 times more than the time of a real video.

### 6. Expected behavior

Option, that user can view all slides in 1 minute 49 seconds, as in real video.

Thanks.

**Comment by Bludkey** [comment]
It seems fixed with last update!

**Comment by NickeManarin** [comment]
Changes were made with v2.28 that increased the preview speed.
