### ISSUE TITLE
[Feature request] Show Keyboard Clicks

### ISSUE THREAD

**Issue by alpgul** [NickeManarin/ScreenToGif#235]
Can you add to show keyboard clicks in record?
For Example:
![ show keyboard clicks](https://raw.githubusercontent.com/mushanshitiancai/vscode-paste-image/master/res/vscode-paste-image.gif)

**Comment by NickeManarin** [comment]
Yes, record something, while the Editor is open, head over to Image > Key strokes, personalize the appearance and press Apply.

**Comment by vatterspun** [comment]
Related #43
