### ISSUE TITLE
[Feature request] Shadow border

### ISSUE THREAD

**Issue by Kristinita** [NickeManarin/ScreenToGif#239]
### 1. Request

It would be nice, if would be possible to add shadow effect for frames as already existing `Border` feature.

### 2. Example

![Shadows](https://i.imgur.com/wMk2svm.png)

### 3. Argumentation

With shadow effect images look more beautiful.

### 4. Expected behavior

User record a video → select all frames (<kbd>Ctrl+A</kbd>) → `Image`:

Now user can select `Shadow` as select `Border` → user set shadows → `Apply` → shadows successful applied for all frames.

### 5. Examples in another apps

In [**Greenshot**](https://github.com/NickeManarin/ScreenToGif/issues/237) users can add shadows.

**If** would be possible edit in Greenshot multiple ScreenToGIF frames, it solves this request.

Thanks.

**Comment by NickeManarin** [comment]
Done!
It will be available with the next release, v2.19 in a few days.

> Editor UI with previewer
  
![image](https://user-images.githubusercontent.com/14798947/66262322-a54d9c80-e7b3-11e9-885f-79189aa9e035.png)

> Samples (Gif and Apng)  

![Shadow Test](https://user-images.githubusercontent.com/14798947/66262426-eba3fb00-e7b5-11e9-81b3-ef3f894b29ff.gif)
![Shadow Test](https://user-images.githubusercontent.com/14798947/66262430-f494cc80-e7b5-11e9-9347-d58fa128a0f3.png)

> Task  

![image](https://user-images.githubusercontent.com/14798947/66262425-e5158380-e7b5-11e9-8637-bd79e988ae76.png)

**Comment by vatterspun** [comment]
This looks great.  I know I did that UI suggestion but this looks much sharper than I expected.  Shadows help separate elements and give them a sense of structure, but I guess animations need it more than other things?  It's a big difference.  Thanks for the extra work on this.

**Comment by Kristinita** [comment]
**Status: CONFIRMED** :heavy_check_mark:

### Testing

I created this `.apng` file via ScreenToGIF.

![Thanks `.apng`](https://i.imgur.com/z1nwCmo.png)

**Comment by Kristinita** [comment]
@NickeManarin,

**Type: Suggestion**

### 1. Summary

You can add answer to [**this**](https://graphicdesign.stackexchange.com/q/80301/66040) Graphic Design question.

### 2. Benefits

1. If you add an answer, I will accept it. You will get at least 25 reputation points on this Stack Exchange site.
1. It can do ScreenToGIF a little more recognizable.

Thanks.

**Comment by NickeManarin** [comment]
Oh, nice idea. I just had to add other gifs, because of the size limit.
