### ISSUE TITLE
WebCam window should constrain the aspect ratio

### ISSUE THREAD

**Issue by DewVinci** [NickeManarin/ScreenToGif#24]
When the webcam window opens, it is never the correct aspect ratio. Also, there is no way to make it correct without guessing. It would be great if it could do one or more of the following:
1. Constrain the dimensions to match the aspect ratio (at least optionally)
2. Have a dropdown to select from supported and/or common sizes (with the correct aspect ratio)

**Comment by NickeManarin** [comment]
I agree with you. Thanks for the feedback.

I should improve the both the Webcam and Board recorders. I left them a little bit out of focus for a while.

**Comment by NickeManarin** [comment]
With the release 2.3.2 I implemented a "Scale" option that resizes the window following the aspect ration of the video feed.

This isn't the best solution, so it should be temporary.
