### ISSUE TITLE
[Feature request] Upload to selected Imgur account and album

### ISSUE THREAD

**Issue by Kristinita** [NickeManarin/ScreenToGif#240]
### 1. Request

It would be nice, would be possible to upload gif or apng to selected Imgur account and album.

### 2. Argumentation

I organize my images on albums. It brings more order to affairs.

### 3. Examples in other apps

Imgur API allow to solve this. [**ShareX**](https://getsharex.com/) supports upload to selected account and album:

![ShareX](https://i.imgur.com/SnqFSXt.png)

Thanks.

**Comment by web2033** [comment]
I second that.

**Comment by NickeManarin** [comment]
I'm still polishing it, but it will look like this:

![image](https://user-images.githubusercontent.com/14798947/37005133-ae8c1530-20b1-11e8-916e-bc1b18103daf.png)

You can select the album right away or pick one before uploading.

**Comment by Kristinita** [comment]
@NickeManarin:

**Status: :crying_cat_face: Not fixed**

### 1. Environment

+ ScreenToGif 2.13.1

### 2. Steps to reproduce

I authorize to my Imgur account in browser.

For ScreenToGif: `Options` → `Upload Services` → `Get OAuth token`

### 3. Expected behavior

Successful get OAuth token.

### 4. Actual behavior

> Woah there!
> The information you sent wasn't quite correct. Please return to the place that sent you to this page and try again.

![ImgurScreenToGIFOAuth](https://i.imgur.com/jfeIxvE.png)

Thanks.

**Comment by NickeManarin** [comment]
I forgot to update the Chocolatey package.
In a couple of hours it should be updated.

**Comment by Kristinita** [comment]
**Status: :heavy_check_mark: Fixed for me** in 2.13.3

Thanks!

**Comment by Kristinita** [comment]
**Type: Feature request**

### 1. Summary

@NickeManarin, could you do the same for `.apng` files?

### 2. Behavior

#### 2.1. Expected

`.gif`:

![GIF](https://i.imgur.com/o037Ywf.png)

#### 2.2. .apng

No `Upload the file` option:

![APNG](https://i.imgur.com/rGWgvlX.png)

### 3. Note

Also, it would be nice, if would be possible upload `.gif` and `.apng` files to different Imgur albums.

Thanks.

**Comment by NickeManarin** [comment]
@Kristinita I believe so.

**Comment by NickeManarin** [comment]
Done!
It will be available with v2.25

![image](https://user-images.githubusercontent.com/14798947/83956525-6a65a200-a835-11ea-886e-40ade3774325.png)
