### ISSUE TITLE
Error while encoding the gif with Gifski

### ISSUE THREAD

**Issue by DemoJameson** [NickeManarin/ScreenToGif#242]
► Title - 
　　Encode
▬ Message - 
　　　Error while encoding the gif with Gifski.
○ Type - 
　　　System.Exception
♦ [Version] Date/Hour - 
　　　[2.11] 01/15/2018 00:42:56
▲ Source - 
　　　ScreenToGif
▼ TargetSite - 
　　　Void Encode(System.Collections.Generic.List`1[ScreenToGif.Util.Model.FrameInfo], Int32, ScreenToGif.Util.Parameters, System.Threading.CancellationTokenSource)

♠ StackTrace - 
　　　在 ScreenToGif.Windows.Other.Encoder.Encode(List`1 listFrames, Int32 id, Parameters param, CancellationTokenSource tokenSource)

**Comment by NickeManarin** [comment]
Hi, this bug was fixed and it will be available with the next version of the app.

#225
