### ISSUE TITLE
Cannot run because of TypeInitializationException

### ISSUE THREAD

**Issue by kapsh** [NickeManarin/ScreenToGif#25]
I cannot run screentogif 2.2.0 on Windows 7 with .NET Framework v4.0.30319 installed. 
There are two errors in event log:

```
Application: ScreenToGif 2.2.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException
Stack:
```
```
Faulting application name: ScreenToGif 2.2.exe, version: 2.2.0.0, time stamp: 0x57cc4202
Faulting module name: KERNELBASE.dll, version: 6.1.7600.16385, time stamp: 0x4a5bdbdf
Exception code: 0xe0434352
Fault offset: 0x0000b727
Faulting process id: 0x8a0
Faulting application start time: 0x01d22ac8d97e734f
Faulting application path: C:\Users\admin\AppData\Local\Temp\ScreenToGif 2.2.exe
Faulting module path: C:\Windows\syswow64\KERNELBASE.dll
Report Id: 17e96c45-96bc-11e6-b2db-005056a43f38
```

(Yes, stack in message is empty).

**Comment by kapsh** [comment]
Version 2.1 on the same system shows Windows message "has stopped working" with this additional details:
[WER38CA.tmp.zip](https://github.com/NickeManarin/ScreenToGif/files/541607/WER38CA.tmp.zip)
[WER385C.tmp.appcompat.txt](https://github.com/NickeManarin/ScreenToGif/files/541606/WER385C.tmp.appcompat.txt)
[WER3186.tmp.WERInternalMetadata.xml.txt](https://github.com/NickeManarin/ScreenToGif/files/541609/WER3186.tmp.WERInternalMetadata.xml.txt)

(Maybe this was fixed in 2.2)

**Comment by NickeManarin** [comment]
.Net framework 4.6.1 required.

**Comment by kapsh** [comment]
Ok, thanks. I've missed this.
