### ISSUE TITLE
Bug in ".webm" output? (workaround)

### ISSUE THREAD

**Issue by PeterZuge** [NickeManarin/ScreenToGif#252]
_Note:  I have downloaded ffmpeg.exe from inside the utility and am using the latest version (version 2.11)._

Using ffmpeg as the encoder, and outputing to a ".webm" file results in a 0-byte file.
Changing the codec to "**libvpx**" resolves the problem.

Original "Extras" section (before my modification):
`-c:v libx264 -pix_fmt yuv420p -vf "pad=width={W}:height={H}:x=0:y=0:color=black"`

My modification to "Extras":
`-c:v libvpx -pix_fmt yuv420p -vf "pad=width={W}:height={H}:x=0:y=0:color=black"`

This change now correctly creates the output file as intended.  Obviously, changing the codec causes an issue if you want to output MP4 (you need to switch back to "**libx264**").  

Perhaps automatically changing the codec in "Extras:" if ".webm" is selected as file output?

Thanks!

**Comment by dogancelik** [comment]
I had the same problem, this fixed it, thank you @PeterZuge

**Comment by UNiXMIT** [comment]
Thanks that workaround works great. I wondered why it wasn't working. Thanks

**Comment by Hrxn** [comment]
Can confirm, this issue is still present for me (latest version of ScreenToGif). But the workaround works as described.

**Comment by NickeManarin** [comment]
With the latest release, v2.18, the app now supports presets for each file type when using FFmpeg.
Each file type has its own default preset, and for webm, I added the proper command to use `libvpx`.
