### ISSUE TITLE
Wrong screen location recorded (high DPI issue?)

### ISSUE THREAD

**Issue by jdpurcell** [NickeManarin/ScreenToGif#253]
The first time I position the recorder window and record, it works fine. When I switch back from the editor to record mode, if I don't re-position the record window, it records the wrong screen location. This may be related to high DPI; I'm using Windows 10 with 150% scaling.

The issue started with commit 453fae2613df254dbc486ec1845e2881562b15b1, with one of the changes in Recorder.xaml.cs.

Screenshot of the GIF timeline; notice how part of the recorder window border was captured:
![image](https://user-images.githubusercontent.com/6741660/35782446-2bb34ff4-09c6-11e8-9b71-bbbaf823fa39.png)

**Comment by NickeManarin** [comment]
Interesting, I forgot to calculate the position after loading the window. The event that is triggered when the window is repositioned does not fire on load.

I'll fix it and republish v2.12 shortly. Thanks for the feedback.

**Comment by NickeManarin** [comment]
Fixed. :)
