### ISSUE TITLE
System.Windows.Markup.StaticExtension

### ISSUE THREAD

**Issue by GWWalter** [NickeManarin/ScreenToGif#257]
After recoder recode and stop, the process had error exception, the message as below, please help me to solve this problem, thank you very much.

![s2g](https://user-images.githubusercontent.com/36215567/35894934-0fef28c0-0bf0-11e8-8956-c9a6c3362bbb.png)

OS: Winodws 7 Pro SP1

`
於 System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   於 System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   於 System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   於 System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   於 ScreenToGif.Windows.Other.Startup.Recorder_Executed(Object sender, ExecutedRoutedEventArgs e)
   於 System.Windows.Input.CommandBinding.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   於 System.Windows.Input.CommandManager.ExecuteCommandBinding(Object sender, ExecutedRoutedEventArgs e, CommandBinding commandBinding)
   於 System.Windows.Input.CommandManager.FindCommandBinding(CommandBindingCollection commandBindings, Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   於 System.Windows.Input.CommandManager.FindCommandBinding(Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   於 System.Windows.Input.CommandManager.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   於 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   於 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   於 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   於 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   於 System.Windows.Input.RoutedCommand.ExecuteImpl(Object parameter, IInputElement target, Boolean userInitiated)
   於 MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   於 System.Windows.Controls.Primitives.ButtonBase.OnClick()
   於 System.Windows.Controls.Button.OnClick()
   於 System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   於 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   於 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   於 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   於 System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   於 System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   於 System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   於 System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   於 System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   於 System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   於 System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   於 System.Windows.Input.InputManager.ProcessStagingArea()
   於 System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   於 System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   於 System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   於 System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
`

**Comment by NickeManarin** [comment]
This is a bug with .Net Framework, here's the same issue by another user:

https://github.com/NickeManarin/ScreenToGif/issues/256

Here's how to fix it:

https://github.com/dotnet/announcements/issues/53

**Comment by GWWalter** [comment]
It's fix. Thank you!
