### ISSUE TITLE
Playback (Alt+P) skips multiple frames

### ISSUE THREAD

**Issue by PaulIndrome** [NickeManarin/ScreenToGif#26]
When playing the recorded animation in-program, the refresh rate of the window is inconsistent with the framerate of the animation and thus a lot of frames (about 4 in 5) are skipped. 
This makes it very hard to preview animations when doing frame-sensitive work.

Update: Application restart seems to fix it. Has not reappeared so far. Might be related to the usage of hotkey.

(Otherwise this tool continues to be the one and only useful gif-creation software I've come across so far.)

**Comment by NickeManarin** [comment]
Thanks for the feedback. :D

I believe that I fixed this bug.
