### ISSUE TITLE
[Feature Request] Position of the main window should be remembered

### ISSUE THREAD

**Issue by user3323** [NickeManarin/ScreenToGif#263]
I think it would be great if the position of main window would be remembered.

For now it launches in the center of screen.

**Comment by NickeManarin** [comment]
Which window is the main window for you? 
Because for me it's the **Editor** and that window already remembers its position.

**Comment by user3323** [comment]
![stg2](https://user-images.githubusercontent.com/24613274/36081158-e813cfb0-0fa3-11e8-8cf4-e1879e7217b8.png)

**Comment by NickeManarin** [comment]
Done.
It will be available with v2.13.
