### ISSUE TITLE
[Feature Request] Function "Clear TEMP folder" should not ask confusing questions

### ISSUE THREAD

**Issue by user3323** [NickeManarin/ScreenToGif#264]
In settings, tab Temp files, when you press "Clear TEMP folder" - it will ask a very confusing question for this function "Would you like to save projects, that are 5 days or newer"... Well, it confuses so much. Because option like this, when you want to "clear" or "delete" something - almost in every app it asks "Are you sure?" with "Yes / No" answers. And here what we have - the opposite. User may click "Yes" not even reading the question, and he will not delete projects 5-day old or newer.

I think, that function "Clear TEMP folder" should NOT ask anything at all.

It would be nice, if you could make an option (mark / tick) near the "Clear TEMP folder" that will say something like "Don't clear projects, made for last [xx] days", and those people who don't want to touch that projects - will click on that mark and that's it. Everyone else will unmark it - and will never see confusing question again.

PS: and by the way, you have implemented an option to choose a number of days, so in my case it's "**1 day**", but it asks me about "Do you want to save projects, made for last **5 days**". Should be fixed.

**Comment by NickeManarin** [comment]
> PS: and by the way, you have implemented an option to choose a number of days, so in my case it's "1 day", but it asks me about "Do you want to save projects, made for last 5 days". Should be fixed.

Fixed.

**Comment by NickeManarin** [comment]
I've made a new dialog, with a different wording.

![image](https://user-images.githubusercontent.com/14798947/78508420-3995bd80-775d-11ea-8f11-c50a6d980dfe.png)
