### ISSUE TITLE
Window height of the editor

### ISSUE THREAD

**Issue by user3323** [NickeManarin/ScreenToGif#265]
When the editor is open after you recorded the GIF - the height (and width) should be remembered by last user adjustment, I think.

Because, look at this one:

![stg](https://user-images.githubusercontent.com/24613274/36006443-9c16b042-0d45-11e8-92a2-4e0f7b8d23b5.png)

I have a screen height maybe twice bigger than the height of STG's window. So it allows STG's editor window be much bigger in sizes. But as you can see - it's height makes scroll bar to appear. And the worst part is - it hides the input field of "file name". So every time you need to adjust the window height or to scroll it, and only after that to type a file name. Annoying.

**Comment by NickeManarin** [comment]
I fixed this issue. It will be available with the next release (v2.13).

**Comment by user3323** [comment]
@NickeManarin  thanks!
