### ISSUE TITLE
[Performance Request] About starting speed

### ISSUE THREAD

**Issue by waldens** [NickeManarin/ScreenToGif#266]
Recent versions of the ScreenToGif are starting more and more slowly, even as long as 15 to 20 seconds in my PC.

I miss the starting speed of the early version, and just tested, ScreenToGif v1.4.1, the first version I used in 2015, can start with only 1 second.

Of course, I understand that the more powerful the feature, the performance will inevitably be reduced, however, just a little hope, is it possible to optimize the starting speed? Thanks.

**Comment by user3323** [comment]
I think you should write your PC stats info

For me - the latest version starts for about 1 second. Ultra fast.

**Comment by waldens** [comment]
@user3323 Thank you for your reply.
ScreenToGif v2.12  + Win7 SP1 x64 + SATA HDD + .NET 4.7

I can't assert that my PC is not a negative factor, maybe it's indeed too old (bought in 2013). I'm just saying, the same PC, same repro steps, v1.4.1 only need 1s to start, while v2.12 need much much longer (both are the time of the first start after PC boot)

Here is the v1.4.1 portable link in case someone want to test: 
https://github.com/waldens/waldens.github.io/raw/master/ScreenToGif.exe
Their startup time are both within 1s in you guys PC?

**Comment by NickeManarin** [comment]
The app was taking 5 seconds to load with this low-end PC:
i3 5th gen, 4GB DDR3, SATA HDD, Win 10 without any dedicated graphics card.

I'm curently changing how the app starts and closes, so I'll run a performance test later.
Thanks for the feedback.

**Comment by Sethur** [comment]
This should be interesting as well regarding hotfix 4055002:

[https://support.microsoft.com/en-us/help/4074880/description-of-the-security-and-quality-rollup-for-net-framework-4-6-4](https://support.microsoft.com/en-us/help/4074880/description-of-the-security-and-quality-rollup-for-net-framework-4-6-4)

**Comment by Sethur** [comment]
Update: Replacing
```
            if (Environment.OSVersion.Version.Major == 6 && Environment.OSVersion.Version.Minor == 1)
            {
                try
                {
                    var search = new ManagementObjectSearcher("SELECT HotFixID FROM Win32_QuickFixEngineering WHERE HotFixID = 'KB4055002'").Get();
                    Global.IsHotFix4055002Installed = search.Count > 0;
                }
                catch (Exception ex)
                {
                    LogWriter.Log(ex, "Error while trying to know if a hot fix was installed.");
                }
            }
```
with
```
Global.IsHotFix4055002Installed = false; // Might be different on your system
```
fixed this issue. Startup is now < 1s again.

**Comment by NickeManarin** [comment]
@Sethur Thank you for finding out what was slowing down ever more the startup. I'll fix it.

Still, for @waldens, the app was slower even before this Hotfix detection code was added.

**Comment by NickeManarin** [comment]
Any news on how fast the app starts now for you?

**Comment by waldens** [comment]
@NickeManarin Less than 2s, this issue can be closed. Thank you.
