### ISSUE TITLE
gif transparency replaced by a black background?

### ISSUE THREAD

**Issue by aguyinmontreal** [NickeManarin/ScreenToGif#267]
I opened a .gif that was created by a different software with ScreenToGif. 

I edited it, everything was fine.

Then, when I saved it to a new .gif file, the transparent background was replaced by a black background. How can I fix this?  I tried changing the "unchanged pixels" colors, but it doesn't do anything. :/

**Comment by NickeManarin** [comment]
Gif transparency is currently not supported.

**Comment by aguyinmontreal** [comment]
thanks for letting me know!

**Comment by Lopol2010** [comment]
hi friends. i have recorded video in ~1080p~7fps~5sec its 750KB. now i have recorded 500x200-5fps-5sec and its 2 MB CARLLLL 2 MB! I have wasted much time to figure out what settings i used to save GIF, but always i have ge 1MB+ the same via another 1080p gifs. Is this first gif i recorded MAGIC? THank you.

**Comment by hzj629206** [comment]
Please support transparency. It's very useful.

**Comment by maxmax91** [comment]
Up for transparency. It would be enough to replace one color with transparent. Thank you for the program, very nice.

**Comment by byzod** [comment]
Need this, badly

**Comment by NickeManarin** [comment]
Support for transparency added, but it wont work right now with some features.
You can import your gif with transparency and save them, without turning the background black.

![EbkC_NIWsAEZ4Jn](https://user-images.githubusercontent.com/14798947/86024974-0d0fdb80-ba04-11ea-9d7b-a7d60a9a531f.png)

To enabled, just tick the option "Enable transparency". You can let the app detect the transparency in the frame or pick one color to be converted to transparent.

This feature will be available with the next version.
