### ISSUE TITLE
Incorrect message: 'There's not enough space left on the drive where this app stores its cache'

### ISSUE THREAD

**Issue by ForkandBeard** [NickeManarin/ScreenToGif#268]
I get the message 'There's not enough space left on the drive where this app stores its cache' (n% left)...'

But I have 70+GB free on my c drive...

When I go to 'Save as' gif regardless, I get an error '0.png' not found...

**Comment by NickeManarin** [comment]
I'm not sure what's happening, I'll need more details. 
It would be helpful if you could open the Feedback window and send me the log files (if any of it shows up).

Can you show me a screenshot of Options > Temporary Files?  I want to see where the cache is located.

**Comment by ForkandBeard** [comment]
The "Save As" .gif is working now so maybe not worth investigating... but I still get the no space left warning:
![image](https://user-images.githubusercontent.com/158564/36065547-4d9da4de-0e94-11e8-95c7-9df56b89350c.png)

There's no log file in the 'Feedback' window.

Here's the 'Temporary Files' form:
![image](https://user-images.githubusercontent.com/158564/36065530-21c09916-0e94-11e8-84d4-61eed2517ecf.png)

**Comment by NickeManarin** [comment]
Thank you. I'll adjust the message to appear only if there's less than 2 GB of space left, instead of being based on a percentage.

**Comment by NickeManarin** [comment]
Done.
