### ISSUE TITLE
[Feature request] When Shift-Selecting frames keep up preview with last selected frame

### ISSUE THREAD

**Issue by duarteframos** [NickeManarin/ScreenToGif#27]
In the editor window when shift-selecting frames keep up the main preview with the last selected frame. Currently it always shows the first selected frame, and it would be useful te see a full sized version of the last selected in the frame range, so one could see what was being used for the operation.

This actually works pretty well when shift-selecting backwards say from frame 100->80 with [Shift]-[Left Arrow] but selecting forward, like say, frame 100->120 will no longer update the full size preview.

Also if I shift-select with the arrow keys all works fine, but if I shift select with the mouse from say frame 10->20 and and repeatedly press [Shift]-[Left Arrow] to deselect, it will change selection to 10->9, 10->8, 10->7 instead of 10->19, 10->18, 10->17 etc.

If I do it in reverse order and use the shit+mouse to select the frame range 20->10 it all works as expected, pressing [Shift]-[Right Arrow] will correctly update selection to 20->11, 20->12, 20->13, etc.

**Comment by NickeManarin** [comment]
Understood :)

**Comment by NickeManarin** [comment]
Done! (release 2.5, when available)

Shift+Left/Right will preview the current focused frame.
Shift+Click and after that Shift+Left/Right will arrange the selection based on the latest selection.

**Comment by duarteframos** [comment]
Cool thanks for the fix! Looking forward to the next release :)
