### ISSUE TITLE
adding text and overlay is confusing

### ISSUE THREAD

**Issue by Shemesh** [NickeManarin/ScreenToGif#272]
using the functionality under: image > text, overlay
i had hard time to understand how can i apply it to ALL images.
there is no mention of how to do this, not in the app, and not in the docs.
frustrating...
...finally i understood i should select all images in the timeline.

a good solution is to have **two** buttons with clear description:
1. apply to selected image(s)
2. apply to all images

**Comment by NickeManarin** [comment]
I understand that I need to improve the docs, but I'm not sure if adding a third button will improve the usability.

**Comment by Shemesh** [comment]
or maybe a checkbox "apply to all" ?

**Comment by NickeManarin** [comment]
Adding another element will only make things more difficult, and there's not enough space anyway.
I should improve the docs and the usability of the timeline.

**Comment by NickeManarin** [comment]
When opening the feature, a hint will tell you that the action will be applied to all selected frames.
