### ISSUE TITLE
Auto-clear of TEMP folder does NOT work

### ISSUE THREAD

**Issue by user3323** [NickeManarin/ScreenToGif#273]
STG version - 2.12 (**portable**)
OS: win7x64

I've set my "Auto-clear" option to 1 day:

![temp 2](https://user-images.githubusercontent.com/24613274/36406317-9b8460d6-15fe-11e8-819c-dfdb6cf1d7b7.png)

 And it does not work.

Today is February 20.

![temp 1](https://user-images.githubusercontent.com/24613274/36406309-960595da-15fe-11e8-8128-d9d9e253bb58.png)

... as you can see - projects from February 18 are still in the Temp folder.
And I just wonder, how is "Auto-clean" function supposed to work? Is it supposed to launch in the background without any permission from OS and user? There are no any STG registry startup entries. So, how? And why it does not work?

**Comment by NickeManarin** [comment]
Did you open the editor after changing the value? The task that deletes the folders happens when you open the editor.

**Comment by user3323** [comment]
@NickeManarin 

yes. You can see on the screenshot - the latest project date is February 20.

**Comment by vatterspun** [comment]
I may be seeing something similar:

![desssssssss](https://user-images.githubusercontent.com/1289134/50862122-5841b480-1360-11e9-978d-f047d3687798.png)

This is an issue both of course becuase it's taking up a lot of space long after I've closed the program, but also it's saving to AppData with the portable version.  Normally the portable version should save to the local folder by default.  Not that having the option to save elsewhere would be a bad thing -- you might have more or less space on your C:\ drive than a removable drive or cloud-based software.

**Comment by NickeManarin** [comment]
The app clears the temporary folder during the startup. Open projects (on other instances) are not deleted.

Any issues when clearing the folders will be logged.
