### ISSUE TITLE
Do you really want to delete these frames? ...

### ISSUE THREAD

**Issue by user3323** [NickeManarin/ScreenToGif#275]
For now the focus after that - on the "NO".

But the focus should be on the "YES" by default. So user can just press "Enter" and that's it.

**Comment by NickeManarin** [comment]
I'm not sure if it's a good idea to have a destructive action (**yes** to delete the frame) as the default behavior.

Would you like to make this optional?

Or maybe add keyboard shortcuts like **NumPad1** for **Yes** and **NumPad2** for **No**.

**Comment by user3323** [comment]
Why is that destructive? =) It will do the main thing - to warn user about deletion operation.

It's not critical at all. But still annoying. And why - because I've used like hundreds of Windows apps for many years and literally everywhere - if there is a function for deletion warn about "Are you sure?" - focus is always on "Yes". I cannot remember at least one app, where focus would be on "No".

So, first of all - it's a habit.
But also it has really no sense to make focus be on the "No". Because if the user already pressed "Delete" button - he wants to delete the frames. (expecting 1% of cases when someone pressed it by mistake)
And if the user wants to delete it - what is the need to make an additional obstacle, focusing on the answer "No"?

To make an option? How it would be look like?
"On what button do you prefer to focus after trying to delete the frames"?
Nah!

**Comment by user3323** [comment]
No one can delete frames "by mistake" pressing "Delete ---> Enter".

And even if so - those unique users, who will do that - they also would delete frames "by mistake" pressing "Delete ---> Left arrow ---> Enter".

**Comment by NickeManarin** [comment]
> Why is that destructive?
I mean, the action of deleting something is "destructive".

Anyway, for most actions, the Yes button will be the default.
Except when discarding a project and when asking to keep the most recent projects (when trying to clear the temporary folder).

It will be available with v2.13.
