### ISSUE TITLE
Coder algorithm 2.0 (Octree) - green screen issue

### ISSUE THREAD

**Issue by user3323** [NickeManarin/ScreenToGif#276]
I've recorded a gif and saved it using 2.0 (Octree), as always.

But this gif has a huge green screen issue:

![terminal - resize changes path octree](https://user-images.githubusercontent.com/24613274/36464402-4948c994-16d8-11e8-84af-5dc888c41e96.gif)

... also tried all other coders: FFmpeg, NeuQuant, Gifski - they're all OK. No green screen.

Here is a project - https://mega.nz/#!LQ1yhYIY!9FFedCM-twXzwveIQlf3OyIQoHVTq4QKdpT1HcK-iPs

Here is Octree GIF - [green screen (Octree).zip](https://github.com/NickeManarin/ScreenToGif/files/1742933/green.screen.Octree.zip)

**Comment by NickeManarin** [comment]
What's happening is that the algorithm is failing to identify the correct green color as the color that should be treated as transparent.

Usually changing the dummy color to magenta fixes this behavior (unless you recording has magenta too).

**Comment by NickeManarin** [comment]
This bug was fixed with the latest version, v2.26.1.
