### ISSUE TITLE
Invalid checksum in Chocolatey package

### ISSUE THREAD

**Issue by Litee** [NickeManarin/ScreenToGif#278]
Hi,

I am getting an error trying to upgrade choco package to version 2.12.1. Downloaded file has SHA256 = DCB840810542DA366872E3E6D3A8F2C90EBA14C5C2C703265D9F29A3F491B314 while PS script expects 7F6C7700DF2EFD87B1BDD955369D0A23A072A089ECCF649D6C2AE64FC0C806CB...

**Comment by NickeManarin** [comment]
It should be fixed in a few minutes. Thanks for the feedback. :)

Btw, the Chocolatey package has its own repo: 
https://github.com/NickeManarin/ScreenToGif-Chocolatey
