### ISSUE TITLE
Add proxy support for uploads

### ISSUE THREAD

**Issue by BobVul** [NickeManarin/ScreenToGif#279]
Some networks require proxies.

It would be useful to support some way to configure a HTTP(S) proxy, at a minimum. Even better if SOCKS4/5 proxies can be supported too, but those might require additional libraries.

**Comment by NickeManarin** [comment]
I added the option to manually set a proxy or to get it from the default settings of the system.

Now the problem lies in testing this feature. I don't have a proxy enabled in here. Can you test it for me?

**Comment by BobVul** [comment]
Thanks! Is there a binary or updated source available? The last commit on GitHub was 15 days ago.

At the moment I only have a SOCKS5 proxy, though I can get an HTTP bridge if necessary.

**Comment by NickeManarin** [comment]
Thank you, I'll share the binary with you. Here's the file:

[ScreenToGif.zip](https://github.com/NickeManarin/ScreenToGif/files/1783383/ScreenToGif.zip)

I added support for HTTP proxy for now. I'll try Socks5 later.

Check if it's possible to download FFmpeg or Gifski (Options > Extras) and if it's possible to upload to Imgur/Gyfcat (you can use the anonymous upload).

Again, thank you for your help. :)

**Comment by BobVul** [comment]
The manual proxy works well for both Imgur upload and Gifski download.

Unfortunately, the system proxy seems to not do anything (proxy specified via Internet Options, works with Firefox using system proxy).

**Comment by BobVul** [comment]
As an example, I'd expect the request to appear in [Fiddler](https://www.telerik.com/download/fiddler) when it's acting as the system proxy.

**Comment by NickeManarin** [comment]
Thank you for testing :)
I fixed that issue with the system proxy not being used, it now returns the Windows settings.

[ScreenToGif_Test.zip](https://github.com/NickeManarin/ScreenToGif/files/1787346/ScreenToGif_Test.zip)

**Comment by BobVul** [comment]
Looks like it works. Thanks!

**Comment by NickeManarin** [comment]
Awesome!

Yes, not sure if it's that easy. :/

**Comment by NickeManarin** [comment]
I'll leave SOCKS for later.
