### ISSUE TITLE
Feature request: Auto gif uploading

### ISSUE THREAD

**Issue by Light1c3** [NickeManarin/ScreenToGif#281]
A way to easily record and share something would be amazing

My current go-to software for this is recordit and I think implementing something like that would make this my go-to software!

**Comment by NickeManarin** [comment]
The feature to upload to Imgur(Anonymous)/Gifcat(Anonymous)/Yandex is available right now.

I'm currently developing the option to upload to a personal Imgur album.

Also, you can set to copy the link after the uploading.
Is this what you mean?

**Comment by Light1c3** [comment]
Yup, that's basically it! It has a few more steps than I would have liked, but for how robust the software is, I'm not complaining! A quicker way of taking screencast and sharing it wouldn't be bad though :P

I would love an easier way to select a portion of the screen. Dragging the mouse of the area you want would be amazing.

**Comment by Light1c3** [comment]
I should point out, this software is amazing! wish I could help make it better :D

**Comment by NickeManarin** [comment]
> I would love an easier way to select a portion of the screen. Dragging the mouse of the area you want would be amazing.

Did you try the new recorder? Options > Application

**Comment by Light1c3** [comment]
YOU ARE A GOD! This is awesome, and exactly what I want :D

**Comment by Light1c3** [comment]
How can I help make it better? I know c# if that's helpful

**Comment by NickeManarin** [comment]
Helping with ideas for improvements and finding/investigating bugs would be awesome. :)

**Comment by Light1c3** [comment]
I'm on it!
