### ISSUE TITLE
CANNOT SAVE GIF

### ISSUE THREAD

**Issue by seaoutbeen** [NickeManarin/ScreenToGif#286]
@NickeManarin 
Hi, Nicke Manarin.,
Thank you for answering me.
I am the user who have problem with saving gif file on my laptop.

> Hi,
> 
>  
> 
> I can’t read Japanese, this is what the translator gave me:
> 
>  
> 
>                 Unable to save the file. You have specified an output file but cannot save it.
> 
>  
> 
> Can you show me a screenshot of what happened?
> 
>  
> 
> Regards,

The notification said that it cannot find the file to output.

<img width="960" alt="default" src="https://user-images.githubusercontent.com/26630518/37252042-ffa67b08-255d-11e8-806f-f3e28bb5eb1b.PNG">

**Comment by NickeManarin** [comment]
![37252042-ffa67b08-255d-11e8-806f-f3e28bb5eb1b](https://user-images.githubusercontent.com/14798947/37255501-28e8615c-252c-11e8-9b7a-94431a17a234.png)

This folder, are you sure that it exists?

If you are not sure, click on the folder icon to select another folder.

**Comment by seaoutbeen** [comment]
@NickeManarin 
The folder means desktop in Japanese and I don't think I can miss it...

**Comment by NickeManarin** [comment]
Yes, but it's a relative path. If the location of ScreenToGif.exe has changed, the app won't be able to find the correct folder.

Just to be sure, erase the text from that text box and click on the folder icon again, to select the desktop folder.

**Comment by seaoutbeen** [comment]
@NickeManarin 
I'm sorry for telling you this, but I could save the gif file on my folder since you notified me to check the path of your exe file. Thank you!

**Comment by NickeManarin** [comment]
Great!
