### ISSUE TITLE
Import a GifFile without normal file ending

### ISSUE THREAD

**Issue by EndlessMISAKA** [NickeManarin/ScreenToGif#287]
When a GifFile is not end with a GIF Trailer, that the Program will getting into a no-end loading.
Since we used the same Decoder, so I used the bad giffile to tested, and found this bug.
In my program this bug will throw a exception, so I changed the code to ignore the exception.

Maybe you will has a question that why should I need to fixed this bug? 
Because this bad giffile can open by Windows Photo like a normal giffile.

![bad](https://user-images.githubusercontent.com/25360394/37323444-d8bffdcc-26be-11e8-90d8-460cbb3296a3.gif)

Best Wishes to you.This is a wonderful program.
(Sorry,I don't good at English.)

**Comment by vatterspun** [comment]
I'm not sure I understand what you're having issues with.

> (Sorry,I don't good at English.)

Could you describe what you saw?  Could you then describe what went wrong?  What were you expecting to see?

**Comment by NickeManarin** [comment]
@vatterspun The app stays in an infinite loading process when a corrupted gif file is imported. So, @EndlessMISAKA wants the app to be able to load all possible frames, without staying in an infinite loading.

**Comment by NickeManarin** [comment]
Done. With v2.13, it will load all frames until it can read anymore.

![image](https://user-images.githubusercontent.com/14798947/37499966-80019c34-28a5-11e8-855f-293ddfd55172.png)
