### ISSUE TITLE
Mac version please!

### ISSUE THREAD

**Issue by compsci78** [NickeManarin/ScreenToGif#29]

**Comment by NickeManarin** [comment]
I was recently researching ways of doing this. I'm open to suggestions.

I'll probably use Xamarin tools because I know nothing about native OS X development.

**Comment by NickeManarin** [comment]
Actually, I went all the way to download a working VM, download Xamarin Studio, be asked to download XCode just to understand that I need to pay 99$ for a license.

So,  NO. F*cking joke, apple.

**Comment by komapoow** [comment]
Heard the VS now available for Mac as well?

**Comment by NickeManarin** [comment]
It's the same Xamarin Studio with a different name. Still needs XCode and Apple Developer subscription.

:/

**Comment by yoyoys** [comment]
you can create a free apple developer account for non-publish.
but i think mono framework is another good solution for this project.

**Comment by lzf0402** [comment]
want mac version, too

**Comment by Sungq1990** [comment]
want mac version, too
