### ISSUE TITLE
Publish the app to Microsoft Store

### ISSUE THREAD

**Issue by Kenya-West** [NickeManarin/ScreenToGif#292]
Microsoft Store is one place for everything in your life, moving your experience to a safe one and making it accessible from many devices that added to your Microsoft account.

Publishing apps to Microsoft Store is benefit both for users and developers + enterprise. Deploying classic apps, that available in Microsoft Store, with safe methods to a verified environments is trusted by enterprises and users. From the other hand, developer can benefit from "In-App Purchase" (paid features of the app), making its own Insider programs, setting up subscriptions and advertisements.

Microsoft corporation has opened a door to developers of classic apps, the way to publish your app to Microsoft Store. UWP brings a second life for your apps: notifications, full power of trusted UWP/WinRT API, easy debug, easy deploy, additional features.

Learn more about that easy process [here](https://developer.microsoft.com/windows/bridges/desktop).

Best regards,
Innokenty Ivanov,
North-Eastern Federal University student (Master degree).
Programmer, web developer, **Microsoft Student Partner**.
My [e-mail](mailto:Kenya-West@outlook.com).

**Comment by vatterspun** [comment]
Microsoft Store is one place for everything in your life, moving your experience to a safe one and making it accessible from many devices that added to your Microsoft account.I am not a fan of "app store" software distribution tools for a whole variety of reasons, but it's a fact that many people have machines that are setup to prevent anything save programs from the app store.  As such, it's helpful to have that program added to the 

Also your program is licensed MS-PL, which Microsoft historically promotes over other licenses.

I'm not a fan of the trend toward app store distribution nor the MS-PL license (as discussed on #33), but just some food for thought.

**Comment by NickeManarin** [comment]
@Kenya-West Yes, I already have almost everything ready (I just need to create some images for the Store). But I'm blocked by the fact that I need to be contacted by MS in order to get an authorization to publish the app.

@vatterspun I'm still going to distribute the app by the other 3 means (No install, Installer, Chocolatey).

**Comment by heartacker** [comment]
expect for uwp version ，it  is powerful application i had ever seen about animation picture

**Comment by vatterspun** [comment]
> I'm blocked by the fact that I need to be contacted by MS in order to get an authorization to publish the app.

According to some casual research on the topic, there's a registration fee, which doesn't seem worth it.  Microsoft should be welcoming to free software developers that make their operating system more attractive with quality programs.

**Comment by Rictusempra** [comment]
@NickeManarin 

> I'm blocked by the fact that I need to be contacted by MS in order to get an authorization to publish the app.

I'm notified they have special offer to open-source authors

**Comment by waldholm** [comment]
That's a good idea.

**Comment by vatterspun** [comment]
As there is a fake version of this program (https://www.microsoft.com/en-us/p/screen-recorder-plus-for-windows-10/9pj1c0rfbzn3?activetab=pivot%3Aoverviewtab#) is currently posted to the Microsoft Store despite numberous contacts, I'd maybe avoid the platform altogether.  More info: https://github.com/MathewSachin/Captura/issues/414

As Microsoft Store opened roughly 10 years ago, maybe they need another 10 years to fix their submission system.

**Comment by MathewSachin** [comment]
Another fake version: https://www.microsoft.com/en-us/p/screen-recorder-webcam-recorder/9nzvhnx6krxj?activetab=pivot:overviewtab

**Comment by lostmsu** [comment]
@vatterspun , @MathewSachin , technically they are not "fake", as ScreenToGif has a license, permitting anyone to distribute copies with any modifications and get paid for it.

**Comment by MathewSachin** [comment]
@lostmsu, attribution is still required.

https://github.com/NickeManarin/ScreenToGif/blob/479f6a36a5a19563130112c552652e04eef0d7df/LICENSE.txt#L27

**Comment by lostmsu** [comment]
@MathewSachin have you checked, that they do not ship the LICENSE file, and redacted the original from About window?

**Comment by vatterspun** [comment]
> @vatterspun , @MathewSachin , technically they are not "fake", as ScreenToGif has a license, permitting anyone to distribute copies with any modifications and get paid for it.

> @MathewSachin have you checked, that they do not ship the LICENSE file, and redacted the original authors from About window?

Yeah I've heard this refrain before.  I see this a lot with GPL software where they claim to be open source, the source is obviously *somewhere* and boy you just haven't dug hard enough to find it.  The last time I checked, FreeFileSync was doing this.  I'd suggest the very reasonable license terms around attribution/source code hosting shouldn't be something you have to 

1. Buy their software 
2. Look through the software to make sure it's not SOMEWHERE, 
3. Post an issue with the hosting service. 

But maybe that's just me.

**Comment by vatterspun** [comment]
Update here: the excellent PhotoDemon is also running into this issue.  https://github.com/tannerhelland/PhotoDemon/issues/251#issuecomment-498317095

**Comment by NickeManarin** [comment]
Uh oh, I forgot to close this issue. 
[The app was published to the MS store](https://www.microsoft.com/en-us/p/screentogif/9n3sqk8pds8g?activetab=pivot:overviewtab).
