### ISSUE TITLE
[Feature request] Detect mouse double click, drag and long presses

### ISSUE THREAD

**Issue by laiqun** [NickeManarin/ScreenToGif#294]
how about to complete those features?

**Comment by vatterspun** [comment]
I think he's suggesting that the different mouse clicks should be animated differently in the GIF recording process.  That might be out of scope for a basic screen recording / animation program as even paid tools don't have that functionality.  Still, it's a cool idea.

**Comment by NickeManarin** [comment]
@vatterspun I believe he's using the output json for other reasons (taking into consideration the other issues that he opened). But nice idea anyway.

**Comment by laiqun** [comment]
you can refer https://github.com/gmamaladze/globalmousekeyhook

**Comment by NickeManarin** [comment]
Double click and drag detecting implemented.
Long presses are irrelevant right now, the editor can detect them.
