### ISSUE TITLE
use key stringify name instead of KEY code 

### ISSUE THREAD

**Issue by laiqun** [NickeManarin/ScreenToGif#296]
when I type 't' in json file there is 63,I must check  System.Windows.Input.KEY find 63 meaning alpha 'T'
 {
		"CursorX": 489,
		"CursorY": 523,
		"Delay": 1000,
		"Keys": [{
			"IsUppercase": false,
			"Key": 63
		}],
		"Name": null,
		"Path": "C:\\Users\\laiqun\\AppData\\Local\\Temp\\ScreenToGif\\Recording\\2018-03-18 11-11-01\\5.png",
	}

**Comment by laiqun** [comment]
part of KEY.cs
```
namespace System.Windows.Input
{
    public enum Key
    {
        None = 0,
        Cancel = 1,
        Back = 2,
}
```

**Comment by laiqun** [comment]
also you can still use key code ? I't doesn't matter

**Comment by NickeManarin** [comment]
The json is an internal file, it needs to stay like that.
