### ISSUE TITLE
Tray

### ISSUE THREAD

**Issue by smaragdus** [NickeManarin/ScreenToGif#297]
@NickeManarin 

Please consider adding an option to minimize ScreenToGif to tray only- I do not see great benefit of the tray icon if the program appears in the task-bar too. You may also add an option to disable 'Exiting ScreenToGif' warning message when the program is exited from tray icon.

In my opinion it would be even better if there are 2 'minimize' options:

- minimize ScreenToGif to tray;
- close ScreenToGif to tray;

Thus for example it would be possible to minimize it to task-bar if 'minimize to tray' is not selected and close it to tray if 'close to tray' is selected.

Regards

**Comment by laiqun** [comment]
Yeah ,same with me

**Comment by NickeManarin** [comment]
How would it work with a _multiple window_, _multiple entry points_ implementation like v2.13?

For example, I have 2 editors opened, I minimize both of them. If I click (or double click) to restore, which one wuold be restored? Both? The latest one?

**Comment by smaragdus** [comment]
@NickeManarin 
I think the options I suggested are appropriate for StartUp Window only so you may close this issue. I didn't think that a user may be working with multiple editor windows.

**Comment by NickeManarin** [comment]
@smaragdus With v2.13, you can open the recorder, click to stop and it will search for an editor without any project loaded. If it fails to find, it will open a new editor window.

After finishing the first recording, you can make another recording with a recorder opened by click on the context menu of the tray icon.

I understand that this is a great option for Discord (messaging app), for example. But, for ScreenToGif it can be a little confusing.

**Comment by smaragdus** [comment]
@NickeManarin 
I wonder- what do you think of an option to always show StartUp Window in system tray? When Editor is closed this doesn't exit the program but just the Editor provided that "close to tray" is enabled? Do you consider this counter-intuitive and useless? I mean- StartUp Window serving as a central control unit for program's modules?

**Comment by NickeManarin** [comment]
@smaragdus I'm sorry. I believe that I didn't understand what you explained. 
Do you mean that if I click to restore the app, it could open the Startup window? If that's the case, it would be a little bit redundant, since the tray icon menu already can do what the Startup window does.

**Comment by NickeManarin** [comment]
Btw, I plan to add options for selecting which window to open when left clicking or double clicking.

**Comment by smaragdus** [comment]
@NickeManarin 
I am sorry I didn't explain well what I meant.

ScreenToGif - StartUp window has 3 title bar buttons (like almost any Windows program"- "Minimize", "Maximize", "Close". "Minimize" button sends ScreenToGif to task bar and to system tray, I thought of an option to close program modules without exiting the program in case there is an option to close StartUp Window to tray- this would work only with StartUp Window and will allow closing modules without exiting the program.

Any advantages? Perhaps in some cases- for example the user has finished working with the editor and want to remove program from task bar without exiting it- sometimes while working with different editors at the same time the task bar becomes a bit cluttered (at least mine).

Please feel free to close this issue- I am not closing it myself because you may have some other ideas about the system tray icon. I do not want to complicate things with useless suggestions. My initial idea was an option to  minimize the program to tray only and thus remove it from task bar.

**Comment by NickeManarin** [comment]
I added options to select what to do when clicking on the system tray icon in v2.20.
Taking into consideration how the app works with multiple windows, Minimizing to the system tray instead of the taskbar could cause some issues, so I can't do that. :/
