### ISSUE TITLE
yearn to Full Screen

### ISSUE THREAD

**Issue by ZCShou** [NickeManarin/ScreenToGif#3]

**Comment by NickeManarin** [comment]
Working on it. I just need to adjust the UI, to be usable without interfering.

**Comment by ZCShou** [comment]
Thanks for your answer!   hope the work is going on smoothly

**Comment by NickeManarin** [comment]
I'm currently having problems with high memory consumption. I'll have to postpone to next release (2.3).

**Comment by komapoow** [comment]
Nicke, to fix the memory leak may be to clean links to empty/disposed objects by using WinAPI "EmptyWorkingSet"?

**Comment by NickeManarin** [comment]
I know, I'm using GC.Collect().

**Comment by komapoow** [comment]
Right. But sometimes, I don't know why, but GC.Collect does not clean the unused memory properly. I such cases I use API "EmptyWorkingSet"
