### ISSUE TITLE
Snap to Window icon is misleading

### ISSUE THREAD

**Issue by MarioLiebisch** [NickeManarin/ScreenToGif#30]
Tried using the tool and so far it's very intuitive. However this one feature really confused me at first.

Currently the "Snap to Window" button for the Recorder window uses the typical "Crop" icon. So I assumed this would allow me to drag any area on screen for recording (similar to how Microsoft's OneNote and SnipIt Tool work). Instead the tool snapped to some maximized window and I had trouble figuring out what actually happened.

For the current functionality of "Snap to Window" I'd highly suggest using a more common icon for something like this, i.e. the typical crosshair that's (to my knowledge) rather common in other programs offering some window selection. Here's an example from Process Explorer:

![Process Explorer screenshot](http://i.imgur.com/G04dqbu.png)

I'd edit the icon in myself, but to be honest I couldn't figure out how to edit the resources so far, since I typically only work with Windows Forms.

**Comment by NickeManarin** [comment]
Agreed. I had to manually create a vector icon with Illustrator and export as XAML to add to the program. Back during development of this feature I had no Illustrator, so simply using the Crop icon was the quick step.

**Comment by NickeManarin** [comment]
Replaced by a crosshair. I may change again to a more detailed crosshair in the future.
