### ISSUE TITLE
Extend Caption, Free text, Free drawing and obfuscate over multiple frames 

### ISSUE THREAD

**Issue by Andries-Smit** [NickeManarin/ScreenToGif#301]
When editing the image I would like to apply that change to not only to a singe frame.
It would be helpful to have an option to apply it to a number milliseconds or number of frames.

Example 
- adding a text that will show for the first 2 seconds.
- Obfuscate text, in the whole animation. (not adding per frame)

**Comment by laiqun** [comment]
already have those features

**Comment by NickeManarin** [comment]
Hi @Andries-Smit ,
To apply those overlays, you just need to select multiple frames.
To select multiple frames, you can use **Ctrl + Click**, **Shift + Click**, **Shift + Left/Right/Home/End** or **Ctrl + A**.
