### ISSUE TITLE
Thr problem of USE

### ISSUE THREAD

**Issue by c0001** [NickeManarin/ScreenToGif#307]
# Hi maintainer:

Sorry for change this text area to English lately for about 9 hours.

Now I found two user experiencs referred problem:

1. Within the using of `screentogif` I found one problem which lets me down that:

> In the any position of screentogif's UI (ps: almost of all 😄 ) there' always show the clickbord
> tooltip-popup window by double clicking. Is this the origin design willing in it or was the bug?
> 
> It let me must be duplicated doing sth like chosen the slider bar of `Gifski` .

2. There's none worked effection when I move the `ffmpeg` and `gifski` to the root dir of where
   screentogif was in even if the setting panel had been detected both of them like this operation
   upon. Does it mean that I must to setting the system variable of them although I'd like portable
   software rather than what like this?
   
   
I love this tool so much while it provide me the best convinient in some lash-up.

Hope for your help 😺 .

**Comment by Rictusempra** [comment]
Please use English here.

A brief summary:
1. double click will prompt clipboard.
2. Option does detet ffmpeg & gifski in screentogif folder but converter failed to find them

**Comment by laiqun** [comment]
请使用英语！

**Comment by laiqun** [comment]
第一个问题怎么复现？我这边没法复现你的情况

**Comment by NickeManarin** [comment]
Hi, let's see if I understood your text correctly.

> 1) By double-clicking anywhere in the app, a tooltip will appear. 
 
I can't reproduce this, can you record it for me? You can open ScreenToGif twice to do that.

> 2) FFmpeg and Gifski are not being detected...

You can simply type `.\gifski.dll` or `gifski.dll` if the Gifski DLL (or FFmpeg) file is at the same folder where ScreenToGif is located.

![image](https://user-images.githubusercontent.com/14798947/38284216-7d14da6e-3790-11e8-9412-9c9beb73e81f.png)
