### ISSUE TITLE
Editing --> "Border" - has to be an option "outer" instead of "inner"

### ISSUE THREAD

**Issue by user3323** [NickeManarin/ScreenToGif#313]
![image](https://user-images.githubusercontent.com/24613274/38627673-34986d22-3db8-11e8-93a2-4da4d4366f24.png)

How about to make an option to allow for a border be outer (enlarging width and height of the gif) instead of inner space?

Because, for example, I want to make a border 10 pixels wide on every side... and it covers gif so bad.

**Comment by NickeManarin** [comment]
Done! It will be available with the next version (v2.19), in a few days.
You can simply put negative values to expand the border outwards.

> NOTE: When expanding the frame size, the border will be applied to all frames, since the project must have a constant frame size.

![image](https://user-images.githubusercontent.com/14798947/66260133-c8b32000-e790-11e9-89ec-cddc133053ab.png)

By the way, you'll be able to add border as a task:

![image](https://user-images.githubusercontent.com/14798947/66260175-7de5d800-e791-11e9-8a3d-1a31221ab766.png)
