### ISSUE TITLE
Window appears offscreen

### ISSUE THREAD

**Issue by jameskraus** [NickeManarin/ScreenToGif#319]
If you use ScreenToGif on a second monitor, turn it off, disconnect the monitor and restart ScreenToGif then it will appear off screen. Unlike some offscreen programs, you can't use Alt+Space to get control of the Window. I can't find a way to get it to appear on screen again.

**Comment by NickeManarin** [comment]
Do you know which window is outside the bounds? (Startup window, recorders or the editor)

Also, is worthy to check if the display is truly disconnected. (Sometimes, after unplugging the monitor from a PC, Windows keeps the secondary screen active)

**Comment by jameskraus** [comment]
It's the recorder window. No idea if it was "really" disconnected as far as
windows was concerned. Do you know what code handles opening/positioning
the Window on startup? I'd be willing to try for a PR if I knew where to
start.

**Comment by NickeManarin** [comment]
@jameskraus Which recorder are referring to? The new one or the old one (the one with a small interface or the one with a punctured rectangle)?

Because with the old one, you can press Alt + Space to control the window. See it (my OS has other lanaguage than English):
![window](https://user-images.githubusercontent.com/14798947/41826950-51ab84b4-7803-11e8-8ea8-f5974af2dbab.png)

**Comment by jameskraus** [comment]
@NickeManarin it's the old one. That might be a good enough solution to this problem. I haven't run into the problem again, so I haven't prioritized looking into it more.

**Comment by NickeManarin** [comment]
Oh, that's strange. I'm able to press Alt + Space select "Move" and use my arrow keys to move the window.

Anyway, with the next version of the app, the new code that positions the window will be available.

**Comment by dimitar-a-dimitrov** [comment]
Hi there! There is a much shorter way to ensure that the recorder window is visible. May I do a PR with my version?

**Comment by kayvanbree** [comment]
I'm going to close #354 (duplicate). Can we get a fix for this? I can't record a screen because I can't find my recorder.

**Comment by NickeManarin** [comment]
@kayvanbree Yes. While the fix for this issue is not live yet, you could try deleting the settings file that is usually located inside %APPDATA%/ScreenToGif

**Comment by kayvanbree** [comment]
@NickeManarin Still can't record fullscreen on my smaller screen (4k and 1080p monitor), but I can use the new UI again. Thanks!

**Comment by NickeManarin** [comment]
@jameskraus @kayvanbree With the current version of the app, there`s some changes in the way that both of the recorders work.

Still, if a window keeps positioned outside the screen, you can right click the system tray icon of the app and open the troubleshooter to reset the its position.

**Comment by kayvanbree** [comment]
This issue can be closed, right @NickeManarin?

**Comment by kayvanbree** [comment]
@NickeManarin, this issue can be closed right?

**Comment by jameskraus** [comment]
Closing issue from @NickeManarin's response
