### ISSUE TITLE
Version 2.3 - Can't figure out how to set recording area

### ISSUE THREAD

**Issue by BGMcoder** [NickeManarin/ScreenToGif#32]
With Version 2.3 something changed, and now there is no box to size to set the area for the recording.  When I record it just records the entire screen.  In the Application settings, I have "Enable Fullscreen mode" UN-checked.  I'm running Windows 7 Pro x64.

Am I missing something?

**Comment by NickeManarin** [comment]
That's my fault. I must have mixed some settings...

Yes, I did, Snapshot mode and Fullscreen mode are interchanged. :/

Right click on the recorder button, enable "Snapshot mode" and and disable again to go back to normal recording. 

Sorry. :O

**Comment by BGMcoder** [comment]
Ah!  I never imagined to right-click on the record button!  I right-clicked on everything else though!  I was surprised when there was no menu on the options button.

Okay, so that gets me to snapshot mode - but that wasn't really my problem.

The problem is that I can't figure out how to set the size of the recording area.  There is no frame to size.

**Comment by NickeManarin** [comment]
Sorry, follow this instead:

Right click on the recorder button, uncheck the "Fullscreen mode" to go back to normal recording.

**Comment by BGMcoder** [comment]
Thanks; that does work - a little confusing, but it works.
