### ISSUE TITLE
Win 10 Enterprise Failure

### ISSUE THREAD

**Issue by GaalexxC** [NickeManarin/ScreenToGif#320]
This is an upgrade to previous version not new install. Running the latest Windows 10 version 1803 build 17661.1001. The April 2018 final Redstone build on the Insider fast ring. After several failures rebooted and same error. Could need refactoring for Win 10 as this is the final before Redstone 5. Ran the Windows compatibility troubleshooter and returned incompatible program Attached error:

![screengif](https://user-images.githubusercontent.com/28851458/39953848-55849b5a-5582-11e8-9e1e-5cc75192414f.PNG)
![screengif2](https://user-images.githubusercontent.com/28851458/39953849-558de3ae-5582-11e8-9c7c-cf00c8eb0202.PNG)

BTW great app, love it!

**Comment by vatterspun** [comment]
Have you tried using the "Portable" install as a workaround?

**Comment by vatterspun** [comment]
Have you tried using the "Portable" install as a workaround?

**Comment by vatterspun** [comment]
I haven't seen this issue but now that I think about it I may not have the latest version.  I'll try to retest in the coming week or two with the current version.

**Comment by GaalexxC** [comment]
Just some more info for you. I checked the error code 2503 and found some permissions and some other Windows installer issues associated with this code. I checked permissions as well as re-registered the Windows installer and restarted the Installer service. Also tried version 2.13.1 / 2.13.2 and had no luck, same issue. The Windows event logs had nothing more to say either just the error code, nothing more.
I was thinking about removing my version and trying a new install but worried I wouldn't be able to get it back in and really need it for screens of my work. I will keep on it and if I find anything or do happen to get it working will post. Thanks

**Comment by GaalexxC** [comment]
Bingo! The issue is with Win 10 when you use your MS login to access your machine it creates a new admin for your account which is USER (msloginemail) So I had all Admins with full permissions but the USER (msloginemail) wasn't in the list. Added my MS USER (msloginemail) with full permissions and it installed perfectly. Gotta love Windows...

Thanks Nicke!

**Comment by vatterspun** [comment]
I guess this got resolved but I tested the installer version and it worked fine on my Win10x64 system.  I did get an admin prompt, which might be part of the problem (I couldn’t take a screencap of it for some reason).  Here’s my about screen:

![image](https://user-images.githubusercontent.com/1289134/39970533-a3146d06-56b2-11e8-9455-5a205f1047cb.png)

**Comment by GaalexxC** [comment]
Version 1703 to 1803 major changes in Windows 10, almost a completely different OS matter of fact as it is a pre-requisite for Redstone 5 and I see many differences from previous builds. So I had no problem installing 2.13 many months ago before the Win 10 version upgrade last week to 1803. 95% of issues in Windows are permissions issues, too many users for an application when all you should have is the current logged in user as owner.

![win10](https://user-images.githubusercontent.com/28851458/39974162-de2372f6-56f4-11e8-9a47-bd18df0116e4.PNG)

**Comment by vatterspun** [comment]
> major changes in Windows 10, almost a completely different OS 

I've heard frustrating from a number of other developers with the way Windows 10 makes drastic internal changes.  It seems like previous versions of the OS attracted developers with being relatively stable and uniform, unlike the rapidly-changing MacOS and wide selection of Linux desktops.  Now I wonder.
