### ISSUE TITLE
How to just get a screen shot

### ISSUE THREAD

**Issue by toddmo** [NickeManarin/ScreenToGif#321]
I don't want a video. I just want a screen shot. I want to draw a rectangle on the screen and capture that.

Can I do that?

If not, can you make it do that? Thanks.

**Comment by NickeManarin** [comment]
If you enable the snapshot mode (under Options) the recorder will take a single screenshot each time you press to record (or if you use the shortcut key).

**Comment by vatterspun** [comment]
> If you enable the snapshot mode (under Options) the recorder will take a single screenshot each time you press to record (or if you use the shortcut key).

Oh cool.  Nice to know.

**Comment by vatterspun** [comment]
I think you can safely close this issue.

**Comment by laiqun** [comment]
You can press "PrtSc" key on keyboard,then open "mspaint", click "paste".
Thx

**Comment by sbaum2s** [comment]
> If you enable the snapshot mode (under Options) the recorder will take a single screenshot each time you press to record (or if you use the shortcut key).

I do not find that option. Since there are also several tabs and maybe named differently...in version 2.41.3

**Comment by NickeManarin** [comment]
> > If you enable the snapshot mode (under Options) the recorder will take a single screenshot each time you press to record (or if you use the shortcut key).
> 
> I do not find that option. Since there are also several tabs and maybe named differently...in version 2.41.3

Right click the "fps" ans select "Manual" (or click until it switches to "Manual"):

![Image](https://github.com/user-attachments/assets/d4312e73-cadf-4939-9edb-8ea4f528c12f)

![Image](https://github.com/user-attachments/assets/211b106c-45e2-4863-afd5-2381452b9f7a)

Or go to Options > Recorder > Capture Frequency and select there:

![Image](https://github.com/user-attachments/assets/229fda23-86b1-403a-a16e-cde649bc3518)
