### ISSUE TITLE
Can no longer open: "unhandled exception" - hotket already in use

### ISSUE THREAD

**Issue by mckinley120** [NickeManarin/ScreenToGif#324]
Does anyone know how I can fix this issue opening up the program?

![image](https://user-images.githubusercontent.com/39424725/40263908-b0ccae3e-5ae7-11e8-8025-e66bda4a4e01.png)

**Comment by NickeManarin** [comment]
I fixed this bug, but I didn't release a new version yet.

Could you check if ScreenToGif wasn't already running?

**Comment by mckinley120** [comment]
​No it was no longer running...I terminated all its processes in CMD
terminal, yet it gave the same alert when I tried relaunching the program.

Thanks​
