### ISSUE TITLE
Out of screen when detached monitor

### ISSUE THREAD

**Issue by biohazardxxx** [NickeManarin/ScreenToGif#325]
Usually I have 3 Screens when docked with Laptop.
After undoc and have only one screen, I don't get the recorder window. I belive it is starting in an unavailable location where it was last time closed.
Any chance to add a check if the staratup location does realy exists and if not use a default one?

**Comment by Workshop2** [comment]
I also have this issue. I can't use the app now 👎

**Comment by NickeManarin** [comment]
@Workshop2 Can you enable the other recorder UI? Open Options > Application > Enable new recorder UI.
Or you can also clear the current settings, head over to Options > Temporary Files > Click the little red X near the "Settings location" group.

**Comment by NickeManarin** [comment]
@biohazardxxx Which recorder were you using? The "new recorder" or the old one? (The new one you can click and drag to select a screen area, like the snipping tool).

**Comment by Workshop2** [comment]
@NickeManarin I can't get to the app, it's floating outside of my window and I can't get it back into view. Where are the settings kept on disk? I could clear it manually.

**Comment by biohazardxxx** [comment]
same here.
When I had back to my 3 screens then I could get it back. once I dock off to one screen and missed to move it to main screen it will be lost again.

**Comment by vatterspun** [comment]
> After undoc and have only one screen, I don't get the recorder window. I belive it is starting in an unavailable location where it was last time closed.

I have this same problem with LibreOffice.  My workaround:

1. Holding the **Shift** key, right-click on in the task bar icon
2. Click **Maximize**

![image](https://user-images.githubusercontent.com/1289134/52169104-b4e28600-26f8-11e9-8f9c-26db0c07ecee.png)

**Comment by NickeManarin** [comment]
I'm further improving the automatic positioning of the screens, with v2.20 there's another fix incoming. #551

**Comment by NickeManarin** [comment]
I reworked the new recorder UI and I also rewrote the screen detection algorithm, adding the option to not remember the position and/or size of the previous screen region.

This can disabled/enabled in `Options > Recorder > Other`.

Also, in last case scenario, it's also possible to use the Arrow keys to move the recorder (hold Alt to increase the speed) for both the newer or older recorders.

**Comment by JPustkuchen** [comment]
Important note to all who are affected by this issue: **You have to switch to the new UI manually!**
Settings > Recorder > Select "New" and Save!

**Comment by NickeManarin** [comment]
@JPustkuchen Yes, and that newer UI will be the default one in the near future. :)
