### ISSUE TITLE
Can there be an option for it to also show the keys clicked

### ISSUE THREAD

**Issue by WELZ-gh** [NickeManarin/ScreenToGif#326]
For making "tutorial" videos, just so they know if you just clicked Shift/Control etc.

(There's an option for the circle on mouse click - which is awesome)

**Comment by NickeManarin** [comment]
For the key presses, you can apply later, it's not automatic. Head over to Image tab > Key Strokes (Alt + H).

**Comment by WELZ-gh** [comment]
@NickeManarin ahh thanks a lot, I didn't know about that, is it documented anywhere?

**Comment by NickeManarin** [comment]
:)

The wiki of this project is incomplete, but it's here: https://github.com/NickeManarin/ScreenToGif/wiki/Help#ribbon

**Comment by WELZ-gh** [comment]
_[Changes feature request to make it possible to be automatic]_
