### ISSUE TITLE
Color picker is inaccurate when placing in HEX values

### ISSUE THREAD

**Issue by WELZ-gh** [NickeManarin/ScreenToGif#330]
I was pasting in HEX values and was quite surprised at what they showed.

The color on the left is what it's supposed to show, the color on the right is what it actually shows.

The problem has something to do with it mixing around the numbers (it has the 61, 187, 210 correct, just in wrong order - and one of them was applied to alpha as well)

![image](https://user-images.githubusercontent.com/35234925/40694034-80b82e22-6388-11e8-8693-55e3cd2e464f.png)

![image](https://user-images.githubusercontent.com/35234925/40694068-b3ff29ca-6388-11e8-95f2-3543684e5a88.png)

**Comment by NickeManarin** [comment]
Try pasting #FF3DBBD2 instead.
I'll fix this by checking the length of the code. 
Thanks.

**Comment by NickeManarin** [comment]
Fixed. Now it will work like this:

If you paste **#11** or just **11**: It will apply **0xFF** to the alpha value and **0x11** to RGB.
If you paste **#F411** or just **F411**: It will apply **0xF4** to the alpha value and **0x11** to RGB.
If you paste **#F41122** or just **F41122**: It will apply **0xFF** to the alpha value and **0xF4 + 0x11 + 0x22** to RGB.
If you paste **#FFF41122** or just **FFF41122**: It will work as usual.
