### ISSUE TITLE
transitions not working on Windows 10 Pro

### ISSUE THREAD

**Issue by atentoni** [NickeManarin/ScreenToGif#331]
I am using ScreenToGif on Windows 10 Pro, and I can't seem to get any transitions to work.  I have no problems getting transitions to work from my computer at home.

When I choose Fade to Color, the color picker always displays white, no matter what the hex code is.   Then when I click apply, it inserts extra frames, but they are all the same as the last frame -- there is no fading.

Here is a Jing video to demonstrate:  https://www.screencast.com/t/sDlM921P

I would just attribute this to user error, but I can get it to work at home, so I think it might be a bug.

Thanks!

**Comment by NickeManarin** [comment]
The Alpha value is zero. Change it to 255 and it will work. :)

I'm working with some changes with the ColorPicker UI, so I'll make more clear that a transparent color was selected.

**Comment by NickeManarin** [comment]
Done. I added a warning explaining that a transparent color was selected when trying to "fade to a color".
Also, I made it more clear that a transparent color was selected.
