### ISSUE TITLE
Dark theme not working

### ISSUE THREAD

**Issue by spikespaz** [NickeManarin/ScreenToGif#336]
The dark theme options for the editor is not working on the Windows 10 Preview 17134.

![image](https://user-images.githubusercontent.com/12502988/41061447-78130c42-6987-11e8-9c14-7856d6e2ba42.png)

**Comment by NickeManarin** [comment]
The color scheme 'Dark' is suppose to work only for the Editor background (where the frame is displayed). 
Can you show me a screenshot of what you are seeing?

**Comment by spikespaz** [comment]
Oh I see, yes then it does work. But the recorder theme is definitely not dark(er).

**Comment by NickeManarin** [comment]
Well, you selected "Medium". It's gray-ish but not dark. If you wish to change the colors, just click on the rectangles under the "Color scheme" selector.
