### ISSUE TITLE
[Feature Request] Recording a specific window

### ISSUE THREAD

**Issue by Manipendeh** [NickeManarin/ScreenToGif#338]
Right now, it records the screen, but when I try to record gameplays, for example, it records what's behind the game window. Would be good to have something for that

**Comment by WELZ-gh** [comment]
You can choose where on the screen you want to record and easily resize it to fit the window.

Additionally, there is a feature to auto select an entire window for you, the button looks like this:

![](https://user-images.githubusercontent.com/35234925/41557658-555db81c-730c-11e8-89c8-81cfd59b1913.png)

You just click+drag until it has the correct area of the window selected (outlined) and then release. [GIF](https://user-images.githubusercontent.com/35234925/41557809-c92598fa-730c-11e8-8758-ed80c0ab1d2f.gif)

**Comment by NickeManarin** [comment]
I believe that the app needs DirectX capabilites in order to record games. That's why it does not record games.

This is a bit out of scope right now.
