### ISSUE TITLE
Blank screen - Buttons invisible

### ISSUE THREAD

**Issue by xtbe** [NickeManarin/ScreenToGif#339]
When starting up the application I get a blank window where the buttons are not visible. Tried already several things but can't get it working.

OS: Windows 10 - April Update

![snap1](https://user-images.githubusercontent.com/909796/41498404-1660744c-716d-11e8-983c-5c597ed56876.png)

**Comment by NickeManarin** [comment]
Hi, this is the second feedback about this problem that I've got. I still don't know for sure what's happening. :/

I'm assuming that you are running the latest release (v2.13.3). Can you right click the ScreenToGif icon on your notification area (system tray)? Try opening the editor or the recording, etc.

This could be an issue with a video driver, can you share with me the name/model of your graphics processor? Also the driver version?

If you have multiple monitors, try draging the window to another monitor, just to check if the rendering starts to work.

I'm running W10 1803, build 17134.48 with a GeForce GTX 970, driver version 398.11 and the app is running fine.

**Comment by xtbe** [comment]
Hi,

It seems not possible to turn off Hardware Acceleration in Windows 10 (April update) this slider is gone.

I tried a few options by right-clicking in the sys tray, the "xxxxxx recording" options are displayed correctly. All the other ones result in blanks screens.

I'll see if I can find updated drivers for the GPU perhaps this could help. 
I agree this is probably a GPU (driver) error in combination with WPF

Only one monitor.
GPU running on the laptop with issues is an Intel HD Graphics HD5500.  So this is an integrated GPU.

**Comment by NickeManarin** [comment]
Can you try using this version?
https://1drv.ms/u/s!Atz6mWWOy6N8oOUKTu2EmDtzWwLtTg

This version has the hardware acceleration disabled. The UI looks a bit laggy because of that.

**Comment by xtbe** [comment]
Tried with the version you asked to test and it works correctly.
I don't experience any real annoying lag.

Tnx a lot

**Comment by choldgraf** [comment]
Just a note that this started happening to me all of a sudden as well. It looks just like the image in the top thread. Also using integrated intel graphics.

**Comment by NickeManarin** [comment]
Try updating the graphics card driver. I'm not sure what's hapening.
WPF uses DirectX 9 to render its elements.

**Comment by NickeManarin** [comment]
Closed as external.

Anyway, if it happens again, run with hardware acceleration disabled by running the app in software rendering mode:

https://github.com/NickeManarin/ScreenToGif/wiki/Startup-parameters
