### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by Solarunit** [NickeManarin/ScreenToGif#34]
Hi! Any plans to release ScreenToGif for Linux?

**Comment by NickeManarin** [comment]
Not yet. I know nothing about native development on Linux. :/

**Comment by Hrxn** [comment]
Well, you can use C# and Dotnet on Linux, but in a quite limited manner. GUI related stuff, WPF, probably not at all, not even beginning to think about that media part which is highly platform specific.

But there is an alternative you might want to try: https://github.com/MaartenBaert/ssr
