### ISSUE TITLE
Unable to record full screen

### ISSUE THREAD

**Issue by TopStudyWorld** [NickeManarin/ScreenToGif#343]
We should be able to record the full screen with a single click. The toolbar hides the top part of the screen, so it doesn't record the full screen.

**Comment by vatterspun** [comment]
I'm not sure about single click, but I can see some advantages to full screen recording, especially with an editor component that can crop later.  After all, if you have a fast computer, why not get everything and decide what to use later?

I guess with full screen the toolbar should float or be temporarily invisible?  Maybe some kind of "full screen" mode with a "maximize" box in the top bar.  then it would switch floating bar near the bottom that doesn't get recorded, maybe with just a stop/start function?  Or just a brief floating pop up mentioning the record, stop, and pause key combos.

In terms of interface, I could mock something up if that's helpful.

**Comment by NickeManarin** [comment]
@TopStudyWorld Go to Options > Application > Check the "Enable the new recorder UI".  

After that, open the recorder, click on the dropdown button and select "Screen".  

![fullscreen](https://user-images.githubusercontent.com/14798947/41823401-c4f14266-77d5-11e8-9dad-c3369b12aa84.png)

The app will prompt you to select one screen to record, just click to select.
When you start recording, the UI will be minimized.
The recording will pause when you bring the UI to the foreground.

**Comment by ctstacey** [comment]
@NickeManarin Fantastic Work, much respect! ❤️

I run v2.37 as a portable, and had to **restart the application** before the changes took effect.

(I won't admit how long it took to figure that out 🤣)

**Comment by Stevoisiak** [comment]
> @TopStudyWorld Go to Options > Application > Check the "Enable the new recorder UI".
> 
> After that, open the recorder, click on the dropdown button and select "Screen".
> 
> ![fullscreen](https://user-images.githubusercontent.com/14798947/41823401-c4f14266-77d5-11e8-9dad-c3369b12aa84.png)
> 
> The app will prompt you to select one screen to record, just click to select it. When you start recording, the UI will be minimized. The recording will be paused when you bring the recorder UI to the foreground.

I do not see these options in ScreenToGif 2.38.1. There is no "Enable the new recorder UI" checkbox in the options, and there is no area dropdown in the recorder.

![image](https://github.com/NickeManarin/ScreenToGif/assets/1330770/9c5b77cc-98ca-4b71-b143-e6c2c0395953)

![image](https://github.com/NickeManarin/ScreenToGif/assets/1330770/86f74f78-9ae6-4b14-a486-3731f81320f1)

**Comment by Stevoisiak** [comment]
> @TopStudyWorld Go to Options > Application > Check the "Enable the new recorder UI".
> 
> After that, open the recorder, click on the dropdown button and select "Screen".
> 
> ![fullscreen](https://user-images.githubusercontent.com/14798947/41823401-c4f14266-77d5-11e8-9dad-c3369b12aa84.png)
> 
> The app will prompt you to select one screen to record, just click to select it. When you start recording, the UI will be minimized. The recording will be paused when you bring the recorder UI to the foreground.

The new recorder UI is now in Recorder options in ScreenToGif 2.38.1 
![image](https://github.com/NickeManarin/ScreenToGif/assets/1330770/7e252403-8a0a-448b-934f-46a29f7bfd30)
