### ISSUE TITLE
New recorder can't catch the window

### ISSUE THREAD

**Issue by YuryKomar** [NickeManarin/ScreenToGif#349]
Noticed that new recorder can't catch the ESET NOD32 Internet Security window...

The old one can do that...

**Comment by NickeManarin** [comment]
Sorry for the delay, but try adding ScreenToGif as an exception.
Also, you could try using the new capture method (DirectX) available in this test version: #551

**Comment by NickeManarin** [comment]
This bug was fixed. It happened because some windows don't use the standard Windows title bar, which caused them to be ignored by the new recorder.

**Comment by YuryKomar** [comment]
Perfect job ;) Thx.
