### ISSUE TITLE
Version 2.3 Can't change Frame Time Length

### ISSUE THREAD

**Issue by BGMcoder** [NickeManarin/ScreenToGif#35]
In version 2.2 we could, in the playback tab, adjust the length of the frame.  You could only change one frame at a time though.

But in 2.3, you can't change it anymore - the edit box is missing.
Here's my dilemma - I need the base frame time length to be 300ms instead of 1000ms.

I know you can change the delay, but I want to change the frame time.

I would like to see two settings here:
1. Set default frame length (so I can just do it globally and not have to edit the time of each frame)
2. Put back the time editor into the playback tab (and make it work for selected frames)

**Comment by NickeManarin** [comment]
Frame time, did you mean delay/duration?   
**Delay** and **frame time** (or duration) are the same thing.

To change the delay of each selected frame you have two options (Under the **Edit** tab):

**Override** (also called replace), will replace all of the values to a specific value ranging from 10ms to 2.500ms.

*or*

**Increment/Decrement**, will increment (if the value is positive) or decrement (if the value is negative) all of the values.

**Comment by BGMcoder** [comment]
In 2.2 there was delay and there seemed to be the slide duration.  The default is 1000ms.  If they are the same why are the limits for the delay only from 10ms to 2.5ms?  I want a frame duration of 200ms, and the default is 1000.  Also changing the "delay" does not change the duration total on the frame in the timeline.

**Comment by NickeManarin** [comment]
By "default Slide duration" do you mean the default duration of the **Snapshot mode**?

A little correction: Gif specification only allows delays with 10ms to 2,550ms (2.55 seconds). (I mixed the comma with the period)

**Comment by BGMcoder** [comment]
No, I don't mean shapshot mode - I always do mine manually anyway - less editing and smaller files.  What I mean is how long the gif stays on one particular image before it switches to the next one.
It seems to me that it stays the length of "slide duration" + "delay".  Slide duration (in the older version) could be set to 300ms instead of 1000ms, irregardless of the delay.
What I want to see is the option to set a default on the slide duration (honestly, I don't care about delay).

**Comment by NickeManarin** [comment]
I'm closing this issue because you can change the delay of selected frames.
