### ISSUE TITLE
Improper Number Manipulation when Incrementing / Decrementing filenames

### ISSUE THREAD

**Issue by NoiSek** [NickeManarin/ScreenToGif#351]
When specifying video output options and attempting to increase or decrease the filenumber, the code here will always affect the last number of a filename:

https://github.com/NickeManarin/ScreenToGif/blob/1a4399a0622ca44213d2ae0b2e18abcd6446ed61/ScreenToGif/Windows/Editor.xaml.cs#L4726

Meaning a filename with an extension specified that includes a number will increment / decrement the extension rather than the filename itself.

As an example, with a filename like `filename25.mp3`, incrementing five times would produce the following output:
 
- file25.mp4
- file25.mp5
- file25.mp6
- file25.mp7
- file25.mp8

**Comment by NickeManarin** [comment]
The file extension is not supposed to be typed directly into the filename text box. There's a combo box (selector) to the right. :)

**Comment by NickeManarin** [comment]
Btw, which version are you using? The latest version has a dropdown (with the file formats) very close to the text field where you type the filename.

**Comment by NoiSek** [comment]
I am not using any version of this, I'm just passing along information from the thread that it seems you have already discovered 😄 

Figured someone should actually raise the issue on the repo when I saw there was no bug filed.

**Comment by NickeManarin** [comment]
That user was using an old version of the app, in which the file format dropdown was not very close to the filename.
The current version of the app has a more easy to understand layout. So this is no longer a problem.
