### ISSUE TITLE
Upper frame border's issue

### ISSUE THREAD

**Issue by user3323** [NickeManarin/ScreenToGif#352]
I want to record part of screen WITH title of the app.
But STG is not gonna allow me, because of it's upper recording frame border.

![image](https://user-images.githubusercontent.com/24613274/42212960-38282b3c-7ec0-11e8-829d-f41331110f11.png)

I'm moving it upper, but it jumps back down.

Can you fix it?

**Comment by NickeManarin** [comment]
Can you use the new recorder UI?
Or if you wish to stay with the older recorder, you can right-click at the "record" button to enable the "thin mode".

**Comment by user3323** [comment]
@NickeManarin 

What do you mean by **_new recorder UI_** ?

And yes, I've enabled "thin mode" and it's great.
Would be good if you will make a button for this, so there will be no need to find it on the right click of record button.

**Comment by NickeManarin** [comment]
To enable the new recorder UI, go to Options > Application > "Enable the new recorder UI".
It's a completely different recorder, with less UI on your way.


There's another way to enable "Thin mode", same place as the new recorder UI.

**Comment by user3323** [comment]
@NickeManarin 

look at that... 

![stg1](https://user-images.githubusercontent.com/24613274/42403056-4a9dcb5e-8187-11e8-97d0-8c1e2c5e55ae.gif)

launching 2nd copy of STG (when new UI enabled) makes UI become minimized to 0 (both of them)

**Comment by NickeManarin** [comment]
@user3323 I'm sorry, I need to improve the UX of the first launch of that recorder.

You must click the button to the left of the "record" button, then you can click and drag to select a region of the screen.

**Comment by NickeManarin** [comment]
@user3323 Did you click on the third button from the right? The one to the left of the "record" button?
Also, since that was your first time opening that recorder, you could simply click to "record", it would ask you to select a screen region.

**Comment by user3323** [comment]
@NickeManarin 

now I use latest version and can use New UI

But, can you make a little area or areas (in corners) near rectangle to drag and drop the selected area?

**Comment by NickeManarin** [comment]
> But, can you make a little area or areas (in corners) near rectangle to drag and drop the selected area?

Create another request for that feature. :)
