### ISSUE TITLE
About Donate

### ISSUE THREAD

**Issue by sylrty** [NickeManarin/ScreenToGif#353]
We hope you  can add the way of donation by AliPay . Because in China, most of people do not have a PayPal account.
By the way, your software is awesome. tks

**Comment by NickeManarin** [comment]
If I understood correctly, the only way to spend any value deposited on a Alipay account is by buying things from the Alibaba group (Aliexpress, for example)? Is that right?

**Comment by vatterspun** [comment]
It does look like AliPay is popular and I'm all in favor of you seeing donations, but I'd wait until someone actually wants to donate via that system to set something up.

**Comment by laiqun** [comment]
Yes, Mostly Chinese use AliPay or Wechat Pay. Those look like a copy of PayPal.

**Comment by NickeManarin** [comment]
Looks like Alipay and Wechat Pay is China only. I could not find any info in foreigners using those apps. :/
