### ISSUE TITLE
Bug when cancelling the codec selection window when using the system encoder

### ISSUE THREAD

**Issue by vletoux** [NickeManarin/ScreenToGif#362]
On a brand new install of Windows 7 with latest patches and the latest version of ScreenToGif, I tried to save a video.
I selected the « system » encoder and it showed a Window to select a codec.
Without any good codec, I pressed cancel and the application crashed immediately.

I see the crash occurs in the Dispose method of the AviWriter class.

This is a non blocking bug but happens quite surprisingly and without recovery possibility.
=> should the exception management being handled at a higher level to avoid an application crash (and the lost of its data) ?

**Comment by NickeManarin** [comment]
Thanks, I was able to fix this bug and it will be available with the next release (v2.14). 
It will still appear as an error after cancelling the encoding, but it wont crash the app.

**Comment by NickeManarin** [comment]
> and the lost of its data

Btw, if the app closed for you, you can recover your project by clicking on the **Recent Projects** button.
