### ISSUE TITLE
Remove duplicate frames without reducing overall length

### ISSUE THREAD

**Issue by brianjlacy** [NickeManarin/ScreenToGif#364]
Is it possible to remove duplicate frames without reducing the overall length of the video?

In other words, I want to use the "Remove Duplicates" tool to reduce the file size by removing all but one frame from each **contiguous sequence** of duplicates, BUT extend the duration of the remaining frame to the total duration of the original sequence of duplicates, thus allowing the duration and content of the overall video to remain unchanged. Is this currently possible?

**Comment by NickeManarin** [comment]
It should be possible to achieve this by selecting the option to sum the delay of the removed frames into the remaining frame.
But I believe that the options is not working properly right now.
I'll try to fix right now, maybe it's going to be available with the next release (v2.14).

**Comment by NickeManarin** [comment]
I got it. It works when selecting these options: 

![image](https://user-images.githubusercontent.com/14798947/43672396-618a34a8-9783-11e8-8c0e-5478519ce317.png)

It does not work when selecting the "Frame removal" option as "Remove the first frame".

**Comment by NickeManarin** [comment]
Fixed. :)

**Comment by vatterspun** [comment]
Love the similarity percentage -- that's huge.  Thanks!

**Comment by NickeManarin** [comment]
@brianjlacy This week.
