### ISSUE TITLE
App crash - Hotkey already in use

### ISSUE THREAD

**Issue by haybeseret** [NickeManarin/ScreenToGif#366]
Hi,
Windows 10,
Appversion - 2.13.3

[18_08_01.txt](https://github.com/NickeManarin/ScreenToGif/files/2250083/18_08_01.txt)

**Comment by NickeManarin** [comment]
Hi, this bug was fixed.
The fix will be available with the next release.

While the new version is not available, you can delete the settings file.
Head over to **%appdata%\ScreenToGif** and delete the **Settings.xaml** file.
