### ISSUE TITLE
Save to Video crash on tsccvid64.dll 

### ISSUE THREAD

**Issue by EdePC** [NickeManarin/ScreenToGif#368]
Save as > Video > Encoder System > Save > Compressor > [Any] > CRASH

Nombre de la aplicación con errores: ScreenToGif.exe, versión: 2.13.3.0, marca de tiempo: 0x5adfb36c
Nombre del módulo con errores: tsccvid64.dll, versión: 3.0.0.0, marca de tiempo: 0x4c44a8a8
Código de excepción: 0xc0000005
Desplazamiento de errores: 0x0000000000005def
Identificador del proceso con errores: 0xcc4
Hora de inicio de la aplicación con errores: 0x01d42a7152fd1302
Ruta de acceso de la aplicación con errores: C:\Users\EdSon\Desktop\ScreenToGif.exe
Ruta de acceso del módulo con errores: C:\Windows\SysWOW64\tsccvid64.dll
Identificador del informe: 0b538f13-9665-11e8-beba-f739e0df3f38

Camtasia Studio codec error?

Workaround: Go to codec with error: C:\Windows\SysWOW64\tsccvid64.dll and rename to tsccvid64.dll.bak

**Comment by majkinetor** [comment]
I confirm this.

**Comment by NickeManarin** [comment]
Closing as external.
