### ISSUE TITLE
Detect Mouse Clicks not working

### ISSUE THREAD

**Issue by rogeriodec** [NickeManarin/ScreenToGif#370]
Although I've checked "Detect mouse clicks" option, it's not showing in the captured video.
I'm I doing something wrong?

**Comment by NickeManarin** [comment]
What kind of content are you trying to record?
Some windows that were open with admin rights don't report mouse clicks.

**Comment by rogeriodec** [comment]
In fact. I also did a test capturing a video and the clicks out of the window are captured and the clicks inside the window are not.
I never heard of this limitation.
However, you certainly know Camtasia and there is not this problem with this software.
Therefore it might have some solution for this.

**Comment by NickeManarin** [comment]
> I also did a test capturing a video and the clicks out of the window are captured and the clicks inside the window are not.

Which app was that? I want to do some testing.

**Comment by rogeriodec** [comment]
See https://imgur.com/Brb7yxp.
It seems **any** app with admin privileges has the same problem.

**Comment by rogeriodec** [comment]
Perfect! 
Thank you very much! 
(I will collaborate with you via PayPal).

**Comment by NickeManarin** [comment]
Thank you!

**Comment by janzitniak** [comment]
> > It seems that any app with admin privileges has the same problem.
> 
> Yes and if you run ScreenToGif as admin too, the clicks are detected.
> 
> > And although off topic I would like to know how to set up the loop limit (or not loop) for the generated gif?
> 
> Save As > Gif options expander > **Looped gif**, **Repeat forever** and **Repeat count** options.
> 
> > Você é Brasileiro? Em todo caso acho que devemos falar em inglês para ficar acessível aos outros, não é?
> 
> Sim, exato. É melhor escrever em inglês para todo mundo conseguir ler. :)

Dear Nicke.

If I launch ScreenToGif 2.18 in admin mode and Microsoft Excel 365 too I still get _There's no detected mouse clicks on your project_ message if I record something. I used your Mouse Clicks in Image tab.

Regards
Jan

**Comment by NickeManarin** [comment]
I'm able to capture the mouse clicks fine. Have you tried to run both apps without admin rights?

![Excel](https://user-images.githubusercontent.com/14798947/64176936-c9286600-ce34-11e9-9474-289a2daf2104.gif)
