### ISSUE TITLE
"Copy to Clipboard" just puts a PNG in your clipboard.

### ISSUE THREAD

**Issue by codeHusky** [NickeManarin/ScreenToGif#371]
![image](https://user-images.githubusercontent.com/6946558/43691974-ec1e5b56-98e8-11e8-9ccc-d31e03cff230.png)
I pasted this into the editing box from ScreenToGif. This is not a gif, this is a PNG.

**Comment by NickeManarin** [comment]
Duplicated #251 Basically, it's not possible to copy gifs to the clipboard, maintaining all frames.

**Comment by codeHusky** [comment]
Well, is there really a point of having the feature if it doesn't work as implied by the name?

**Comment by NickeManarin** [comment]
If you are talking about `Save As > Copy to clipboard > File`, then yes. Because it copies the file, allowing you to paste it somewhere else, using the File Explorer.

I could remove the single frame being copied too, to avoid this issue.

**Comment by vatterspun** [comment]
I think the clipboard function has it's uses so I wouldn't remove it.  Maybe change "Copy to clipboard" to "Copy frame to clipboard" or "Copy current frame to clipboard" to avoid confusion?
