### ISSUE TITLE
FFMPEG not found click here to set options > Extras doesn't do anything

### ISSUE THREAD

**Issue by TomasHubelbauer** [NickeManarin/ScreenToGif#376]
Hello, I am using the latest version of ScreenToGif and its a fresh installation on a system without FFMPEG. When I record something and then proceed to try and save it using FFMPEG, it prompts me to install it because it's not in path.

The slide-out panel with that prompt however doesn't react on click.

And more unfortunately, when I start a new FFMPEG instance and go Options through that so that I don't lose my project in the original one (don't want to save and load, it's a pain), when I download FFMPEG using Extras and then save the options, returning to the original instance doesn't see the now provided FFMPEG path anyway, it appears to be using a cached view of the options which cannot be refreshed as far as I can tell in any other way that to restart.

**Comment by NickeManarin** [comment]
Hi, I can't reproduce what you are seeing.
Here's what happens while I'm using it:

![ffmpeg2](https://user-images.githubusercontent.com/14798947/45912318-b2d8f400-bdf5-11e8-97d1-e956b7eb0f24.gif)

(I skipped the recording while the download and the encoding was happening)

**Comment by FermJacob** [comment]
Can confirm that the download functionality is working for me as well.

**Comment by TomasHubelbauer** [comment]
Thanks, I will try to put together a repro, might have been a problem with a specific machine.

**Comment by NickeManarin** [comment]
I fixed an issue related to the detection of FFmpeg/Gifski in v2.15.1.
Can you still reproduce this issue?

**Comment by TomasHubelbauer** [comment]
Yeah clicking on the yellow line saying "Click here" doesn't do anything still. Going to Options > Extras manually, downloading FFMpeg and then reexporting the video works though 👌

**Comment by NickeManarin** [comment]
> In your screenshot, the yellow line is a blue link, in my case the text is black and not underlined.

Ahhhh! :(
I missed one place. Thanks.

It was the message that appears when pressing the button to export a video.
