### ISSUE TITLE
Consider remembering the choice of encoder and extension

### ISSUE THREAD

**Issue by TomasHubelbauer** [NickeManarin/ScreenToGif#377]
I use ScreenToGif almost exclusively to encode to MP4 so I'd like to suggest the app remembers to select FFMPEG every time after the first time I have selected it and also to remember the extension (default is AVI).

It does remember the path as of now (which is awesome) and the file name (which is not very useful and I wonder if it could be turned off?) so I think it makes sense to persist the state of the entire encoding options pane upon closing.

**Comment by NickeManarin** [comment]
I remembers the encoder, the file extension and also now there's support for multiple presets for each file type (FFmpeg).
