### ISSUE TITLE
Suggestion - FFmpeg video import

### ISSUE THREAD

**Issue by NickeManarin** [NickeManarin/ScreenToGif#378]
Allow FFmpeg to be used as the video importer instead of the default MediaElement (WMP) currently being used.

[Shouldn't be too hard to accomplish that](https://stackoverflow.com/questions/27568254/how-to-extract-1-screenshot-for-a-video-with-ffmpeg-at-a-given-time).

**Comment by vatterspun** [comment]
The obvious workaround for that is just to create a recording of a video using ScreenToGif. However an import component would be a pretty cool addition just in terms of image/video quality.

**Comment by NickeManarin** [comment]
Done!

![image](https://user-images.githubusercontent.com/14798947/69056947-bf53df00-09ef-11ea-8aa3-9c93f09956d4.png)

I merged the changes made by @manbokGo and added my own.
