### ISSUE TITLE
hope to increase the reduction of GIF in Telegreat

### ISSUE THREAD

**Issue by findwisdom** [NickeManarin/ScreenToGif#379]
The GIF uploaded by the user in the Telegreat client is converted to MP4. 
Want to add the ability to bulk restore GIF in TG, 
Bulk restore by folder. 
Automatically naming GIF as the original MP4 name

**Comment by vatterspun** [comment]
Never heard of Telegreat before today.  It looks like a Telegram front-end.

Anyway, I'd suggest making this feature request to Telegram.  This seems out of scope for ScreenToGif.

---

EDIT: Tested with standard Telegram and it doesn't convert GIF to MP4.  So the workaround is don't use Telegreat.
