### ISSUE TITLE
BUG: Capture image quality loss when Progress bar added

### ISSUE THREAD

**Issue by dsanalytics** [NickeManarin/ScreenToGif#380]
Symptom: Once progress bar is added (either with text or without), image quality deteriorates with every apply in that dialog. You have to apply it around 5 times in order to make it easy to notice, but it's present with every apply. Can you make it lossless apply? I have not checked whether other modifications (like adding transitions) do the same.

Env: S2G v2.14.1 + Win7 SP1 64bit Home Premium

![snap-n4-00171-ann](https://user-images.githubusercontent.com/32625394/46349611-1fcf6380-c618-11e8-895c-38953f8f9755.png)

![snap-n4-00172-ann](https://user-images.githubusercontent.com/32625394/46349625-29f16200-c618-11e8-9715-64a39357f4f9.png)

Thanks for this great utility and for your work.

**Comment by dsanalytics** [comment]
Everything is default - I just captured couple of frames as an example for posting and added progress bar and text.

Project: [example-project.zip](https://github.com/NickeManarin/ScreenToGif/files/2463121/example-project.zip)

![image](https://user-images.githubusercontent.com/32625394/46713379-e56b5500-cc1b-11e8-8cd9-e01488b8355e.png)

**Comment by dsanalytics** [comment]
Any updates/fixes for this bug?

**Comment by NickeManarin** [comment]
Sorry for the delay, this was a bit of an edge case. 

It was fixed. I tested applying the same feature x10 times or more.
No loss of quality.

**Comment by dsanalytics** [comment]
Thanks - appreciated.
