### ISSUE TITLE
BUG: Discard Project prompts even when turned off

### ISSUE THREAD

**Issue by dsanalytics** [NickeManarin/ScreenToGif#381]
Discard always prompts for confirmation - being turned off in options is ignored.

Env: S2G v2.14.1 + Win7 SP1 64bit Home Premium

![image](https://user-images.githubusercontent.com/32625394/46350119-8a34d380-c619-11e8-9ec9-33c2d0326450.png)

![image](https://user-images.githubusercontent.com/32625394/46350129-8dc85a80-c619-11e8-9e00-5da16a84d690.png)

Thanks.

**Comment by NickeManarin** [comment]
I fixed it. Thanks.
It will be available with the next release.
