### ISSUE TITLE
StG forget gifski when edit .gif file from context menu

### ISSUE THREAD

**Issue by byzod** [NickeManarin/ScreenToGif#382]
**Extra info:**

When open StG with normal way (double click ScreenToGif.exe), the gifski working properly.

The relative gifski path in the Extra page was auto-filled by StG itself after clicking the download button.

Windows 10 x64, StG 2.14.1

**Reproduce:**
![a_1](https://user-images.githubusercontent.com/848607/46404271-3f10e280-c737-11e8-9aeb-b09b168396a7.gif)

**Expect:**

Export to .gif file normally

**Actual:**

What you see in  the image above

---

BTW, there're some problems when setting the gifski location, I didn't remember how but it was really confusing, maybe you can spend sometime test it

**Comment by NickeManarin** [comment]
I remember changing how the extras selection/download works. 
Did you select (or download) the Gifski while using the current version of the app or with the previous one?

Anyway, I was able to fix this bug. Thanks.
The app was interpreting `gifski.dll` as `C:\Windows\system32\gifski.dll` when opening from the `Open with` context menu.

It was happening with the FFmpeg too.

**Comment by byzod** [comment]
I'm getting this error again with the latest version (2.37.2)

StG location: "C:\App\Something\ScreenToGif\ScreenToGif.exe"

Target gif location: "K:\Down\R\test.gif"

When right click on that gif and right click then choose edit with StG, then try to save the result I got error

```
FileNotFoundException

Could not find file 'K:\Down\R\gifski.dll'.

   at System.IO.FileInfo.get_Length()
   at ScreenToGif.Util.GifskiInterop..ctor() in C:\Users\nicke\source\ScreenToGif-Current\ScreenToGif\Util\GifskiInterop.cs:line 169
   at ScreenToGif.Util.EncodingManager.Encode(ExportProject project, ExportPreset preset, Int32 id, CancellationTokenSource tokenSource) in C:\Users\nicke\source\ScreenToGif-Current\ScreenToGif\Util\EncodingManager.cs:line 792
```

**Comment by NickeManarin** [comment]
Try setting the fullpath in the extras page.
