### ISSUE TITLE
Uses A Lot Of Resources

### ISSUE THREAD

**Issue by GKid94** [NickeManarin/ScreenToGif#383]
The software uses a lot of my CPU, RAM and Disk when it's loading the recorded GIF and when it's saving it and the GIF's size is really large

**Comment by vatterspun** [comment]
It is?  ScreenToGif on my Win7 machine is taking up 11 megs of RAM, which is below average for programs of its type.  ShareX (which also generates screen recordsings) for example takes up around 20 megs.

As far as GIF file size, various tricks to reduce size are discussed in #299 

If you need a very lightweight recorder, LiceCap uses considerably fewer resources but also has fewer features and no editor component.

**Comment by GKid94** [comment]
![23142](https://user-images.githubusercontent.com/18757054/46578754-b039e980-ca06-11e8-9426-429dbfd1d298.jpg)


![41231](https://user-images.githubusercontent.com/18757054/46578755-b0d28000-ca06-11e8-8ab2-5980d41b3498.jpg)

**Comment by GKid94** [comment]
Maybe, can you optimize the program and make it lighter on resources

**Comment by NickeManarin** [comment]
@GKid94 With v2.20, there's a new recorder method, it uses DirectX, so it supposed to be lighter.
Also a memory cache can be used, further improving the performance.

Now, when saving, the app needs to copy some files, so it's going to give your HDD a bit of work. So far there's no solution for that.

**Comment by NickeManarin** [comment]
Closing this as there's not much else to be done.
