### ISSUE TITLE
[Feature Request] Dark theme

### ISSUE THREAD

**Issue by musm** [NickeManarin/ScreenToGif#384]
Please add dark theme!

**Comment by cmdrflexo** [comment]
This would be a great feature and I am sure many would agree! :D

**Comment by vatterspun** [comment]
Good suggestion.  My understanding is that real power savings from AMOLED screens are already here for most phones but a few years away for standard screens and laptops.  Still, it's a nice thing to have when most of your other programs are using dark / gray skins.

**Comment by NickeManarin** [comment]
Oh, I forgot to close this issue!
There's now 4 themes, including a very dark option, with low contrast.

![image](https://user-images.githubusercontent.com/14798947/65804950-2d9bc400-e15a-11e9-92c5-b95f2f7b7947.png)
