### ISSUE TITLE
Newer versions crash - NotifyIcon.IconSource exception

### ISSUE THREAD

**Issue by mrfearless** [NickeManarin/ScreenToGif#388]
I can only install ScreenToGif 2.12.1 - any newer versions seems to crash on launching.

```Set property 'ScreenToGif.Controls.NotifyIcon.IconSource' threw an exception.```

I have uninstalled and installed afresh each version after ScreenToGif 2.12.1 to test, and this is the last version that will work, all the newer versions crash the same way. Im using windows 7 x64.

**Comment by NickeManarin** [comment]
Can you provide the entire stack trace?

**Comment by mrfearless** [comment]
I downloaded the source and commented out the  section in https://github.com/NickeManarin/ScreenToGif/blob/e7d753743524c825ca741cb9d7d6960c3387ac8a/ScreenToGif/App.xaml#L97 and recompiled. 

I can get ScreenToGif to load now. 

Although it does complain about a NotifyIcon missing, but it doesn't crash/hang now. Once it shows the exception box messages and after clicking ok ScreenToGif.exe is still loaded in memory and has to be killed via task manager or process explorer.

I could comment out those other NotifyIcon references, but just wanted to test this out.

Still no idea why it is causing this exception.

**Comment by NickeManarin** [comment]
Are you up to date with your Windows 7 machine.
I had tested the version of ScreenToGif with the notification icon with Windows 7, but I don't have a machine/VM with Win7 anymore.

You can also opt-out from displaying a notification icon, edit the settings file or comment out the line of code that calls the exhibition of the icon from the App.xaml.cs file.

**Comment by mrfearless** [comment]
Yes I keep my Win7 x64 up to date with latest security and rollups.

Ok I will look into doing that.

**Comment by NickeManarin** [comment]
I'm going to close this issue, to keep track using the other, which has more activity.
