### ISSUE TITLE
Bundling FFmpeg

### ISSUE THREAD

**Issue by longzheng** [NickeManarin/ScreenToGif#389]
I just tried ScreenToGif for the first time and was a bit surprised to see that exporting to MP4 wasn't natively supported. I realized that it supports FFmpeg output, but it requires it to be installed.

I was wondering if there any limitation to bundle FFmpeg as part of ScreenToGif so users don't have to install it separately?

(I guess retain the ability to override the FFmpeg install as an advanced option)

**Comment by longzheng** [comment]
Also noticed that you do have a button to download FFmpeg in the options, but it prompts the user to specify a download location.

Could I suggest if the app is installed, then at least this button by default would save FFmpeg to the installation directory (so it's 1 step less for the user)?

**Comment by vatterspun** [comment]
You might also want to do what ShareX has integrated with their software: an auto-download feature.  That will maintain a small download size and enable video export for the users that need it.

![image](https://user-images.githubusercontent.com/1289134/47042229-5ea10580-d150-11e8-8368-f09e0270626b.png)

Alternatively, you might point to one of a number of available open FFMPEG font-ends for a video export tool that works with the amazing number of features built into that tool.

Some possibilities:

* FFmpegCatapult: https://github.com/mylesthaiss/FFmpegCatapult
* SmartFFmpeg: http://freeware.satria.de/SmartFFmpeg/index.php?lang=EN
* WinFF: www.biggmatt.com/winff/

---

Related thread: #376

**Comment by riverar** [comment]
Worrying about the size of the program is completely wrong headed. Also, ffmpeg encodes to a mind-boggling number of formats, in various containers, so the "MP4" complaint is wrong.

**Comment by smaragdus** [comment]
I searched my  machine and it turned out that there are 71 instances of **ffmpeg.exe** used by various programs- players, converters, video, audio and tag editors, downloaders, catalogs, servers, etc. Most of these programs come with absolute, hard-coded paths to **ffmpeg.exe** and as a result I have not just multiple instances but also different (in most cases- outdated) versions of **ffmpeg.exe**. Besides  a huge waste of space it is also a huge waste of time to update these instances one by one.

**Comment by majkinetor** [comment]
Could be done via #431 too and looks like more semantically correct as each tool can lead its own life.

**Comment by NickeManarin** [comment]
#563
