### ISSUE TITLE
[Feature request] Save at stop recording and auto save project

### ISSUE THREAD

**Issue by Kristinita** [NickeManarin/ScreenToGif#39]
### 1. Request

1. It would be nice, if you add option `save as project after recording`. If user record GIF and press stop, video automatic will be save as project.
2. It would be nice, if you add `auto save` option. Project will be automatic saved, for example, after 20 actions or 5 minutes of work.

### 2. Justification

Unfortunately, sometimes ScreenToGIF crash for me, if I edit my GIF. I need record and edit GIF again.

In order not to lose the results of my work, I need often save as project. If ScreenToGIF crash for me, I can open my project again and continue working. It would be nice, if Save as Project will be automatic.

### 3. Examples on other apps

For example, on [Codepen.io](http://codepen.io/) site is automatic save after code changes.

Thanks.

**Comment by NickeManarin** [comment]
You can now open recent projects by **File > Recent Projects** or `Ctrl+L`.

It will list all of your projects that didn't get erased on a list at the right side of the window, in a panel.

From there you can load the project as if you just recorded.

I still need to implement the "Auto save" feature. It is easy to do, I just need to create a setting like you wrote.

**Comment by NickeManarin** [comment]
Auto save feature done. The project is saved every time something is loaded, like after applying an overlay.
