### ISSUE TITLE
Slowing down

### ISSUE THREAD

**Issue by Jaxinson** [NickeManarin/ScreenToGif#396]
Every time I export a gif, it's a lot slower than the preview of it. I'm trying to save just an 81 frame gif with every frame at 10 ms, but every time I save it, I check it in the file after and it plays about 5 times slower.

**Comment by Jaxinson** [comment]
![1 1 splash intro](https://user-images.githubusercontent.com/44829737/48115500-18136800-e231-11e8-838e-ab71fa515cd5.gif)

**Comment by Jaxinson** [comment]
In the preview it's much faster, although I'm not sure how I could record that

**Comment by NickeManarin** [comment]
Indeed, the output gif has 10ms in each frame.

But that does not mean that every browser/viewer will display each frame as 10ms. 
Saving with 20ms will do the job.

![20ms](https://user-images.githubusercontent.com/14798947/48169308-e4404d00-e2d9-11e8-9dc7-76d3767a368f.gif)

**Comment by RudeySH** [comment]
I have the same issue.

> Saving with 20ms will do the job.

I couldn't find any way to specify the ms when saving to gif. Where is this option?

Should I just set the recorder to 50 fps with fixed framerate?
