### ISSUE TITLE
bugs?

### ISSUE THREAD

**Issue by asdf1324** [NickeManarin/ScreenToGif#4]
1. when trying to save resource file by clicking  Options - Language - here (if you are offline), program says 'Impossible to save the Xaml file' , 'String resource not found'.
![image](https://cloud.githubusercontent.com/assets/19871820/17782170/3e95d8b2-65ad-11e6-9d2e-eb7941cac447.png)

2. program crashes when trying to cancel importing frames from video in editor.

these two files are logs which automatically created when it crashed/failed to save Xaml file.
[log_18_8_2016.txt](https://github.com/NickeManarin/ScreenToGif/files/425415/log_18_8_2016.txt)
[log_19_8_2016.txt](https://github.com/NickeManarin/ScreenToGif/files/425416/log_19_8_2016.txt)

Using Windows 10 Home K x64 (Version 1607, Build 14393.51) - Korean running on i5-6600K and GTX960 with 16GB RAM.

**Comment by NickeManarin** [comment]
Fixed. Thank you.

I had to change the name of the main resource and I forgot to update this area.

**Comment by NickeManarin** [comment]
I also fixed the second bug.
