### ISSUE TITLE
[Bug] On Dispacher Unhandled Exception - Unknow

### ISSUE THREAD

**Issue by Kristinita** [NickeManarin/ScreenToGif#40]
### 1. Summary

I can not record one my GIF.

### 2. Expected behavior

Successfull all GIF's record.

### 3. Actual behavior

Stop recording on ~1609 frame 4 times for me.

![Stop and crash](http://i.imgur.com/UtmoTlY.gif)

### 4. Steps to reproduce

I record GIF use Sublime Text 3 and [**KeypressOSD**](https://gist.github.com/tmplinshi/6933557) AutoHotkey script. I can not end of record.

[**Full today log on Gist**](https://gist.github.com/Kristinita/ba0ba8e360093d043971869562ce1a0f).

### 5. Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**ScreenToGif:**
2.3.161030
**.NET Framework**
4.6 Build 394802
**Sublime Text:**
Build 3126
**AutoHotkey:**
1.1.24.03
**KeypressOSD:**
2.0.6

Thanks.

**Comment by NickeManarin** [comment]
Thanks for the feedback. If you disable cursor capture, does it work?

**Comment by NickeManarin** [comment]
Fixed. Available with version 2.3.2. I'll publish on Chocolatey.
