### ISSUE TITLE
Disabling "detect mouse clicks" option does not work in 2.14.1

### ISSUE THREAD

**Issue by C0deboy** [NickeManarin/ScreenToGif#402]
This option is broken in version 2.14.1. Unchecking it does not take affect. Also there is no color picker when it is enabled. Clicks are detected regardless of this option.

Works fine in 2.13.3. Not sure about 2.14, but probably bug was introduced in this version.

**Comment by C0deboy** [comment]
Also why destination folder allows only to select files? It force user to provide path to folder by hand.

**Comment by NickeManarin** [comment]
Fixed. If you want to disable it right now, remove the automated task that adds the mouse clicks highlights.

**Comment by NickeManarin** [comment]
>           Also why destination folder allows only to select files? It force user to provide path to folder by hand.

You can select a file destination and remove the filename later.

**Comment by C0deboy** [comment]
Thank you for quick response and for the fix.

> You can select a file destination and remove the filename later.

What if the file does not exists which is almost always the case for me?
Your workaround is not user friendly. Can't you just change this restriction for folder?
