### ISSUE TITLE
[Bug]record-screen bug

### ISSUE THREAD

**Issue by Vixb1122** [NickeManarin/ScreenToGif#403]
When i record whole screen by using new recorder UI, the pre-start feature doesn't work, and shortcuts doesn't also work after recording starts.

config:
1. enable "Use a pre start countdown" and value is 3
2. enable the new recorder UI
3. open the screen recorder
4. change record-mode to `Screen`

bug:
* pre-start feature doesn't work
* shortcuts doesn't work after recording starts

![image](https://user-images.githubusercontent.com/17810492/49790946-589f5d80-fd6a-11e8-8117-6509ff20a52d.png)
![image](https://user-images.githubusercontent.com/17810492/49790963-62c15c00-fd6a-11e8-8a82-b1ca061893b8.png)

**Comment by NickeManarin** [comment]
The shortcuts bug was fixed.

The pre-start countdown works for me, you must press the red circle button in order to start the recording.

**Comment by NickeManarin** [comment]
Fixed.

If there's no space for the capture controls to be displayed during recording, a splash window will appear, with a countdown.

This will appear whether you have enabled or not the pre-start countdown, but it will use the pre-start countdown value.

![image](https://user-images.githubusercontent.com/14798947/90419118-7919d200-e08c-11ea-8dd4-1f4db345e2dc.png)
