### ISSUE TITLE
How can I hide the toolbar when I record the fullscreen?

### ISSUE THREAD

**Issue by li-zheng-hao** [NickeManarin/ScreenToGif#406]
![image](https://user-images.githubusercontent.com/22129824/50155548-50659600-0307-11e9-8605-f94aeb78e126.png)

I want to hide the toolbar but I don't know how to configure it

**Comment by NickeManarin** [comment]
You are using an old version of the app. Download v2.14.1, enable the new recorder UI under Options and select the Screen capture mode.
