### ISSUE TITLE
Can you increase the boot function at boot time?

### ISSUE THREAD

**Issue by xc135** [NickeManarin/ScreenToGif#408]
Can you increase the boot function at boot time?I think this feature is urgently needed because I have to start it every time at system boot time.

**Comment by smaragdus** [comment]
@NickeManarin 
I suppose that he requests an option ScreenToGif to start with Windows but I may be wrong.

**Comment by xc135** [comment]
Yes,this is what is my requests.Can you achieve this?

**Comment by vatterspun** [comment]
> I think this feature is urgently needed because I have to start it every time at system boot time.

This might help: 
https://answers.microsoft.com/en-us/windows/forum/windows_7-windows_programs/how-to-add-a-program-to-startup/91d18255-659e-4796-87f6-5e6c814c7d50

**Comment by WELZ-gh** [comment]
@xc135 I don't see why this feature is really needed, but there are ways to do it using Group Policy Editor.

**Comment by xc135** [comment]
> 
> 
> > I think this feature is urgently needed because I have to start it every time at system boot time.
> 
> This might help:
> https://answers.microsoft.com/en-us/windows/forum/windows_7-windows_programs/how-to-add-a-program-to-startup/91d18255-659e-4796-87f6-5e6c814c7d50
> 
> I'm curious why you need ScreenToGif running at boot. Why you need the program always available? What are you using it for?

Because when I chat with my friends, I often send img and gif to them. In Snipaste, the app has a default  option in windows start up. In this case, I will easily intercept the img and send to them.

**Comment by xc135** [comment]
> 
> 
> @xc135 I don't see why this feature is really needed, but there are ways to do it using Group Policy Editor.

Thank you, I know this method can be achieved. But I think it's best to set it in the app.

**Comment by vatterspun** [comment]
> Thank you, I know this method can be achieved. But I think it's best to set it in the app.

Why do you need it inside the app?  Isn't copying a shortcut to the Startup folder adequate?

**Comment by xc135** [comment]
> 
> 
> > Thank you, I know this method can be achieved. But I think it's best to set it in the app.
> 
> Why do you need it inside the app? Isn't copying a shortcut to the Startup folder adequate?

yeah,I think I will try it.
