### ISSUE TITLE
Minimum delay duration feels too low, could be lowered to 5 ms

### ISSUE THREAD

**Issue by Taberone** [NickeManarin/ScreenToGif#410]
Delay duration being a minimum of 10 feels too low. feels like it should be a minimum of 5 ms. My GIFs I make in the Editor are a lot slower now when I make them in ScreenToGif after updating to the newest version, and I suspect the delay duration is the cause.

Using an entirely different tool to make GIFs (EzGif) and setting the delay to 5 ms, my GIFs aren't too slow anymore. Setting the delay to 10 ms makes it as slow as what ScreenToGIF saves it as now.

**Comment by NickeManarin** [comment]
Gifs only accept a delay as multiple of 10ths, with a minimum of 10ms.

So, if a frame has 11ms delay, the gif will be created with a delay of 10ms.
A 18ms delay will be converted to 20ms and so forth.

Older versions simply truncated the delay value, any delay between 10ms to 19ms was getting converted to 10ms.

I'm not sure how EzGif accepts 5ms as the delay value.

**Comment by NickeManarin** [comment]
Closing this, as it's not possible to use less than 10ms in each frame.
