### ISSUE TITLE
Stop hotkey doesn't work when recorder gui is behind window.

### ISSUE THREAD

**Issue by Lonsol** [NickeManarin/ScreenToGif#413]
Whenever I try to record a gif whilst in fullscreen, the recorder GUI disappears beneath the selected window. This wouldn't be so much of an issue, but the stop hotkey refuses to work when the recorder GUI is behind the window.

I checked my media player to see if there was any conflicting keyboard shortcuts, but there appears to be none.

**Comment by NickeManarin** [comment]
Fixed. Thanks! It will be available with v2.15.2.
