### ISSUE TITLE
Thanks and new screenshot

### ISSUE THREAD

**Issue by vatterspun** [NickeManarin/ScreenToGif#416]
Thanks for the hard work on the new release.  Also, a new slideshow-style screenshot is posted to the ScreenToGif screenshot entry on TPFC: https://www.portablefreeware.com/index.php?id=2895

As with #360, please close this issue.

**Comment by NickeManarin** [comment]
Thanks! :)

**Comment by vatterspun** [comment]
Please don't re-open, just using this thread to point to a update discussing your mouse-follow enhancement https://www.portablefreeware.com/forums/viewtopic.php?p=97292#p97292

**Comment by NickeManarin** [comment]
Nice! :)
