### ISSUE TITLE
Capture doesn't match region when display scaling is not at 100%

### ISSUE THREAD

**Issue by JasonKleban** [NickeManarin/ScreenToGif#42]
Whatever this Windows 10 setting is:

![image](https://cloud.githubusercontent.com/assets/17498172/20847565/abac934a-b89c-11e6-83e5-70d99a0f8532.png)

screws up the capture region compared to the position of the capture window.

I have 125% on one monitor and 100% on the other, if I'm on the 100% it captures as expected, using Screen2Gif on the 125% screen grabs the unscaled top, left, width, height of the intended region instead of the intended one.

**Comment by NickeManarin** [comment]
Just to check, are you using the version 2.3.2?

**Comment by JasonKleban** [comment]
Oops!  I was testing an old version.  Sorry!

**Comment by NickeManarin** [comment]
Alright :)
