### ISSUE TITLE
about the audio recording :)

### ISSUE THREAD

**Issue by yinch3ng** [NickeManarin/ScreenToGif#423]
Hi guys,

First of all, I really thank you all about this software ,it is a very nice free tool to help me do many works .

I just want to know whether the audio recording feature is possible to be supported in the future ?? 

Many thanks for your reply :D

**Comment by vatterspun** [comment]
See #50 

I'm not saying it's impossible, but I see a few problems with this request:

1. Adding audio to the screen recordings is that importing that data into the editor feature is a whole other box of complexity.  If you cut some frames, does it cut the audio for those frames?  Does it run alongside?  
2. It's fundamentally a GIF recording program, which doesn't involve audio.  The only video component is in the export function, which is just sending the info to FFMPEG.

Alternatives:
1. You might import the GIF or video file into a standard editor and add audio.
2. I used to recommend Camtasia, but it costs a lot more than it used to.  You might want to look into ShareX or OBS for screen+audio recording.

**Comment by yinch3ng** [comment]
Thank you so much :)

**Comment by vatterspun** [comment]
> Thank you so much :)

Sure thing, hope that helped

**Comment by majkinetor** [comment]
Use ActivePresenter. Its free, awesome, and has a feature you want. You can automate install/update via choco: `cinst activepresenter`. I can't recommend ShareX due to the 'lets do everything in the world' mentality.

**Comment by vatterspun** [comment]
> Use ActivePresenter.  Its free

ActivePresenter is great, but it's not exactly free.  It includes a watermark and some features are limited.  I actually prefer the old version versus the newest (they host both on their site).  YMMV.

**Comment by ericpyle** [comment]
OBS works for me! Thanks for the recommendation @vatterspun

**Comment by Hot12345** [comment]
Im looking to record audio and format it in .MP4
Example to record a screenration with Teams voice/audio example. 

Is that possible? @vatterspun If not which application do you recommand?

**Comment by vatterspun** [comment]
> Is that possible? @vatterspun If not which application do you recommand?

Already covered earlier in the thread by @ericpyle -- OBS is the way to go.  I've tested it at length and it's just unbeatable.

**Comment by ITJoePC** [comment]
ShareX is exactly what I was looking for.  Thank you for suggesting it.
ScreenToGif is amazing for GIF purposes.

**Comment by bob454522** [comment]
I really would love to see this feature added to ScreenToGif - (ie ability to record audio while doing a screen cap , or even worst-case record after a cap and overlay the audio).

I get the argument that audio is not directly related to screen capture,  but if you all have the webCam functionality, i think its not a stretch to consider audio recording within the scope of this project (and within the scope of screen capture utilities).

In my case it was the difference between using just ScreenToGif as i frequently do,  and having to install another separate screen cap app (when i needed to do an audio recording + screen cap)  (not ideal)
thanks

**Comment by NickeManarin** [comment]
@bob454522 I'm currently working on a complete rewrite to the app (adding support for multiple layers).
With that, I'll be possible to ass support for audio tracks more easily.
