### ISSUE TITLE
Choose the recorder screen TopMost or not 

### ISSUE THREAD

**Issue by brownsugar** [NickeManarin/ScreenToGif#424]
I think it should be an optional feature for users to choose whether to enable or not.
In some cases, some programs need to find element in the screen I want to capture, but due to ScreenToGif is always on top, it will make the ui under it unselectable.

**Comment by NickeManarin** [comment]
I'm sorry, but in order to work, the recorder needs to be on top. You can try using the new recorder UI which is smaller.
