### ISSUE TITLE
Worst issue of all 

### ISSUE THREAD

**Issue by ogrotten** [NickeManarin/ScreenToGif#425]
None (=

Just wanted to say it's a great app and thanks for making it.

Here's where I used it: https://steamcommunity.com/sharedfiles/filedetails/?id=1618463074

I have grand plans on making more of those, and this app will be instrumental in those endeavors.

**Comment by vatterspun** [comment]
Neat.  Most of my uses of this program have been demonstrative for submitting better bug reports or to edit an existing GIF.  Never thought it might be used for something artistic.

**Comment by NickeManarin** [comment]
> Just wanted to say it's a great app and thanks for making it.
You're welcome. :)
