### ISSUE TITLE
[Bug] APNG image output

### ISSUE THREAD

**Issue by vatterspun** [NickeManarin/ScreenToGif#426]
**Background**: Trying to create a simple image slideshow for a freeware notepad program.

**Setup**: Win7x86, STG 2.15.1 (portable)

**Steps**:

1. Add some static images from file
2. Override frame delay
3. Save as APNG file

Result: some odd overlapping color issues: 

![2](https://user-images.githubusercontent.com/1289134/50861193-9093c380-135d-11e9-916c-7c4dbf94ea08.png)

**Other notes**: I tried disabling "detect unchanged pixels" but got the same result.  I was able to export to GIF and then use PNGOptimizer to get to the APNG file I was looking for, but obviously with some quality loss.

**Comment by NickeManarin** [comment]
Fixed in https://github.com/NickeManarin/ScreenToGif/releases/tag/2.15.2

**Comment by vatterspun** [comment]
Oh badass!  Thanks :)

**Comment by vatterspun** [comment]
I retested the latest version 2.15.2 but unfortunately getting similar results with a few screencaps of the Everything search program:

![a5](https://user-images.githubusercontent.com/1289134/50917807-23873900-1404-11e9-9625-5d10691d2a15.png)

**Comment by NickeManarin** [comment]
Hmm,  I'm missing something. I just downloaded both files (portable, installer) did a recording, opening menus and everything looks fine.
I had the option to ignore repeated pixels turned on too.

Did you check if you are using v2.15.2? If so, can you share your project? Maybe there's something different with the frames...

**Comment by vatterspun** [comment]
I realized my initial step listing was incomplete.  It's modifying the timing to slideshow speed that seems to create the overlapping issue.

Could you retest by setting the delay override to 2100?  As below ...

Setup: Win10x64

Steps:

1. Grab a bunch of same-size screenshots.  Something with some overlapping white space.
2. Select **Load** to add the screens to the editor 
3. At the bottom of the screen, select all frames
4. From the Edit screen click Override and change the delay to 2100
5. File - Save as APNG 

Defect: same as above.

Sorry for the confusion, I didn't think the delay had anything to do with it.  Bad bug reporting on my part.

**Comment by NickeManarin** [comment]
Like this one?

![test](https://user-images.githubusercontent.com/14798947/51090020-f5378f80-175c-11e9-992f-ed1ae9249f67.png)

**Comment by NickeManarin** [comment]
How did you create your screenshots? Can you share them? I think that this is related to an unexpected image content.

**Comment by vatterspun** [comment]
> How did you create your screenshots?

I used Greenshot.  I'll attach a recording of what I did (created also using STG) to show you all the steps.

Notes on the recording:

1. After the initial screenshot of the Everything program, I was pressing a key combo of CTRL+SHIFT+L for "capture last region" so it was able to grab the window with the menu items.  That didn't show up very clear in the recording.

2. The last step was moving the recorded PNG file into Firefox.  I accidentally deleted a few too many connecting frames in the recording.  I realize that wasn't super clear.

Process:
![a11](https://user-images.githubusercontent.com/1289134/51091704-cff25380-1753-11e9-871a-3625686a8af5.png)

Individual images:
[images.zip](https://github.com/NickeManarin/ScreenToGif/files/2753651/images.zip)

**Comment by vatterspun** [comment]
> Thanks for the detailed feedback

Thanks for noticing :)  Getting that video down to a reasonable size took a really long time.

> Tomorrow I think that I can create a new release of the app.

Awesome, I look forward to testing :)

**Comment by vatterspun** [comment]
Retested successfully with and without "detect changed pixels". Thanks!

**Comment by NickeManarin** [comment]
Thanks :)

**Comment by vatterspun** [comment]
Your program in use for software slideshow animations over on the S2G thread at PFW: https://www.portablefreeware.com/forums/viewtopic.php?p=92617#p92617
