### ISSUE TITLE
Built in update does not work as intended

### ISSUE THREAD

**Issue by Shkyrockett** [NickeManarin/ScreenToGif#427]
It is really cool that ScreenToGif has a built in update system, but I don't think it is quite working as intended.  

## Actual:
As it works now, when a new update is available the user gets a blue link at the top of the widow reporting that a new update is available. Clicking the link brings up a modal dialog that informs the user that the program will be closed and updates installed, and the user is presented with a save dialog. 

Next, once the file is downloaded and saved, the installer is then executed modally which prevents the program from closing, and the installer proceeds to install ScreenToGif in bootstrap mode requiring Windows to be restarted because the program is still running and the files cannot be replaced while they are in use.

Once the installation completes, another modal dialog is presented reporting that Windows has to be restarted to complete the installation. This dialog has the option to skip restarting, which is useful to use when you are working on something else. Then the user is dropped to the Installation complete dialog. The most obvious button is to press is Finish; which immediately restarts Windows despite the user pressing the skip reboot button on the previous dialog. How Rude! I was working on something else!

## Expected:
The expected behavior would be for the installer to be run using shell execute non-modally, the modal dialog box closed, and the ScreenToGif program terminated. This would allow the installation to complete without needing to restart Windows.

**Comment by NickeManarin** [comment]
Hi, I built a new updater from scratch and I just added an auto-updater mode to it.
Every time that the app is open, it will query GitHub/FossHub for new releases.

If a new release is found, it will be downloaded and the user will be able to install right away, by clicking in any notification (Startup window or Editor window). There's an option to start the app after the update, if manually set to install via this way.

If the user does not click to install, it will be prompted when closing the app. The option to start the app after the update is hidden.

The updater will install (or only replace the necessary files if in portable mode) and it will close automatically.

No restart is needed.
