### ISSUE TITLE
Windows Defender/Rising - False positive on ScreenToGif

### ISSUE THREAD

**Issue by NickeManarin** [NickeManarin/ScreenToGif#428]
Some users are reporting a detection by anti virus software.

It started with Windows Defender, yesterday: **Trojan:Win32/Emali.A!cl**
Right now, Windows Defender stopped thinking that this app is a virus. (Check your virus definition, update if possible)

But another AV engine called "Rising" started report this right now: **Trojan.Emali!8.10004 (CLOUD)**
https://www.virustotal.com/#/file/2a5d3e289df51fa5309f2291e60ac47956dcccb53baff81d8a57d07596c63cbf/detection

**Comment by NickeManarin** [comment]
I'm no longer getting these false positives.

**Comment by NickeManarin** [comment]
Again, but this time with the Zipped portable:

Trojan:Win32/Vigorf.A

Checking for new virus definitions won't solve this time. I uploaded that file to Microsoft as a false positive detection. Let's see what they say about it.

**Comment by NickeManarin** [comment]
Apparently, now it's not being detected anymore, at least with virus definition v1.283.2893.0:

![id 1](https://user-images.githubusercontent.com/14798947/51090500-f324ff00-1763-11e9-99dd-d6efb311f957.PNG)
![id 2](https://user-images.githubusercontent.com/14798947/51090502-f3bd9580-1763-11e9-8081-2df9151fad8a.PNG)

**Comment by smaragdus** [comment]
@NickeManarin 

The problem is not in the program but in the trashy antiviruses and their incessant false positives.
