### ISSUE TITLE
[Bug] Modfiy GIF image colors number

### ISSUE THREAD

**Issue by vatterspun** [NickeManarin/ScreenToGif#429]
Looks like some kind of weird field entry oddity.  Hardly a showstopper but definitely doesn't seem like what you intended.

---

Setup Win10x64

1. Create a GIF (doesn't matter what)
2. Click Encoder - 2.0
3. In the Gif Options fold-down from the colors box, select the numbers and type "128"

**Defect**: Can't edit just shows up as 256.  

Other notes: If you type in "111" it shows up as "112" so something's odd with this field.

**Comment by NickeManarin** [comment]
Done. It will available with v2.15.3.

What was happening, exactly? The input was getting processed/validated on time instead of after the focus was lost (and because there's a minimum value of 2). So when typing '1', the value was being changed to '2'.

**Comment by vatterspun** [comment]
> What was happening exactly?

Pretty much what you're describing.  Since I'm getting the hang of recording stuff in your editor so ... I just detailed out the process with keystrokes below ...

---

![a19](https://user-images.githubusercontent.com/1289134/51293389-56b56380-19d4-11e9-9105-607530312205.gif)
