### ISSUE TITLE
[Feature request] Screen Recorder - Capture keyboard input (shortcuts)

### ISSUE THREAD

**Issue by KrzysztofKarol** [NickeManarin/ScreenToGif#43]
Option to capture keyboard input shortcuts (eg. CTRL +A, CTRL + D) and add it to frame.

The question is where to show it? Center, with opacity?

**Comment by NickeManarin** [comment]
I was thinking about recording the key strokes and giving the option to add as overlay with customizations.

**Comment by sirtet** [comment]
Yes, this would be an awesome feature.
Recording mouse-clicks is already great, but keys are also quite important for tutorial-type recordings.

I'd like to show all key-presses with their duration:
eg. show key representations along the bottom of the screen. Show each key from the moment on  it is pressed, add more keys next to it as combinations are pressed, remove each as the key is released.

**Comment by sirtet** [comment]
To reasonably show also very short key-presses, some kind of fade-effect would be needed, but i guess that's obvious for @NickeManarin, as you have already done this for the click-events?

PS:
Only left-clicks are currently recorded. 
Even though seldom, some cases might need to indicate right-clicks too...

**Comment by NickeManarin** [comment]
@sirtet Yeah, that's a problem, but mouse clicks are recorded during each frame capture. 

Also, if you press two keys between the capture of one frame, I have to show both keys

**Comment by NickeManarin** [comment]
![keys](https://cloud.githubusercontent.com/assets/14798947/22957818/16657dbe-f312-11e6-839b-cef463e7c9eb.gif)

Almost there...

**Comment by sirtet** [comment]
great!

Some Ideas:
1.
Did you try to display bottom-left instead of centered?
I think it will be more readable, now characters are moving when more are pressed...
Having them left, they would only move if earlyer-pressed ones are released.
Or keys could maybe keep their position, leaving blanks for released keys? This would probably work for most cases, as pressing many keys at the same time is quite rare.

2.
I would not comma-separate, but give them a background (same as mouse-click?).
Pressing the comma- key would currently look... how?
Pressing keys with longer names like __ctrl__ would currently look how?

**Comment by NickeManarin** [comment]
> Did you try to display bottom-left instead of centered?  

There's a lot of options, like a Caption, + background. :)

> Or keys could maybe keep their position, leaving blanks for released keys? This would probably work for most cases, as pressing many keys at the same time is quite rare.

Or make them go upwards? I think this could be an option.

> I would not comma-separate, [...]

Nice! It needs to be customizable, so you could use any text as separator. This would enable the keys to go upwards by using a new line as separator. I also should add an option to block how many keys can appear at the same time.

> but give them a background (same as mouse-click?).

This feature has the same properties as the Caption + a background option.

> Pressing the comma- key would currently look... how?

Special keys are still being displayed as their internal names, such as Oemcomma. I have to fix this. Should be easy to convert to text. I'm not sure if someone would benefit from using the internal name instead.

> Pressing keys with longer names like ctrl would currently look how?

Modifier keys are attached as their internal names too, with a '+' sign before the normal keys. I have to polish this too, to accept multiple modifiers.

**Comment by NickeManarin** [comment]
![keys 1](https://cloud.githubusercontent.com/assets/14798947/23094999/f6224728-f5e9-11e6-88a3-4b23ebd694e0.gif)

![keystrokes](https://cloud.githubusercontent.com/assets/14798947/23095079/12214e32-f5eb-11e6-8f88-3aeacb60ba03.PNG)

I believe that's it.

**Comment by sirtet** [comment]
Wow, looks nice.  
I thought, that maybe it could be useful if there was a visible difference between the actual key press duration, and the added delay. 
But that could be added later if really needed, right?

**Comment by NickeManarin** [comment]
Right now I'm not capturing the real duration of the key press, I'm just capturing the keys between frame number 1 and frame number 2. 

With that in mind, I did start to implement a viewer/editor to view/edit the keys before applying. So, yes, possible and future feature.

**Comment by neilsustc** [comment]
Great work! 👍

Could you please add some filters such as "ignore single modifier key", "only capture key chords"?

And it could be better to add fade-effect, I guess that will decrease opacity per frame?

**Comment by hughes** [comment]
If you've landed on this issue from a google search and can't figure out how to use this feature:

- you need at least version 2.8.1
- you don't need to enable it before recording
- just click "Key Strokes" on the Image tab after recording

**Comment by kiewic** [comment]
How to display the pressed keys should go into the [FAQ page](https://github.com/NickeManarin/ScreenToGif/wiki/FAQ-%28Frequently-Asked-Questions%29) 😊

**Comment by cavo789** [comment]
Hello guys

If I good understand keystroke recording is possible but I didn't find where. I've installed the very latest version of ScreenToGif (2.23.1) and, when starting the recording, I didn't find "Key Strokes" on the screen. Am I missing something ?

Thanks !

**Comment by NickeManarin** [comment]
@cavo789 Read the comment made by Hughes.

**Comment by cavo789** [comment]
Hello

Better this morning... I've found where to make it happens.

Have read more than once the last comment of Hughes (thanks) but has missing the last and very important part: **after recording**

So, starting the recording already capture keystrokes. 

But we need to "show" them once the recording has been ended. And, to do this, **after recording** we need to go to the `Image` tab, click on the `Key Strokes` and click on `Apply` to make key strokes visible on the captured gif.

Thanks NickeManarin.

(note: did't find in the FAQ how to, seems the page is missing)

**Comment by NickeManarin** [comment]
@cavo789 Yes, the wiki is imcomplete.

**Comment by cavo789** [comment]
@NickeManarin Really no worries, your tool is really, really, really! nice and so much useful.

Now, I know where is the Keystrokes feature ;-)

Thank you Nicke.

**Comment by cool-delete** [comment]
I tried to use the record keyboard button "Key Strokes" on the Image tab click Apply and then prompt

`There 's No KeyStorkes on Your Recording.`


os:win10 20H
version :2.34

**Comment by NickeManarin** [comment]
@cool-delete Were you typying into an application that was running as admin? Or perhaps some other uncommon application?

**Comment by cool-delete** [comment]
> @cool-delete Were you typying into an application that was running as admin? Or perhaps some other uncommon application?
yes ,as admin running app,whether Screer also needs to run as an admin?

**Comment by hunagyp** [comment]
"There 's No KeyStorkes on Your Recording."
This happens to me as well. Situation: I'm running a virtual machine (guest win10 pro, host win11 pro;same physical PC)
VM app: Virtualbox 7.0.6, VM view: scaled/seamless - does not matter.
screen2gif is running on the host. I make all my recordings on the VM's screen area.
Mouse clicks are correctly recorded. But not keypresses. At the end of the recording I get the "There 's No KeyStorkes on Your Recording." message.
Is there any workaround for this?
