### ISSUE TITLE
[Question] Front page source code note

### ISSUE THREAD

**Issue by vatterspun** [NickeManarin/ScreenToGif#430]
Just a question really ... you've got a note on the (not uncommon in open source projects) frustration you're having with someone selling copies of your work.  However, there's an additional statement "That's not why I'm sharing the source code, at all."

Could you clarify on this?  Is ScreenToGif closed source?

I'm certainly fine with you distributing your work in freeware form and I'm hoping you can find a way to share the source code in some format (maybe two versions behind, missing UI elements, etc.), right now the project is on Github and listing an MS-Pl license, which is an open license.

**Comment by NickeManarin** [comment]
The reason why I'm sharing this project as free and open source is to help others. It's great when people use my code in other projects.

What is not great is to get the full source code and share as a paid app (without adding any other features to it, or even by removing most features). 

I mean, I'm here sharing the full project for free...

**Comment by vatterspun** [comment]
Yeah, please close the issue.  I literally misread it as "that's **why I'm not** sharing the the source code at all" rather than "That's **not why** I'm sharing the source code, at all."  My fault.
