### ISSUE TITLE
Suggestion for enable/disable loop playback.

### ISSUE THREAD

**Issue by tomasorti** [NickeManarin/ScreenToGif#434]
Hi!
Congratulations, _**ScreenToGif**_ is **AWESOME**!

I have a suggestion for a new control for **enable/disable loop playback**.
It would be nice that at the right bottom corner.
Where the `SelectFirstFrame/SelectPreviousFrame/Play/SelectNextFrame/SelectLastFrame` are.
If enabled, would behave as it is now.
If disabled, the playback would stop at the last frame.

Best regards!

**Comment by NickeManarin** [comment]
Thank you. :)

**Comment by vatterspun** [comment]
Retested successfully with and without "detect changed pixels".  Thanks!

**Comment by NickeManarin** [comment]
Done, it will be available with v2.19.

![image](https://user-images.githubusercontent.com/14798947/66098055-5ca99f80-e577-11e9-9173-5637a7cf5560.png)

**Comment by neo7BF** [comment]
Actually this setting not working with 2.27.3. Unchecking this, the gif remains in loop.

**Comment by NickeManarin** [comment]
> Actually this setting not working with 2.27.3. Unchecking this, the gif remains in loop in chrome and in Windows Foto. https://i.imgur.com/vnXIpr4.gif

That's not what you think it is. The feature cited on this issue ticket is for the playback, inside the editor.

For saving, it's in the Gif options section of the Save As panel.

![image](https://user-images.githubusercontent.com/14798947/113516338-152b1780-9550-11eb-99a9-4c1e4b43ecdc.png)
