### ISSUE TITLE
Unable to upload Imgur over 20MB

### ISSUE THREAD

**Issue by SinTeKoe** [NickeManarin/ScreenToGif#435]
I am unable to upload any .gif (using the Gifski codec) that is over 20MB. I'm able to save the .gif and upload it manually to imgur as long as its under 200MB (as the help section has noted is the limit on .gifs & video). I've tried looking around for any similar issues but it seems that its just unique to me, so I don't know if I'm just missing something. I am logged in to my imgur account in the app. This is the error I seem to be constantly getting, but an unsure what it exactly means.
![image](https://user-images.githubusercontent.com/7077353/51355781-c5023080-1a7d-11e9-9323-0881d18bfba7.png)

**Comment by NickeManarin** [comment]
The ImgUr API has a limit, if I recall. 
I need to display a better error message when dealing with that.

**Comment by SinTeKoe** [comment]
Ah, alright, I didn't think the API would have different rules then the upload web service.
