### ISSUE TITLE
[Bug] FFMPEG PNG export

### ISSUE THREAD

**Issue by vatterspun** [NickeManarin/ScreenToGif#438]
From the changelog:
> Added FFmpeg as an optional encoder for Apng

While I was working on #426 , I decided to test out the new FFMPEG encoder capability ...

Setup: Win7x86
1. Download portable program and set to local folder (portable)
2. Under Extras, tried pointing to an existing FFMPEG DLL from a few years ago (no luck)
3. Downloaded a fresh copy using the interface in the Extras menu
4. Saved to the local folder (same place as screentogif.exe)
5. Save a brief recording to the local folder

**Defect**: Error msg:

![image](https://user-images.githubusercontent.com/1289134/51432976-9b284580-1c06-11e9-8941-10d807813270.png)

Tried restarting with the same result.  Maybe something from the old FFMPEG DLL is cached?  I can retest and skip step 2 if you need.  I just ran out of time to do a thorough test.

**Comment by NickeManarin** [comment]
Add a space inside the "Extras" text box. I was testing that with and without content, but on the first time is null instead of empty, that's the bug. Thanks for the feedback.

**Comment by vatterspun** [comment]
Ah cool, glad it was an easy fix.  Thanks :+1:

**Comment by 3xploiton3** [comment]
nice, work after 

> Add a space inside the "Extras" text box. I was testing that with and without content, but on the first time is null instead of empty, that's the bug. Thanks for the feedback.

ok, it work, tks

**Comment by NickeManarin** [comment]
This was fixed with 2.17.1.
