### ISSUE TITLE
[Feature Request] Adding emphasis / dimming border (low priority)

### ISSUE THREAD

**Issue by vatterspun** [NickeManarin/ScreenToGif#443]
One way to focus attention in any animation is to dim the area surrounding it.  I got the idea from the program's own Obfuscation tool so I didn't have to mock anything up.  This is present in some commercial packages like Camtasia, but is far from critical in terms of what ScreenToGif provides as a program (there's already highlighter and box drawing tool that mostly do what this describes).

The idea is that you select an area of the screen to call attention to an item or topic (e.g. a series of dates as below).

![image](https://user-images.githubusercontent.com/1289134/51808908-42892600-2260-11e9-9881-7f097883c2c5.png)

You'd draw a box around the and it would selected screens, presumably with a customizable gray level (light gray for subtle to fully black).  The animation would fade to gray on a few slides bordering the first one, then fade back to normal afterwards.

Just an idea.

Related: #311

**Comment by vatterspun** [comment]
I'm going to close this one.  The more I think about it the less I think this is something ScreenToGif really needs.  Feel free to reopen if you disagree.

**Comment by NickeManarin** [comment]
This is a nice idea, let's leave it open.

**Comment by vatterspun** [comment]
> This is a nice idea, let's leave it open.

Thanks :)

**Comment by NickeManarin** [comment]
Done. The obfuscation tools were improved.

![image](https://user-images.githubusercontent.com/14798947/90325313-7ade7b00-df50-11ea-9179-fc48db6bbcbe.png)

![1](https://user-images.githubusercontent.com/14798947/90325325-98134980-df50-11ea-8ae3-fd6ebabe99e7.png)

You can now add dark or light spots (or the inverse of that).

![1](https://user-images.githubusercontent.com/14798947/90325332-a9f4ec80-df50-11ea-9541-cba7eec76e01.png)

**Comment by vatterspun** [comment]
:) Hey, glad you liked that idea.  Thanks!
