### ISSUE TITLE
[Feature request] Progress Bar - Text > Current date and time (low priority)

### ISSUE THREAD

**Issue by vatterspun** [NickeManarin/ScreenToGif#444]
**Feature**: One alternative to adding a time code progress bar would be the actual time (and date) of the recording *live*.

**Why?** I occasionally submit bug reports using ScreenToGif just to make sure I everyone sees just exactly what I did to cause an issue.  This would primarily help with showing either a process failed *because* it was run at a certain time or let developers/admins explain why it failed (e.g. server was offline, Internet was down, etc.).

![image](https://user-images.githubusercontent.com/1289134/51884173-b2280f80-234b-11e9-8be9-1c562e7b1746.png)

I got the idea from a ShareX request: https://github.com/ShareX/ShareX/issues/3782 ... and there's also a static version of this for just any old Windows title bar: http://www.whisperingpinessoftware.com/tbdt.html (freeware).

**Comment by WELZ-gh** [comment]
Good idea, but maybe there should be options for time format and time zone (it should also display the time zone)

**Comment by vatterspun** [comment]
> maybe there should be options for time format and time zone

Multiple tech support people I work with are in another time zone.  I didn't think of that.  Good suggestion.

**Comment by NickeManarin** [comment]
Done!

It will support all kinds of formats available right now in the .Net Framework.
You can display the end time of the gif too.

![image](https://user-images.githubusercontent.com/14798947/54076376-e0bdd200-4289-11e9-846f-337b3739afaa.png)

Formats:
https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings
https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings

**Comment by vatterspun** [comment]
Nice!  Thanks :)
