### ISSUE TITLE
save as video formats

### ISSUE THREAD

**Issue by mammadkoma** [NickeManarin/ScreenToGif#446]
Hi and thank you for your great app
Is it possible to save as to other video format like mp4?
It just get avi and most sites doest not support avi like instagram.
mp4 format is great.

**Comment by mammadkoma** [comment]
Yes I found where I can download ffmpeg.exe :
https://www.youtube.com/watch?v=xcdTIDHm4KM

**Comment by vatterspun** [comment]
Is it possible to save as to other video format like mp4?

Yes, it's under the Video - FFMPEG menu.  There's a dropdown menu for MP4 next to the file name:

![image](https://user-images.githubusercontent.com/1289134/52168733-1ef82c80-26f3-11e9-9571-754811016bd9.png)
