### ISSUE TITLE
Unable to run the Application on my Win XP, 32-bit edition.

### ISSUE THREAD

**Issue by saurabhdua82** [NickeManarin/ScreenToGif#45]
![clipimage](https://cloud.githubusercontent.com/assets/23373249/20860006/3345e444-b994-11e6-8d42-08db380e864f.jpg)

Hello There!

Please refer to the enclosed pictorial description & help figure out the cause behind this Error message?
Iam trying to use your Application on my Win XP, 32-bit edition.
Inputs will be sincerely appreciated.

Thank you.

**Comment by NickeManarin** [comment]
System requirements: Vista or superior.
https://github.com/NickeManarin/ScreenToGif/wiki
