### ISSUE TITLE
How to use the screen magnifier?

### ISSUE THREAD

**Issue by Stanny2017** [NickeManarin/ScreenToGif#450]
I just do not know how to magnify my screen to show the detail position, anyone can help me?

**Comment by WhiterunLydia** [comment]
![2019-02-12_213158](https://user-images.githubusercontent.com/47240078/52639843-29df6800-2f10-11e9-85ec-ab22ea4a80fd.png)
You can try the new version of the recorder interface, you can display the coordinates of the focus, but it is not easy to use now, I hope to support the keyboard direction button adjustment, mouse drag and drop is not accurate and easy to make mistakes.

**Comment by NickeManarin** [comment]
>  I hope to support the keyboard direction button adjustment

I just implemented that. It will be available with v2.17

Also, I'm closing this since it was already answered.
