### ISSUE TITLE
Can't type when screen recorder is on

### ISSUE THREAD

**Issue by karimcambridge** [NickeManarin/ScreenToGif#452]
Whenever I turn on the screen recorder and select a window, the keyboard goes into a different mode where keys are basically commands like r turns into run... Right now my backspace and delete isn't working and enter is literally enter and not adding a new line lol.. how to turn this off?

-- Only way to fix is by restarting, see it even made me accidentally make 2 issues

**Comment by NickeManarin** [comment]
That's a strange bug... Are you starting the recording by pressing a shortcut key or by pressing the Record button?

**Comment by karimcambridge** [comment]
I was using shortcut key

Win10, latest

**Comment by NickeManarin** [comment]
Maybe that activated a mode in your keyboard. Try using the record button to see if it works normally.

**Comment by karimcambridge** [comment]
I don't think so. The key was like f11 or something, that isn't activating anything.

**Comment by NickeManarin** [comment]
So, any news on this issue?

**Comment by karimcambridge** [comment]
I gave up and moved to a different program, sorry. The issue was predominant.

**Comment by NickeManarin** [comment]
Ok, which program did you try to record anyway?
Which recorder did you use? Old or new?

**Comment by NickeManarin** [comment]
This behavior sounds like the Sticky Keys feature, from windows.
When enabled, pressing R opens the Run command directly without having to press the Windows key.
The same happens with the E key, it opens the Explorer directly.

You can see if you enabled the Sticky Keys by accident or by using any other software, by opening `Windows Settings > Ease of Access > Keyboard`.

**Comment by karimcambridge** [comment]
I'm not sure, remember I created this issue months ago.

Thanks
