### ISSUE TITLE
Feature Request: Add progress bar for Remove duplicate frames

### ISSUE THREAD

**Issue by Crashnorun** [NickeManarin/ScreenToGif#456]
When a users selects to remove duplicate frames and clicks _apply_ there is no visual indication that the application is still active / processing. It would be great if there was some form of a visual cue.

There are two options that come to mind:

1. A progress bar identifying how many frames have been analyzed vs remaining. For example if a recording contains 100 frames the progress bar would be from 1 - 100 and as the application starts to analyze frame 2, the progress bar would read 2%. As the application analyzes frame 3, the progress bar would read 3%, etc.
2. An [undeterminate progress bar](https://material.io/design/components/progress-indicators.html#)

Great application!! Thanks for your support.

**Comment by NickeManarin** [comment]
Thanks! I forgot to implement that.

**Comment by NickeManarin** [comment]
Done. It will be available with the next release.

**Comment by Crashnorun** [comment]
Awesome! You rock!!
