### ISSUE TITLE
[Bug] Source array not long enough

### ISSUE THREAD

**Issue by vatterspun** [NickeManarin/ScreenToGif#458]
I'm generating a screenshot slideshow similar to the steps described in #426 ... oddly today I started getting an error:

Setup: Win7x86
Steps:
1. Grab some screens of various sizes with Greenshot
2. Load into STG, add a progress bar and a watermark
3. Save as weither GIF or APNG

Defect:
![2019-03-02 22_17_11-exception viewer](https://user-images.githubusercontent.com/1289134/53690914-f76ba280-3d38-11e9-8a7e-54704fa49ce3.png)

Attempted workarounds: I tried deleting the watermark but no difference.

**Comment by NickeManarin** [comment]
Are the pictures the same size? If you can share the pictures I can fix this bug, Thanks.

**Comment by vatterspun** [comment]
Sorry for the delay on this, having some system issues that are preventing a re-test.

**Comment by NickeManarin** [comment]
It's alright. :)

**Comment by NickeManarin** [comment]
Can I close this issue? I'm not sure if it still happens.

**Comment by NickeManarin** [comment]
Closing this issue as inactive. I believe this issue should not happen anymore, 
I added some checks when importing frames with different sizes.
