### ISSUE TITLE
Cannot Compile From Clone

### ISSUE THREAD

**Issue by trebleCode** [NickeManarin/ScreenToGif#461]
Attempting to clone and build the solution in VS 2015 results in thousands of errors on dozens of controls, and roughly a dozen between HookTest and the TranslatorWindow.xaml.cs

Most errors on the controls are where brackets or semicolons are expected, and a few about getters/setters expected.

All but one from the tests are related to P/Invokes.

This is after restoring NuGet Packages and not performing any updates on the testing components.

Then: Build > Build Solution

Build debug log was too long to post, link below:

(https://pastebin.com/fwXcuvZy)
```

**Comment by NickeManarin** [comment]
C# 7 is required for this project.
https://github.com/NickeManarin/ScreenToGif/wiki
