### ISSUE TITLE
Is encoder gifski only work just for windows x64 but not x86?

### ISSUE THREAD

**Issue by GrennKren** [NickeManarin/ScreenToGif#462]
Basically why I asking this because I've tried convert video into gif with gifski encoder, but didnt work in my Windows 7 x86 but successful in windows 10 x64.

What error I got is this
![1](https://user-images.githubusercontent.com/34759917/54072254-568a6380-42b3-11e9-97e3-95a8032c74cf.jpg)

Other than that, I was also tried using gifski executable version in windows 7 x86.
![2](https://user-images.githubusercontent.com/34759917/54072280-a5d09400-42b3-11e9-8b7e-2abacd336ae2.png)
"...Not compatible with version of windows you're running. Check your computer's system information to see whether you need a x86 or x64 version of program..."

Thank you

**Comment by GrennKren** [comment]
more than 2 weeks still no one reply. So that mean, the answer is yes

**Comment by NickeManarin** [comment]
The latest version of ScreenToGif uses a Gifski DLL instead of the executable. 

Open Options > Extras and download Gifski via the download button.

**Comment by GrennKren** [comment]
Looks like I'm not clear enough to describe. I used encoder gifski DLL version from ScreenToGif option, didn't work. Then I tried with executable version..

**Comment by NickeManarin** [comment]
Oh, you didn't mention that on the first message. Anyway, I don't have a Windows 7 (32 bits) machine right now. So I can't test if it's something that can be fixed, sorry. :(

**Comment by GrennKren** [comment]
Yeah it's okay. The bug is not big deal for me, I can just use my windows x64

**Comment by tuchit** [comment]
me
windows 10 x64
gifski encoder doesn't work
neither gifski.dll nor gifski.exe
