### ISSUE TITLE
Adding Frames blurr the existing frames

### ISSUE THREAD

**Issue by ghost** [NickeManarin/ScreenToGif#463]
Hi, i have a problem with blurred Frames.
When i try to add small scenes (1-5 frames) to my project, i have an issue that the existing frames become blurred. It get worse from picture to picture. 

The problem is easy to reproduce: Simply add images frame by frame (snap mode or normal) then look at the previous ones.

I found out that the issue did not exist in version 2.12.1

![BSP](https://user-images.githubusercontent.com/38536525/54211818-3d1b2e80-44e2-11e9-8bae-429d8fee2e0e.gif)

Sorry for my bad english :)

**Comment by vatterspun** [comment]
Can you try exporting your project to APNG format to see if it's any different?

**Comment by NickeManarin** [comment]
@serJOOga Would you mind to share the project and the frames that you are trying to insert? If so, you can email me at nicke@outlook.com.br

**Comment by NickeManarin** [comment]
Closing as inactive.

Try using the latest version, v2.26.1 or send to the images that you were trying to import.
It looks like it was an issue with images having different DPI, an issue which was fixed with the current available version.
