### ISSUE TITLE
Cannot capture keystrokes on Visual Studio

### ISSUE THREAD

**Issue by MithrilMan** [NickeManarin/ScreenToGif#465]
Hey nice project dude!

I'm using latest version 2.16,I tried this utility to capture a screen to show a colleague how to "find by reference", and I recorded me in a small area while I was pressing SHIFT+F12 in Visual Studio, then I went to the Image and clicked on Image, then KeyStroke and Apply and the program complained it didn't had keystrore
![image](https://user-images.githubusercontent.com/5107375/54427511-fc5a2a00-471a-11e9-8b00-94683cb6c4ad.png)

I tried even typing some test but no luck... then I tried to capture keys on notepad and it was working... so there must be something wrong with the capture utility that doesn't capture keys when using some program, any clue?

**Comment by NickeManarin** [comment]
I was able to capture my **Shift+F12** key strokes (with the older and with the newer recorder).

Maybe something else is blocking the capture, like a VS extension or if VS was running with admin rights (_try running StG with admin rights too, if that's the problem_).

![image](https://user-images.githubusercontent.com/14798947/54465146-6e049900-4758-11e9-9d9a-08768cb359d4.png)

**Comment by MithrilMan** [comment]
>  or the fact that VS was running with admin rights

ah-ha!
that was the problem, thanks!
good job!

**Comment by NickeManarin** [comment]
> Is this by design or could be fixed?

It's by design by Microsoft. I can't access a key or mouse events set to a window opened with admin rights if ScreenToGif itself is not launched too as admin.

So, the only way to fix it is to launch my app as admin too.
