### ISSUE TITLE
Req: blur next to pixelate

### ISSUE THREAD

**Issue by awrog** [NickeManarin/ScreenToGif#466]
I really love ScreenToGif, the possibilities and results are great.
I'd like to file a request for (Gaussian) blur next to pixelate.
Pixelate is nice, but in some cases the screens are being affected too much. 
At the moment I take care of blurring outside ScreenToGif, using imagemagick, but that is very time consuming and error prone.
An adaptable blur in ScreenToGif would make it look even more professional!

Keep up the good work and thanks!

**Comment by NickeManarin** [comment]
Thanks, nice idea. :)

**Comment by vatterspun** [comment]
> An adaptable blur in ScreenToGif would make it look even more professional

If you could figure out how to do it with a range or a gradual blur, that would also be useful to not just help block elements that are confidential/private but also focus the user on what you want them to look at.  With lots of simple demo videos an important facet is focusing the user on the area that's important.  Usually you can do that with arrows and red boxes, but blurring is sometimes useful especially with interfaces that have loads of elements or are very colorful.

Examples:

With PDF SAM, a very light blur on the surrounding elements helps focus the eye on the left side of the screen:
![image](https://user-images.githubusercontent.com/1289134/54481555-1ae82000-4804-11e9-8a88-30cad26f3ab0.png)

Discord's interface meanwhile is sometimes so colorful it's hard to find what you're looking for:
![image](https://user-images.githubusercontent.com/1289134/54481649-736bed00-4805-11e9-83be-df4a927415ed.png)

**Comment by awrog** [comment]
I would be perfectly content if ScreenToGif would make use of the imagemagick engine (dll).
The possibilities would be endless!

**Comment by NickeManarin** [comment]
Done. You can also apply all obfuscation methods to the inverse of the selection.

![image](https://user-images.githubusercontent.com/14798947/90325489-9e0a2a00-df52-11ea-9f5b-9da67db75b29.png)

Examples:

![1](https://user-images.githubusercontent.com/14798947/90325440-0ad0f480-df52-11ea-8e03-5d1e20faff3d.png)

![1](https://user-images.githubusercontent.com/14798947/90325446-1c1a0100-df52-11ea-8245-d2b5813d90e6.png)

![1](https://user-images.githubusercontent.com/14798947/90325454-35bb4880-df52-11ea-80b4-326a46613acd.png)

![1](https://user-images.githubusercontent.com/14798947/90325459-47045500-df52-11ea-9df2-157811c9c3bd.png)

Pixelated with smoothened edge:
![1](https://user-images.githubusercontent.com/14798947/90325472-68654100-df52-11ea-8683-10a02e023da8.png)

**Comment by vatterspun** [comment]
> Done. You can also apply all obfuscation methods to the inverse of the selection.

Nicely done - a lot more than was requested.  Thanks :)
