### ISSUE TITLE
gifski integration

### ISSUE THREAD

**Issue by musm** [NickeManarin/ScreenToGif#467]
I installed gifski  via `cargo install gifski` however it does not build the shared library. 
How can I get gifski to work with screentogif ? 

The gifski binaries that are downloadable also do not include the shared libraries.

**Comment by GrennKren** [comment]
you can just use download gifski libraries option inside Screentogif

**Comment by NickeManarin** [comment]
ScreenToGif uses the DLL of Gifski instead of the executable. So, in order to use you need to download the DLL via the download button inside Options > Extras.

**Comment by musm** [comment]
Fair enough, why not just include the dll's by default?
