### ISSUE TITLE
ScreenToGif  is not working on computer with two screens

### ISSUE THREAD

**Issue by AJLoveChina** [NickeManarin/ScreenToGif#469]
ScreenToGif  version : 2.16
My computer :  Windows 10 pro 64bit

What is this issue ?
I have two screens on my computer, one is lenovo and the other is Dell.
When both screens are working, the screenToGif is not working.  It can be opened, but it cannot show capture area, a simple word, just cannnot capture screen to gif.

The result : 
For now, if i want to use ScreenToGif , I must turn off one screen on my computer, then it works.
It's not a happy experience.

**Comment by NickeManarin** [comment]
Try this:

Open ScreenToGif and locate the app icon on your system tray. 
Right-click the icon and open the "Troubleshoot".

Click in "Move all windows to the main screen".
Then select the second option "Here's where your windows will open next time" and click to reset.

![image](https://user-images.githubusercontent.com/14798947/54880049-47f98b80-4e1f-11e9-860b-541eaf8d651c.png)

**Comment by AJLoveChina** [comment]
It works great! Thank you ❤️  @NickeManarin
