### ISSUE TITLE
[Feature Request] Ability to remove every X frames (file size)

### ISSUE THREAD

**Issue by vatterspun** [NickeManarin/ScreenToGif#47]
**Background**: Many GIF files have lots of unnecessary frames that aren't required for demonstrating a process such as clicking start menu, choosing Run, and entering a command.  As a result, you have a detailed GIF that's much larger than it needs to be.

**Solution**; Automatically removing every 2nd, 3rd, or [insert number] frame can help cut down on the overall size of an animation without loosing the content.

To avoid making the process go by too fast, it may also be wise to include options to increase the framerate delay slightly.

**Workaround** (manual method): open the editor and press the left arrow key and then click delete for the length of the file.  Then, select all frames and click "Increase or Decrease" Delay and add 5-10 ms.

---

I'm happy to mock something up if this sounds like a useful feature.

**Comment by NickeManarin** [comment]
Feature named as "Reduce Frame Count", inside the **Edit** tab and grouped inside **Frames**.

**Comment by vatterspun** [comment]
Outstanding!  Thanks :)

**Comment by NickeManarin** [comment]
Done! Give it a try [ScreenToGif 2.5 Preview](https://github.com/NickeManarin/ScreenToGif/files/749222/ScreenToGif.2.5.Preview.zip)

**Comment by vatterspun** [comment]
> Done! Give it a try ScreenToGif 2.5 Preview

Outstanding 👍   Thanks!

**Comment by vatterspun** [comment]
On a side note, I used your program to generate a bug report:

https://i.imgur.com/YzXNcQ2.gif

Bug report: https://github.com/ShareX/ShareX/issues/2266

I didn't have a chance to test this new feature when I was building that, but I did use your program and the manual (workaround) process above to create it.  Thanks!

**Comment by RudeySH** [comment]
Is there any away to apply this operation to a selection of frames, instead of all frames?

**Comment by NickeManarin** [comment]
@RudeySH No... Open a new issue ticket with that feature request. :)

**Comment by blackcat31797** [comment]
> Feature named as "Reduce Frame Count", inside the **Edit** tab and grouped inside **Frames**.

That's very helpful, thanks a lot <3

**Comment by jokerfyy** [comment]
收到啦，请放心，我马上就会看的
