### ISSUE TITLE
Program usage examples

### ISSUE THREAD

**Issue by vatterspun** [NickeManarin/ScreenToGif#472]
Another STG call-out for a program demo:
https://www.portablefreeware.com/forums/viewtopic.php?p=92940#p92940

Also this isn't from STG, but if anyone ever suggests that programs like this aren't worthwhile, see HP's universal printer download page: https://support.hp.com/us-en/drivers/selfservice/closure/UPD/4157320/model/4157320 seen by millions of people every year.  Short animations with very small, clear videos that STG can create are often the best way to explain basic processes.

(Please close this case, it's just for documentation / reference / your amusement.)

**Comment by NickeManarin** [comment]
Thank you for sharing it :D

**Comment by vatterspun** [comment]
> Thank you for sharing it :D

Glad that helped.

I actually came across another example of short, cycled animations.  Note that because of the quality and and frame rate, these are huge **GIF** files (almost 2 megs apeice).  This is a great use case for ScreenToGif as it could have edited these _without quality loss_ to reduce overall page size:

https://www.toptal.com/finance/financial-consultants/powerpoint-presentation-tips-and-hacks
