### ISSUE TITLE
Deactivate Recent Projects

### ISSUE THREAD

**Issue by Japamam** [NickeManarin/ScreenToGif#477]
Hi. So there's some way to not have recent projects saved, i mean deactivate the functionality.
I need this for privacy reasons. 
I delete the files of my work after  i finish but they can still be acessed by the recent projects tab.
If there's not a way plz inform and well if you think it's a good idea you can implement that.

**Comment by NickeManarin** [comment]
You can simply discard each project. They will disappear from the list.

You can also erase the entire temporary folder (the one set under Options > Temporary files).
