### ISSUE TITLE
Blur out areas of screen when editing?

### ISSUE THREAD

**Issue by colinwurtz** [NickeManarin/ScreenToGif#48]
First of all, thanks for your work on this, it's great! Guessing this is an enhancement, but is there a way blur out certain regions of the screen in edit mode? Greenshot[0][1][2] has this ability and would be very useful in ScreenToGif. 

Here's an example of what I mean:

![greenshotdemo](https://cloud.githubusercontent.com/assets/3066044/21406293/6cbe4c02-c790-11e6-81c9-4c40d66f5231.gif)

By the way, when I tried to send feedback through the application it froze when I clicked send and I had kill it manually.

[0]https://github.com/greenshot/greenshot
[1]http://getgreenshot.org/help/#editor-obfuscate
[2]https://github.com/greenshot/greenshot/blob/6f30b68e5737f9d8f23201e0aba7726b62e873a2/Greenshot.Addon.Editor/Drawing/ObfuscateContainer.cs

**Comment by NickeManarin** [comment]
Thanks for the feedback :D
The only way to censor information could be with the FreeDrawing tool (you can select multiple frames to apply).

This feature is possible to implement, I'll add to my list.

Also, the Feedback tool takes a little bit to send because it relies in an e-mail service. Sometimes it does not even work because people try to access the e-mail and it gets blocked. **Not sure why people do this.** :/

**Comment by tilight** [comment]
Push the blur function 👍

**Comment by spottedmahn** [comment]
Hey @NickeManarin - where does feature site in the backlog?  It sure would be handy.

Perhaps you can task it out and the community could help get this implemented?

**Comment by NickeManarin** [comment]
Currently my priority is fixing the bugs that were reported by users during this week. 
But afterwards I can start working on this feature.

I've started researching for some framework method that could find anything ready to use, so I'm probably going to work with the same method that I developed for the old version of the app. It should be easy.

**Comment by spottedmahn** [comment]
@NickeManarin nice ⚡️ !

**Comment by NickeManarin** [comment]
Done! The feature is called "Obfuscate":

Select the rectangle that should be pixelated:
![image](https://user-images.githubusercontent.com/14798947/33509000-2713d586-d6e5-11e7-865a-4a0ee837e9ab.png)

Apply:
![image](https://user-images.githubusercontent.com/14798947/33509010-3d2282d2-d6e5-11e7-91ff-74104dd524da.png)

**Comment by colinwurtz** [comment]
Awesome, looks great! Thanks for all your work on this.

**Comment by spottedmahn** [comment]
awesome 💥 thanks @NickeManarin !! 🎉

**Comment by dogancelik** [comment]
I'd like to request (Gaussian) blur in addition to pixelization. (also mentioned in #194)
