### ISSUE TITLE
Move

### ISSUE THREAD

**Issue by tiotdiz** [NickeManarin/ScreenToGif#480]
II like it, but not all of it.I need to move the windows when I record the chosen screen.

**Comment by tiotdiz** [comment]
I got it,I can drag the window when I use the old record UI,not the new one.
But there is another issue,I can't change the size of the window once I start recording,even I pause it.

**Comment by vatterspun** [comment]
> But there is another issue,I can't change the size of the window once I start recording,even I pause it.

Would it be possible to start with a larger window and then modify/crop the window after recording in the editor?

**Comment by NickeManarin** [comment]
It's not possible to resize the recorder window after starting the recording. Closing as it's a duplicate.
