### ISSUE TITLE
IS this windows only? works on linux?

### ISSUE THREAD

**Issue by ppazos** [NickeManarin/ScreenToGif#481]

**Comment by vatterspun** [comment]
Linux requests:
#192 
#34 
#9 

Mac request:
#29

**Comment by ppazos** [comment]
@vatterspun is that yes or no?

**Comment by NickeManarin** [comment]
@ppazos Yes, windows only. It relies on WPF, which is not crossplatform.

**Comment by vatterspun** [comment]
> @vatterspun is that yes or no?

lol
