### ISSUE TITLE
Installer has issues with high DPI

### ISSUE THREAD

**Issue by linshuhe** [NickeManarin/ScreenToGif#483]
<img width="330" alt="Snipaste_2019-05-12_08-58-10" src="https://user-images.githubusercontent.com/11469461/57576526-1bafd200-7494-11e9-9a6c-ee59d99b87ab.png">

**Comment by NickeManarin** [comment]
Can you tell me which DPI/Scale is your desktop set to?
I tested with 125%, 150%, and 175%, it looks good for me.

Also, are you using the latest version of the installer?

**Comment by NickeManarin** [comment]
@linshuhe Hi

**Comment by NickeManarin** [comment]
I'm closing this as it is inactive.
Also, ScreenToGif has a new installer.

#563
