### ISSUE TITLE
希望能增加在录制时拖动（移动）录制区域窗口的功能。（Added a button to move the area recording window）

### ISSUE THREAD

**Issue by XZPQNBV5** [NickeManarin/ScreenToGif#484]
软件非常棒，希望能增加在录制时拖动（移动）录制区域窗口的功能。

**Comment by XZPQNBV5** [comment]
> 软件非常棒，希望能增加在录制时拖动（移动）录制区域窗口的功能。

![image](https://user-images.githubusercontent.com/50760834/57964617-8c5e5f00-796a-11e9-9f24-1c0b091e7c83.png)
在区域录制窗口中加入类似图中箭头所指的按钮，可以在录制是移动录制窗口。

**Comment by vatterspun** [comment]
I'm on the older version (the old version 2.16) and had to enable the New UI by going into Options - Application - Enable the New Recorder UI.

The old UI let you drag the recording window via the frame, this function (or something like it) would allow moving the recording window around the screen.  Good suggestion.

**Comment by eamodio** [comment]
I would love it if you were able to move/resize the selection window like you can with [Lightshot](https://app.prntscr.com/en/)

**Comment by NickeManarin** [comment]
Done, with the newer UI, you'll be able to click to move the selection rectangle during capture.
It's optional, but enabled by default.

![image](https://user-images.githubusercontent.com/14798947/89720403-1d728900-d9a8-11ea-8d3f-8f489dd35861.png)


I'm also making some changes to the other part of the UI.
Also optional, you can revert to the more compact UI.

![image](https://user-images.githubusercontent.com/14798947/89720386-f451f880-d9a7-11ea-9390-3c183f9e3615.png)

(It's the small part near the bottom right corner of the selection rectangle, it changes position when hidden by the screen)
