### ISSUE TITLE
Gitter link directs to Facebook

### ISSUE THREAD

**Issue by matt-clegg** [NickeManarin/ScreenToGif#486]
**ScreenToGif v2.17.1**

The Gitter link on the Options->About page directs to the Facebook link.

![ac1802b7-c173-4d94-bfa4-4e1f87b5f33f](https://user-images.githubusercontent.com/34515355/58315690-ea2af500-7e09-11e9-9bf4-588916e24eba.gif)

See here:
https://github.com/NickeManarin/ScreenToGif/blob/b49d298095b4357309cb40862c279c5c40912295/ScreenToGif/Windows/Options.xaml#L1422-L1424

**Comment by vatterspun** [comment]
Good catch.

**Comment by NickeManarin** [comment]
Fixed. Thanks. :)
