### ISSUE TITLE
Old way to draw rectangle?

### ISSUE THREAD

**Issue by GsHeri** [NickeManarin/ScreenToGif#488]
Hi there, i just downloaded the new version after having used an older one for about 2 years on my laptop. 
i immediately noticed the "click-drag" way to designate the recording rectangle is gone, and i REALLY miss it.
is there a way to get it back on the current release, or will i have to get an older version?
it's super tedious to have to reposition/resize the whole window if i could just drag a square in 0.5 sec before

sorry if i missed something obvious :)
thanks!

**Comment by NickeManarin** [comment]
I'm sorry, but which version are you writing about?

If I remember correctly, all recording features from v1.4.2 were implemented to the new versions (v2 and newer).

**Comment by GsHeri** [comment]
2.17.1
and i have to say: you're absolutely right. i found it in the meantime (or better... it just came by accident)

when i opened it for the first time today, there was only one big transparent window with a + button on the bottom, where i could attach the recorder to a window, and no way to draw a rectangle.

i then closed the program, and opened it again, and everything looked as i knew it.
so i'm not sure now if that was a bug or a new feature or a new recorder view that i have opened by accident?

**Comment by NickeManarin** [comment]
The new recorder needs to be activated by opening the Options window. But the settings could be lost and reset. Maybe that's what happened.
