### ISSUE TITLE
导入视频的功能没有合理的错误处理

### ISSUE THREAD

**Issue by wybb** [NickeManarin/ScreenToGif#490]
_upperPlayer.MediaOpened += UpperMediaPlayer_MediaOpened;
                    _upperPlayer.MediaFailed += (s, ex) => 
                    {
                        //增加错误处理
                    };
                    _upperPlayer.Open(file);
                    _upperPlayer.Pause();

**Comment by wybb** [comment]
假如电脑上没有安装MediaPlayer就会触发错误，但是ScreenToGif并没有做相关处理

**Comment by NickeManarin** [comment]
Yes, I need to add a warning explaining that the loading failed. Also, I want to use FFmpeg when possible to load the frames if the default media player is not installed.

**Comment by NickeManarin** [comment]
Done. If the media fails to load. The app will warn the user.
