### ISSUE TITLE
Video export FFmpeg options extras should saved

### ISSUE THREAD

**Issue by awrog** [NickeManarin/ScreenToGif#492]
The default video export tot FFmpeg uses: 
`-c:v libx264 -pix_fmt yuv420p -vf "pad=width={W}:height={H}:x=0:y=0:color=black"`
I would like to change that to get a better result.
My changes are not saved in Settings.xaml
Is it possible to save what I enter?

![Screenshot - 6_24_2019 , 10_43_15](https://user-images.githubusercontent.com/12153667/60004460-f5717a80-966c-11e9-86a4-85c401f804c3.png)

**Comment by NickeManarin** [comment]
The app should be saving when getting closed.
Unless there's a problem and it's failing to do so. Do you mind taking a look at the Logs folder to see if there's any exception when reaching the UserSettings part of the code?
