### ISSUE TITLE
Automated Tasks does not work

### ISSUE THREAD

**Issue by Stargazer2576** [NickeManarin/ScreenToGif#493]
Hello,

I have added a task to set delay to 100 ms, but nothing happens after I stop a recording or opening a project.

![Image64](https://user-images.githubusercontent.com/51511827/60193852-99198100-984d-11e9-97f2-fa80c0fd0768.jpg)

Thanks a lot

**Comment by NickeManarin** [comment]
Fixed. Thanks!
