### ISSUE TITLE
[Bug] ArgumentNullException in Translator

### ISSUE THREAD

**Issue by Hyo-Seong** [NickeManarin/ScreenToGif#494]
Now I'm translating to Korean, but bugs in the program.
This is the situation when Exception thrown.
App Start-> Open -> Export -> Export -> scroll down datagrid(BaseDataGrid)
this is error message => System.ArgumentNullException: 'Value cannot be null.
Parameter name: item'

I dont know why this exception thrown...
Because this Exception has no details

**Comment by NickeManarin** [comment]
Download the new version of the translator. 
If the same error appear, send me the exception details.

**Comment by NickeManarin** [comment]
Closing as inactive.
