### ISSUE TITLE
添加设置gif文件大小的功能

### ISSUE THREAD

**Issue by 15678871232** [NickeManarin/ScreenToGif#495]
有些网站上传图片文件大小有限制，如最大300k.
有时候录制文件超过 300k，上传不了网站。

期待保存时可以设置保存gif文件的大小，如设置300k，并能自动移除重复帧。

**Comment by NickeManarin** [comment]
There's already an automatic process that removed duplicated frames and also there's a feature in which you can remove similar frames too.

But setting a limit for how big the can should be would be too difficult with the way it works today.
