### ISSUE TITLE
GIF v1.0 v2.0 and System not Facebook compatible

### ISSUE THREAD

**Issue by svenbieg** [NickeManarin/ScreenToGif#497]
I tried to record my screen and to upload it to Facebook, but Facebook doesn't accept the source.

**Comment by vatterspun** [comment]
I tried to do some research on what might be causing this but all the links I came up with required a Facebook login, which I don't have.  As a workaround, I'd suggest uploading to Imgur or similar sites and just providing a direct link.

**Comment by NickeManarin** [comment]
I've tested v1 and v2, they both work normally. But I only tested a small, less than 1Mb file.
What's the size of your gif? I believe that Facebook has a limit.

**Comment by svenbieg** [comment]
I can't tell, but there was no message about the size. The format had not been accepted, i did try all different settings.
ScreenToGif was the first tool i could find on the web, it was too bad it didn't work!

**Comment by NickeManarin** [comment]
Can you try out smaller sizes? 
If so, make sure to use the latest version.

**Comment by svenbieg** [comment]
I'm sorry it took so long. It is working now, i tried v1 and v2.
