### ISSUE TITLE
Temp. files of board recording aren't removed by 'Clear Temp. Folder' + etc

### ISSUE THREAD

**Issue by asdf1324** [NickeManarin/ScreenToGif#5]
I got some files left in C:\Users\[Username]\AppData\Local\Temp\ScreenToGif\Recording after cleaning Temp. folder.

![capture_2016_08_19_13_10_39_1](https://cloud.githubusercontent.com/assets/19871820/17798711/b656544c-660e-11e6-9d5f-55eb2c753082.png)

Seems like Temporary files created with board recording.. maybe.

Also I got error when using editor, trying to undo 3 frames which deleted by Edit - Frames - Delete. Exception viewer opens up and it says cannot find files in ActionStack folder... I didn't touched anything in Temp. folder before this error happened.

[logs.txt](https://github.com/NickeManarin/ScreenToGif/files/426301/logs.txt)

Thanks.

**Comment by asdf1324** [comment]
+ Can't use program when cancel inserting gif files into existing project. I can see the progress bar on Left-bottom of program, but it does not moves anymore.
![capture_2016_08_19_14_06_07_1](https://cloud.githubusercontent.com/assets/19871820/17799499/1cc151a8-6616-11e6-9732-a0e3b8ba1abd.png)

**Comment by NickeManarin** [comment]
I fixed the first and third bugs. The second one I could not reproduce. Do you think it has something to do with the fact that it was a board recording? (since the board cache files were stored in a wrong folder)

**Comment by NickeManarin** [comment]
The second bug is fixed. Thanks 😄
