### ISSUE TITLE
How can we record sound from microfon as well?

### ISSUE THREAD

**Issue by MonsterMMORPG** [NickeManarin/ScreenToGif#50]
Is that possible?

**Comment by sirtet** [comment]
The GIF format does not support audio, just images.

So this would be usable only for the avi export option. 
Thus i guess this might be out of scope for this Project...

**Comment by MonsterMMORPG** [comment]
@sirtet  yep of course i am talking about video exporting :D

**Comment by NickeManarin** [comment]
@sirtet Yes, it's a bit out of scope right now.

**Comment by thshdw** [comment]
+1 for capturing the mic. The editor is nice and for making quick tutorials audio capture would be ideal.

**Comment by manishcihbba** [comment]
+1 for capturing the mic

**Comment by chrisrusso** [comment]
+1 for capturing the mic.

**Comment by ADTC** [comment]
@NickeManarin please reconsider? I got delighted by how much ScreenToGif has grown when I upgraded from 2.12 to 2.27.3 after a long time of using the older version. There are so many more options now, the interface is better, there's dark theme, and all of that. I really think being able to add sound either when recording the frames or as an added overlay later when editing the frames would be **a huge really helpful new feature**, even if it's a simple audio track. I'm sure FFmpeg has the ability to add the track to the exported video. Of course, more serious editing should be done on the exported video using a proper video workstation. But a single audio track will get the easiest types of audio inclusion done. (Examples: narration or background music)

**Comment by NickeManarin** [comment]
This is a planned feature, but first I need to rework the editor, to support multiple tracks.

**Comment by TishSerg** [comment]
Any update on this?
I can record video, but can't capture audio. That's disappointing. 
I know the app's original purpose was to record GIFs, but now, when we can export it as video, why not add an audio capture ability?

**Comment by TishSerg** [comment]
Ahh, nevermind. I took a look at https://github.com/NickeManarin/ScreenToGif/issues/423

**Comment by qqxiaoteng** [comment]
how to recoerd sound?

**Comment by SlugFiller** [comment]
IMO an editor revamp is unnecessary. Just attach an audio sample to each visual frame on the same timing. Deleting a frame would cut out the matching audio.

This may sound limiting, but remember that it's always possible to export the video from ScreenToGif, and then open it in Kdenlive. In contrast to recording audio in a separate program, and trying to match the timing in post, this is doable and can be completely lossless (Depending on settings). A full video editor feels out of scope for ScreenToGif, and defeats the purpose of it.
