### ISSUE TITLE
Doesn't work with Gsync

### ISSUE THREAD

**Issue by brian6932** [NickeManarin/ScreenToGif#502]
There is a large amount of mouse lag and stuttering,  what happens is that g-sync is trying to match the fps of an unoptimized program which has low fps, This happens because the refresh rate of the monitor becomes less than it's native refresh rate, which in turn, makes the mouse looks laggy. This is common in some hardware accelerated programs, so as you may guess, you have 2 main options for a temp fix, to make ScreenToGif fixed refresh in the control panel or disable Gsync on windowed mode altogether.

**Comment by NickeManarin** [comment]
Closing this was external.

I implemented a feature to improve the cycle rate of the capture system, but I'm not sure if would help anyway with this issue.
