### ISSUE TITLE
Fill color in shapes not working

### ISSUE THREAD

**Issue by itpropro** [NickeManarin/ScreenToGif#503]
The color picker under Image -> Shapes has no functionality. You can pick any color under Fill, but after clicking ok, the color will stay at transparent. I tried different colors, changing the color manually by typing the color code, but I was not able to select another fill color than transparent.
![image](https://user-images.githubusercontent.com/15030951/61968302-f719bf80-afd7-11e9-86c8-ee3b9cb0b819.png)

**Comment by NickeManarin** [comment]
Have you checked the alpha values?

**Comment by itpropro** [comment]
Thanks for your fast reply!
Yes, the alpha values weren't changing anything. However, I updated from 2.16 to 2.18 and the problem seems to be gone.
