### ISSUE TITLE
Gifski编码器不能用

### ISSUE THREAD

**Issue by nextleafzhao** [NickeManarin/ScreenToGif#505]
导入10张720x720的png图片，保存为gif时出错。

**Comment by tuchit** [comment]
yeah, gifski doesn't work for me either. the others is OK

**Comment by NickeManarin** [comment]
The translation says that you can't use Gifski. Can you show me any error message?

**Comment by NickeManarin** [comment]
@nextleafzhao Can you try using the test version of the app? It's here: #551 

Go to where the Gifski.dll is located and delete that file.
After that, go to Options > Extras and download Gifski again.

**Comment by kktt007** [comment]
在windows10下面，自带的2.0好ffmpeg导出的文件最小，系统的最大，其次是Gifski.

**Comment by NickeManarin** [comment]
Closing as inactive.
