### ISSUE TITLE
AmazingApps in readme

### ISSUE THREAD

**Issue by MysterAitch** [NickeManarin/ScreenToGif#509]
Hi,

The "AmazingApps" links link to a website that is now a "parked domain" (i.e. GoDaddy shows ads, as opposed to an actual website) and the repo linked to has been emptied out to have no content (done on 01/Sep/2017 according to the commit history).

https://github.com/NickeManarin/ScreenToGif/blob/master/README.md#L100-L109

My thoughts are that an outright removal would be best as it adds no/minimal value at best, and is harmful at worst.

Kind regards

**Comment by NickeManarin** [comment]
Oh, yes. Thank you, I'll removed it.
