### ISSUE TITLE
Request new decent filetypes h264/h265/webv etc

### ISSUE THREAD

**Issue by FrozenBeard** [NickeManarin/ScreenToGif#512]
Most places support GIFS in a newer video format today, please allow us to export these as  h264/h265/webv etc, I cant find any other app as good as this one where I can just select the screen and record like this, its so annoying having to save as a gif and convert it!

**Comment by NickeManarin** [comment]
Hi, you can download FFmpeg to export your project as MP4/Webm.

Head over to Options > Extras > FFmpeg and download it.

When saving, you can select which encoder to use, which file type, and which FFmpeg video encoder too. 

Btw, make sure that you are using the latest version of ScreenToGif.

**Comment by NickeManarin** [comment]
Close the issue if it works for you.
