### ISSUE TITLE
有人利用该开源软件用于商业行为进行收费

### ISSUE THREAD

**Issue by lvbaocheng** [NickeManarin/ScreenToGif#513]
Download url: https://www.apowersoft.cn/gif

![image](https://user-images.githubusercontent.com/6335294/64149630-f2f38400-ce58-11e9-8ca4-97003e6353a1.png)

![image](https://user-images.githubusercontent.com/6335294/64149648-056dbd80-ce59-11e9-8df6-8b1a5f4296f1.png)
[https://www.apowersoft.cn/store/gif.html?apptype=ads-bd&appvisitor=71103fa172c662ba369fb93f25946c53](https://www.apowersoft.cn/store/gif.html?apptype=ads-bd&appvisitor=71103fa172c662ba369fb93f25946c53)

![image](https://user-images.githubusercontent.com/6335294/64150478-e6702b00-ce5a-11e9-83c4-d0dcfd511464.png)

**Comment by NickeManarin** [comment]
Yes, it's a copy of my work. It's know, thank you.

**Comment by lvbaocheng** [comment]
Ok,you're welcome~
