### ISSUE TITLE
Mouse Clicks not Detected on Application

### ISSUE THREAD

**Issue by roythompsonuno** [NickeManarin/ScreenToGif#515]
STG Version: 2.18 & 2.17
"Detect mouse clicks" is enabled; however, on one of the applications I am trying to record, the click highlighting does not happen. When I focus the desktop, the mouse clicks are highlighted without issue. 

The application is a .Net Winforms app using some DevExpress controls. I'm not able to include screenshots of the application for security reasons. 

I'll take a look at the source, but I figured I'd throw this up just in case there is a known cause for this. I didn't see any other reports of similar behavior. 

![image](https://user-images.githubusercontent.com/31256158/64349392-7b3e6a00-cfbc-11e9-8ace-b4f4a1ce8c0a.png)

![image](https://user-images.githubusercontent.com/31256158/64349457-a032dd00-cfbc-11e9-9d7a-aed3b3de8abe.png)

**Comment by NickeManarin** [comment]
Are you trying to record some app that is running with admin rights?
If so, try running ScreenToGif with admin rights too.

Also, duplicated of https://github.com/NickeManarin/ScreenToGif/issues/370

**Comment by roythompsonuno** [comment]
Looks like that was the problem. Thanks Nicke!
