### ISSUE TITLE
Progression by frame number doesn't display the right numbers

### ISSUE THREAD

**Issue by L0Lock** [NickeManarin/ScreenToGif#516]
On windows 10 using STG 2.18.

When using the Progression overlay to display frame number alongside total frames number, there's the issue that the total of frames is counted from 1, while the frame number is counted from 0.  
So we end up in that strange situation when we're showing he final frame but the overlay says we are not :

![Azri_AllonsAuFastfood_Stepped_issue](https://user-images.githubusercontent.com/16049822/64493077-ca65f280-d27b-11e9-95aa-1537f543935d.gif)

At least, the two values should count numbers from the same start number, either 0 or 1. It seems like the minimum thing.

Ideally, it should also be possible for the user to choose which start number to use. Sometimes it's nice to start on one, sometimes on zero, sometimes you start on a completely different number because ou already made other gifs showing the other frames, ...  
That additional flexibility could really be welcome.

UI side, it could be in a very simple form:

![image](https://user-images.githubusercontent.com/16049822/64492944-55de8400-d27a-11e9-8233-ba8aedd274d9.png)

Thanks for your help!

**Comment by NickeManarin** [comment]
![Index](https://user-images.githubusercontent.com/14798947/65468981-2f087c00-de3c-11e9-81ab-49bd79f0e0be.gif)

Like this? Does it make sense to increase the total too?

**Comment by L0Lock** [comment]
`Does it make sense to increase the total too?`

Good point.  
I think it would be useful only in some circumstances. Let's pretend your nine beautiful frames are actually the 127th of a larger project, it would be nice to be able either to show the real total frame (1-9) or the total frame in the project's context (127-135).

**Comment by hollowdrutt** [comment]
I also get similar unexpected behavior when displaying progress with percentage or bars.
![progress](https://user-images.githubusercontent.com/1944265/65765097-8e5dd900-e127-11e9-96ae-7d6c8afafad5.gif)
I expected 25/100%, 50/100%, 75/100%, 100/100%

But perhaps fixing the issue when displaying frame number will solve it for the other presentations as well?

**Comment by NickeManarin** [comment]
@L0Lock There's one problem when the total is not offset: at the ending frames, if the total is not offset, the frame number would go beyond the total (15/10).
So I'm going to offset the total too for now.

@hollowdrutt I also corrected that part of the code. 
All frames now start from +1, including the other precisions modes (miliseconds, seconds, etc).
For the frame number I'll let the user choose the starting frame.

Also, you'll be able to set the progress as a automatic task.

![image](https://user-images.githubusercontent.com/14798947/65769666-7d529f00-e10a-11e9-8f16-35dc9888da1a.png)
