### ISSUE TITLE
CTRL+Space reacts on ScreenToGif

### ISSUE THREAD

**Issue by dschiller** [NickeManarin/ScreenToGif#517]
My App I wanna record uses Shortcut Ctrl+Space but unfortunately ScreenToGif also reacts on Ctrl+Space. I can not find any Option to disable that.

**Comment by NickeManarin** [comment]
Put the focus inside one of the size boxes. It will ignore the keypress like that.

**Comment by NickeManarin** [comment]
I believe the recorder is reacting to the Space keypress, as it's an equivalent to Enter when the focus is on a button. As I wrote before, move the focus to any other element on the record window.
