### ISSUE TITLE
Add setting for default image-options

### ISSUE THREAD

**Issue by sirtet** [NickeManarin/ScreenToGif#52]
I always use the progress-bar feature, so it would be nice if there was a setting that a progress bar should always be added.

Someone else might always want a watermark, etc...

Not sure how the apply- functionality would work, as it needs rendering time to apply.
Something happening in the background?

**Comment by NickeManarin** [comment]
Right now, each overlay is merged with the final image. I'm planning to implement a layer system that could get this kind of feature in the bag.

**Comment by NickeManarin** [comment]
It's available as a form of tasks and you can set via Options > Automatic Task > Progress.
