### ISSUE TITLE
Addition of color eyedropper tool to color selector

### ISSUE THREAD

**Issue by stephen147** [NickeManarin/ScreenToGif#521]
It would be nice to have an eyedropper tool to select colours for new shapes, texts' etc.

This could also pick a colour from other applications also.

The reason for this is to cover items with the same colour as the nearby colour to hide that part of the UI, same as the obfuscate tool only not noticeable.

![image](https://user-images.githubusercontent.com/14054664/65406566-d4d5cf80-ddd7-11e9-92d9-0b0743b7f5e0.png)

**Comment by NickeManarin** [comment]
Great idea. :)

**Comment by NickeManarin** [comment]
Done!
I also added a transparency slider.

![image](https://user-images.githubusercontent.com/14798947/65779101-86993700-e11d-11e9-814a-d2f48d41035c.png)

![image](https://user-images.githubusercontent.com/14798947/65779347-f3accc80-e11d-11e9-9f7b-f83e6c5209cf.png)

**Comment by stephen147** [comment]
Thanks very much, does it allow idropping to other applications?

**Comment by NickeManarin** [comment]
Yes.
