### ISSUE TITLE
Allow inserting APNG's to the edit window

### ISSUE THREAD

**Issue by Mc-muffin** [NickeManarin/ScreenToGif#522]
So, when dragging and dropping an APGN with .apgn extension into the editor window the application says it is in an invalid format: 

![image](https://user-images.githubusercontent.com/8714476/65849527-9462de00-e310-11e9-80c8-bb21d1499578.png) 

If an APGN with .png extension is used instead it will import just the very first frame of animation (acting like a regular png image) could this feature be added given that the tool can export to APGN?

Many thanks again for the awesome application!

**Comment by vatterspun** [comment]
I've been following this format closely and I've never heard seen the APGN suffix  It's just been PNG, sort of like animated GIF has no AGIF.  I've seen one or two projects use "APNG" but that's all.

**Comment by NickeManarin** [comment]
I would have to replace the default (from .Net Framework) method of loading PNG's and use a custom built one. Now that I know how APNG's works, I can simply reverse the logic from the APNG encoder.
It make take some time to finish, probably v2.20.

**Comment by NickeManarin** [comment]
So far, with the next release, v2.20, you'll be able to import `.apng` files as a static image. 
I'm going to take more time to develop a proper APNG importer.

**Comment by NickeManarin** [comment]
Done. It will be ready for v2.21.
