### ISSUE TITLE
Suggestion: Add font shadow, underliine and outline

### ISSUE THREAD

**Issue by stephen147** [NickeManarin/ScreenToGif#523]
It would be nice to have these 3 added to the free text formatting options.

![image](https://user-images.githubusercontent.com/14054664/65960929-6d5df680-e44d-11e9-978b-4f97b02c2da1.png)

**Comment by mabakay** [comment]
> It would be nice to have these 3 added to the free text formatting options.

There is ready solution for text decorations like underline, strikethrough and shadow effect, #786

**Comment by NickeManarin** [comment]
Feature added by @mabakay :)
