### ISSUE TITLE
New cursor follower doesn't seem to work.

### ISSUE THREAD

**Issue by WELZ-gh** [NickeManarin/ScreenToGif#529]
I've tried using it in new and old UI and it doesn't work.

I set up the shortcut and toggled it on/off multiple times to no avail.

**Comment by NickeManarin** [comment]
Sorry, I'm going to release a new version in a few minutes with a fix for it. 
Thanks for the feedback.

(If you set up the other key, to temporarily disable the cursor following, it will work normally)

**Comment by WELZ-gh** [comment]
@NickeManarin I actually tried setting the disable keystroke and nothing happened (couldn't even set the keystroke)

![gif](https://i.imgur.com/F0Oujhs.gif)

**Comment by WELZ-gh** [comment]
@NickeManarin another bug when cursor following is enabled is that you can't move your mouse towards the end of the frame (before you start recording) unless you disable it with the key. 

It should really only start following once recording has begun. Like this I can still resize or access the tools etc.

**Comment by NickeManarin** [comment]
@WELZ-gh Yes, it makes sense. I'm going to disable the repositioning when not in recording.
I'm goin to generate a new version in a few minutes with both fixes.

**Comment by NickeManarin** [comment]
Done, can you check it, please?

**Comment by NickeManarin** [comment]
Thank you. :)
