### ISSUE TITLE
RTE when undo

### ISSUE THREAD

**Issue by neminovno** [NickeManarin/ScreenToGif#53]
Create gif with screen recorder, copy last frame, paste it multiple times, undo multiple times, RTE appears.

**Comment by NickeManarin** [comment]
With version 2.3.1, I got a RTE while pasting very quickly.
...
I know what's happening, but I'm not sure if it's the same thing as you bumped into, it relates to the fact that there's a asynchronous operation starting while there's another happening.

I have to study a way to avoid this problem. Thanks for the feedback.

**Comment by NickeManarin** [comment]
Fixed. It should not throw runtime error anymore.
