### ISSUE TITLE
[Feature Request] Focus the file name text box when the Save panel is opened

### ISSUE THREAD

**Issue by reduckted** [NickeManarin/ScreenToGif#533]
I use this application just about every day for capturing things like reproduction steps for bugs and discussing experimental UI changes and absolutely love it! Thank you. 😁 

However, the one thing that slows down my workflow is that when I press `Ctrl+S`, I have to move the focus to the text box for the file name. I use the same settings for all of the GIFs I save, so when I save, the only thing I need to do is enter a file name. 

It would be awesome if the text box for the file name had the focus when the Save panel opens. Then all I would have to do is press `Ctrl+S`, enter a name, and press `Enter`, and my GIF has been saved.

If you like this idea, I'm happy to submit a pull request for it.

**Comment by NickeManarin** [comment]
Yes, it makes sense. I'll take a look at your PR.
