### ISSUE TITLE
[Feature Request] Option to prevent multiple instances

### ISSUE THREAD

**Issue by Quisquose** [NickeManarin/ScreenToGif#537]
When launching ScreenToGif from a shortcut (e.g. Start Menu or hotkey) it runs a new instance every time. 

Seeing as it's possible to have all ScreenToGif windows closed and only have a system tray icon present, it's easy to forget that ScreenToGif is already running, so you ended up going back to the Start Menu (or pressing your own launch hotkey) to open it. This results in yet another instance of the program running, and you can end up with multiple identical icons in the system tray.

Having an option to restrict ScreenToGif to one instance would mean that if ScreenToGif is already loaded that any subsequent attempts to launch the program would just activate the _existing_ instance instead of launching a new one.

**Comment by vatterspun** [comment]
Good suggestion.  This is already one of the most feature-complete animation tools I know of outside of commercial software.  As such, it's going to start getting used for some important projects that take some late hours.  Anything to help avoid getting confused between windows and files is going to save a lot of headaches.

**Comment by NickeManarin** [comment]
Feature is available with v2.21.
When the app is already running, it will simply focus on the first instance.

**Comment by Quisquose** [comment]
Very much appreciated! Thank you for your ongoing hard work on this project.

**Comment by embix** [comment]
> When the app is already running, it will simply focus on the first instance.

Is it still possible to record ScreenToGif with ScreenToGif somehow? I wanted to record my default workflow but it won't let me. Once one instance is recording, the other won't record.
