### ISSUE TITLE
自动化任务的内容错误（Automated Task）

### ISSUE THREAD

**Issue by kekeyu2266** [NickeManarin/ScreenToGif#539]
添加 延时更新，实际是 按键
添加 按键，实际是 延时更新
![1233](https://user-images.githubusercontent.com/24601737/67058522-be792480-f187-11e9-9c9b-baf5db6c8af6.gif)

**Comment by NickeManarin** [comment]
Oops, thank you.
It was fixed, I'm going to release v2.19.3 tomorrow.
