### ISSUE TITLE
[Bug] Title frame bugs

### ISSUE THREAD

**Issue by Kristinita** [NickeManarin/ScreenToGif#54]
I record video → `Stop` → editor was opened for me → <kbd>Alt+T</kbd> → I have 2 small bugs.

![2 bugs](http://i.imgur.com/orXof2i.png)

### 1. Font size

All settings from previous editing — `Font Family`, `Font Style` and so on — was saved for me. But only `Font Size` have value `20`, even in previous video editing I usually make `80` or any other value.

### 2. Delay

I make `3000` value → `Apply` → but I get `1000` value, not `3000`. I need press <kbd>Alt+O</kbd> → change `Delay` → `Apply` for change delay of my title frame.

### 3. Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**ScreenToGIF:**
2.3.161201

Thanks.

**Comment by NickeManarin** [comment]
1. I'm not sure what's happening with the font size. It saves the value for me. 
2. Fixed ;) The maximum value for that field was 1,000 and I increased to 25,500.

I'll release version 2.4 today with this bug fix.

**Comment by Kristinita** [comment]
@NickeManarin, problem is reproduced for me in 2.4.0.170115 version. I record and edit GIF → set value to 80 → save GIF → close STG → record and edit another GIF → my font size value reset to `20`.

Thanks.

**Comment by NickeManarin** [comment]
@Kristinita Now I could reproduce. By closing the app after saving.

**Comment by NickeManarin** [comment]
1. Fixed. The binding of the value wasn't using the TwoWay mode. It was read-only.
