### ISSUE TITLE
Gifski error

### ISSUE THREAD

**Issue by boi114514** [NickeManarin/ScreenToGif#544]
![捕获](https://user-images.githubusercontent.com/53002293/67918249-7c63d000-fbd6-11e9-9f6d-374969c80c75.PNG)
win10  X64
ScreenToGif v2.19.3

**Comment by boi114514** [comment]
WIN10 1903
NET Framework 4.8

**Comment by NickeManarin** [comment]
Make sure that you downloaded the Gifski.dll from Options > Extras.
Also make sure that there's no antivirus blocking the dll.

**Comment by PhilipPino** [comment]
```
   at ScreenToGif.Util.GifskiInterop.Start(Int32 quality, Boolean looped, Boolean fast)
   at ScreenToGif.Windows.Other.Encoder.<Encode>d__24.MoveNext()
```

**Comment by NickeManarin** [comment]
Are you trying to save the gif inside a folder which has non-latin characters? Or maybe the folder where the frames are stored has non-latin chars too.

You could try to download the beta version of 2.20, which is a pinned issue here.

**Comment by boi114514** [comment]
> 您是否要将gif保存在具有非拉丁字符的文件夹中？也许存储帧的文件夹也具有非拉丁字符。
> 
> 您可以尝试下载2.20的测试版，这是此处的固定问题。

I didn't set the non-Latin alphabet.

**Comment by boi114514** [comment]
> 您是否要将gif保存在具有非拉丁字符的文件夹中？也许存储帧的文件夹也具有非拉丁字符。
> 
> 您可以尝试下载2.20的测试版，这是此处的固定问题。

I didn't set the non-Latin alphabet.

**Comment by NickeManarin** [comment]
So, you did not save the file to a folder or filename with any Chinese characters? 
`C:\User\您\动画制作.gif`
This example would not work, for example.

Anyway, @boi114514 and @PhilipPino, try using  this version in here:
https://github.com/NickeManarin/ScreenToGif/issues/551

**Comment by boi114514** [comment]
> 您是否要将gif保存在具有非拉丁字符的文件夹中？也许存储帧的文件夹也具有非拉丁字符。
> 
> 您可以尝试下载2.20的测试版，这是此处的固定问题。

Thank you very much. The new version you provided solves the problem.

**Comment by NickeManarin** [comment]
Great. The new version will be release next week.
The version that you downloaded is just a beta release.

**Comment by PhilipPino** [comment]
For me the new version dont solved the problem.
I tried the gifski command version and I found out that we need some Visual C++ Redistributable.
https://support.microsoft.com/en-ae/help/2977003/the-latest-supported-visual-c-downloads

**Comment by NickeManarin** [comment]
@PhilipPino 
What's the entire error message that you get while trying to run the new version 2.20?
(make sure to delete the old DLL and download the new one while using v2.20)

**Comment by NickeManarin** [comment]
> I tried the gifski command version and I found out that we need some Visual C++ Redistributable. Now it worked.

The command version is not supported by ScreenToGif and it has other problems anyway (no support for variable framerate).

**Comment by PhilipPino** [comment]
> @PhilipPino
> What's the entire error message that you get while trying to run the new version 2.20?
> (make sure to delete the old DLL and download the new one while using v2.20)
> 
> EDIT:
> Wait, I missed the part where you said that it worked, do you mean that v2.20 now works after installing the Visual C++ redist?

I only tested it to find the problem why gifski don't work. There was an error that says vcruntime140.dll is missing. After I installed the the vc++2015-2019 it worked also in your screentogif (v19 and v20)

In v20 the error was the same... but I think without vcruntime140.dll screentogif cant even run a gifsky command.

**Comment by NickeManarin** [comment]
> I only tested it to find the problem why gifski don't work. There was an error that says vcruntime140.dll is missing. After I installed the the vc++2015-2019 it worked also in your screentogif (v19 and v20)
> In v20 the error was the same... but I think without vcruntime140.dll screentogif cant even run a gifsky command.
> So you only need to know what vc library gifski exactly use and put then into the installer or something...

Ohh, now I understood. Thank you. I'm going to add a link so the user can download VC++, since it's a requirement for Gifski.

**Comment by boi114514** [comment]
I mean, after using 2.20 directly, there's no problem. I didn't install Visual C + +.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Philip Kretzschmar"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月13日(星期三) 上午8:42
收件人:&nbsp;"NickeManarin/ScreenToGif"<ScreenToGif@noreply.github.com&gt;;
抄送： &nbsp;“ boi” <2506482048@qq.com&gt;;“提及” <mention@noreply.github.com&gt;;
主题:&nbsp;Re: [NickeManarin/ScreenToGif] Gifski error (#544)



 
@PhilipPino
  尝试运行新版本2.20时收到的完整错误消息是什么？
 （确保使用v2.20时删除旧的DLL并下载新的DLL）
 
编辑：
 等等，我错过了您所说的地方，您的意思是说安装Visual C ++ redist后v2.20现在可以工作了吗？
  
我只测试了它为什么gifski不工作，发现问题。出现错误，提示缺少vcruntime140.dll。安装vc ++ 2015-2019后，它在您的screentogif（v19和v20）中也可以使用
 
在v20中，错误是相同的...但是我认为，如果没有vcruntime140.dll，screentogif甚至无法运行gifsky命令。
  
- 
您收到此邮件是因为有人提到您。
直接回复此电子邮件，在GitHub上查看，或取消订阅。
