### ISSUE TITLE
Exporting 1531-frame project results in corrupted video

### ISSUE THREAD

**Issue by mtlynch** [NickeManarin/ScreenToGif#546]
I've successfully exported shorter videos I recorded with ScreenToGif, but I recently tried recording a longer one (1,531 frames) and ScreenToGif seems to have trouble exporting it as an .avi. It corrupts the colors and shows frames out of order.

Here's the project file:

* https://goobox.io/dl#eT9WqQAC!/MGv3X_dV

If I Save as "Vdieo" @ 30 fps, with "Flip the video (vertically)." checked, then select the .avi extension with System encoder (100% quality), the result is a video that doesn't match the captured frames.

### Original

![wgt1157 1157](https://user-images.githubusercontent.com/7783288/68134775-9bbd6e80-fef0-11e9-9322-42cd9132c2dc.png)

### Exported

![vlcsnap-2019-11-04-10h42m42s195](https://user-images.githubusercontent.com/7783288/68134603-5ef17780-fef0-11e9-815d-b0e7bebbf2d1.png)

### Environment

* Windows 10 x64 (Version 10.0.18362 Build 18362)
* ScreenToGif 2.19.3

**Comment by NickeManarin** [comment]
I recommend using FFmpeg and exporting as MP4 instead.
The inbuilt AVI encoder is not optimal, also it really depends of which compressor you used.
Some work, some don't. :/

![image](https://user-images.githubusercontent.com/14798947/68140530-bb619080-ff0a-11e9-8c36-dbd937e990ab.png)

I tested creating an uncompressed video and a video using the Intel IYUV compressor and both worked normally, just the file size was big.

**Comment by mtlynch** [comment]
Good to know. Thanks!

**Comment by NickeManarin** [comment]
Which compressor did you use, btw?

**Comment by mtlynch** [comment]
I chose "Full Frames (Uncompressed)" when I hit this bug.

I just tried with a different encoder and it did output the video successfully. Thanks for your help!
