### ISSUE TITLE
Support default AV1 output option

### ISSUE THREAD

**Issue by saschanaz** [NickeManarin/ScreenToGif#547]
This should work:

```
-c:v libaom-av1 -pix_fmt yuv420p -vf "pad=width={W}:height={H}:x=0:y=0:color=black"
```

**Comment by NickeManarin** [comment]
When using those parameters, the encoding will fail. FFmpeg told me that the codec is experimental and in order to use it, you have to put `-strict -2`.

**Comment by saschanaz** [comment]
Oh, true! We probably should mark it as experimental or just defer this.
