### ISSUE TITLE
2.4 crashes when starting with 2.3.2 settings.xaml

### ISSUE THREAD

**Issue by panther2** [NickeManarin/ScreenToGif#55]
Error log is attached.

After deleting the old setting.xaml, 2.4 starts flawlessly.
[17_01_08.txt](https://github.com/NickeManarin/ScreenToGif/files/692348/17_01_08.txt)

Windows 7.64, Up to date .NET

**Comment by NickeManarin** [comment]
Looks like a problem with the German translation. Strange that it works for me when starting, but gives me an error while opening the Editor.

**Comment by NickeManarin** [comment]
Thanks for the quick feedback, btw.
Fixed.

**Comment by panther2** [comment]
You are welcome. Thanks for the quick fix. 
Runs fine now!

**Comment by NickeManarin** [comment]
Great! :D
