### ISSUE TITLE
[Preview] Version 2.20

### ISSUE THREAD

**Issue by NickeManarin** [NickeManarin/ScreenToGif#551]
This issue was open, so you can test new features before they are released to everyone.

Download here: [**ScreenToGif.2.20.Preview.5.zip**](https://github.com/NickeManarin/ScreenToGif/files/3991705/ScreenToGif.2.20.Preview.5.zip)

(Updated November 14th)
(Updated November 17th)
(Updated December 04th)
(Updated December 21th)

### What's new?

• The app now uses/requires **.Net Framework 4.8**.  
• Experimental **support for multi-DPI set of screens** (All windows, including the recorders).  
• Screen capture via DirectX 11.1 (Desktop Duplication API, requires Windows 8 or newer).   
• Screen capture can use a configurable memory cache with support for compression.  
• You can now set actions to be executed when clicking on the app icon on the system tray.  
• The default FFmpeg Webm encoder is now set to VP9.  
• Added support for version 0.9.3 of Gifski (delete the older DLL and download again via Options > Extras).  
• You can now cancel the gif encoding that uses Gifski.  
• When exporting as project, the app will use the encoder window instead of locking down the editor.  
• You can use FFmpeg to import frames from video (I also improved performance while importing video with the default method).  
• The executable can interpret arguments to disable/enable hardware acceleration.  
• The maximum permitted outwards thickness of the border was increased.   
• German, Turkish and Russian translation were updated.  

### Fixed:

♦ The new recorder had issues with the positioning of the record controls while using multiple screens.  
♦ The troubleshooter had issues displaying the correct position of the screens.  
♦ The screen recorder was not capturing animated cursors correctly.  
♦ The space bar was not set as the Play/Pause button anymore.  
♦ The Gifski encoder now accepts saving gifs to a path (also loading frames from a temporary path) that contains non-latin characters.  
♦ The text was overflowing and not wrapping properly in the FFmpeg command text boxes.  
♦ It was not possible to set shortcuts when deploying with Intune.  
♦ When trying to type special characters with the help of the Right Alt key, some commands were being fired instead. Because the underlying system translates Right Alt to Ctrl + Alt.  

### What needs to be tested? 

○ Are the new (**DesktopDuplication**) and old (**BitBlt**) capture methods faster than before?   
○ Is **200 MB** enough as a maximum size for the memory cache?   
○ Is the DesktopDuplication capture correctly capturing your screen?   
○ Test screen DPI changes while the recorder window is open (for both recorders).   
○ Test stopping the recording (for all capture modes, for both recorder).  
○ Test using the Gifski encoder with paths with different non-latin characters (I tested with Chinese and Russian characters).  
○ Left click, Double left click and middle click actions for the system tray icon.   
○ Since this preview build has **support for multi-DPI set of screens**, further testing needs to be done to ensure that all windows are DPI agnostic.  Only the new recorder has no support yet.

### Observations

♠ Version number in test release is still 2.19.3, that will change later.  
♠ Upload services won't work in this test release.  

--------------
![Application](https://user-images.githubusercontent.com/14798947/69020667-17f58e80-0994-11ea-95eb-1d44488626d9.png)

![Recorder](https://user-images.githubusercontent.com/14798947/69020668-17f58e80-0994-11ea-9b99-6dcf8f19798d.png)
--------------
More features and bug fixes may be added before the v2.20 release.

**Comment by jakovljevic-mladen** [comment]
Hey @NickeManarin,

I can confirm that
>The new recorder had issues with the positioning of the record controls while using multiple screens.

is fixed.

Environment:

Windows | Architecture | Used | Available | Total
-- | -- | -- | -- | --
10.0.18362.0 | 64 bits | 208.5 MB | 3.6 GB | 15.9 GB

Monitors

Bounds | Working Area | DPI/Scale | Primary?
-- | -- | -- | --
0:0 • 1920x1080 | 0:0 • 1920x1030 | 120dpi / 125% | Yes
1920:-522 • 1920x1080 | 1920:-522 • 1920x1030 | 120dpi / 125% | No

Thank you!

**Comment by NickeManarin** [comment]
@jakovljevic-mladen Great! Thank you. :)

**Comment by NickeManarin** [comment]
Update uploaded, preview 2.

**Comment by NickeManarin** [comment]
Update uploaded, preview 3.

**Comment by NickeManarin** [comment]
Update uploaded, preview 4.

A bug with the FFmpeg video importer was fixed.
Also several bugs with the recorders were fixed (related to having two screens of different DPI).

**Comment by NickeManarin** [comment]
Update uploaded, preview 5.

Small fix for DeviceLost/DeviceReset crash with DesktopDuplication API.

**Comment by NickeManarin** [comment]
Version 2.20 is GA.
