### ISSUE TITLE
Allow Float FPS

### ISSUE THREAD

**Issue by Crispin-at-Linknode** [NickeManarin/ScreenToGif#554]
Hi,

I want to record 1 frame every 30s... at present I use 1fps and then the other utility to remove X frames after each frame to thin the data (I have other issues with this I will document).

Could you allow 0.1 fps or change the units to frames per minute?

 thanks - Crispin

**Comment by NickeManarin** [comment]
This feature was implemented with a discrete step system (`frames per second`, `frames per minute` and `frames per hour`).

**Comment by NickeManarin** [comment]
![image](https://user-images.githubusercontent.com/14798947/123360818-583fca00-d544-11eb-86d7-2e9b89c973cc.png)
