### ISSUE TITLE
2.4 crashes when stopping a screenrecord.

### ISSUE THREAD

**Issue by panther2** [NickeManarin/ScreenToGif#56]
Updated Error log is attached.

Seems to be similar to #55
[17_01_08.txt](https://github.com/NickeManarin/ScreenToGif/files/692352/17_01_08.txt)

Windows 7.64, Up to date .NET

**Comment by NickeManarin** [comment]
Indeed, this bug was related to the issue #55.
Caused by a missing test from the German translation.

Fixed. Download again from the releases section.
