### ISSUE TITLE
Uncap negative border maximum

### ISSUE THREAD

**Issue by DanielRosenwasser** [NickeManarin/ScreenToGif#561]
I want to create room above an existing GIF so that I can put a static image on every frame via the watermark feature. Recently, you added the ability to expand borders in a negative direction (#313) which is great! However, setting a negative border is capped to -20. I need much more room there.

Any chance this can be uncapped? Or is there a better way to only change the canvas size without scaling existing image frames?

**Comment by DanielRosenwasser** [comment]
(I guess what I'm really looking for is a way to change canvas size, and "add border" is my roundabout way of asking for it)

**Comment by NickeManarin** [comment]
I'm going to increase the limit, but in a future version, I'll add the option to resize the canvas too.

**Comment by NickeManarin** [comment]
https://github.com/NickeManarin/ScreenToGif/issues/551

I decreased the limit to -500, is that enough?

**Comment by DanielRosenwasser** [comment]
Sorry for not following up - yes, that's probably reasonable for what I was trying to do. Thanks!
