### ISSUE TITLE
[Preview] New installer

### ISSUE THREAD

**Issue by NickeManarin** [NickeManarin/ScreenToGif#563]
This issue was open, so you can test new features before they are released to everyone.

Download here: [**ScreenToGif Setup.zip**](https://github.com/NickeManarin/ScreenToGif/files/4108959/ScreenToGif.Setup.zip)

Download the texts to translate: [**Strings.en.zip**](https://github.com/NickeManarin/ScreenToGif/files/4108965/Strings.en.zip)

(Updated December 15th, 2019)
(Updated December 19th, 2019)
(Updated January 24th, 2020)

### What's new?

• Well, the installer was rebuilt from scratch...  
• New interface.  
• It's now possible to select which features you want to install.  
• If needed, .NET Framework 4.8 will be downloaded and installed.  
• The installer supports translations. If you want to translate it, download the **Strings.en.zip** above.   
• You can also see, how much storage space the installation will need.  

### Fixed:

♦ DPI support was improved.  
♦ During the uninstallation, the app folder was not being removed.  
♦ Fixed the messages/warnings when the installation finishes.  

### What needs to be tested? 

○ ???

### Observations

♠ Version number in test release says 2.20 but it actually installs 2.19.3, that will change later.   
♠ I'm forcing the detection of .NET Framework to result in False, so that the Prerequisites step can appear. That will change later too.  

----------------------------

![Welcome](https://user-images.githubusercontent.com/14798947/70837877-5a1fbd80-1de4-11ea-9a69-213a9c58bfe4.png)
![Framework](https://user-images.githubusercontent.com/14798947/70837873-5a1fbd80-1de4-11ea-808e-1e470d782232.png)
![Output](https://user-images.githubusercontent.com/14798947/70837875-5a1fbd80-1de4-11ea-9c35-5fc87f3b3952.png)
![Progress](https://user-images.githubusercontent.com/14798947/70837876-5a1fbd80-1de4-11ea-9831-6f87b58e82fb.png)
![Downloading 1](https://user-images.githubusercontent.com/14798947/70837871-59872700-1de4-11ea-9359-2f535871677d.png)
![Downloading 2](https://user-images.githubusercontent.com/14798947/70837872-59872700-1de4-11ea-8571-077edce47ee4.png)
![Done](https://user-images.githubusercontent.com/14798947/70837870-59872700-1de4-11ea-86b4-dafa394c973e.png)
![Maintenance](https://user-images.githubusercontent.com/14798947/70837874-5a1fbd80-1de4-11ea-9650-d7ea6e6770ae.png)
![Installer](https://user-images.githubusercontent.com/14798947/70837898-76235f00-1de4-11ea-9193-59b36f55aeb4.gif)

**Comment by SilentSin** [comment]
I had to look up what each of the optional components are (SharpDX and Gifski) so it might be worth adding links to them and/or descriptions of what they do in ScreenToGif.

**Comment by NickeManarin** [comment]
Thanks for the feedback. I'm going to add tooltips, explaining what each component is responsible for.

Indeed, I have no control over how long the UAC dialog takes to appear. :/

**Comment by mrfearless** [comment]
For me on Windows 7 x64 the process for downloading and installing the .net 4.8 framework seemed to stall. The progress bar kept going, but i noticed a .tmp.exe (forget exact name, but info indicated it was the 4.8 .net installer) in process explorer that didnt seem to be doing anything (after leaving it for 20 minutes). I killed the that tmp.exe process and the setup continued, informing me some stuff might not have succeeded (the 4.8 .net specifically). The installation continued, ended and then i was able to launch the app from the shortcut placed on the desktop - app opened fine - the tray/task icon didnt show, although space for an icon in the traybar was created (which is related to the shell notify icon issue #525).

**Comment by NickeManarin** [comment]
@mrfearless Yes, the .NET installation takes a lot of time. It took like 30s for me, and I already had it installed...

**Comment by NickeManarin** [comment]
Update uploaded.

**Comment by NickeManarin** [comment]
Another update was uploaded. Bug fixes.

**Comment by NickeManarin** [comment]
Another update was uploaded, only bug fixes. Should be ready now.

**Comment by NickeManarin** [comment]
The new installer is GA.
