### ISSUE TITLE
[Feature Request] Automatically merge duplicate frames while recording

### ISSUE THREAD

**Issue by SilentSin** [NickeManarin/ScreenToGif#565]
First thing I do on pretty much all my gifs is merge duplicate frames so it's clear how long each frame actually takes. Automatically merging them when the recording finishes would be handy, but I'm wondering if it would be possible to actually merge them while recording, simply checking each frame as it comes in so that I don't need to wait for it to re-process them all later.

**Comment by NickeManarin** [comment]
During recording is quite expensive to do it. 

It's easier to have a task that runs after the recording ends. I could create a task with the same options as the **Remove Duplicates** feature.

**Comment by SilentSin** [comment]
I hadn't thought of that. Reducing the capture rate due to the extra processing required probably wouldn't be worth it unless you could offload it to another thread or something.

At least having it as an automated task would be nice.

**Comment by vatterspun** [comment]
> During recording is quite expensive to do it.

Maybe an ongoing duplicate check isn't worth the effort, but maybe implement an auto-pause when there's no screen activity?

**Comment by NickeManarin** [comment]
This feature was implemented, but it's only available when recording with DirectX.

To use it, simply enable this option:

![image](https://user-images.githubusercontent.com/14798947/91860180-bca23d80-ec41-11ea-9450-7699fb9cc905.png)
