### ISSUE TITLE
Window record mode doesn't line up with windows

### ISSUE THREAD

**Issue by cinderblock** [NickeManarin/ScreenToGif#568]
I'm trying to record a window. Weirdly, the selection boxes don't align with open windows very well. Also interesting is that it will not let me use the right 1/4 of my main monitor. The ScreenToGif UI simply disappears past a certain line on my main monitor.

I'm suspecting this has to do with running on a computer with multiple monitors of different resolutions.

**Comment by NickeManarin** [comment]
Hi, which version of ScreenToGif are you using? (v2.19.3 is the latest)

Also, which recorder are you using? Looks like it's the new recorder UI.

**Comment by cinderblock** [comment]
I'm on 2.19.3.

Yes, I think I am using the "new recorder UI". (I think I had just switched to it)

I'm trying to reproduce it but now it seems to be working well. Maybe it was a problem caused by changing UIs?

**Comment by NickeManarin** [comment]
Hmm. That UI is basically a fullscreen transparent window. If the whole window is shifted to the side, all it's inner elements are going to be shifted too.

I'm going to re-work that recorder, I'm not going to use a fullscreen window anymore.

**Comment by cinderblock** [comment]
Idk. Seems better now. It felt like none of the windows lined up. Boxes were like 10% bigger than expected. Could have been just everything was shifted, but didn't notice that specifically.

The really weird behavior was the tiny screen recording "toolbar" would basically go behind a wall on the right ~25% of my main monitor and no longer be visible (whichever part was behind the invisible wall)

**Comment by cinderblock** [comment]
I think I was able to reproduce this by using this little known holdover menu option of Windows's:

![image](https://user-images.githubusercontent.com/419955/71397843-8cdf6800-25d3-11ea-81aa-3651840eefbd.png)

By moving the recorder widget, your full screen interface gets moved to. This broke ScreenToGof issues on my second Windows computer temporarily.

**Comment by NickeManarin** [comment]
> By moving the recorder widget, your fullscreen interface gets moved too. 

Yes, that's what happened. Now I'm not sure how.
