### ISSUE TITLE
ScreenToGif crash at the start

### ISSUE THREAD

**Issue by Romans96** [NickeManarin/ScreenToGif#569]
Hello! I've used screentogif in the past without any problem.
Now when i launch it it crashes without starting (appears only the screentogif icon in the bottom right on application bar and then disappears).
I tried to uninstall it and install the msi version. I tried the portable version, i tried also to start both with administration permissions but nothing, it continue to crash after started (no errors or messages) it only closes and disappear

**Comment by NickeManarin** [comment]
Try opening the app again, it will crash. Now open the Event Viewer and navigate to **Windows Logs > Application**.

Search for error logs, there should be two of them, one should contain a detailed stack trace of the crash.

**Comment by NickeManarin** [comment]
Hi, is it working?

**Comment by NickeManarin** [comment]
Closing this as it is inactive.
