### ISSUE TITLE
[feature request] Local .gif

### ISSUE THREAD

**Issue by EMLVIRUS** [NickeManarin/ScreenToGif#57]
Add ability to import local .gif files, edit and save as new ones.

**Comment by NickeManarin** [comment]
You can do that already. 

Open the Editor,
File > New > Media or Project > Select gif file.

or

Drag and drop into the Editor or the executable of ScreenToGif.

**Comment by vatterspun** [comment]
> You can do that already

Have tested this and can confirm.
