### ISSUE TITLE
importing avi files can be highly inconsistent + other issues

### ISSUE THREAD

**Issue by MeatPony** [NickeManarin/ScreenToGif#570]
When importing my 25 FPS 50 frame avi file (2 seconds long) it seems to add an extra frame, so it becomes 0-50 which means there are 51 frames. Some of the frames repeat multiple times, and the frames that do are inconsistent between imports. I have checked my avi files and it is fine. Also, upon exporting my 50 frame gif (when I remove the extra frame) and I import it into the other software I use, it only has 45 frames, not 50, as it should be.

**Comment by NickeManarin** [comment]
Can you try out this version? 
#551

**Comment by MeatPony** [comment]
2.20 seems to have fixed the issues, I only used FFmpeg to import this time, didnt test regular importing. When importing it into my software there are 50 frames like there are supposed to be. No duplicate frames, and no extra frame.

**Comment by NickeManarin** [comment]
I also changed a bit how the regular way worked. Can you test it?

**Comment by MeatPony** [comment]
While using regular mode: The first two frames were duplicates and the last 3 frames were the same too. The number of frames appears to cap at 50, which it shouldn't be. It should be 49

**Comment by NickeManarin** [comment]
Closing this since it works with v2.20, although only with the new importer.
