### ISSUE TITLE
Have anybody used the Nvidia NVENC？

### ISSUE THREAD

**Issue by imeltemi** [NickeManarin/ScreenToGif#571]
![图片](https://user-images.githubusercontent.com/22288411/71440435-0b551a80-2738-11ea-8754-905c7719f4f3.png)

I use the 
`-c:v h264_nvenc -pixel_format yuv420p -preset default` 
to start the NCENC output video，the output is successful ，but the speed increase is not obvious, and the CPU usage is still very high. 
My graphics card is P2000, after turning on the NVENC encoder which only takes 5%. I am not familiar with the ffmpeg command. Can anyone help me?

**Comment by NickeManarin** [comment]
This feature was properly implemented in version 2.28.

![image](https://user-images.githubusercontent.com/14798947/123360554-e49dbd00-d543-11eb-8787-dc2feac3864b.png)
