### ISSUE TITLE
It seems that I can't download gifski.dll completely

### ISSUE THREAD

**Issue by dytfy666** [NickeManarin/ScreenToGif#572]
1. In ScreenToGif >option >extra, the gifski.dll should have been 1M in size, but the file I downloaded is only 502k.
2. The path of gifski.dll don't contain chinesen, it's in D:\gif.
3. Gifski encoding is failing when using, and The error report is as follows:
![Error Report](https://user-images.githubusercontent.com/58970365/71483395-9cb0b380-2842-11ea-9370-888f32235f6d.png)
4.I'm In China, I download gifski in option>extra through VPN, maybe there will be errors in this way, so I want to ask if there is any place where I can download gifski.dll directly, because ffmpeg.exe is directly downloaded, and then manually associated in screentogif.
Finally, Thanks for your great software.

**Comment by imeltemi** [comment]
Have a try agian and again,I encountered the same problem many times, but maybe I was lucky that time, and then I downloaded it successfully，No need to use VPN

**Comment by dytfy666** [comment]
> Have a try agian and again,I encountered the same problem many times, but maybe I was lucky that time, and then I downloaded it successfully，No need to use VPN

OK, I'll try,thanks

**Comment by NickeManarin** [comment]
You can also download it manually from here:
https://github.com/NickeManarin/ScreenToGif/wiki/Help-▪-FAQ-▪-Unable-to-download-Gifski
