### ISSUE TITLE
Launch ScreenToGif recording from command line? e.g. screentogif.exe -boxcorners=0,0,800,600 -duration=60s

### ISSUE THREAD

**Issue by josephernest** [NickeManarin/ScreenToGif#574]
Is it possible to launch a record directly from command line?
Something like:

    screentogif -boxcorners=0,0,800,600 -duration=60s -savefile=test.gif

?
Thanks!

**Comment by NickeManarin** [comment]
It's currently not possible to do that.

**Comment by josephernest** [comment]
Thank you for your answer @NickeManarin.

Do you think a simpler feature like:

    screentogif -boxcorners=0,0,800,600 -startrecording

(i.e. no stopping, no saving from command-line) 

would be possible?

**Comment by NickeManarin** [comment]
Yes, I'll implement that feature in a future release. But the user would have to pause/stop the recording manually.

**Comment by Sironas** [comment]
Hello,

This feature is really interesting for me too but stopping it manually would break the purpose of launching it in command line.

Is it possible to find a way when the program is closed/killed to save the gif ?
Maybe another command to the exe file ?

Thank you

**Comment by tankorsmash** [comment]
Looking forward to this feature; it would be nice to be able to bind S2Gif to a hotkey (outside of S2G), and have it start up ready to record a specific part of my screen.

**Comment by NickeManarin** [comment]
Done. This feature will be available with the next release (v2.32).

I'm going to update the wiki with the details about the switches/command parameters. 
But the usage is like this (all parameters were shortened):

`.\ScreenToGif.exe -n -o s -r 300,300,400,250 -f 15fps -l 00:00:06 -c`

-n = new instance
-o =open
 s = screen recorder
-r = region (`Rect`)
-f = capture frequency
-l = time limit (`TimeSpan` as **HH:MM:SS.FFF**)
-c = start capture

**Comment by NickeManarin** [comment]
https://github.com/NickeManarin/ScreenToGif/wiki/Startup-parameters

**Comment by tankorsmash** [comment]
Awesome, thank you @NickeManarin!
