### ISSUE TITLE
[Bug] Saving a frame as an image: unable to overwrite existing image, even with the option checked.

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [NickeManarin/ScreenToGif#577]
To reproduce:

1. Record something.

2. Edit > Delete All Next.

3. Save the frame somewhere.

4. Repeat the process and attempt to overwrite the previous file, with the option to do so checked.

![image](https://user-images.githubusercontent.com/19352442/72110211-9cfe8380-3305-11ea-8805-8c2b3b55a004.png)

P.S. Thanks for the awesome app! I love the crisp UI and all the editing options I get :)

**Comment by NickeManarin** [comment]
I was using the property of "Overwrite on save" of the Gif filetype, mistakenly. It is working normally now. Thanks.

**Comment by AleksandrHovhannisyan** [comment]
Awesome, thanks!
