### ISSUE TITLE
64-bit build

### ISSUE THREAD

**Issue by EMLVIRUS** [NickeManarin/ScreenToGif#58]
You can expect better performance because of new command sets.
If you concern about compatibility issues, release 32/64-bit builds separately.

**Comment by EMLVIRUS** [comment]
Just a hint: you may add detecting and redirecting in case of error:
pack both 32/64 bit exe in the same zip archive and set relevant paths.
e.g. If user runs the 64-bit exe in 32-bit OS, redirect back to 32-bit exe.
same for 32-bit exe.

**Comment by NickeManarin** [comment]
Done. Ready for the next release.

It's a single .exe that will target your instruction set properly.
