### ISSUE TITLE
[Feature Request] Auto Close the Encoder window

### ISSUE THREAD

**Issue by KybernetikGames** [NickeManarin/ScreenToGif#581]
I often have a lot of windows open when recording gifs and the Encoder window is not particularly useful when it isn't actively saving a file so it would be nice to have the option for it to close itself when it is done. That would also be useful for letting me know when it is finishes so I don't need to keep checking the window.

**Comment by NickeManarin** [comment]
I'm thinking of removing that window and putting the encoding item inside the notification list.

**Comment by NickeManarin** [comment]
The encodings now are going to be displayed in a pop-up (in the notification center of ScreenToGif).

![EahGeM8XQAAfluV](https://user-images.githubusercontent.com/14798947/86025891-25342a80-ba05-11ea-9998-29d6f0c45721.png)

You can still use the old Encoder window. But it will be disabled by default.
