### ISSUE TITLE
[Feature Request] filename as date format

### ISSUE THREAD

**Issue by seongwon-kang** [NickeManarin/ScreenToGif#582]
I'm using this wonderful tool to capture current state of working app, and I need to save timestamp about when I started to capture.
I want to add save option to save filename with date format (manually or pre-formatted), to prevent typo and make ease to manage gifs.

**Comment by NickeManarin** [comment]
Hi, you can do that already. Just put your date format inside two question marks: 
`Video ?dd-MM-yyyy?` -> `Video 28-01-2020.mp4`

**Comment by lisonge** [comment]
how can format filename accurate to the second?

**Comment by lisonge** [comment]
@NickeManarin 

## log record

![2020-07-23 12-25-36](https://user-images.githubusercontent.com/38517192/88252202-eaf63a00-ccdf-11ea-9406-28719f5271fc.gif)

## log output

```
[下午12:25:07][vscode-sqlite][INFO] Activating extension vscode-sqlite v0.8.2...
[下午12:25:07][vscode-sqlite][INFO] Extension activated.
[下午12:25:11][vscode-sqlite][DEBUG] SQLite3 command: 'sqlite3'
[下午12:25:11][vscode-sqlite][DEBUG] Database path: 'e:\Documents\Projects\pixiv-bucket\assets\illust-info.db'
[下午12:25:11][vscode-sqlite][DEBUG] Query: SELECT * FROM `artwork`;
[下午12:25:11][vscode-sqlite][DEBUG] Statements:
[{"sql":"SELECT * FROM `artwork`;","position":{"start":[0,0],"end":[0,23]},"type":"SELECT"}]
[下午12:25:16][vscode-sqlite][DEBUG] SQLite3 command: 'sqlite3'
[下午12:25:16][vscode-sqlite][DEBUG] Database path: 'e:\Documents\Projects\pixiv-bucket\assets\illust-info.db'
[下午12:25:16][vscode-sqlite][DEBUG] Query: SELECT * FROM `artwork`;
[下午12:25:16][vscode-sqlite][DEBUG] Statements:
[{"sql":"SELECT * FROM `artwork`;","position":{"start":[0,0],"end":[0,23]},"type":"SELECT"}]
```

## file [sqlite file url](https://drive.google.com/file/d/1DEYSGjQIdYkUnXlaOWmuect2TBOjoaVO/view?usp=sharing)

but i think this log is useless

**Comment by NickeManarin** [comment]
@lisonge Hmm, I'm following your line of thought. Why did you post that?

Are you having an issue while naming the file using date time inside two question marks?
(Because that's what this issue ticket is about)

**Comment by lisonge** [comment]
@NickeManarin 

i am sorry, I send wrong  comment  of another [issues](https://github.com/AlexCovizzi/vscode-sqlite/issues/120)

and in the beginning i want to know use date format filename and accurate to the second

I already know use 
```
?yyyy-MM-dd hh-mm-ss?
```

**Comment by NickeManarin** [comment]
Here's a list of the possible formats:

https://www.c-sharpcorner.com/blogs/date-and-time-format-in-c-sharp-programming1

**Comment by lisonge** [comment]
ok, thinks

**Comment by hced** [comment]
Adding to this, I'd like to suggest including something like a question mark next to filename and when clicking on that, show a popup that tells the user that time may be enclosed within two question marks. (As a new user, I paused to figure this out and had to search for it.)
