### ISSUE TITLE
use colon(:) in filename timestamp notation(?hh:mm:ss?) returns error

### ISSUE THREAD

**Issue by seongwon-kang** [NickeManarin/ScreenToGif#587]
![image](https://user-images.githubusercontent.com/56567660/74403267-fe1bf880-4e69-11ea-92bb-cc218d016dbd.png)

**Comment by NickeManarin** [comment]
Hi, a file cannot be named with a **:**

https://stackoverflow.com/a/31976060/1735672

**Comment by seongwon-kang** [comment]
Oh, I did't checked whether file creates, :(
