### ISSUE TITLE
default ffmpeg VP9 options speeds up the output video

### ISSUE THREAD

**Issue by A-tG** [NickeManarin/ScreenToGif#589]
Recorded video has 15fps. I have to manually add "-r 15" to avoid speeding up. Maybe there is should be some builded-in argument like {W} and {H} but for the framerate. VP8 dont have that problem.

**Comment by NickeManarin** [comment]
Doesn't look like it's speeding up to me. 
But I'm going to let the {F} parameter available anyway.

**Comment by A-tG** [comment]
I checked again. It looks like PotPlayer's (video player that I use) built-in ffmpeg decoder vp9_cuvid treats 15fps or 5 fps video as 25fps and speeds everything up.

**Comment by A-tG** [comment]
Also DXVA decoder works fine in PotPlayer, but reports 25 FPS, and correct "actual fps", VLC Player just dont play video at all. Standard Windows Media Player and "Movide & TV" works normal. Also no "framerate" property in file properties -> details if it should be.

**Comment by NickeManarin** [comment]
You can add manually the FPS to the params text box (as you are currently doing) and save it to always use that (as a preset).

Not sure what else to do in this case.

**Comment by NickeManarin** [comment]
Closing this as external.
