### ISSUE TITLE
Override set to frame 0 does not have an effect

### ISSUE THREAD

**Issue by igor2x** [NickeManarin/ScreenToGif#59]
Problem on ScreenToGif 2.4, but it was already a problem in previous version 2.3.2.
1. Click on Recorder and record something.
2. In Editor in frame window at bottom scroll to the first frame (frame 0) and click on it.
3. Menu Edit and click on Override.
4. In Delay (ms) inputbox type in: 5000 and click on Apply button at bottom.
5. Make sure frame 0 is still selected and from right-bottom click on Play button. Problem appears. It looks like if "override" is set for frame 0 then it has zero effect.

Somehow work-around:
1. Click on frame 1.
2. Menu Edit and click on Move Left icon. Now 5000 ms frame is at second place.
3. Click on Run button and now 5 second delay has an effect.

It looks to me time for first frame (frame 0) is set it is just skipped.

**Comment by NickeManarin** [comment]
Do you mean during the preview (playback)? The override sets the value to 5000ms, but the preview jumps right away to the next frame while starting the playback.

**Comment by igor2x** [comment]
Exactly in step 3 overrride was set to 5 seconds, but playback (the same if saving into gif file) just jumps right away to the next frame.

**Comment by NickeManarin** [comment]
There was a bug with that field (the override box) not being able to update the value to override the selected frames. Only after the second time it was updating the value.
