### ISSUE TITLE
Hard to stop a preview in player of editor after import

### ISSUE THREAD

**Issue by F8ER** [NickeManarin/ScreenToGif#593]
Dear Developers,

Thank you very much for this project.

Although, it's worth to mention that:
1. It's hard to stop a preview in player of editor after import(video?).
Maybe it's related that mouse click must be very fast(between frame change) to stop it?

Preview:

![](https://i.imgur.com/zjk6F1m.gif)

2. Mouse is selected in preferences, but is not shown as you might notice above:

![](https://i.imgur.com/aKg8gTD.png)

3. When starting rendering a window of progress(progress bar) which is opened in bottom right corner of screen is cut(part of window is hidden) if screen(monitor?) is scaled, for example, 150%.

Also, what do you think about adding a grids(crosses) to region selections, like 4x4, 9x9 etc.?

Is that a correct behavior? Thank you!

Best regards

**Comment by NickeManarin** [comment]
1 and 2 looks fine in here. Which version of the app are you using?

![Play-Pause](https://user-images.githubusercontent.com/14798947/74868301-c95de480-5334-11ea-94ec-e2030cdcf377.gif)

Can you show a screenshot of n. 3?

**Comment by vv7v7** [comment]
Thank you for a reply.

The version is currently the last one: https://github.com/NickeManarin/ScreenToGif/releases/download/2.20.4/ScreenToGif.2.20.4.Portable.zip
Maybe this might exist when imported video is bigger? Also, it's worth to mention that it stops instantly every time after clicking on previous or next frame(near pause) button even when pause does not stop it.

For me a video was about 33000 frames and cropped while importing from 6000 to 18000 frames (total 761 at 60 FPS) frames in preview.

![](https://i.imgur.com/5bB6mCi.png)

A screenshot of n. 3:

This is a button right corner of a 4K screen scaled to 150% when rendering:

![](https://i.imgur.com/5BSckI9.png)

**Comment by NickeManarin** [comment]
Number 3 was fixed, so with the current version (v2.26.1) it should be displaying correctly (You are going to have to enable "Display encodings in a separated window" on Options > Editor in order test it).

Number 1 and 2: Looks like the clicks were not being properly registered within the button. Can you check again with the current version (v2.26.1)?

**Comment by F8ER** [comment]
> Number 3 was fixed, so with the current version (v2.26.1) it should be displaying correctly (You are going to have to enable "Display encodings in a separated window" on Options > Editor in order test it).
> 
> Number 1 and 2: Looks like the clicks were not being properly registered within the button. Can you check again with the current version (v2.26.1)?

I **very** appreciate your help! 😄

The "**2**" seems works properly:

<img src="https://i.imgur.com/D7Dfxbw.gif" width="400px" />

The "**3**" seems works properly:

<img src="https://user-images.githubusercontent.com/25136754/91647116-0549d300-ea57-11ea-8513-82a60e9369f1.png" width="400px" />

The "**1**" is interesting. It seems like right after media import(i.e. "*.mp4" video) and **first preview play** it might do not allow to stop the preview playing, but after full play and auto rewind(2 loop) it allows to do so(used different record service to record):

<img src="https://i.imgur.com/w8c3eqd.gif" width="400px" />

---

Interesting. Found something related to new record window. Posted in different GitHub issue #708.

Once more. Very appreciated.

Regards

**Comment by NickeManarin** [comment]
For **1**, I just imported a 60fps MP4 video, with 761 frames, 60fps (16ms), small sized frame (100px) and went directly to the playback tab after importing and hit play.

I was able to pause normally.

If you are not recording the process, can you pause normally? Perhaps it's another app interfering with the pause process.

Can you test with this version?
[ScreenToGifTest.zip](https://github.com/NickeManarin/ScreenToGif/files/5146121/ScreenToGifTest.zip)

I added an workaround. I want to see if it's working.

**Comment by F8ER** [comment]
Thank you

1. Downloaded and launched a test version ~~(virus free, thank you)~~ 😊
2. Imported a [video](https://i.imgur.com/EA9hV8v.mp4)
3. Pressed `Play` and `Paused` did not work for the first loop, but only second.

It's worth to mention that button `Next frame` which is next to `Play/Pause` works even for first loop which also pauses it.

> ... Perhaps it's another app interfering ...
Currently, this happens with and without other record application running

Regards

**Comment by NickeManarin** [comment]
Sorry for the delay.

With v2.28, the previewer was updated.
Can you check if the issue persists?

**Comment by F8ER** [comment]
> Sorry for the delay.
> 
> With v2.28, the previewer was updated.
> Can you check if the issue persists?

While testing in different ways, the issue didn't appear. Awesome!
I very much appreciate you, dear developers, for the contributions ✨

**Comment by NickeManarin** [comment]
Awesome!
