### ISSUE TITLE
Use of timestamp notation not allows to designate new save destination

### ISSUE THREAD

**Issue by seongwon-kang** [NickeManarin/ScreenToGif#594]
![20-02-21 10 34 15](https://user-images.githubusercontent.com/56567660/74996105-0392c780-5496-11ea-90e9-396c375d1bbc.gif)

if I uses timestamp notation, I can't target new save destination.
is there a good way to designate save destination to a folder?

**Comment by NickeManarin** [comment]
Yeah, that needs a change. Not sure what to do right now.

**Comment by NickeManarin** [comment]
With the next version, that button will open the folder selection by default, which enables the selection of a folder even when using a file with timestamping.
