### ISSUE TITLE
I get this error whenever I try saving my gif right after I updated to 2.20.4

### ISSUE THREAD

**Issue by YuushaNi** [NickeManarin/ScreenToGif#595]
![2020-02-21](https://user-images.githubusercontent.com/61337564/75084099-c6592480-54eb-11ea-9ee7-d8ba71016c0a.png)

**Comment by NickeManarin** [comment]
Are you trying to export with Gifski?
Try deleting the Gifski.dll and downloading it again via Options > Extras or here:

https://github.com/NickeManarin/ScreenToGif/wiki/Help-▪-FAQ-▪-Unable-to-download-Gifski

**Comment by YuushaNi** [comment]
Thank you! It worked!

**Comment by YuushaNi** [comment]
Thank you! It worked!
