### ISSUE TITLE
Preview Resize does not work anymore 2.20+

### ISSUE THREAD

**Issue by RalinStorm** [NickeManarin/ScreenToGif#596]
When resizing the video/GIF prior to import in the Editor the program ignores any changes and imports the full size video/GIF now.

There is also an error notification in "Extras" that I do not understand and believe it may have something to do with the new SharpDx additions.

**Comment by NickeManarin** [comment]
Ok, the MediaPlayer importer scaling is not working.

About the error notification, can you show me the screenshot of the error?

**Comment by RalinStorm** [comment]
Sure.
![ScreenToGif_gid0kRLvgV](https://user-images.githubusercontent.com/58577864/75101641-17791f00-55a5-11ea-9543-466c7330d599.png)

**Comment by NickeManarin** [comment]
The app checks if the current folder (where the app is located) has the three SharpDx DLL's.
Not sure exactly what is happening without looking at the logs (You can share them via the Feedback tool too).

You can manually download SharpDx from here: 
https://github.com/NickeManarin/ScreenToGif/wiki/Help-▪-FAQ-▪-Unable-to-download-SharpDx

**Comment by RalinStorm** [comment]
> The app checks if the current folder (where the app is located) has the three SharpDx DLL's.
> Not sure exactly what is happening without looking at the logs (You can share them via the Feedback tool too).
> 
> You can manually download SharpDx from here:
> [https://github.com/NickeManarin/ScreenToGif/wiki/Help-▪-FAQ-▪-Unable-to-download-SharpDx](https://github.com/NickeManarin/ScreenToGif/wiki/Help-%E2%96%AA-FAQ-%E2%96%AA-Unable-to-download-SharpDx)

Thanks, the FAQ solved the 2nd issue. Now there's just the 1.

**Comment by NickeManarin** [comment]
I fixed both bugs. Thanks.
