### ISSUE TITLE
Could not load 'SharpDX.DXGI'

### ISSUE THREAD

**Issue by grafanauser** [NickeManarin/ScreenToGif#598]
I have chosen the DirectX option in settings->Recorder. Then I used the download button for SharpDX. in Settings -> extras. But when i try to record something, this popups:

![grafik](https://user-images.githubusercontent.com/47564534/75157167-da7f6a80-5713-11ea-82ee-9f198282bf00.png)

**Comment by NickeManarin** [comment]
Is your anti-virus blocking the access to the DLL?

https://github.com/NickeManarin/ScreenToGif/wiki/Help-▪-FAQ-▪-Missing-dependency-%28.Net-Framework-or-DLL%29

**Comment by grafanauser** [comment]
it did not work on 2 different windows 10 computers. One with Windows defender and one with a different antivir tool. But I didnt get any antivirus warnings. Further information: I used the portable version of screenToGif. Starting it as admin did not help either.

But i now tried to use the installer instead of the portable version. Now it works.

PS: the wiki is hard to navigate. I checked the wiki, but did not find the link you posted. The wiki pages are collapsed by default which is not the case for other wikis on github. A wiki with a tree like structure on the right, would be more user friendly in my opinion. 

PS2: awesome tool. :)

**Comment by NickeManarin** [comment]
Still with the portable version, did you check if the DLLs were blocked by Windows?

Right click on the DLLs > check if the file is blocked.
Also, where did you store the DLL's? Maybe it could be inside a folder that the app can't access.

**Comment by grafanauser** [comment]
They are not blocked. No "unblock" button is shown. I checked all files.

I tried out different storage location: download folder, desktop folder and now C:\Users\myUserName\Documents\screenToGif. the same error message appeared with the portable version.

When I compare the portable and the installed version now, both show the same path to SharpDx
![grafik](https://user-images.githubusercontent.com/47564534/75162059-30a4db80-571d-11ea-9242-da7579621ee5.png)

But the portable version still has the error when i am trying to record, while the installed version does not. (or does the installed version does not use the shown path? i checked installing sharpDx in the installer)

**Comment by NickeManarin** [comment]
Wait, I see what's happening. The app is unable to load the DLL's when they are not in the same folder as the executable.

I'm going to see if I can fix this.

**Comment by grafanauser** [comment]
you are right, it works when the files are in the same folder. strange... I thought i tried that out first.

**Comment by NickeManarin** [comment]
Fixed. It will be available with v2.21.
