### ISSUE TITLE
ThinkPad external keyboard trackpoint scrolling crash

### ISSUE THREAD

**Issue by serenedu** [NickeManarin/ScreenToGif#599]
Hi, when saving recorded Gif, in the save as panel, if I scroll using ThinkPad external keyboard trackpoint which is the only scrolling device I have, the trackpoint scrolling crashes, and is unusable unless I reboot the system. I know it might be a keyboard driver problem, but I'm hopeless with lenovo's support team. Any other app won't crash the scrolling, can you check the EventListener for scrolling please, I think it's certainly not an ordinary one.
![image](https://user-images.githubusercontent.com/28700378/75309611-7fbd4e80-588c-11ea-836a-57bd85cb1153.png)

**Comment by serenedu** [comment]
For this, I've tried all kinds of similar software, by far none comes close to ScreenToGif, really hope this could be fixed.

**Comment by NickeManarin** [comment]
That's a normal scroll viewer. Not sure what's different to the point that an external software crashes on scroll.

Can you test other scroll viewers, outside of the Editor window?
Like the ones in the Options window (Resize the window to a smaller size to see the scrollbars).

Also, have you tried to simply close the Lenovo software and start again, without having to restart the whole system.
Also x2, you can try restarting the Windows Explorer too.

Other than that, you can open the Event Viewer and check if there's any error entry in there.

**Comment by serenedu** [comment]
Hi, I've tried scrolling in the language panel
![image](https://user-images.githubusercontent.com/28700378/75407332-b14a1e80-594d-11ea-844b-5154de431e09.png)
And the scrolling crashed again, had to reboot system since it's a driver, not sure how to restart a driver, even if I could restart it, it would crash again the next time I scroll in ScreenToGif.
Here's the event viewer detail, the keyboard driver HScrollFun.exe crashed.
[log.txt](https://github.com/NickeManarin/ScreenToGif/files/4259243/log.txt)

**Comment by serenedu** [comment]
Hi, thanks for the quick response. I've tried scrolling in the options windows, also crashed scrolling. I suppose any scroll viewer in STG will crash scrolling. By looking at the event viewer, I did find the crashed program "HScrollFun.exe", by starting it, my scrolling went back, don't need to reboot system any more :D. Here's the [detailed log](https://github.com/NickeManarin/ScreenToGif/files/4259830/log.txt)

After knowing the crashed program's name, I did some researches on it, it turned out many thinkpad users had this issue since 2013 or earlier, and this driver still is not fixed. I've gone hopeless with Lenovo's support team beforehand, was not surprised :D. Other users mentioned Visual Studio, Source Tree etc. were the main software causing the crash. Here's the earliest [post](https://forums.lenovo.com/t5/ThinkPad-T400-T500-and-newer-T/ThinkPad-Preferred-Scrolling-for-Bluetooth-Keyboard-Keeps/td-p/1209848?page=1) I found regarding this issue. I hope these info can help you tackle this compatibility issue, thanks.

**Comment by NickeManarin** [comment]
From what I understand. HScrollFun.exe fails to deal with ScrollViewers of WPF apps. ScreenToGif and VisualStudio are WPF apps.

You can try disabling that "Preferred scrolling" or save that script that the user created as a "script.ps1" file to run each time that the scroll crashes again.

Other than that, it's impossible for me to fix it. It's beyond my reach.

**Comment by wenfangdu** [comment]
Not sure why, in v2.36, ScreenToGif no longer crashes HScrollFun.exe, I'm pretty sure HScrollFun.exe hasn't been updated. @NickeManarin
