### ISSUE TITLE
[Suggestion] Add the ability to make settings portable

### ISSUE THREAD

**Issue by Tyf0x** [NickeManarin/ScreenToGif#6]
Hi,

I discovered ScreenToGif not so long ago and I must say it is awesome!

As the title says, I'm suggesting to add the ability to turn the application fully portable to carry the settings over on any machine (USB key).

I'm not sure how much is implied there but file paths will most certainly need to be made relative.

Thoughts?

**Comment by NickeManarin** [comment]
Thank you 😄 

Portability is a main request. Indeed, paths need to be relative. I'm thinking about creating special codes (like %DIR%) that will be resolved/calculated during runtime.

**Comment by NickeManarin** [comment]
Ready for release 2.3.

The `UserSettings` is based on a resource dictionary named `Settings.xaml`.

To make your settings local, just create an empty text file and rename it to `Settings.xaml`.

If no local resource present, the app looks for a resource located inside the folder `%APPDATA%/ScreenToGif`.

If no appdata resource present, a default one will be loaded into memory. All properties changed during runtime will be saved inside the current resource file.
