### ISSUE TITLE
[Feature request] Several small bugs and feature requests

### ISSUE THREAD

**Issue by Kristinita** [NickeManarin/ScreenToGif#60]
### 1. Settings reset

**Problem**: I use Chocolatey [**ScreenToGIF package**](https://chocolatey.org/packages/screentogif). After ScreenToGIF upgrade, all my settings reset to default. For example, my [**Title frame settings in 2.3 version**](https://github.com/NickeManarin/ScreenToGif/issues/54#issue-199431600) and now, in 2.4 version:

![2.4 Title frame](http://i.imgur.com/MxXtTZP.png)

**Request**: It would be nice, if after Chocolatey upgrades settings not will be reset.

### 2. Executable file name

**Problem**: In version 2.4 executable file was named `ScreenToGif 2.4.exe`. I use [**nnCron**](http://www.nncron.ru/index.shtml) task scheduler, and I run ScreenToGIF via <kbd>Super+Alt+S</kbd> hotkey. But after each ScreenToGIF update, name of executable file was changed and I need to change task settings of my Task Scheduler.

**Request**: It would be nice, if ScreenTo GIF executable file will always be named `ScreenToGIF.exe`.

### 3. Shortcuts conflict

**Problem**: In ScreenToGIF I use shortcut <kbd>F6</kbd> for `Start/Pause` and <kbd>F8</kbd> for `Stop`. For example, I record GIF in my text editor. I press <kbd>Shift+Super+F6</kbd> shortcut to run command of my text editor and ScreenToGIF pause recording. I need rewrite my hotkeys in my text editor without <kbd>F6</kbd> key.

**Request**: It would be nice, if screen recording will be paused only after <kbd>F6</kbd> key, but not after shortcuts with <kbd>F6</kbd> key: <kbd>Ctrl+F6</kbd>, <kbd>Shift+Super+F6</kbd> and so on.

### 4. Snap to Window

**Problem**: I sprained window of my text editor almost the entire height of the monitor → I drag `Snap to Window` button → I drop it to bottom or top my text editor window → you may see in image, that my window cropped in top and I get empty space in bottom.

![Snap](http://i.imgur.com/8EIyeIY.png)

If window for recording small for me → `Snap to Window` worked normally for me, but if window almost the entire height of the screen, I have this problem.

**Request**: It would be nice, if you fixed this problem.

### 5. Chocolatey pre-release

**Problem**: In Chocolatey you may add prerelease versions, [**example**](https://chocolatey.org/packages/TeraCopy/3.0.3.20150603-alpha). Users of ScreenToGIF will be known about new changes and will not write bugreports about already fixed bugs like [**that**](https://github.com/NickeManarin/ScreenToGif/issues/54#issue-199431600).

**Request**: It would be nice, if you will be add pre-release versions in Chocolatey.

Thanks.

**Comment by NickeManarin** [comment]
1. That's strange. The default location for the settings file is under the AppData folder. 

2. I started renaming the file to ScreenToGif.exe to work with ShimGen for Chocolatey. But I'll also use the filename without the version for the standard downloads too.

3. Now fixed. If the shortcut keys are triggered with modifier keys, I'll ignore.

4. I understand what's happening, and I'm working with a different approach. But for now, you could enable the "thin mode" under Options > Application.

5. If there is a big change, I'll think about releasing a prerelease version.

**Comment by NickeManarin** [comment]
4. Good news:

![region](https://cloud.githubusercontent.com/assets/14798947/26708489/6b032e16-4722-11e7-9727-474bdbeaf9ca.gif)

![window](https://cloud.githubusercontent.com/assets/14798947/26708491/6d8ef386-4722-11e7-8edb-d9eb9749241e.gif)

I'm still developing this new recorder, it will be ready for v2.8

**Comment by NickeManarin** [comment]
4. Done!

I'll work with 1) right now.

**Comment by NickeManarin** [comment]
For the issue [1], I believe it has nothing to do with the chocolatey, unless the settings file is being stored inside the same folder as the executable.

So, it may be a problem that happens when saving the settings after exiting the app. I improved the saving process to revert the file to a previous backup if something fails.
