### ISSUE TITLE
There is no Alipay for chinese

### ISSUE THREAD

**Issue by Bu-Chuan** [NickeManarin/ScreenToGif#600]
Student like me, who don't have a credit card, so you know, as a chinese, I can't “help the project”.

**Comment by NickeManarin** [comment]
As far as I know, Alipay is China only.

**Comment by Bu-Chuan** [comment]
Yes, and I happen to be Chinese

**Comment by NickeManarin** [comment]
I understand, but I'm not a Chinese national. It does not look like that I can create an account.

**Comment by vatterspun** [comment]
Dupe issue: #353
