### ISSUE TITLE
App crashes on load trying to access AccountDomainSid

### ISSUE THREAD

**Issue by robeving** [NickeManarin/ScreenToGif#601]
https://github.com/NickeManarin/ScreenToGif/blob/55b6ad12bd5792e3171aa45a12184e05bce993fd/ScreenToGif/App.xaml.cs#L81

So it looks like you check user for null but not AccountDomainSid. AccountDomainSid can actually be null as well which causes an exception when you run the app.

Fix is to change to user.Value.ToString()

```
var mutexName = (user != null ? user.Value.ToString() : Environment.UserName) + "_" + location;
```

**Comment by NickeManarin** [comment]
Ok, I'm going to replace with:

`var mutexName = (user?.Value ?? Environment.UserName) + "_" + location;`

**Comment by NickeManarin** [comment]
Fixed. A new version will be released shortly.
v2.21.1
