### ISSUE TITLE
ScreenToGif  stop work on windows 7 64 bit !!!  why ?  

### ISSUE THREAD

**Issue by linux0ne-su** [NickeManarin/ScreenToGif#605]
![企业微信截图_158319625822](https://user-images.githubusercontent.com/60182556/75732402-58073400-5d2d-11ea-8c25-3d6422ba33f3.png)

**Comment by NickeManarin** [comment]
Do you have .net Framework 4.8 installed?

**Comment by linux0ne-su** [comment]
.net Framework 4.8 no installed.

still need to install this software on adnroid phone??

There's no such thing in the software market...



At 2020-03-03 09:04:28, "Nicke Manarin" <notifications@github.com> wrote:

Do you have .net Framework 4.8 installed?

**Comment by NickeManarin** [comment]
So, download and install .NET Framework 4.8. 
It is required in order to work.

http://go.microsoft.com/fwlink/?LinkId=2085155

**Comment by hellishvictor** [comment]
Same problem here; after of download the portable version it didn't launch.
Solved using the v2.19.3 (which is prior to the implementation on v2.2x of .NET Framework 4.8).
https://github.com/NickeManarin/ScreenToGif/releases/tag/2.19.3

**Comment by NickeManarin** [comment]
Have you people tried to download .NET 4.8? It's a requirement to run newer releases.

**Comment by hellishvictor** [comment]
Some people dont want or can't install updates on the system. I'm one of those right now. Maybe in the future, but not now. Thanks anyway and keep up the good work, ScreenoGif is awesome.

**Comment by NickeManarin** [comment]
Closing this issue as inactive.
