### ISSUE TITLE
Screen size detection is wrong, actural 1920*1080 but show 1919*1079

### ISSUE THREAD

**Issue by levid7** [NickeManarin/ScreenToGif#606]
My screen is 1920*1080. However when I use screen mode to select, it show the screen is 1919*1079. How should I do to capture the full screen 1920*1080? Thanks.

**Comment by NickeManarin** [comment]
Which recorder are you using? The new one?
If so, which selection mode are you using?
If the "region" mode, you can drag 1 pixel to the sides to actually get that one missing pixel.

Or you could simply select the "screen" mode.

**Comment by NickeManarin** [comment]
Which recorder are you using? The new one?
If so, which selection mode are you using?
If the "region" mode, you can drag 1 pixel to the sides to actually get that one missing pixel.

Or you could simply select the "screen" mode.

**Comment by levid7** [comment]
I use the new interface and DirectX capture mode. When choosing the screen size, I use the 'screen' mode, but it tells my screen is 1919x1079. Screenshot through PrtSc is attached here, which is 1920x1080. 
![Screen](https://user-images.githubusercontent.com/32792075/75939540-7011bb80-5ec5-11ea-87fd-889802abb446.png)

**Comment by NickeManarin** [comment]
Are you using a high DPI screen?

**Comment by levid7** [comment]
I don't know whether 1920x1080 is of high DPI. This resolution is my laptop screen resolution, Thinkpad X380 Yoga.

**Comment by the-j0k3r** [comment]
DPI and resolution are separate things.

https://www.tenforums.com/tutorials/5990-change-dpi-scaling-level-displays-windows-10-a.html

Im going to guess that @NickeManarin wants to know if this setting has been changed. Default is 100% or 96DPI (DPI = [Dots Per Inch](https://en.wikipedia.org/wiki/Dots_per_inch)) If you changed it the show us what the settings are now.

**Comment by levid7** [comment]
O, I got it. Yes I have changed my screen DPI, it is 125%. When I change it back to 100%, the screen size indentification is right, 1920x1080.

**Comment by NickeManarin** [comment]
What probably is happening is that the app is receiving the resolution scaled and when converting to 96DPI, it's not rounding correctly the values.

**Comment by the-j0k3r** [comment]
This is predictable, 96DPI = 100% \ 4 = 24DPI increments for each added 25% increase, up to 225% max DPI or 240DPI

**Comment by levid7** [comment]
> What probably is happening is that the app is receiving the resolution scaled and when converting to 96DPI, it's not rounding correctly the values.

Is there any chance to fix this issue?

**Comment by NickeManarin** [comment]
@levid7 I'm working with this right now. I actually redesigning that recorder, to work better with high DPI (and multiple screens) (the other already was update with a better support).

**Comment by levid7** [comment]
Great and thanks! Waiting for the update.

**Comment by SJT1988** [comment]
Ditto, same issue, frequently off by one pixel. Not messing with resolution

**Comment by NickeManarin** [comment]
It's done. Since from now on, the recorder will support a multi-DPI set of screens, I'm displaying the actual size and the native size next to it.

![image](https://user-images.githubusercontent.com/14798947/89720335-61b15980-d9a7-11ea-9416-b3553142dd71.png)

If the screen has a scaling of x1.00, only the native size will be displayed.

![image](https://user-images.githubusercontent.com/14798947/89720350-8dccda80-d9a7-11ea-9ba1-463284615fb3.png)

I'm also working on some optional changes for the recorder UI, you'll be able to check some details about the current selected screen.

![Size details](https://user-images.githubusercontent.com/14798947/89719473-14c98500-d99f-11ea-98cd-b13651df07ae.png)

**Comment by SJT1988** [comment]
This is not my reported issue. My reported issue concerned the Cinemagraph
feature.

**Comment by NickeManarin** [comment]
@SJT1988 You received a notification about [this issue](https://github.com/NickeManarin/ScreenToGif/issues/606) because you added a comment, 18 days ago.

**Comment by levid7** [comment]
Great!. Waiting for version 2.27.
