### ISSUE TITLE
It's all black when record the video on the internet

### ISSUE THREAD

**Issue by Keneyr** [NickeManarin/ScreenToGif#608]
I tried to record the video on youku, but the result is all black . Why??
![f7f426933ff8903d2162934b1b7903d](https://user-images.githubusercontent.com/25053570/75953822-29d05280-5eed-11ea-88a7-740aa53266d7.png)

**Comment by Keneyr** [comment]
I used the latest release , version 2.22

**Comment by Keneyr** [comment]
It only failed on youku, I tried bilibili and it's ok....

**Comment by Keneyr** [comment]
Can somebody help me , I am confused and exhausted....

**Comment by Keneyr** [comment]
I got it. Turn off the hardware accelerate mode
![image](https://user-images.githubusercontent.com/25053570/75976097-b7736880-5f14-11ea-89e9-3527702c0fda.png)

**Comment by NickeManarin** [comment]
It was in the middle of the night when you opened this issue ticket. We live in different timezones, it's not possible for me to answer right away.

You could also try to recording using the DirectX capture mode, with v2.22.
