### ISSUE TITLE
there is a short pause and delay for running the ScreenToGif 2.22

### ISSUE THREAD

**Issue by dytfy666** [NickeManarin/ScreenToGif#609]
I'm sorry, but I'm having some problems!
When I double-click the ScreenToGif.exe, there is a short pause and delay before it starts
.It then takes a little time for figure 1 to appear.
The version ScreenToGif 2.21 started normally,
is the initialization process problem?
And thank you for your program.
My computer operating system is Win10 1903.

![figure 1](https://user-images.githubusercontent.com/58970365/75987193-76864e80-5f2a-11ea-9b5f-a6147467a0be.png)

**Comment by NickeManarin** [comment]
Have you found out what happened? 

It could be Windows Defender scanning the file for the first time.

**Comment by dytfy666** [comment]
en,thank you!
Maybe my computer CPU is old!
