### ISSUE TITLE
Question: Parameters to use when edit a gif from another app

### ISSUE THREAD

**Issue by stephen147** [NickeManarin/ScreenToGif#610]
I was wanting to open the gif in the editor window from FastStone image viewer. I suppose the same can be said of any other external app.

Here are the settings (which only open the app). Are there parameters that I can pass to open the file directly in the editor.

![image](https://user-images.githubusercontent.com/14054664/76075982-dcf48680-5f95-11ea-8c45-e14ca2af3f57.png)

**Comment by NickeManarin** [comment]
Jus the filename, it will open in the editor normally. You can also drag files into the desktop shortcut.

**Comment by stephen147** [comment]
Ah, the progress bar was still processing as the gif was large. I tried with a smaller file and works with the setting in the screenshot in the OP. Straight to the editor.

Thanks.
