### ISSUE TITLE
Gifski update request

### ISSUE THREAD

**Issue by byzod** [NickeManarin/ScreenToGif#611]
Bug #556 was fixed since gifski 0.10.1, [as said by the author Kornel](https://github.com/ImageOptim/gifski/issues/105#issuecomment-580512702)

But I can't find how to download .dll version of gifski 0.10.1, can you please update the gifski download link in the options? Thanks :D

**Comment by NickeManarin** [comment]
I need to build a new version using the source.

**Comment by byzod** [comment]
> 
> 
> I need to build a new version using the source.

Thanks for that, I'll wait for it 👍

**Comment by NickeManarin** [comment]
There's a major bug with Gifski 0.10.2. 
With the new timestamp system, it's not possible to set the delay of the last frame.

I'm waiting for a fix.

**Comment by NickeManarin** [comment]
I updated Gifski to v1.2.0 with a custom fix for the timings issue.
