### ISSUE TITLE
'Insert from Media' causes error

### ISSUE THREAD

**Issue by qsdnlj** [NickeManarin/ScreenToGif#612]
Hi, whenever I click on 'Insert from Media' (Ctrl+Shift+O) in the Editor, it brings up an error message that begins: "Provided filter string is not valid. Filter string should contain a description of the filter, followed by a vertical bar and the filter pattern." Here's what it looks like: [https://i.imgur.com/vXhTESk.png](https://i.imgur.com/vXhTESk.png)

Any help would be greatly appreciated. Thanks!

**Comment by NickeManarin** [comment]
From the screenshot, it looks like you are using a very old version of the app. Have you tried to download the latest version? v2.22

**Comment by NickeManarin** [comment]
Which version are you using?

**Comment by qsdnlj** [comment]
I'm using version 2.0.

**Comment by NickeManarin** [comment]
That's a very old version. Download v2.22 and it should work.

**Comment by NickeManarin** [comment]
So, have you tried to use the latest version?

**Comment by NickeManarin** [comment]
Download the latest version, v2.22.1 and it should work.

I'm closing this issue as inactive.
