### ISSUE TITLE
unable to upload gifs most of the time

### ISSUE THREAD

**Issue by kingjasko** [NickeManarin/ScreenToGif#615]
unable to upload gifs most of the time

The remote server returned an error: (400) Bad Request.

   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ScreenToGif.Util.WebHelper.<SendFile>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ScreenToGif.Cloud.Imgur.Imgur.<UploadFileAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ScreenToGif.Windows.Other.Encoder.<Encode>d__24.MoveNext()

**Comment by NickeManarin** [comment]
Which version are you using? Also, where did you download it from? 
(From the releases, using from the source, third part, etc).

**Comment by kingjasko** [comment]
2.20.1

from here : https://www.screentogif.com/downloads.html

i will try updating it to latest version i'll let u know if it works

**Comment by kingjasko** [comment]
latest 2.22.1 version seems to be working correctly, i'll post here if the problem arises again, thanks for the quick support.

**Comment by NickeManarin** [comment]
Great. Closing this issue.

**Comment by kingjasko** [comment]
I got it again on the latest version.


>    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at ScreenToGif.Util.WebHelper.<SendFile>d__6.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at ScreenToGif.Cloud.Imgur.Imgur.<UploadFileAsync>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at ScreenToGif.Windows.Other.Encoder.<Encode>d__24.MoveNext()

**Comment by NickeManarin** [comment]
Can you share with me the project that you are trying to upload?

Perhaps you are hitting a limit (size, length, quantity)...

**Comment by kingjasko** [comment]
after some more testing, I'm pretty certain the problem might be in size of the gifs im trying to upload, imgur makes the bigger gifs into .mp4 ending, i dont know what connection that would have with anything, but it always fails to upload when that happens, but with smaller gifs (under 10MB it seems) it does the job nicely

The remote server returned an error: (400) Bad Request.
