### ISSUE TITLE
Hope that the "Edit>Reduce Frame Count" action can applies to selected frames

### ISSUE THREAD

**Issue by ElliotMok** [NickeManarin/ScreenToGif#616]
I have already installed the newest version 2.22.1. The action "Edit>Reduce Frame Count" applied to all frames, even though I only selected part of frames.

**Comment by NickeManarin** [comment]
Indeed, currently it applies to all frames.

**Comment by MWalshDSPC** [comment]
+1 on this suggestion.  Sometimes there's a section of the 'video' that I want to playback at a faster speed (fast forward through a boring section of tutorial)

**Comment by NickeManarin** [comment]
Done. It will be available with v2.23.

**Comment by NickeManarin** [comment]
Btw, this was a duplicate of #584
