### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by xmha97** [NickeManarin/ScreenToGif#617]
Hello, Installer not working...
![image](https://user-images.githubusercontent.com/23485114/77847923-dee8e880-71d5-11ea-8d91-7e64dc452bd7.png)
Please help me.

**Comment by NickeManarin** [comment]
Looks like the installer had some issues accessing the file, probably because of insufficient read permissions.

Did you click "Yes" or something like that on the UAC message that poped up?

Try moving the file to your desktop and running from there.

**Comment by NickeManarin** [comment]
@xmha97 Do you still have this issue?

**Comment by xmha97** [comment]
No, Thanks.
