### ISSUE TITLE
Single-frame "screen grab"

### ISSUE THREAD

**Issue by lcichanowicz** [NickeManarin/ScreenToGif#62]
I realize the main purpose is to record over time, video, but I just want a simple static screen grab that captures hover state and pointer.  Can I do this with ScreenToGif?  If so, how?

Thanks,
Lee

**Comment by NickeManarin** [comment]
Currently, there's a feature called "Snapshot", under Options > Application > Enable snapshot mode. (Or right click on the Record button)

It captures a single frame every time you press "Snap" or your shortcut key (usually F7).

**Comment by NickeManarin** [comment]
Hi did you manage to take the snapshots?

If so, please close this question.
If not, just ask me. :)
