### ISSUE TITLE
Report plagiarism

### ISSUE THREAD

**Issue by lijingxiang888** [NickeManarin/ScreenToGif#620]
A company copied your tool and made a charging tool at the address: https://www.apowersoft.com.cn/make-gif?bd_vid=8762156119853365115

**Comment by NickeManarin** [comment]
Yes, I'm aware.
Share with others that it's a copy of ScreenToGif, a free and pen source app.

**Comment by lijingxiang888** [comment]
我觉得这是对原创的不尊重，至少应该做点什么

**Comment by lijingxiang888** [comment]
I think this is a disrespect for originality, at least something should be done

**Comment by vatterspun** [comment]
See issue #501 

> something should be done

To the extent possible, there are some sites that are attacking their reputation: https://www.portablefreeware.com/forums/viewtopic.php?p=91446#p91446
