### ISSUE TITLE
Mouse movements unstable when recording remote desktop screen

### ISSUE THREAD

**Issue by erickmp07** [NickeManarin/ScreenToGif#622]
**Bug description**
I'm working with a notebook and connected to my desktop by Remote Desktop Application.
This desktop has the ScreenToGif (version 2.22.1) installed and I'm trying to record the screen of my remote desktop, but the mouse movements are unstable.
I think that is a bug caused by de remote desktop connection because when I'm working with the desktop the mouse movements are ok.

**Steps to Reproduce**

1. Connect with a computer using the Remote Desktop Application (this computer has to have ScreenToGif installed);
2. Open the ScreenToGif;
3. Enter Record mode;
4. Start recording;
5. Move the mouse.

**Expected behavior**
The mouse movements should be fluid.

**References**
![screen-to-gif-mouse-movement-bug](https://user-images.githubusercontent.com/16216886/78291866-862e8e00-74fc-11ea-938a-80eb7e82ad6f.gif)
This gif was generated by ScreenToGif

**Device and Application Information**
OS (both): Windows 10
OS Version (both): 1909
OS Build (both): 18363.720
Architecture (both): X64
Application Version: 2.22.1

**Additional context**
I don't know if this bug is recent, but I tested two versions of ScreenToGif and the bug persists.

**Comment by NickeManarin** [comment]
If you put `false, false` on this line:

https://github.com/NickeManarin/ScreenToGif/blob/master/ScreenToGif/Windows/Recorder.xaml.cs#L177

Does it result in the same kind of unstability?

**Comment by erickmp07** [comment]
> If you put `false, false` on this line:
> 
> https://github.com/NickeManarin/ScreenToGif/blob/master/ScreenToGif/Windows/Recorder.xaml.cs#L177
> 
> Does it result in the same kind of unstability?

Yes. I changed the parameters, but the unstability persists.

**Comment by NickeManarin** [comment]
The issue was fixed by @pr8x and it will be available with the next release.
