### ISSUE TITLE
Option to align Free Text

### ISSUE THREAD

**Issue by zcraber** [NickeManarin/ScreenToGif#624]
Would be great if there is an option to align Free Text automatically. 

Something like this (screenshot from Photoshop):

![image](https://user-images.githubusercontent.com/61133303/78330939-a7e25080-75a2-11ea-9942-0b736aaeeddd.png)

**Comment by NickeManarin** [comment]
Right now, there's the Caption feature, which has an aligned option.

**Comment by mabakay** [comment]
> Would be great if there is an option to align Free Text automatically.

There is pull request with text alignment for left, center, right and justification - #779 Possibility to align text within free text

**Comment by NickeManarin** [comment]
Feature added by @mabakay.

The option to align vertically by bounding box will come after the editor get reworked to support layers.
