### ISSUE TITLE
Make the start menu shortcut available for all users in Windows 10

### ISSUE THREAD

**Issue by xmha97** [NickeManarin/ScreenToGif#629]
I’m using ScreenToGif on Windows 10.
I have a suggestion that follows:
ScreenToGif installer creating a shortcut to:
"%AppData%\Microsoft\Windows\Start Menu\Programs\ScreenToGif.lnk"
And other users can't access to ScreenToGif app.
![image](https://user-images.githubusercontent.com/23485114/78747560-ef8c2200-797e-11ea-8668-6c463e8540eb.png)
I have to copy the shortcuts to another user, manually.
Please make the start menu shortcut available for all users.
You should change on ScreenToGif installer to create the shortcut for all users:
"%ProgramData%\Microsoft\Windows\Start Menu\Programs\ScreenToGif.lnk"
Thanks

**Comment by NickeManarin** [comment]
I'll add an option to set the shortcut to all users, right below the "Start menu" checkbox.

**Comment by xmha97** [comment]
> 
> 
> I'll add an option to set the shortcut to all users, right below the "Start menu" checkbox.

Thanks <3

**Comment by NickeManarin** [comment]
Done, it will be available with the next release.
Also, the UAC popup will only appear when necessary.

![image](https://user-images.githubusercontent.com/14798947/81223393-4d327f00-8fbc-11ea-94e1-0e8b14e90b64.png)

**Comment by xmha97** [comment]
Thanks 😘
