### ISSUE TITLE
I think you could make the "Save" / "Cancel" button bigger in the lower right corner

### ISSUE THREAD

**Issue by nanch** [NickeManarin/ScreenToGif#63]
It's kind of hard to see/notice on large screens.

Or you could use a higher contrast color since it's a primary action once you're in the "save" mode.

Cheers!

**Comment by NickeManarin** [comment]
I'll have to fiddle with some ideas, to accommodate multiple resolutions. Thanks ;)

**Comment by NickeManarin** [comment]
I increased the text size by a few points. I can't increase too much because it would cause problems with the localization (some languages have bigger words).
