### ISSUE TITLE
With relative paths, the display of additions is buggy

### ISSUE THREAD

**Issue by wvxwxvw** [NickeManarin/ScreenToGif#631]
![2020 04 08_173111](https://user-images.githubusercontent.com/13194155/78796586-326dea00-79bf-11ea-9960-2b99541baae5.jpg)

**Comment by NickeManarin** [comment]
Thanks, it was fixed.

![image](https://user-images.githubusercontent.com/14798947/78815815-27a75b00-79a7-11ea-8888-8eaff1a53eb5.png)
