### ISSUE TITLE
Installation doesn't proceed

### ISSUE THREAD

**Issue by saschanaz** [NickeManarin/ScreenToGif#632]
![image](https://user-images.githubusercontent.com/3396686/78829105-0f0a6580-79e6-11ea-940b-6f0b09c22475.png)

No UAC prompt on the taskbar and the cancel button doesn't respond. I'm using Windows 10 build 19041.153.

**Comment by NickeManarin** [comment]
I noticed that for some people the UAC prompt takes more time to appear.
For how long did you wait?

This process is handled by the MSI (Microsoft Installer), so I have no control.

**Comment by saschanaz** [comment]
At least 10 minutes and zero progress. 🤔

**Comment by NickeManarin** [comment]
Not when waiting for the UAC to appear. The process was already called... 

Just to check, is this a new installation, a manual upgrade (you manually downloaded the update), or it was downloaded and started installing automatically by the app?

You can try to run the update manually as an admin. By using a command prompt.

- Open Powershell as administrator:
- Run this command (replacing the path to the installer): `msiexec /i “pathtotheMSIfile”`

**Comment by saschanaz** [comment]
It's a new installation. I waited hours and it did nothing.

**Comment by NickeManarin** [comment]
Have you tried to run as admin via Powershell?

Btw, are you the administrator of the PC?
Do you have the UAC enabled?

**Comment by saschanaz** [comment]
![image](https://user-images.githubusercontent.com/3396686/78898576-517a8380-7a74-11ea-9222-fa6f4ed78fc4.png)

![image](https://user-images.githubusercontent.com/3396686/78898656-6f47e880-7a74-11ea-84fa-6c96a780f88d.png)

Well, it still doesn't do anything. It now insists a dialog is detected but I'm not seeing anything on my taskbar.

**Comment by NickeManarin** [comment]
You should be doing this when running as admin:

![Install](https://user-images.githubusercontent.com/14798947/78901426-b1f6ca00-7a4e-11ea-88bb-fd1b0d8fdbe8.gif)

Anyway, I'm going to search for a cause.

**Comment by saschanaz** [comment]
>You should be doing this when running as admin:

True, and I'm exactly doing that.

**Comment by NickeManarin** [comment]
Oh no, I wanted to write "The installer should be doing this:". My mistake.

**Comment by saschanaz** [comment]
Tried this again today with the same installer and it now works. Not sure what's the difference today. Feel free to close this.

**Comment by NickeManarin** [comment]
Oh nice!

Do you remember what changed? Did you restart the computer?

**Comment by saschanaz** [comment]
>Do you remember what changed? Did you restart the computer?

Yes, and IMO that's the only possible reason. "RESTART YOUR MACHINE" 😂
