### ISSUE TITLE
[extras] not possible to download SharpDx

### ISSUE THREAD

**Issue by n8v8R** [NickeManarin/ScreenToGif#638]
* W10 Pro x_64 v1909 b18636.752
* STG portable 2.23.1
___
![Annotation 2020-04-15 134254](https://user-images.githubusercontent.com/13611490/79333819-b3246d00-7f0e-11ea-8eca-86772ea90d57.png)

![Annotation 2020-04-15 134255](https://user-images.githubusercontent.com/13611490/79333833-b7e92100-7f0e-11ea-9a5c-c5224b86f118.png)
___
issue does not exhibit with downloads of FFmpeg | Gifski

**Comment by NickeManarin** [comment]
Strange, you can download manually from here:

https://github.com/NickeManarin/ScreenToGif/wiki/Help-▪-FAQ-▪-Unable-to-download-SharpDx

But if you are able to download Gifski, the download of SharpDx should work too.

**Comment by n8v8R** [comment]
The manual download worked.

Seeing the app error it might be caused by a node's GroupPolicy -> ECC curve order (policy setting determines the priority order of ECC curves used with ECDHE cipher suites.) and only the following curves are permitted in this order:

- curve25519
- brainpoolP512r1
- brainpoolP384r1
- brainpoolP256r1
- secP521r1
- secP384r1
- secP256r1
- secp224r1
___
The node has also TLS1.3 enabled which is not by default via this registry tree:

`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Client`

**Comment by NickeManarin** [comment]
@n8v8R Can I do anything within ScreenToGif to fix it? Or is it something that you configure it in your OS?

**Comment by n8v8R** [comment]
Did not re-test since the manual download but now have, meanwhile the node's OS upgraded to v2004 b19041.450 and STG 2.26.1, and the issue does not exhibit.
