### ISSUE TITLE
Wiki Text Suggestions

### ISSUE THREAD

**Issue by phil-davis** [NickeManarin/ScreenToGif#64]
I have a few minor edit suggestions for the Wiki https://github.com/phil-davis/ScreenToGif-Wiki/commit/6a4330138657216d148f8ad09d6b88530ac199af
It is not possible to directly fork a GitHub WiKi and make pull requests. I cloned like described here:
http://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

**Comment by NickeManarin** [comment]
Thank you :D

I'll see if I understand how to merge the wiki contents with Git or I'll merge manually.

**Comment by phil-davis** [comment]
There is probably some way to pull a commit from my repo.

**Comment by NickeManarin** [comment]
Indeed. I'll give it a try tonight.

**Comment by NickeManarin** [comment]
Done.
