### ISSUE TITLE
Insert "Shapes" is bafflingly difficult to work with.

### ISSUE THREAD

**Issue by jaxjexjox** [NickeManarin/ScreenToGif#642]
This particular menu it's extremely easy to put a shape down that you don't want and can't seem to adjust.

Luckily I haven't applied the shape, to the GIF I'm attempting to build, however I simply can't use this function because suddenly I lose the ability to resize / move the object I've applied - it's just kind of stuck there, no where in the UI is there a 'clear shapes' that I can see

If I hit cancel, it closes the shapes menu, removing the (proposed) shape. If I re-open the shapes section the item is back, un-selectable, unable to be adjusted.

Can there be a 'clear all shapes' or "shape highlight selection tool" or something?

**Comment by jaxjexjox** [comment]
Ok look I've found the option - I apologise, BUT........


where it says "select"  maybe just put an arrow / mouse cursor to th eleft of that text - will be useful.

**Comment by NickeManarin** [comment]
Yes, the UI/UX isn't great. That should go away in a future version, favoring a system like what Photoshop does (Selection mode, Insert shape mode, etc).
