### ISSUE TITLE
Default filename and some jingy thingy

### ISSUE THREAD

**Issue by jaysonragasa** [NickeManarin/ScreenToGif#648]
I added a way to have a default filename as date and time. Is this possible to be implemented in the official version?
![image](https://user-images.githubusercontent.com/63760343/80932933-275a7e00-8df4-11ea-8c60-3a8951f6a1b0.png)

What about adding a thing like Jing does? I don't mind having another thing like this  and if this is implemented. I will totally ditch jing for the rest of my life. I have been using Jing for like 4 years now I think. LOL

![image](https://user-images.githubusercontent.com/63760343/80932988-5ec92a80-8df4-11ea-9114-f5ccbd94278b.png)  
![asd](https://user-images.githubusercontent.com/63760343/80933174-1d854a80-8df5-11ea-9827-0cd2172cca61.jpg)

-- your fan since version [**2.14.1**](https://github.com/NickeManarin/ScreenToGif/releases/tag/2.14.1)

**Comment by NickeManarin** [comment]
Hi, you can use the date format by typing a date format between two questions marks: '?'.
If you move your cursor on top of the filename text box, you'll see that information.
https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings

You can right click on the system tray icon to launch the recording, or use keyboard shortcuts set in Options > Shortcuts.
![image](https://user-images.githubusercontent.com/14798947/80989748-c0e15a00-8e0b-11ea-86dc-3fd72236e238.png)

**Comment by jaysonragasa** [comment]
> Hi, you can use the date format by typing a date format between two questions marks: '?'.
gotcha

> You can right click on the system tray icon to launch the recording, or use keyboard shortcuts set in Options > Shortcuts.
Yes that should be great. I think I will re-create Jing floating blob

**Comment by jaysonragasa** [comment]
closing this issue now! Great work as always!!
