### ISSUE TITLE
Why everywhere he writes the same thing. "Are you sure you want to go out?"

### ISSUE THREAD

**Issue by maxvlas** [NickeManarin/ScreenToGif#651]
**Hello!**
In the settings it is like this.
![2020-05-10_185532](https://user-images.githubusercontent.com/11572859/81504090-1035f780-92f0-11ea-9246-797f22cb847a.png)
I just did it, I didn’t click anything in the editor, I tried to immediately close this window and it shows this window.
![2020-05-10_185717](https://user-images.githubusercontent.com/11572859/81504139-3d82a580-92f0-11ea-851d-b750cf511595.png)
Why does it write in the window that I can open it.
Where will I open it if I did not save even the project.
Why doesn’t he write here that the data will be lost, etc., for example, how other programs warn.
Here's an example in paint.net
![XntT2DDeJP](https://user-images.githubusercontent.com/11572859/81504232-b8e45700-92f0-11ea-8257-cc3e722f72a0.gif)
I saved the project
![2020-05-10_190225](https://user-images.githubusercontent.com/11572859/81504278-095bb480-92f1-11ea-925e-e997a497a2b5.png)
I close the editor and again this window shows me.
![2020-05-10_190258](https://user-images.githubusercontent.com/11572859/81504315-2a240a00-92f1-11ea-9c66-3a1269987ebe.png)
Why does he show me if I have already saved the project?

**This warning window seems to me to work incorrectly, it shows it everywhere.**
![8WIQwmlEGi](https://user-images.githubusercontent.com/11572859/81504468-17f69b80-92f2-11ea-80a4-717abc860e50.gif)

**Comment by NickeManarin** [comment]
ScreenToGif currently works in a different way than PaintNET. 

When you record something, the frames are stored in a cache folder. They stay there until you manually discard them (or when it's discarded by the cleaning task).

**Comment by maxvlas** [comment]
Thank you very much figured out.

  12.05.2020, 02:19, Nicke Manarin <notifications@github.com>

  ScreenToGif currently works in a different way than PaintNET.

  When you record something, the frames are stored in a cache folder. They stay
  there until you manually discard them (or when it's discarded by the cleaning
  task).
