### ISSUE TITLE
Delayed mouse cursor.

### ISSUE THREAD

**Issue by maxvlas** [NickeManarin/ScreenToGif#652]
**Hello!**
When I start recording from the board there, the mouse cursor moves normally.
![2020-05-13_095046](https://user-images.githubusercontent.com/11572859/81780650-8f4d4a80-94ff-11ea-8ba7-46433a9c123b.png)
When I turn on screen recording
![2020-05-13_094652](https://user-images.githubusercontent.com/11572859/81780348-0e8e4e80-94ff-11ea-9267-f97f167adc8e.png)
and move the mouse in the program window, it moves with a slight delay, not as fast as on the Windows screen.
Downloaded earlier versions there too.
Is this the way it should be, a slight delay in the movement of the mouse or not?
Maybe this is because my computer is already old, 15 years old?
Checked on the [ShareX](https://github.com/ShareX/ShareX) program I do not have a mouse cursor delay there.
Attached a gif there it is visible how slowly moves in a window, and after switching off is faster.
![2hMluupbjk](https://user-images.githubusercontent.com/11572859/81781194-6da09300-9500-11ea-8de2-ae71b5acd41f.gif)

**Comment by NickeManarin** [comment]
That's because the recorder is getting the mouse position and image to render on top of the captured image.

The other program uses FFmpeg if I recall correctly.

If you upgrade to Windows 10, you can use a new capture method which is faster (DirectX).

**Comment by maxvlas** [comment]
> If you upgrade to Windows 10, you can use a new capture method which is faster (DirectX).
And on Windows 7 can not be done?
I have these settings
![2020-05-15_181825](https://user-images.githubusercontent.com/11572859/82066998-cfb3f080-96d8-11ea-943f-bec89f4821d6.png)

**Comment by NickeManarin** [comment]
The DirectX mode cannot be used in a Windows 7 machine. It's not supported by the DesktopDuplication API, made by Microsoft.

**Comment by maxvlas** [comment]
> The DirectX mode cannot be used in a Windows 7 machine.

This is clear. Thanks for the answer.
I'm just asking on Windows 7 you can’t do anything already? Only Windows 10 to set?

**Comment by NickeManarin** [comment]
You can try enabling the "image cache" (K3w b na...) and the async recording. Not sure if it will help you.

![image](https://user-images.githubusercontent.com/14798947/82156919-a0c28980-9854-11ea-96f8-e2594b2e8ec1.png)

**Comment by maxvlas** [comment]
> You can try enabling the "image cache" (K3w b na...) and the async recording.
I will try this.
Thank you very much for your help.
