### ISSUE TITLE
"Save to clipboard" "File" option doesn't seem to copy image to clipboard?

### ISSUE THREAD

**Issue by fluffynuts** [NickeManarin/ScreenToGif#653]
First, thanks for ScreenToGif (and I've donated, after just a few minutes usage, because it's really good).

Now on to the issue I'm having: I create a recording, select "Copy to clipboard", toggle "File" on, and save. ScreenToGif says it's copied to the clipboard, but I notice that I can't paste into browser inputs (like this one) which would accept image data. So I have to save as a file, open with windows photo viewer and copy/paste from there.

I'm not sure how to get ScreenToGif to record itself (opening multiple instances didn't get me there), so I've used RecordIt -- which I want to stop using (:

https://recordit.co/tObVAwQTy4

**Comment by NickeManarin** [comment]
Hi, thanks for the donation. :)

I'm assuming that you are running the latest version.
Windows does not support copying an animated gif as image, only single frames images are supported.

When copying as a 'file', you can paste in the file explorer as if you wen there and pressed Ctrl + C on the exported file.

For recording ScreenToGif using itself, go to Options > Application and enable multiple instances. Or simply duplicate ScreenToGif.exe and execute the copy.

**Comment by fluffynuts** [comment]
Thanks for getting back to me.

I tried to use the multiple instances setting to get ScreenToGif to record itself, but the second instance didn't show up it's recording area. Anyways, I don't think it's something that would often matter (:

**Comment by fluffynuts** [comment]
Also what you said about not being able to copy/paste gifs on windows makes something else I saw today make sense: when I copied from Windows Photos to Slack, I got a png sent, which is not what I expected. I figured (incorrectly) that it was slack being silly (:

**Comment by NickeManarin** [comment]
It should appear exactly where you left the previously instance of the app, but first you need to save the settings by closing the Options window.

**Comment by NickeManarin** [comment]
Yes, Windows Photos also copies as a PNG rather than a Gif.

**Comment by BruceLee569** [comment]
Perhaps automation can be automated to complete the operation of opening the copy. When I press `CTRL + S`, save the GIF to the default folder, then open the folder and select it, send the `Ctrl + C` event of the keyboard to copy the GIF Go to the shear plate.

**Comment by NickeManarin** [comment]
@BruceLee569  That's basically what is done when you select the option to copy as file.

Windows has no support for copying Gifs as image, only as file.
Same as Ctrl + C the file on Windows Explorer.

**Comment by BruceLee569** [comment]
> @ BruceLee569 选择要复制为文件的选项时，基本上就是完成此操作。
> 
> Windows不支持将Gif复制为图像，而仅复制为文件。
> 与Ctrl + C相同，Windows资源管理器中的文件。

So how is telegram detect to the GIF replicated in my clipboard?

**Comment by NickeManarin** [comment]
@BruceLee569 It probably gets the path copied and loads manually the image.

Try saving and set to copy as "File" and see if Telegram is able to load the gif properly.

![image](https://user-images.githubusercontent.com/14798947/117583561-28487e80-b0de-11eb-801e-968247f64919.png)

Telegrams is able to load the gif if the clipboard is set to copy as "File":

![Tele](https://user-images.githubusercontent.com/14798947/117583635-a0af3f80-b0de-11eb-9e19-7db07092e993.gif)
