### ISSUE TITLE
DirectX capture mode won't work under Win10 2004 update, only blank frames was captured.

### ISSUE THREAD

**Issue by Mirr0ch1** [NickeManarin/ScreenToGif#655]
Hi, I'm using Win10 2004 with an AMD 5700XT card. After updating to the March Update, the DirectX capture mode of ScreenToGif stopped working.

I've tried to reinstall ScreenToGif / run under administrator mode / redownload the lastest version of sharpdx libs from nugetm only none of those worked.

I'm not a technical guy myself, therefore I wont be able to provide any kind of logs.
Would you like to take a look into this issue? huge thx

**Comment by sommerper** [comment]
I just installed the app for the first time and I'm getting a black recording with mouse cursor trails. Could be related?

**Comment by NickeManarin** [comment]
Does it still work with the BitBlt (old) capture method?

**Comment by NickeManarin** [comment]
>@sommerper I just installed the app for the first time and I'm getting a black recording with mouse cursor trails. Could be related?

Could you tell me more about your computer? Windows version, graphics card model, ScreenToGif version, etc.

Also, are you trying to record DRM content?

**Comment by Mirr0ch1** [comment]
damnnn

A quick update: it's working now, out of no reason. please close this issue.

sorry for bothering😂
