### ISSUE TITLE
Hide mouse press highlight

### ISSUE THREAD

**Issue by Pawper** [NickeManarin/ScreenToGif#658]
Hi, I was doing a recording of dragging to select text, and I couldn't figure out how to hide the yellow circle highlighting the mouse press. I would like the option to disable this.

**Comment by NickeManarin** [comment]
It's a post-recording task. Just remove it from here:

![image](https://user-images.githubusercontent.com/14798947/82344025-ea80b080-99c9-11ea-932f-5dde6c15430d.png)

**Comment by vatterspun** [comment]
> It's a post-recording task. Just remove it from here

I was wondering that too.  Thanks.
