### ISSUE TITLE
Feature request: temporarily disable automated tasks

### ISSUE THREAD

**Issue by fart20** [NickeManarin/ScreenToGif#664]
It should be possible to temporarily disable automated tasks. I have not found a way to accomplish this, except the delete them entirely. But when I would need it later, I would have to configure all settings again (e.g. key strokes).

Suggested solution: add an "active" option to all tasks, which is true by default.

Additional issue:
The table of all automated tasks is sortable. I don't think that should be possible, because the order of tasks is relevant.

Additional question:
What is the meaning of the colors of each row? I added a key stroke task which is display with a green background, even though I have not configured that color.

**Comment by NickeManarin** [comment]
I added a checkbox both in the table and in the Edit window to enable the tasks.
Old tasks (from previous version of the app) and newer tasks (when creating them) will be set to enabled by default.

![image](https://user-images.githubusercontent.com/14798947/83340028-e26a2000-a2a9-11ea-9f86-03147c6c3286.png)

![image](https://user-images.githubusercontent.com/14798947/83340033-f1e96900-a2a9-11ea-9fee-74f329a75556.png)
(Wording may change, but I think that "Enable" is a bit better)

I removed the possibility to sort the table, as it was indeed something that should not be possible.

The table style uses a different color for alternate rows, you can find the same style in the Recent Projects table.

**Comment by fart20** [comment]
Dear developer guy, you are soooo awesome! 😄
