### ISSUE TITLE
国产gif加水印的软件都要收费，这个软件真是良心哈，免费好用功能强大，第一次发帖哈。

### ISSUE THREAD

**Issue by hehu158** [NickeManarin/ScreenToGif#665]
国产gif加水印的软件都要收费，这个软件真是良心哈，免费好用功能强大，第一次发帖哈。

**Comment by Jerrylum** [comment]
謝謝，别忘記贊助作者 :)

He said: some software with the "Gif watermark" function is not free in China. This software is free and powerful. Also, this is my first issue, haha.

**Comment by NickeManarin** [comment]
😊
