### ISSUE TITLE
黑色背景的gif图片编辑一下为什么就变成黑色背景了？

### ISSUE THREAD

**Issue by lz1473** [NickeManarin/ScreenToGif#666]
黑色背景的gif图片编辑一下为什么就变成黑色背景了？

- [ ] 
![Image of Yaktocat](http://yuntu88.oss-cn-beijing.aliyuncs.com/fromlocal/lz1473@qq.com/20200602/jyMmpZsDwX.gif)
![Image of Yaktocat](http://yuntu88.oss-cn-beijing.aliyuncs.com/fromlocal/lz1473@qq.com/20200602/4aK5375Afc.gif)

**Comment by lz1473** [comment]
透明的图片变成了黑色背景的图片了

**Comment by lz1473** [comment]
Why a picture with a transparent background becomes a picture with a black background

**Comment by NickeManarin** [comment]
Go to `Options > Extras` and download FFmpeg.

Use that encoder to export your gifs. The other encoders don't support transparency.
