### ISSUE TITLE
The new Selection Mode sometimes eat my CPU

### ISSUE THREAD

**Issue by dschiller** [NickeManarin/ScreenToGif#667]
The new Selection Mode where you can draw a Rectangle on the Screen sometimes make my PC unusable while dragging the Borders of the Rectangle to select the Record Area. Per Move it gets slower and slower until the Computer freezes and Screen2Gif chrashes.

**Comment by NickeManarin** [comment]
Do you have multiple screens or are you running the app on a laptop/notebook?

I'm starting the design of that window from the scratch again, with a better support for multiple screens.

**Comment by dschiller** [comment]
Hi Nicke, it is Multiple Screens on a Desktop PC.

**Comment by liuyescv** [comment]
Thanks for the update

**Comment by NickeManarin** [comment]
The recorder was fully reworked.
I also disabled by default the marching-ants animation that could cause slowdowns during the selection mode (but it can be turned back in).

**Comment by dschiller** [comment]
Thanks a lot! It seems the Portable Version didn't get this Update.

**Comment by NickeManarin** [comment]
It's not yet available, it's due to next weekend.
