### ISSUE TITLE
Clean Wiki and other pages?

### ISSUE THREAD

**Issue by yarecky1** [NickeManarin/ScreenToGif#669]
Hi,

Maybe it's time to clean wiki page? ;)
For instance: [this page](https://github.com/NickeManarin/ScreenToGif/wiki/Help-%E2%96%AA-Issues-%E2%96%AA-Error-while-opening) says that some bug will be fixed next weekend (Feb 22nd). :)

J.

**Comment by NickeManarin** [comment]
I removed that page, but yeah, the wiki needs some attention.

**Comment by yarecky1** [comment]
Checked other pages on Known Issues wiki page [here](https://github.com/NickeManarin/ScreenToGif/wiki/Help-%E2%96%AA-Known-issues) and the rest seems to be OK. Close for now.

**Comment by NickeManarin** [comment]
Thanks!
