### ISSUE TITLE
Download button defaults to Documents instead of Downloads folder

### ISSUE THREAD

**Issue by AmadeusW** [NickeManarin/ScreenToGif#673]
This is a very minor bug.
The download button in the Update window opens file browser in Documents folder, even though the standard followed by all apps is to open the Downloads folder
![image](https://user-images.githubusercontent.com/1673956/84193232-f226f880-aa4f-11ea-8493-e50e4d209ed8.png)

**Comment by NickeManarin** [comment]
As far as I remember the window was built from scratch a few releases ago, to support automatic updates.
Now there's a simple 'Update' button, without the need to select a folder.

**Comment by NickeManarin** [comment]
Closing this issue as newer version of the app have a different behavior.
