### ISSUE TITLE
[Improvement] Remove green progress animation on task bar when importing a video

### ISSUE THREAD

**Issue by theFireProjet** [NickeManarin/ScreenToGif#674]
## Steps to reproduce the issue
1. Open the Editor
2. Load a video
    press (File) > Load
    pick a video file (.mp4)

"Import frames from video" window opens up

### Actual behaviour
While the import window is open, a green progress indicator animation plays on the "ScreeToGif - Editor" window on the task bar. It is really annoying and pointless.

### Expected behaviour
The animation is misplaced and shouldn't be there.
<details>
<summary>Explination</summary>
This animation indicates an action in progress, but there is none. It's not used whenever a program is simply waiting for the user to finish a task, it's used when the <b>program</b> is working on a task on its own. If the user randomly pauses their task in ScreenToGif exactly at that point and does something else, the animation continues infinitely and keeps distracting the user.
</details>

### Screenshot
![Screenshot (434)](https://user-images.githubusercontent.com/61639215/84449956-1f8dc500-ac4f-11ea-9907-f7e616f4f672.png)

### Context

ScreenToGif version: 2.25

**Comment by NickeManarin** [comment]
Done.
