### ISSUE TITLE
[Problem] High CPU usage after selecting frames to import from a video

### ISSUE THREAD

**Issue by theFireProjet** [NickeManarin/ScreenToGif#677]
## Steps to reproduce
1. Open the ScreenToGif Editor
2. Load a video
    press (File) > Load
    pick a video file (.mp4)

"Import frames from video" window opens up

3. Maximize the window
4. Adjust the starting point of the picture sequence that's supposed to be imported
    quickly press the arrow up button to increase the time by 10ms a lot of times (20 to 50 times, 200 to 500 ms)

### Actual behaviour
While adjusting the starting point, the preview picture of the current frame updates quickly. It doesn't lag behind, this becomes evident when switich directions (changing from pressing arrow down or up). Still the CPU load continues a couple of seconds, maybe half a minute or a minute after stopping to adjust the settings. For that time the loading animation of the mouse pointer flickers while it is in ScreenToGif.
Here are the exact values: ScreenToGif creates 100% load on one logical core and 25% load for the program overall. (This means, one _physical_ core is used at 100% without multi-threading.) While ScreeToGif is not busy it doesn't use more than 1% overall most of the time.

### Expected behaviour
The CPU load is understandable while the program has to load the signle frames for the preview picture while changing the starting point. I assume that as soon as the preview pictures are not loaded (don't change) anymore (in my case this is max. 1 second after I don't adjust the settings anymore) the CPU load should stop.

Maybe the CPU load has a good reason, but I don't know the inner mechanics of ScreenToGif. From my perspective (that I explained above), it seems like the program creates more CPU load than necessary. I want to report this just to check whether it is indeed a valid issue or I'm mistaken.

### Context

**Video properties**
Resoluation: 1440*2960
Total bitrate: 5441 kBit/s
Frame rate: 35.96 frames/second

**Import properties**
Scale: 100 %
Resolution: 1440*2960
Frame rate: 60 fps (maximum)

**Screen properties**
Resolution: 1920*1080
Windows scale setting: 125% (default for notebooks)

**CPU properties**
Model: Intel Core i5-8350U @ 1.70GHz
Base speed: 1.90GHz
Speed under load from ScreenToGif: 3.50-3.60 GHz
Physical cores: 4
Logical cores: 8

**Programm properties**
ScreenToGif version: 2.25

**Comment by NickeManarin** [comment]
There's not much else that I can do besides recommending you to switch the importer to FFmpeg. 
The default importer uses a media player to load the video and capture the stills by scrubbing.  

What that media player uses in its core is beyond me.

**Comment by NickeManarin** [comment]
As I wrote before, switch to import using FFmpeg.

It's on the top right corner of the Video Source window.
