### ISSUE TITLE
Question / feature request : hide mouse cursor in the recording

### ISSUE THREAD

**Issue by Lucas-C** [NickeManarin/ScreenToGif#679]
Hi

I'd like to generate a GIF by recording some manual steps performed in a web browser.
However, I dot not want the mouse to appear on the final recording.

Would it be feasible to adapt this software to "ignore" the mouse cursor ?

Regards

**Comment by NickeManarin** [comment]
Head over Options > Recorder and untick the option to capture the mouse cursor.

**Comment by Lucas-C** [comment]
Wonderful ! Thank you very much
