### ISSUE TITLE
Question / feature request : specify a recording framerate below 1 FPS

### ISSUE THREAD

**Issue by Lucas-C** [NickeManarin/ScreenToGif#680]
Hi

I'd like to generate a GIF by recording some manual steps performed in a web browser.
However, because the process is long & slow, I'd like to only take a screen capture once every 10s or every minute.

Is it possible to do so already ? It seemed to me that the minimum FPS is 1.

Else, would it be possible to support a FPS between 0 & 1 please ?

Regards

**Comment by NickeManarin** [comment]
Hi, this feature was implemented, but it is not yet available.

It will be available with v2.26, this month.

**Comment by Lucas-C** [comment]
Wonderful, thank you !
