### ISSUE TITLE
Control the speed of the recorded GIF

### ISSUE THREAD

**Issue by amirmeimari** [NickeManarin/ScreenToGif#681]
Hey 👋
I don't know if this is a UX issue or docs are not complete yet. how can I increase or decrease the speed of the output gif file? I've change this settings but my output speed remains the same!
for example if I recorded a gif in 3 sec, I wanted an output file with just a 1-second duration.

![image](https://user-images.githubusercontent.com/34706947/85268064-45a33880-b48b-11ea-9eaf-3f803791f322.png)

**Comment by NickeManarin** [comment]
Hi, you need to select the frames that you want to manipulate, click on any of those three delay options and click apply later.

In this case, I think that the "Scale" should do the job. Apply the manipulation, check on the Statistics tab to see if the animation has 1 second or not.

**Comment by amirmeimari** [comment]
Thank you for the reply but this solution is not working for me. I did the following:

recorded a 10-sec gif and then selected all frames and reduced the "Scale" to 1 then exported it.
the output file is exactly the same. I've looked at the statics tab the duration is different though.
take a look at this screenshots:

statics before the change:
![image](https://user-images.githubusercontent.com/34706947/85361568-805fac00-b531-11ea-8545-177defb88a92.png)

then selected all frames and changed the scale:
![image](https://user-images.githubusercontent.com/34706947/85361589-979e9980-b531-11ea-9c4c-9f8297143870.png)

static tab after the change:
![image](https://user-images.githubusercontent.com/34706947/85361618-a8e7a600-b531-11ea-9efa-aadee9f8bb6f.png)

as you can see the duration changed but the output file is not changed. and the output file size in both scenarios the same (17.6KB).

output file before the change:
![before](https://user-images.githubusercontent.com/34706947/85361955-873aee80-b532-11ea-91f1-d4e7ca562480.gif)

output file after the change:
![after](https://user-images.githubusercontent.com/34706947/85361982-96ba3780-b532-11ea-94ab-16eb469b57b8.gif)

I'm using version 2.25 windows 10 pro version 2004

**Comment by NickeManarin** [comment]
Try reducing the framerate. 
The frames are hitting the minimum delay (i'ts written in the green text below the scale value).
I need to increase the brightness of that text in dark mode.

**Comment by NickeManarin** [comment]
The brightness of the info texts was increased.
Your issue can be solved by using the "Reduce frame rate" feature in order to cut down frames from the recording.

**Comment by SoutrikDas** [comment]
For me Selecting all the frames then scaling the delay duration % to 1 works.

**Comment by squidovado** [comment]
I have this bug repro. Version 2.37.1.0
Setting delay works OK for playback, but when I save the gif itself, it's speed isn't changed.
