### ISSUE TITLE
Question:  What is the difference between distributions?

### ISSUE THREAD

**Issue by Geeyun-JY3** [NickeManarin/ScreenToGif#684]
What I want to know is mainly about the Microsoft Store version because I notice that you wrote “Some features are disabled due to enforced policies.” in the “Options > About” page. 
So I just want to know:
1. What is difference between Microsoft Store version and installer version(`.msi`)?
2. What is difference between Microsoft Store version and portable version?

**Comment by NickeManarin** [comment]
Here's the difference:

* `Installer`: The app + plugins + visualstyle.xml for the icon on the start menu.
* `Portable`: Just the app.
* `Store`: The app (except: auto-update, plugin download, post encoding commands, links to donation) + visualstyle.xml for the icon on the start menu.

For the app being distributed in the Store, I can't call other assemblies or download stuff from the web. Also, I can't add links for donations.

**Comment by Geeyun-JY3** [comment]
> Here's the difference:
> 
> * `Installer`: The app + plugins + visualstyle.xml for the icon on the start menu.
> * `Portable`: Just the app.
> * `Store`: The app (except: auto-update, plugin download, post encoding commands, links to donation) + visualstyle.xml for the icon on the start menu.
> 
> For the app being distributed in the Store, I can't call other assemblies or download stuff from the web. Also, I can't add links for donations.

Got it.
Thx.
