### ISSUE TITLE
How to remove green artifacts?

### ISSUE THREAD

**Issue by andrecool-68** [NickeManarin/ScreenToGif#685]
This happens when a project file is saved to a Gif file.
![000](https://user-images.githubusercontent.com/3471892/86563271-c161b280-bf6c-11ea-857d-f398fd7a0577.gif)
![Безымянный](https://user-images.githubusercontent.com/3471892/86565418-75b10800-bf70-11ea-809f-a08a7c739a0d.png)

If you save the project in mp4 (ffmpeg.exe) then there are no such artifacts

![1111111](https://user-images.githubusercontent.com/3471892/86565689-fd971200-bf70-11ea-911a-2332bb59a97d.png)

Please help me solve this problem!

**Comment by NickeManarin** [comment]
Just update to v2.26, it will work normally.
This issue was caused by the encoder not being able to decide which green color to pick as the transparent key of that frame.
