### ISSUE TITLE
Editor page is not displayed properly

### ISSUE THREAD

**Issue by Jasonwi** [NickeManarin/ScreenToGif#691]
version 2.26.1
OS : Windows10 1909
CPU : AMD R5 4600U
GPU : Vega 6
displayed like broken but the program work normal 
maybe the GUI failed when call the GPU

![Snipaste_2020-07-13_10-55-38](https://user-images.githubusercontent.com/59698185/87268483-110c2500-c4fd-11ea-970c-a728ab74c0bc.png)

**Comment by NickeManarin** [comment]
Looks like a video driver issue. Have you tried to run the app on Software rendering mode?

> Options > Application > Disable hardware acceleration.

**Comment by Jasonwi** [comment]
it's worked



Form mobile client
在 Nicke Manarin <notifications@github.com>，2020年7月15日 上午2:36写道：

Looks like a video driver issue. Have you tried to run the app on Software rendering mode?

Options > Application > Disable hardware acceleration.

**Comment by NickeManarin** [comment]
Try updating your video driver and see if it works normally next time.
