### ISSUE TITLE
gifski encoding tiny bug

### ISSUE THREAD

**Issue by JohnJane-Doe** [NickeManarin/ScreenToGif#693]
![1](https://user-images.githubusercontent.com/68457457/87846039-d690f680-c907-11ea-8f07-1fa58336c719.png)

after encoding
last frame breaks in two

![2](https://user-images.githubusercontent.com/68457457/87846044-e14b8b80-c907-11ea-988c-ba54ec56c5a1.png)

**Comment by NickeManarin** [comment]
That's a workaround for another issue with the encoder. It should go away with the next release of it.

**Comment by NickeManarin** [comment]
Fixed.
