### ISSUE TITLE
Cinemagraph feature "smears" its result

### ISSUE THREAD

**Issue by SJT1988** [NickeManarin/ScreenToGif#694]
The "ScreenToGif" saving option (default) that finds unchanged pixels works great sometimes, not-so-great other times. I commonly throw up image sequences where almost half of the pixels are unchanged but it can't detect them. Comparable gifs that are barely 8mb are sometimes 20mb because of this.

I wanted to paint-in an inverted chroma key using the Cinemagraph feature. This is supposed to literally highlight pixels in an image that are changing over the sequence. When you activate this tool, the image preview force-zooms to 100%. After painting, the program thinks for a bit and SMEARS the zoomed-out image within the painted area over the 100% area. I have not verified any kind of workaround for this. This is an important feature and I hope it gets fixed?
![Annotation 2020-07-21 195313](https://user-images.githubusercontent.com/41922761/88129535-33511300-cb8d-11ea-9173-5e9cc5c56ac4.jpg)

**Comment by NickeManarin** [comment]
Can you share the project and your system related settings? (take a print of the statistics tab)

**Comment by NickeManarin** [comment]
> The "ScreenToGif" saving option (default) that finds unchanged pixels works great sometimes, not-so-great other times. I commonly throw up image sequences where almost half of the pixels are unchanged but it can't detect them.

The encoder should be detecting any unchanged pixel. It's a pixel-by-pixel operation.

**Comment by SJT1988** [comment]
Hi, it's a pretty big project (lots of large, rich frames). What I am doing is marking the pixel AREA that I KNOW the character will be contained in as he rocks side-to-side--all the "non-static" pixels, including his shadows. I assume that this marked region persists over all frames?

I am unable to send the project because (check this out):
The frames begin as 1920x1080, ~2mb each;
I batch-crop and batch-resize them in the project to 540x540
(I expect after Cinemagraph WORKS that the recalculated pixels will be about 3/4 that);
I save a new image sequence from the program, but the frames it produces are the same file size--almost 2mb each! There is no optimization happening with those frames, and no option to save in any format other than PNG.
...
Funny enough the project itself is reduced to about 1/4. Still 80mb. I am attaching a Google Drive link:

https://drive.google.com/file/d/1CjvUKoU8Rl8_mmOFuJXuKeybi_bo6naY/view?usp=sharing

**Comment by NickeManarin** [comment]
Hi, I asked for a screenshot of the statistics tab because I guessed it could be an issue related to a different DPI of the screen and the recorded content.

From your first picture, I was not sure of what I was looking at. Now I'm aware of the issue.
Thanks.

**Comment by SJT1988** [comment]
I think I left the download link "restricted", I apologize for that oversight. That link is now public.

**Comment by NickeManarin** [comment]
Thanks. That's the issue, the Cinemagraph is currently broken for projects with a different DPI than the screen. As you can see, yours is 72 DPI.

As a workaround, try generating the images with 96DPI (I'm guessing that you generated them using other app).

**Comment by NickeManarin** [comment]
Fixed.
Results in an image with the same size and DPI.

Before applying cinamegraph: 

![image](https://user-images.githubusercontent.com/14798947/90049545-54e47c80-dcab-11ea-8922-f767fb9d4d5a.png)

After:

![image](https://user-images.githubusercontent.com/14798947/90049601-688fe300-dcab-11ea-803c-317365d4ca54.png)
