### ISSUE TITLE
Cant record anything after updating to 2.26

### ISSUE THREAD

**Issue by ghost1372** [NickeManarin/ScreenToGif#699]
after updating from 2.25 i cant record anything
version 2.25 = work fine
version 2.26 and 2.26.1 = not working

**Comment by ghost1372** [comment]
fixed by changing startup folder

**Comment by NickeManarin** [comment]
Do you mean the cache folder? Or did you move the app to another folder?

**Comment by ghost1372** [comment]
@NickeManarin  i downloaded portable version in folder and everytime i updated app in this folder (with screentogif built in updater) after updating to 2.26 I could not record anything But by deleting the folder and downloading the new version in another folder, the problem was solved
