### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by IhorLaputin** [NickeManarin/ScreenToGif#7]
Can be? added functionality to record sound from Microphone as input to save in as Video like Presentation, or option to add recorded sound to timeline.

**Comment by NickeManarin** [comment]
Sorry, but sound recording isn't on my list.

**Comment by NickeManarin** [comment]
ScreenToGif was initially planed to be a small screen recorder that creates gifs (soundless).

**Comment by Kristinita** [comment]
@NickeManarin , now, in April 2017 in ScreenToGIF possible export projects to `avi` video format.

What do you think about recording system sounds? I try to use many gratis video recorders and I select [**Active Presenter**](https://atomisystems.com/activepresenter/), if I need record sounds with video. But I think, that ScreenToGIF have more features and better usability than ActivePresenter.

Thanks.

**Comment by gentunian** [comment]
@NickeManarin This is interesting for now on 2021, you are able to export capture to different kind of video format. Also you can add webcam, board drawing, and so on. Looks like adding a sound clip or microphone recording may sound like a good addition to the project.

**Comment by timtak** [comment]
Sound would be great. 

I am a teacher and often I have to explain to students how to do things with their computers this would be difficult without audio narration.  ScreenToGif has everything except sound. It is light and fast and I like the GUI.

I have used the commercial screen shot taking software Snag** but I have a lot of computers these days (home, two in my hut, lap top and desktop in my office) and that makes commercial software, if I am to use it everywhere, expensive. I think I would need three license at 35USD an educational license. 

Wink is okay but for some reason I have not really liked it in the past. I guess I am going to have to try to use Wink again. I did but the sound was really choppy. 
https://www.youtube.com/watch?v=iHF7jkoIFY0
I will keep trying.

The software mentioned by Kristina is a lot of money (more for one license than Snag** is for three).

**Comment by Kristinita** [comment]
> The software mentioned by Kristina is a lot of money (more for one license than Snag** is for three).

@timtak, ActivePresenter [**has a free edition**](https://atomisystems.com/activepresenter/free-edition/). This is enough for my needs. (Also, you can find crack for Pro version on the Internet, if it is permissible for your ethical reasons).

Thanks.

**Comment by timtak** [comment]
Thank you. I thought were an affiliate. Yes, I like it. It seems that if I don't use the advanced features there is no watermark in the free edition. It has a webcam capture so that I can add my speaking face to the software explanation, like this
https://youtu.be/4wIPtrCfjh4
 or make PowerPoint slideshow presentations plus face type captures of my lectures (but for the fact that Zoom will be using the camera). 

Thanks again. That will I think do for me. If i get to like the 200 usd is not that much but, again, the problem will arise with the number of computers. It is licensed for one computer, but one is free to move it as often as one pleases.

**Comment by ido1990** [comment]
Same here.
I really like ScreenToGif and now when I can export to MP4, sound is really missed feature.
This software is great, I was looking for such a software for long time...
