### ISSUE TITLE
Enhancement: Button on the Capture Window to Discard Capture

### ISSUE THREAD

**Issue by RickStrahl** [NickeManarin/ScreenToGif#700]
I find myself wasting a lot of time when capturing a screen capture and messing it up (which I do often :smile:). 

Right now I have to:

* Press Stop - at this point the capture is saved
* Wait for main window to open
* Go to File
* Go to Discard Project
* Delete the capture
* Confirm

Since this happens so often it would be really nice if there was a 'Delete' or 'Discard' button next to the stop button to throw out the current capture without having to go through all these steps that take roughly 10-15 seconds.

**Comment by NickeManarin** [comment]
Hi @RickStrahl 

The discard button appears only when the recording is paused.

![image](https://user-images.githubusercontent.com/14798947/89295358-3f31e000-d637-11ea-861c-33e1ef093b92.png)

**Comment by RickStrahl** [comment]
Oh - never occurred to me to pause and discard. I guess that works, but unintuitive (at least to me). Still think that it would be nice to just have a discard button on the right toolbar. Once I know I need to start over, I just want to get going as quickly as possible again.

Not a big deal, the pause/discard is reasonable enough.

**Comment by NickeManarin** [comment]
I don't remember why I set to display that only when paused when implementing that feature.
I can guess that maybe it's related to the fact that the action has no confirmation dialog yet.

I'm going to add a confirmation dialog and I'm going to change a bit the UX.

**Comment by RickStrahl** [comment]
That's great. I think there's probably a lot of people like me who don't get things right the first time 😃
Thanks!
