### ISSUE TITLE
🐞Bug for Emoji  of  Unicode character set to clipboard📋

### ISSUE THREAD

**Issue by dnknn** [NickeManarin/ScreenToGif#701]
`Ctrl+S`, and then type the file name, if it contains Emoji, it will not be copied to the clipboard normally. A picture tells everything 👇

![208_12005521](https://user-images.githubusercontent.com/10995302/89925813-866f3080-dc36-11ea-8f16-770dc9b715d3.png)

<details>
<summary>Details</summary>

![208_12010735](https://user-images.githubusercontent.com/10995302/89927003-40b36780-dc38-11ea-9a78-14d98dd700eb.png)

</details>

- ##  Current bug:
&emsp;&emsp; \xx\\`??Temporary Lock??.gif`  &emsp; (The path string output to the clipboard)
- ##  Expected behavior: 
&emsp;&emsp; \xx\\`🔏Temporary Lock🔏.gif`  &emsp; (The path string output to the clipboard)
- ## How to fix: 
&emsp;&emsp;  Support Unicode character set coding (UTF-8+/16+) into clipboard to fix this bug.

**Comment by NickeManarin** [comment]
Fixed. 
Thanks for the feedback.
