### ISSUE TITLE
[BUG] Broken interface

### ISSUE THREAD

**Issue by sebastianbertoli** [NickeManarin/ScreenToGif#703]
On my system the interface seems to be pretty broken. Any ideas how I could troubleshoot this? Thanks! (Awesome tool by the way!)

![bug](https://user-images.githubusercontent.com/9196354/90371853-d6ebf100-e06f-11ea-9ec4-fc6807aeeb93.gif)

**Comment by NickeManarin** [comment]
I would say that's a video driver issue.

Try disabling hardware acceleration in **Options > Application > Disable hardware acceleration**.

**Comment by sebastianbertoli** [comment]
That solves it, thank you!
