### ISSUE TITLE
Questions About Save As Shortcode

### ISSUE THREAD

**Issue by eblabs** [NickeManarin/ScreenToGif#706]
https://github.com/NickeManarin/ScreenToGif/blob/54de1168e75b79f689b05e84e7321ed4329ec957/ScreenToGif/Resources/Localization/StringResources.en.xaml#L1352

Thanks for the great tool! I was just trying to figure out how to set automatic naming and I didn't understand this info message.

"Name of the file. Insert Date/Time format between '?'"

Thanks for more info on this!

**Comment by eblabs** [comment]
Btw, thanks for all your hard work on this!!

**Comment by eblabs** [comment]
MyGif_'YYYY-MM-DDThh:mm:ss'
MyGif_?YYYY-MM-DDThh:mm:ss?

Also, I tried both of these, but this didnt work...

**Comment by NickeManarin** [comment]
It needs to follow the [C# Datetime format specification](https://www.c-sharpcorner.com/blogs/date-and-time-format-in-c-sharp-programming1), but also it needs to follow Windows file naming scheme (you can't use `:`).

But anyway, `T` was not supported.
I just added it, so with next version you can use it.

So, with this corrected file name, it will work:
`MyGif_?yyyy-MM-dd hh-mm-ss tt?`
`MyGif_2020-08-29 01-30-20 PM`

(Just remove the `tt` to work with v2.26.1)

**Comment by eblabs** [comment]
Perfect, thanks so much!! It would be great to add this info to the tooltip, or textfield right click menu.

Thanks again!!

**Comment by NickeManarin** [comment]
I'm going to improve that experience.

**Comment by eblabs** [comment]
Hi, I keep coming back to this conversation to find the correct shortcode :)

Would it be possible to have some presets in a right click menu?

Love this tool, thanks again for all your hard work on this.

**Comment by NickeManarin** [comment]
Hi, yes. I'm rewriting the whole app and I plan to improve the export experience.
What would be the most used formats that you use?
