### ISSUE TITLE
Resolution numbers are off

### ISSUE THREAD

**Issue by GhbSmwc** [NickeManarin/ScreenToGif#707]
I'm using a Insignia monitor to have my PC screen huge, the problem? This:
![image](https://user-images.githubusercontent.com/13095760/91645091-3ce15c80-ea10-11ea-9587-aee2d63cbca0.png)

The image resolution is 200x200, and ScreenToGif is also set to 200x200 (but is actually bigger than that), but they do not match.

I have the zoom settings on paint set to exactly 100% Here is the test image (for you to download and then use ScreenToGif on):
![image](https://user-images.githubusercontent.com/13095760/91645077-17ece980-ea10-11ea-8900-6c1d0257f787.png)

**Comment by NickeManarin** [comment]
Paint is displaying a 200x200 image with 96dpi.

ScreenToGif is measuring a 200x200 screen area with something greater than 96dpi.

Here's a screenshot of my screen with 96dpi:
![image](https://user-images.githubusercontent.com/14798947/91645202-84b8b180-ea19-11ea-8997-ec650a914101.png)

**Comment by GhbSmwc** [comment]
Is there a way I can match the Dpi?

**Comment by NickeManarin** [comment]
No, Paint sizing and ScreenToGif sizing detection are not configurable.

**Comment by NickeManarin** [comment]
But, you can change the DPI/Scale of your screen.

![image](https://user-images.githubusercontent.com/14798947/91645281-3bb52d00-ea1a-11ea-9e41-4b6151508723.png)

**Comment by GhbSmwc** [comment]
Tried setting it to 100% (I can see even more things with this setting, awesome!), and tried the same image here (thank goodness my browser didn't resize the image on the page) and was close enough:
![image](https://user-images.githubusercontent.com/13095760/91645448-1d97fe80-ea13-11ea-91f0-e641c47b4e86.png)

Also feature suggestion: Enable the user to move the recording window pixel-by-pixel. Normally, all windows lets you do this when you rightclick the titlebar of the window and move, and you can press CTRL+<ArrowKeys> to move it precisely.

**Comment by NickeManarin** [comment]
> Also feature suggestion: Enable the user to move the recording window pixel-by-pixel. Normally, all windows lets you do this when you rightclick the titlebar of the window and move, and you can press CTRL+ to move it precisely.

This was implemented already and it will be available with the next version (v2.26).
You'll be able to control the movement using the arrow keys, the resize with Shift/Ctrl + arrow keys.

Holding Alt while moving or resizing will set the steps to 5px, else 1px.
