### ISSUE TITLE
New record window issue

### ISSUE THREAD

**Issue by F8ER** [NickeManarin/ScreenToGif#708]
Dear Developers,

Thank you very much for this project.

Although, it's worth to mention:

<img src="https://i.imgur.com/4KCZ89j.png" width="400px" />

1. If you change the interface while old is opened, it might not change the interface without reopening record window.
2. The area selection(in new record window) is about 4 frame per second(FPS) on 150% scaled ~4K(2160p) screen.

Regards

**Comment by NickeManarin** [comment]
1) That's expected, as it's two separated windows. Closing the recorder and opening again is required.

2) The performance of the area selection was improved (actually, the whole recorder was reworked) and this improvement will be available next version (2.27).

**Comment by F8ER** [comment]
> Closing the recorder and opening again is required.
Thank you! Although, what if it shows such message or automatically reopened it? ☺
