### ISSUE TITLE
Gifski download link in wiki is wrong

### ISSUE THREAD

**Issue by smiley** [NickeManarin/ScreenToGif#709]
The Gifski download link on [Help ▪ FAQ ▪ Unable to download Gifski](https://github.com/NickeManarin/ScreenToGif/wiki/Help-%E2%96%AA-FAQ-%E2%96%AA-Unable-to-download-Gifski) points to:
[`https://github.com/NickeManarin/ScreenToGif-Website/raw/**master**/downloads/Gifski.zip`](https://github.com/NickeManarin/ScreenToGif-Website/raw/master/downloads/Gifski.zip)
...while the link is actually on the `gh-pages` branch:
[`https://github.com/NickeManarin/ScreenToGif-Website/raw/**gh-pages**/downloads/Gifski.zip`](https://github.com/NickeManarin/ScreenToGif-Website/raw/gh-pages/downloads/Gifski.zip)

**Comment by NickeManarin** [comment]
Thanks. I also fixed the SharpDx link too.
