### ISSUE TITLE
encoding error

### ISSUE THREAD

**Issue by JohnJane-Doe** [NickeManarin/ScreenToGif#711]
![20200904](https://user-images.githubusercontent.com/68457457/92215944-88907c00-eed0-11ea-92d0-66a22e84ab04.png)

**Comment by NickeManarin** [comment]
Looks like you are using an older version of Gifski.

Try deleting the current gifski.dll and downloading again via the built in downloader in Options > Extras.

**Comment by JohnJane-Doe** [comment]
[Gifski.zip](https://github.com/NickeManarin/ScreenToGif/files/5180434/Gifski.zip)

Is this the latest version?

**Comment by NickeManarin** [comment]
It appears to be the latest version.

https://github.com/NickeManarin/ScreenToGif/wiki/Help-%E2%96%AA-FAQ-%E2%96%AA-Unable-to-download-Gifski

**Comment by JohnJane-Doe** [comment]
This issue has been resolved by installing vc++.

https://github.com/NickeManarin/ScreenToGif/issues/693 But this problem is still unresolved.

**Comment by NickeManarin** [comment]
#693 will be released with v2.27 (next version).
It will require the download of a new Gifski dll again.

Which Visual C++ redist did you install?

**Comment by JohnJane-Doe** [comment]
Visual C++ 2015-2019 Redistributable.

**Comment by NickeManarin** [comment]
Not sure if you found this before, but there is a wiki page explaining that VC++ was required:

https://github.com/NickeManarin/ScreenToGif/wiki/Help-%E2%96%AA-FAQ-%E2%96%AA-Unable-to-use-Gifski

I just need to make the app aware that the VC++ is installed or not.

**Comment by JohnJane-Doe** [comment]
I got the information here https://github.com/NickeManarin/ScreenToGif/issues/544

Thanks for your help.

**Comment by NickeManarin** [comment]
Ah, great. Thanks.
