### ISSUE TITLE
File is not copied to clipboard

### ISSUE THREAD

**Issue by AmjadHD** [NickeManarin/ScreenToGif#712]
![stg_copy_bug](https://user-images.githubusercontent.com/33235928/92291258-2491a600-ef18-11ea-9408-d50b52527e3f.gif)
OS: Windows 10 64bit
STG version: 2.26.1 and prior

**Comment by NickeManarin** [comment]
Copying as "File" is the same as copying the file on the Windows Explorer.
It does not appear on my clipboard history.

If you want, you can copy the file path instead.

**Comment by AmjadHD** [comment]
The file is not copied at all, for example i can't just paste (`ctrl+v`) in a github issue, it doesn't work.

**Comment by AmjadHD** [comment]
I may be misunderstanding, isn't that supposed to copy the contents of the file to the clipboard ? If not how come such common option not added ?

**Comment by NickeManarin** [comment]
The file will be copied as a file the same way that a `Ctrl + C` on Windows Explorer would do.
It's not possible to paste in a GitHub issue text field the same way.

There is no available API to copy the contents of a Gif file to the clipboard as image. That's a limitation of Windows.
It's only possible to copy images with just one frame (JPG, PNG, etc).
