### ISSUE TITLE
Rotated mp4 files are warped in importing with ffmpeg

### ISSUE THREAD

**Issue by JJKylee** [NickeManarin/ScreenToGif#719]
**OS**: Windows 10 Home x64 19041.508
**Program**: ScreenToGif 2.27 portable

I recorded my iPad screen in the landscape mode, and the resulting mp4 file has a rotate tag of 270 degrees and a display aspect ratio of 3:4. Any normal player plays it as expected: the video is exactly the same as when it was recorded in the landscape mode.

But while trying to import the mp4 file in ScreenToGif, I found two weird behaviors.

1) FFmpeg rotates the video but the display aspect ratio(DAR) is warped: it still remains 3:4.
2) MediaPlayer does not respect the rotate tag.

Well, 2) doesn't matter since I can always rotate the frames within ScreenToGif. But 1) is a big problem.

In an attempt to fix this problem, I remuxed the mp4 file with a new DAR tag as follows:

`ffmpeg -hide_banner -i INPUT.mp4 -aspect 4:3 -c copy OUTPUT.mp4`

But there was no change. ScreenToGif does not respect this new DAR and just rotates the video with a warped aspect ratio as before.

So this time I just removed the rotate tag without aspect ratio change as follows:

`ffmpeg -hide_banner -i INPUT.mp4 -c copy -metadata:s:v:0 rotate=0 OUTPUT.mp4`

And as expected, this worked the same as 2), and I just needed to rotate the frames in ScreenToGif.

Well, IMHO, this seems like a bug.

**Comment by NickeManarin** [comment]
Hi, do you have a sample video that you can share? 
Like 1-3 seconds long.

**Comment by JJKylee** [comment]
Here's the link: [here](https://drive.google.com/drive/folders/1Fv96A-qk4wyeJ2HEqAvT-Mklu9SlS1Bl?usp=sharing).
This clip will be removed in two days.

**Comment by NickeManarin** [comment]
Thanks. I downloaded it.

**Comment by NickeManarin** [comment]
I fixed the FFmpeg importer.

![image](https://user-images.githubusercontent.com/14798947/93772416-3603cf00-fbf5-11ea-9a0d-1712eef7fe2c.png)
