### ISSUE TITLE
Large cache size when recording for 10-15 min

### ISSUE THREAD

**Issue by 0lm** [NickeManarin/ScreenToGif#720]
hi there

when using screentogif to record a longer video, like 10-15min long (no game recording, just dektop while doing stuff, now and then opening steam client). when  i was done, i waited until it finally renders the videos. when nothing happened after 10 min, i force closed it and checked my HDD space. 50gb were missing. i looked into the screentogif appdata temp folders and saw temp files of the rendering being 50gb big. cant tell hat went wrong. i used it just normal and it never rendered the video but created already 50gb of temp files lol. is that supposed to happen?

**Comment by NickeManarin** [comment]
I don't recommend in using this software for longer than 1-minute captures right now.

Especially when not using a frame cache (see Memory cache under Options > Recorder), since each frame is simply stored as a PNG image inside the cache folder.

If you enable memory cache, it will write the frames to the memory at first, then after reaching the threshold (that you can set, in MB), it will write to a cache on disk as a single file.

**Comment by 0lm** [comment]
oh i see, that's good to know! your explanation makes things clear now. by any chance, there is no way to make screentogif record as a video file, and later convert to a gif file?
or if i should record something with OBS instead, can screentogif convert the video into a good quality gif file?

**Comment by ElliotMok** [comment]
The cache does large when handling a gif file of 8.76mb,2532 frames. It takes 12.2gb, lol...

**Comment by NickeManarin** [comment]
@0lm Right now it can't record as video. But you can import a video later. Quality depends of the content and the compression.
@ElliotMok That should change in near future releases. I'm reworking the editor, so the action stack will occupy less space in disk.

**Comment by Ghostwritten** [comment]
The key is what content you record. If it is a film and television, each photo will occupy more than 1 megabyte. It is terrible to imagine 10 minutes, but you can try to use LICEcap：https://www.cockos.com/licecap/
