### ISSUE TITLE
Updating through the app leaves the uninstaller entry of the previous version in the control panel/settings menu

### ISSUE THREAD

**Issue by Gnbrkm41** [NickeManarin/ScreenToGif#721]
![image](https://user-images.githubusercontent.com/42944058/93182319-88b43580-f774-11ea-8fde-a3a5f8c3a3af.png)
![image](https://user-images.githubusercontent.com/42944058/93182350-8f42ad00-f774-11ea-97b2-0a6d146ed615.png)

It appears that uninstalling the old version actually results in removal of the new version and the uninstaller entry for the newer version still exists after uninstallation. Perhaps the updater logic forgot to update the uninstaller entry?

**Comment by NickeManarin** [comment]
It has something to do with different install modes.

**Comment by NickeManarin** [comment]
Fixed.

I'm giving more control over the installation process.
If the user tries to install on the same folder but with a different access mode (per-user or per-machine), the other version gets uninstalled before the installation continues.

![image](https://user-images.githubusercontent.com/14798947/119424105-2f28e100-bcdb-11eb-84fe-f97f2bb96b51.png)
