### ISSUE TITLE
Quick gif recording to clipboard

### ISSUE THREAD

**Issue by jamesdcockayne** [NickeManarin/ScreenToGif#722]
I think it would be great if there was a way to record a gif and copy it straight to the clipboard without needing to specify a file location or any other settings. As soon as the gif is in the clipboard, the user will be able to instantly paste it into Teams/Slack/an email. 

A bit of background from me, since Covid-19 I've been working from home and relying quite a bit on Greenshot to screenshot and annotate things to help communicate with my team over instant messaging applications. The process usually is to screenshot something then copy that image to the clipboard, then paste into Slack. This is a fast process and it means I can highlight something to my team in almost real time. There are times however when a process is conveyed better as a animation.

I find myself finishing the recording, navigating to `File`, then `Save As` then needing to think of a name for the file, then clicking `Save`, then I can copy it into whatever communication application that i'm using, then trying to remember to delete the file later, since it might have ended up getting mixed up with important documents. 

I can't help thinking that this could be more streamlined for users who aren't making use of ScreenToGif's editing features, but are using for example as a way to share a part of their screen to a college for a quick demo on how to use a feature. I suppose a bit like they do in the Visual Studio Code changelog https://code.visualstudio.com/updates/v1_49

I guess this feature request would be to add the equivalent Greenshot "Copy to clipboard" feature into ScreenToGif

![image](https://user-images.githubusercontent.com/24731453/93337611-4432a380-f821-11ea-9a2e-014be3c27a79.png)

I hope this request makes sense!
Thanks,
James

**Comment by NickeManarin** [comment]
Hi James,

The clipboard of Windows has a limitation, it doesn't like animated gifs.
So, it's not possible to copy gifs into the clipboard as image, without losing all but the first frame.

By the way, ScreenToGif already has the option to simply encode and copy the file to the clipboard:

![image](https://user-images.githubusercontent.com/14798947/93480942-66d1c480-f8d4-11ea-8905-c8dd8b46f7b9.png)

The difference is that you can only copy as "File" (same as Ctrl + C while the file is selected on Windows Explorer) or you can copy the path.
