### ISSUE TITLE
[Feature request] Add the "show/hide capture cursor when recording" to the command panel

### ISSUE THREAD

**Issue by XHXIAIEIN** [NickeManarin/ScreenToGif#723]
I think "show/hide capture cursor when recording " It will be very convenient.  can **placed in the toolbar** or **add a Shortcuts**. 
  
For example:  use **[Snipaste](https://www.snipaste.com/)** can show/hide the capture cursor via the ` key when snipping

**Comment by Geeyun-JY3** [comment]
![image](https://user-images.githubusercontent.com/49396421/94880583-f3b07c80-0495-11eb-9181-3227137c1d16.png)
