### ISSUE TITLE
After changing the delay, the gifs  output become smaller

### ISSUE THREAD

**Issue by aaa26999** [NickeManarin/ScreenToGif#724]
By using a gifski encoder, when I increased the frame delay, the gif's size become much smaller than the origin  one I recorded.
For example, a 800*600 gif I recorded, If I don't change the delay, the gif it makes to be all right. But if I increased the delay, the gif that output become 560*420, however I didn't change the image size yet.

**Comment by NickeManarin** [comment]
By size do you mean resolution or file size?

**Comment by NickeManarin** [comment]
Can you try out v2.27.2?

**Comment by NickeManarin** [comment]
Ok, just download v2.27.2 and it should work.

**Comment by aaa26999** [comment]
Thanks！ It works！

**Comment by NickeManarin** [comment]
Great. :)
