### ISSUE TITLE
Imgur WebException 400 Bad Request

### ISSUE THREAD

**Issue by billw2012** [NickeManarin/ScreenToGif#727]
It appears perhaps there is a size limit. I can upload my gif manually to imgur, ~~but it won't finish processing, I just get a blank image, and no error message~~ and it works eventually (I spoke too soon).
My gif is 100MB...

**Comment by NickeManarin** [comment]
There's a limit. It's supposed to be 10MB for images or 200MB for videos.

https://apidocs.imgur.com/#c85c9dfc-7487-4de2-9ecd-66f727cf3139

**Comment by NickeManarin** [comment]
The uploader logic was updated for v2.28.
The upload should be more stable.

Imgur limits the upload of gifs to less than 10Mib.
