### ISSUE TITLE
Corrupted User-Interface (on AMD?)

### ISSUE THREAD

**Issue by Roritharr** [NickeManarin/ScreenToGif#737]
Hi,
i've just installed and used screentogif on my new HP Elitebook 835 G7 which features an AMD Renoir APU (4750U).

The only other noteworthy non-standard software I'm using is Romex PrimoCache to speed up the SSD for certain workloads which hasn't created any other issues so far. 

My Windows version is: Microsoft Windows 10 Professional (x64) Build 19041.508 (2004/May 2020 Update)

I'm getting a corrupted UI in the Editor, something which I don't see in any other program, here is a screenshot:

![image](https://user-images.githubusercontent.com/561299/95214862-9ea39c00-07f0-11eb-8b1c-6f9b8d491459.png)

This changes in behaviour when I use the window:

![screenToGifIssues](https://user-images.githubusercontent.com/561299/95216326-381f7d80-07f2-11eb-820d-f941b26adbdf.gif)

**Comment by NickeManarin** [comment]
Usually this means that the video driver is not dealing well with rendering the window.
Disabling hardware acceleration should help you a bit.

> Options > Application > Disable hardware acceleration.

**Comment by Roritharr** [comment]
> > Options > Application > Disable hardware acceleration.

Thank you! This solved the issue!

**Comment by Coxxs** [comment]
Same issue here, I'm using Ryzen 4800u with latest driver.
It also affect the WPF editor in Visual Studio 2019. Seems an AMD driver issue.

![image](https://user-images.githubusercontent.com/3007303/103343724-b0cb6880-4ac7-11eb-965b-f1c474088068.png)
