### ISSUE TITLE
feature_request(save_data): preventing all data loss

### ISSUE THREAD

**Issue by Kristinita** [NickeManarin/ScreenToGif#738]
### 1. Summary

If user pressed <kbd>Ctrl+Delete</kbd>:

    it would be nice if he didn’t irrevocably lose all record data.

### 2. Argumentation

Preventing unwanted data loss. It’s no good when the data on which the user worked for many minutes may disappear at once.

### 3. Steps to reproduce

ScreenToGif 2.27.3.

I made any recording → I made any actions in ScreenToGif editor → <kbd>Ctrl+Delete</kbd> (I wanted <kbd>Ctrl+End</kbd>, but missed the keyboard).

#### 4.1. Current

All data of my recording loss 😿. <kbd>Ctrl+Z</kbd> and `Home` → `Undo` have no effect. I need to record my apng again.

#### 4.2. Example of desired

[**Dialog box**](https://docs.microsoft.com/en-us/windows/win32/uxguide/win-dialog-box) with `Yes` and `No` buttons. Example text:

> WARNING
>
> Are you sure you want to delete all data of your recording? You can’t undo this action.

Thanks.

**Comment by NickeManarin** [comment]
Hi @Kristinita.

There's already a confirmation dialog for that action (it defaults to **No** too, as a safeguard):

![image](https://user-images.githubusercontent.com/14798947/95371374-81ce9d80-08b0-11eb-8f24-06eea3350156.png)

It's enabled by default, but it can be disabled:

![image](https://user-images.githubusercontent.com/14798947/95371514-adea1e80-08b0-11eb-9b9e-11ece5ff8214.png)

Perhaps it was disabled, unless there is somehow, a way to bypass that.

**Comment by Kristinita** [comment]
**Status: CONFIRMED** :heavy_check_mark:

Yes, it solves the problem. Sorry for wasting your time.

I don’t remember ever changing anything in the `Editor` settings, so I didn’t even look there.

Thanks.
