### ISSUE TITLE
.net version help

### ISSUE THREAD

**Issue by hmaffin** [NickeManarin/ScreenToGif#74]
Hello,

I'm on a University network so shouldn't really go messing with my .net version - any chance you could add more versions of .net to the mix? :) We only have 4.0

Ta!

**Comment by NickeManarin** [comment]
Hello,

Unfortunately ScreenToGif 2.0 (and greater) is highly dependent of .Net Framework 4.5 (and greater).

The old version of this app (v1.4.2) targeted .Net Framework 4.0, you could give it a try, but it's very old:
http://screentogif.codeplex.com/releases/view/617012

**Comment by hmaffin** [comment]
Thank you :) I am installing 4.6.1 now just because I really want to use the program :) Thank you for your fast response and for the program itself!

**Comment by NickeManarin** [comment]
Alright, you're welcome.  :)
