### ISSUE TITLE
Unable to export selected frames

### ISSUE THREAD

**Issue by parthi2929** [NickeManarin/ScreenToGif#745]
Hi

Thank you for this amazing product. Currently I could not see any option to export only selected frames as Gif. I have a big gif, where I think of splitting, but I am unable to to due to lack of this option. Kindly help.

**Comment by NickeManarin** [comment]
Hi, do you want to export as single frames? 
If so, select all the frames > Save as > Images

**Comment by parthi2929** [comment]
No that is still a painful work around. I had about 6 videos to do. A simple export of `selected frames only` option would be a great productivity booster.

**Comment by NickeManarin** [comment]
Done. It will be available with version 2.28.

![image](https://user-images.githubusercontent.com/14798947/115032002-328ca980-9e9f-11eb-8ca0-b80a20e01af0.png)

![image](https://user-images.githubusercontent.com/14798947/115032043-3fa99880-9e9f-11eb-9cf4-ca301620db74.png)
