### ISSUE TITLE
Reset default settings

### ISSUE THREAD

**Issue by GustavoxDVelop** [NickeManarin/ScreenToGif#749]
How can I reset the default settings? The Gif generated is very large, approx 90Mb, and I don't find something to reset to default settings

**Comment by NickeManarin** [comment]
You can go to Options > Storage and click on the X on the Settings section to erase all settings.

But you can also manually revert the export settings for the gif:

Encoder: ScreenToGif
Quantizer: Neural
Sampling: 10

**Comment by NickeManarin** [comment]
I'm creating a global preset, so you'll be able to reset to default settings easily.

**Comment by NickeManarin** [comment]
Done, it will be available with v2.28.
