### ISSUE TITLE
Change Images After Input

### ISSUE THREAD

**Issue by A13raxas** [NickeManarin/ScreenToGif#75]
There currently doesn't appear to be a way to modify images after they have been created and the slide has been left

**Comment by NickeManarin** [comment]
You could undo and remake your action, since all modifications are merge with the frames after applying.

**Comment by jonletts** [comment]
Is it possible to revert a single frame to its initial state? Basically, I did something, then a bunch of other stuff, then realized the first thing had a spelling mistake… Is it possible to change that?

**Comment by NickeManarin** [comment]
No, unless you do that manually by replacing the file inside the temporary folder of that current recording. :/

**Comment by NickeManarin** [comment]
I'm going to close this issue, since it's being tracked elsewhere.
It's been worked on, I started making some changes to allow this to happen.
