### ISSUE TITLE
 Don’t have this bad countdown while recording or even the recorder is within the recording range

### ISSUE THREAD

**Issue by rr4e** [NickeManarin/ScreenToGif#750]
Don’t have this bad countdown while recording or even the recorder is within the recording range

<img width="855" alt="无标题" src="https://user-images.githubusercontent.com/14058293/97388394-dec9dc00-18cf-11eb-9daf-5b32fe579fef.png">

**Comment by NickeManarin** [comment]
Which version are you using?

This pop up only appears if the recording region is on top of the recording controls (the UI in which you control the capture).

**Comment by rr4e** [comment]
> Which version are you using?
> 
> This pop up only appears if the recording region is on top of the recording controls (the UI in which you control the capture).
2.27.3
yes
Even if he is within the recording range，Maybe this is not necessary? Maybe he is controllable?
The earlier version can record the controls, but it feels very high-tech. thank you very much！

**Comment by NickeManarin** [comment]
Here's how it works:

```
User selects a part of the screen.
The recorder repositions itself to stay out of the way of the selected region.
User start capture.
If the recorder is on the way of the recording region:
    Display splash screen, warning that the UI will be hidden.
    Hide UI and start recording.
Else
   Start recording.
```

What's missing in here is a step that measures if it's possible to move the recording controls out of the way of the selected region.

**Comment by NickeManarin** [comment]
Version 2.32 will have the fix for this issue.
The recorder will try to move it self to the sides when there's space left.
