### ISSUE TITLE
Gifski save file with wrong size

### ISSUE THREAD

**Issue by byzod** [NickeManarin/ScreenToGif#754]
User | Machine | Startup | Date | Running | Version
-- | -- | -- | -- | -- | --
Byzod | ASUKA | 31/10/2020 11:59 | 31/10/2020 12:00 | 0:00:00:26 | 2.27.0.0

Windows | Architecture | Used | Available | Total
-- | -- | -- | -- | --
10.0.15063.0 | 64 bits | 160.9 MB | 10.6 GB | 16 GB

E-mail | .Net Version | Issue? | Suggestion?
-- | -- | -- | --
example@outlook.com | 4.8 or later | Yes | No

---

When save the same project with StG encoding and gifski encoding, gifski result is not original result for unknown reason

 
demo
![A3](https://user-images.githubusercontent.com/848607/97770772-2d49d580-1b71-11eb-875e-000d9e751cf5.gif)

attachment
[bug.zip](https://github.com/NickeManarin/ScreenToGif/files/5468500/bug.zip)

**Comment by NickeManarin** [comment]
Just update to v2.27.3.
________________________________

**Comment by byzod** [comment]
It fixed the problem :D
