### ISSUE TITLE
ScreenToGif window often resizes itself into the recording area

### ISSUE THREAD

**Issue by KybernetikGames** [NickeManarin/ScreenToGif#755]
When I set the recording area, the ScreenToGif window positions itself next to that area, but if it's to the left of the area when I start recording it expands the window to show the Pause and Stop buttons, which causes the edge of the window to go into the recording area and get recorded.

**Comment by NickeManarin** [comment]
Done. It will be available with version 2.32.
The command panel will move the nearest available space when record starts, stops and after a discard (taking into consideration the size change).
