### ISSUE TITLE
Allow the capture region to be moved with arrow keys

### ISSUE THREAD

**Issue by Gnbrkm41** [NickeManarin/ScreenToGif#756]
![image](https://user-images.githubusercontent.com/42944058/98482729-aff42400-2246-11eb-8b4b-7f00c711976a.png)
Would it be possible to move the capture region pixel by pixel using arrow keys (presumably only when the frame is in focus / selected), so you can precisely position the image being captured? it's kind of a pain to achieve one-digit accuracy with mouse only.

**Comment by NickeManarin** [comment]
It's already possible. Just give focus to the recorder controls and use the arrow keys (you can combine with Ctrl and/or Shift to increase the sides, also you can combine with Alt to increase in multiples of 5px).

**Comment by Gnbrkm41** [comment]
D'oh, I could have sworn it didn't work before! 😅
