### ISSUE TITLE
Undesired Padding Around Captured Window

### ISSUE THREAD

**Issue by dsanders11** [NickeManarin/ScreenToGif#758]
When recording a window, the default behavior seems to add two pixels of padding around a window for the capture area. There doesn't appear to be a setting to change this behavior.

It's less than ideal behavior, since it will cause some of the background to be captured and causes a border on the recorded GIFs.

If it's intentional behavior, a setting to change which shows this padding value and lets it be changed to zero would be ideal.

**Comment by NickeManarin** [comment]
It's there to capture a focused window. Windows with focus have a 1px border (in Windows 10).

**Comment by dsanders11** [comment]
Would it be possible to add a setting to change this behavior? The window I'm recording (VS Code) doesn't have a border, so it's leading to more than the window being captured.

**Comment by NickeManarin** [comment]
Yes, it can be added as a size modifier for a VS Code instance when detecting the windows.

You can also crop the recording afterwards.

**Comment by dsanders11** [comment]
> Yes, it can be added as a size modifier for a VS Code instance when detecting the windows.

Is that something that currently exists, or needs to be added? Didn't find any settings for "size modifier".

> You can also crop the recording afterwards.

I'd likely to make a lot of recordings, needing to crop them all afterwards doesn't sound very appealing. 🙂

**Comment by NickeManarin** [comment]
> Is that something that currently exists, or needs to be added? Didn't find any settings for "size modifier".

In code, when detecting the size of the windows, when detecting that it's a VS Code instance, the rectangle will be reduced by 1 px.

**Comment by NickeManarin** [comment]
Closing this ticket to focus on #915

**Comment by GiovanH** [comment]
I came here to report this same issue. On Windows 10, there are two pixels of padding around every window, including VS and windows with custom decorators but also stock windows. I would definitely love to see a global "don't pad windows" option, as the "Window" selector is currently not really usable.
