### ISSUE TITLE
Can't copy output file to clipboard when saving

### ISSUE THREAD

**Issue by osharaki** [NickeManarin/ScreenToGif#759]
The _Copy to the clipboard_ option doesn't work when I'm saving a gif in the **Save as** menu. I'm able to save the gif to a file, but nothing gets added to the clipboard.

![image](https://user-images.githubusercontent.com/38385026/99888193-26cbec80-2c4b-11eb-9b78-bd9e321384ec.png)

**Comment by NickeManarin** [comment]
> Copy to clipboard > File

This option is the same as `Ctrl + C` the file inside the Windows Explorer.

You can't copy Gifs to the clipboard the same way as an image, because Windows does not provide an API for that.
It's impossible for me to add this feature.
