### ISSUE TITLE
ctrl + shift + left/right

### ISSUE THREAD

**Issue by Habbee** [NickeManarin/ScreenToGif#76]
when you select a frame and then hold ctrl + shift + left or right, you used to be able to scroll all the way to the end (or start depending what arrow you hold), but now it keeps going afterwards.

didn't work like this is previous updates, it used to stop at the edge and keep all frames selected.

EDIT: windows 10, 64-bit

PS. amazing update otherwise, keep up the awesome work my friend!

**Comment by NickeManarin** [comment]
<kbd>Ctrl+Shift+Left/Right</kbd> triggers the "Move Left"/"Move Right" commands. 

There's a bug when using this command via keyboard, it's selecting AND moving the frames. It should only move them.

Is that what you meant?

Thanks, btw :D

**Comment by Habbee** [comment]
a few month ago, when I select a frame then held ctrl+shift+arrow it would expand my selection too (not move any frames). I thought it was a cool feature since you could select multiple frames very fast and if you ran all the way to the edge it would stop (it doesn't do that any more).

maybe thats not how you had the feature in mind tho

**Comment by NickeManarin** [comment]
Oh, you can do that with <kbd>Shift + Left/Right</kbd>. :)

It will start expanding your selection.

**Comment by Habbee** [comment]
Ohh I see, I used to hold both ctrl and shift, maybe that stopped working when you added feature for ctrl. I, for some reason, thought you had to hold both of them =)
