### ISSUE TITLE
Statistics tab, Current time 00:00.00 m, when last frame is selected

### ISSUE THREAD

**Issue by duianto** [NickeManarin/ScreenToGif#760]
### Description:
When the last frame is selected, then the Statistics tab shows:
Current time
00:00.00 m

### Reproduction steps:
Create a screen recording
When the Editor opens
Switch to the Statistics tab
Select the last frame

### Observed:
The Current time shows: 00:00.00 m

### Expected:
The Current time should probably show the same time as the Total duration.

### System:
ScreenToGif Version 2.27.3
Windows 10 2004

**Comment by NickeManarin** [comment]
Fixed, thanks to @fyucel
