### ISSUE TITLE
Unable to batch add watermark！

### ISSUE THREAD

**Issue by pxim** [NickeManarin/ScreenToGif#767]
Now use the watermark function. When previewing, there are watermarks on each image, but once saved, only one image has a watermark.

**Comment by NickeManarin** [comment]
What you see before hitting "Apply" is just a preview, based on the current frame selection.

In order to apply the watermark to multiple frames, you need to select them via Ctrl + Click, Shift + Click or Ctrl + A, etc.

**Comment by pxim** [comment]
ok，thank you
