### ISSUE TITLE
Improve SEO!

### ISSUE THREAD

**Issue by stannynuytkens** [NickeManarin/ScreenToGif#77]
Steps to reproduce:

- Search in Google: free screen recorder tool
- [ScreenToGif.com](http://www.screentogif.com/) is nowhere to be found...

**Comment by sirtet** [comment]
Google **free screen recorder tool gif** and you get Rank 1!

As this is not a gereric screen recorder (record a video), but mainly for creating animated gif's (ok, it savess AVI too), it might be hard to score better for the generic search...
Any suggestions what to do?

**Comment by NickeManarin** [comment]
Well, I edited the description tag to include the words "free screen recorder". Other than that, the only thing I can do is to create a [rich card](https://developers.google.com/search/docs/guides/mark-up-content).

**Comment by stannynuytkens** [comment]
I understand it's hard and I'm glad to see all measures are taken to get a higher rank! Would be a shame if people would miss this! Cheers!

**Comment by NickeManarin** [comment]
Now we just need to wait a bit. :)
The website usually benefit more from referencing (links to the website) than organic search (typing "screen recorder"), at least that's what google analytics tells me.
