### ISSUE TITLE
Blurred display

### ISSUE THREAD

**Issue by WJWsir** [NickeManarin/ScreenToGif#770]
![blurred](https://user-images.githubusercontent.com/47811503/102997806-df45c280-4560-11eb-8006-9c2e0973b72c.png)
![display](https://user-images.githubusercontent.com/47811503/102997820-e5d43a00-4560-11eb-8dc0-f80d74b0d6d2.png)
After I install it, I open it and use it to record the screen. The user interface is blurred  as the pictures I pasted. Hope It can be more beautiful.

**Comment by Jerrylum** [comment]
What do you mean "Blurred" ?

**Comment by NickeManarin** [comment]
This is an issue with your graphics adapter. Try updating your video drivers or disable the hardware acceleration of the UI in Options > Application > General.

**Comment by WJWsir** [comment]
Thank you very much!  The UI is normal after following your steps.
