### ISSUE TITLE
can support macOS  ?

### ISSUE THREAD

**Issue by luckywzy** [NickeManarin/ScreenToGif#772]
I not found how to build in macOS system, Does it support？

**Comment by YalandHong** [comment]
Duplicate of #481, #29 and many others.
It seems that this application relies on some features available only for Windows.

For more information about cross-platform, please track #579.

Hope this is helpful to you.

**Comment by NickeManarin** [comment]
I hope that with .NET MAUI, I'll be able to provide a cross-platform solution.
