### ISSUE TITLE
Add the phrase "screen to gif" to the Microsoft Store listing

### ISSUE THREAD

**Issue by NotWoods** [NickeManarin/ScreenToGif#775]
Basically just an SEO suggestion 😄 

Currently the app doesn't show up if you search "screen to gif" on the store. Since the product description is pretty short, the phrase "screen to gif" is never mentioned. If you don't type "ScreenToGif" without spaces, you won't see this app in the results.

**Comment by NickeManarin** [comment]
Thanks. I added the "screen to gif" and "screen2gif" keywords.
