### ISSUE TITLE
Editor has black artificats all over the place

### ISSUE THREAD

**Issue by cypressious** [NickeManarin/ScreenToGif#776]
![grafik](https://user-images.githubusercontent.com/1191816/103664674-ce3e7d80-4f72-11eb-8ec0-7f3a7a73863c.png)

![grafik](https://user-images.githubusercontent.com/1191816/103664776-ee6e3c80-4f72-11eb-9a4c-ee7e11ac0262.png)

User | Machine | Startup | Date | Running | Version
-- | -- | -- | -- | -- | --
krakhman | LAP-KRAKHMAN | 05/01/2021 16:25 | 05/01/2021 16:28 | 0:00:02:22 | 2.27.3.0
10.0.19042.0 | 64 bits | 182,2 MB | 18 GB | 31,2 GB
example@outlook.com | 4.8 or later | Yes | Yes

Processor | Cores
-- | --
AMD Ryzen 5 PRO 4650U with Radeon Graphics | 6 (12)
AMD Radeon(TM) Graphics @ 60Hz | 27.20.11024.11003

Name | Bounds | Working area | DPI/Scale | Graphics adapter | Primary?
-- | -- | -- | -- | -- | --
Wide viewing angle & High density FlexView Display  1920x1080 (\\.\DISPLAY1) | -1920:362 • 1920x1080 | -1920:362 • 1920x1020 | 144dpi / 150% | AMD Radeon(TM) Graphics | No
Interner Bildschirm (\\.\DISPLAY2) | 0:0 • 2560x1440 | 0:0 • 2560x1390 | 120dpi / 125% | AMD Radeon(TM) Graphics | Yes
Interner Bildschirm (\\.\DISPLAY3) | 2560:348 • 1920x1080 | 2560:348 • 1920x1040 | 96dpi / 100% | AMD Radeon(TM) Graphics | No

**Comment by NickeManarin** [comment]
Hi, it's a driver issue with the hardware acceleration. 

Disable it in Options > Application.

#770
