### ISSUE TITLE
保存后弹出完成通知这个可以最小化么?

### ISSUE THREAD

**Issue by abcparks** [NickeManarin/ScreenToGif#783]
保存后弹出通知导致操作的时候, 还要点击一下界面, 感觉挺麻烦的

**Comment by Jerrylum** [comment]
## After the project is successfully saved, can the "Save Complete" dialog be minimized?

He thinks it is very inconvenient to hide the "Save Complete" dialog manually after saving the project.

<br>
Jerry: I think he is talking about this:
![image](https://user-images.githubusercontent.com/12783829/105081487-39d52e80-5acd-11eb-8d4f-339bbe0308e9.png)

**Comment by NickeManarin** [comment]
I can add an optional action that minimizes the popup after finishing all encodings, but that's going to be disabled by default.

I need to make sure that user knows where the encoding is being displayed and when it is ready to open the file.

**Comment by NickeManarin** [comment]
Thanks for the translation @Jerrylum :)

**Comment by abcparks** [comment]
later
