### ISSUE TITLE
通过Store获取后，无法卸载“干净”

### ISSUE THREAD

**Issue by Char-z** [NickeManarin/ScreenToGif#784]
![image](https://user-images.githubusercontent.com/49008623/105079908-0c878100-5acb-11eb-8446-0518732ac637.png)
i get ScreenToGif from Windows Store, then i remove it, but in Settings, there is some mistake??? why? 
![image](https://user-images.githubusercontent.com/49008623/105080257-8b7cb980-5acb-11eb-8ff4-e6017ce2f7a3.png)

**Comment by NickeManarin** [comment]
That's possibly an issue with Windows itself, not ScreenToGif.

That settings page displays all programs that once used the notification drawer (system tray). 
I'm not sure if it ever cleans any missing apps from it.

**Comment by Char-z** [comment]
@NickeManarin 
i have resolve this problem, as your said, that is not ScreenToGif's fault, but Win.
Howto:
1. open regedit
2. delete key `IconStreams` and `PastIconsStream` from `HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\CurrentVersion\TrayNotify`
3. restart explorer.exe from Taskmgr.exe
