### ISSUE TITLE
Applying current operation to all picture

### ISSUE THREAD

**Issue by Bollie15** [NickeManarin/ScreenToGif#785]
This software is the best tools to create gif. I like it!
But I have a question about how to make my current operation on the i-th picture apply to all pictures after i
![_J8{L}BAWS@53IZ QBJ3{PM](https://user-images.githubusercontent.com/56813612/105343973-4799c980-5c1d-11eb-9243-c51835e2a796.png)

Thanks in advance. 👍👍👍

**Comment by NickeManarin** [comment]
You just need to select all the frames that you want to apply the overlay over.
