### ISSUE TITLE
Interface rendering with strange black shadow

### ISSUE THREAD

**Issue by Alendia** [NickeManarin/ScreenToGif#790]
Version 2.27.3
Irregular black shadow appears on interface as shown below.
![image](https://user-images.githubusercontent.com/44888915/105760353-a39d7e80-5f8c-11eb-8ff2-8e3637d5468b.png)

**Comment by NickeManarin** [comment]
AMD graphics adapter? Disable hardware acceleration under Options > Application.
It's a known issue without a proper fix.

Before disabling hardware acceleration, try updating the video adapter graphics first.

**Comment by Alendia** [comment]
Sorry for asking a known fixed issue. Thank you for your advice!!!
