### ISSUE TITLE
New Recorder interface size error on high dpi monitor

### ISSUE THREAD

**Issue by dimitarsp** [NickeManarin/ScreenToGif#793]
Hi, with the new recorder, when trying to record an area 1920 x 1080 on a 4k monitor resolution, with display area set at 150% magnification, the area seems to be about 1.5 time larger than the intended resolution. 

When switching to the old recorder, 1920 x 1080 resolution appears to be correct. When switiching back to the new recorder the resolution changes to a size of  1003 X 646.

**Comment by NickeManarin** [comment]
Done, it will be available with v2.32.

There's still an issue with sizing because of a rounding error.
The frame captured will be 1px smaller than the selection, but I'm going to solve that later.
