### ISSUE TITLE
Empty, transparent frames when capturing from secondary screen

### ISSUE THREAD

**Issue by johnknoop** [NickeManarin/ScreenToGif#798]
I have a large 4K display with 125% zoom factor as my primary display, and the 1080p laptop display as my secondary.

When I record, I'd like to use the laptop screen, because any time I do screen capture on the 4K display, the resulting image is big and blurry (both using ScreentoGif or when just capturing part of the screen using WIN+SHIFT+S).

But if I record from the secondary screen using ScreenToGif, the result is just a bunch of transparent frames with nothing in them.

Is this a known limitation?

OS: Windows 10

**Comment by NickeManarin** [comment]
If the `Snip and Sketch` app also has the same bad result (a blurry image) perhaps there's something wrong with the display adapter of your laptop.

Have you tried to reinstall the graphics driver and restarting your computer?

The only limitation for recording in laptops is that the DirectX capture does not work on secondary screens (DirectX limitation).

**Comment by johnknoop** [comment]
Hi @NickeManarin 

I was probably a bit unclear in my description... The blurry thing is normal, it happens on all Windows computers when you have 125% scaling. That's why I prefer to take screenshots and recordings on my secondary display, which has no scaling (since it's not a high PPI screen). And it's when I use ScreenToGif on my secondary display that the resulting images are just transparent.

**Comment by johnknoop** [comment]
I shot a video using my phone that perhaps shows the problem better:

https://1drv.ms/v/s!AlB0UH0hZbPQieAXA9v5EqJuKYeLOg

**Comment by johnknoop** [comment]
@NickeManarin have you been able to reproduce it?

**Comment by NickeManarin** [comment]
Thanks for the video, but I haven't been able to reproduce with my laptop. I'll have to move my desktop to my living room to test with a 4k screen. 

Have you tried to mode the capture region around the secondary screen to all corners?

**Comment by johnknoop** [comment]
@NickeManarin yes I've tried all kinds of things, like full screen, a window, an area, making that area bigger etc. They all result in transparent pixels.

**Comment by johnknoop** [comment]
@NickeManarin have you had a chance to look at this?

**Comment by johnknoop** [comment]
Oh, I just got the new update. The transparent pixels problem is gone! Unfortunately, it doesn't capture the cursor like it does when recording on the primary screen, but it's a step in the right direction!

**Comment by NickeManarin** [comment]
Ohhh, ok.

I'm going to open a new issue ticket for that.

**Comment by NickeManarin** [comment]
Ohhh, ok.
I'm going to fix that too :)

**Comment by NickeManarin** [comment]
Fixed! 

It will be available with the next version, 2.28.3.
