### ISSUE TITLE
Exception on saving to GIF or Video.

### ISSUE THREAD

**Issue by theKorzh** [NickeManarin/ScreenToGif#8]
Trying to save 1720-frame animation got an exception with text "file 0.png" already exists.
Nothing is changed in recorded frameset except that one frame duration is changed to 2500msec and  some text added to it.
Log file:  ##[log_14_9_2016.txt](https://github.com/NickeManarin/ScreenToGif/files/471133/log_14_9_2016.txt)

**Comment by NickeManarin** [comment]
Thank you for the feedback :)

Just to check, is this related to release 2.2?

**Comment by komapoow** [comment]
Looking at the Log File, so it does not contains an error's line in the code. It will be good if you give us .PDB file from your bin directory. using the file along with .EXE file will give you line number as well while exceptions raising. ;)
Same error i have :(

**Comment by NickeManarin** [comment]
Indeed, I'll make it available to download next time.

I had this same problem during release 2.1 and apparently I didn't fix it. :/

**Comment by theKorzh** [comment]
Yep. Version 2.2
So, what I done so far:
First, I deleted frame #0 from sequence (that frame also looked misplaced). Trying to save GIF resulted to message "0.png not found". Ok...
So I copied 1.png to 0.png in the "Recording<datetime>" folder and clicked "Save" once again. And it works!
Here is full log: [log_14_9_2016.txt](https://github.com/NickeManarin/ScreenToGif/files/471156/log_14_9_2016.txt)

**Comment by NickeManarin** [comment]
I believe it's fixed.
