### ISSUE TITLE
Triple click to select all does not work for file name text boxbox

### ISSUE THREAD

**Issue by XanderLuciano** [NickeManarin/ScreenToGif#80]
You cannot triple click to select the entire file name when saving a gif.

Triple click should behave like CTRL+A and select the entire line. (Try triple clicking this line to see the behavior I am talking about)

Triple clicking requires less accuracy than clicking and dragging, it is easier than trying to press ctrl-a, (and is faster since my hand is already on my hosue), and is a supported in many places.
![triple click stg](https://cloud.githubusercontent.com/assets/13877593/22686384/d8c4a442-ecd8-11e6-8a28-12a6f00263b2.gif)

### Environment

Operating system and version:
Windows 10 Pro 64-bit EN

ScreenToGIF:
2.4

**Comment by NickeManarin** [comment]
I bumped into this issue yesterday. I saw that I'm using the wrong text box type for that field. I just need to switch. Thanks.

**Comment by NickeManarin** [comment]
I already have a visual element for that purpose. It's called `ExtendedTextBox`, already in the solution.

**Comment by XanderLuciano** [comment]
Ah didn't realize that, however `ExtendedTextBox` only does `SelectAll()` when the textbox receives focus, but doesn't allow for triple clicking which I do through `PreviewMouseLeftButtonDownEvent` and checking `if (e.ClickCount == 3)` 

But I can merge my code into `ExtendedTextBox` instead of complicating the codebase.

**Comment by XanderLuciano** [comment]
Updated the PR branch with the above modification.

**Comment by NickeManarin** [comment]
Optional behavior under Options > Interface.
