### ISSUE TITLE
Add winget distribution 

### ISSUE THREAD

**Issue by musm** [NickeManarin/ScreenToGif#801]
Would be nice to add to the winget community package list

**Comment by NickeManarin** [comment]
It's already there.

https://github.com/microsoft/winget-pkgs/tree/master/manifests/NickeManarin/ScreenToGif

**Comment by musm** [comment]
Ah sorry didn't see it when searching. Might be good to add it to the readme?

**Comment by NickeManarin** [comment]
Yes, I ended up just adding to the website.

**Comment by alanlivio** [comment]
Hi @NickeManarin, this is a nice feature.
However, when install from winget, ScreenToGif installer require admin privileges although using the winget --scope=user.
Is there a way to fix it (it may be good for organization-based PCs)?
