### ISSUE TITLE
Installer Source Code

### ISSUE THREAD

**Issue by randyburden** [NickeManarin/ScreenToGif#804]
Hi, would you be willing to share the installer source code?

The installer looks really great and I have not been able to find any polished and complete working installers written with WixSharp using embedded WPF.

FYI, I found your project via an issue you posted on the WixSharp repo: https://github.com/oleg-shilo/wixsharp/issues/99

**Comment by NickeManarin** [comment]
Hi, I can teach you how to create something similar. 
It's a bit of a hack, you just need a XAML host inside a normal WinForms panel.

Besides that, you can use styles found in this repository. :)

**Comment by randyburden** [comment]
Hi, thanks for the offer and tip. I moved forward with a WinForms solution that looks pretty decent.

**Comment by Manvish1230** [comment]
HI Nicke, I am interested in learning on how to create installer like yours.
I am searching for information on how to host XAML inside WinForms panel, but I could not find it.
Could you share some information?

Thanks

**Comment by NickeManarin** [comment]
Just search for "Host WPF elementin WinForms". 
There's a built-in control that allows you to load your own WPF UserControl.
