### ISSUE TITLE
Editor is too wide when it opens

### ISSUE THREAD

**Issue by XanderLuciano** [NickeManarin/ScreenToGif#81]
Whenever I finish recording a gif, the editor opens really wide (looks to be 1920 pixels wide, my screen is 2160 by 1080 for comparison)

Here is how wide it opens at currently:
![image](https://cloud.githubusercontent.com/assets/13877593/22686903/e345ebae-ecda-11e6-9bf3-b603e4148f48.png)

Here is how I think it _should_ open:
![image](https://cloud.githubusercontent.com/assets/13877593/22686922/f09424a6-ecda-11e6-8b1b-a6bf1625d6ee.png)

Here is a screenshot from version 1.4.2, which shows how I would like it to behave:
![image](https://cloud.githubusercontent.com/assets/13877593/22687010/350a3ab2-ecdb-11e6-9b30-152169557740.png)

**Comment by NickeManarin** [comment]
The **Editor** (like the **Recorder**) will save its own size and position. So, if you resize, the app remembers.

**Comment by NickeManarin** [comment]
Done. There's now (for v2.9) two related options:

![image](https://user-images.githubusercontent.com/14798947/28487732-c7169072-6e6d-11e7-93fc-c71c0da3a972.png)

The first one will adjust the window size, as requested by you and the second option will adjust the frame zoom based on the window size. 

Also, if you want to adjust the window size after loading, there's a button for that:

![image](https://user-images.githubusercontent.com/14798947/28487745-417e7b68-6e6e-11e7-8239-0fad13da7c45.png)
