### ISSUE TITLE
Similar products are listed in the Microsoft Store.

### ISSUE THREAD

**Issue by nameofSEOKWONHONG** [NickeManarin/ScreenToGif#813]
Have you ever registered in the Microsoft Store?

It looks like unauthorized software.

Please check the attached screenshot.

![screentogif_copy](https://user-images.githubusercontent.com/24273022/112753633-516fec80-9013-11eb-90cd-11ace532927f.PNG)

![screentogif_copy2](https://user-images.githubusercontent.com/24273022/112753638-592f9100-9013-11eb-9cd5-e206d47a321a.PNG)

**Comment by NickeManarin** [comment]
Ohhh, another copy of the app. :(

They removed the name of the author of the translations:

![lang 30](https://user-images.githubusercontent.com/14798947/112755598-b0077d00-8fb7-11eb-9ec3-7bcd3225e7f5.png)
 
There's a tiny reference to me, tucked in the About section, I could see thanks to one frame in a gif made by the developer.
I had to download the gif and extract the frame to read it. Hahaha

![info 53](https://user-images.githubusercontent.com/14798947/112755649-fe1c8080-8fb7-11eb-9d99-dc850e4d3216.png)

Looks like the name of the de is Alexey:

![name 36](https://user-images.githubusercontent.com/14798947/112755673-17bdc800-8fb8-11eb-84e5-576fa88c6ee0.png)

Alexey, if you are reading this, it's is a 1/10 job.
Why did you remove the author names of the translations?
Why there's just one tiny reference to me, not even to the name of the app?
