### ISSUE TITLE
Can anyone tell me what is wrong with this software？

### ISSUE THREAD

**Issue by HankeZhao** [NickeManarin/ScreenToGif#817]
![录制](https://user-images.githubusercontent.com/44726566/113140676-50c99700-925b-11eb-8ef2-76e972e57ae5.gif)
my system is win10，software version is 2.27.3.0

**Comment by NickeManarin** [comment]
There's a pinned issue about this:

![image](https://user-images.githubusercontent.com/14798947/113143583-ac1b6b00-9202-11eb-97dd-4f09c8bf7f85.png)

It's an issue with the rendering, related to AMD hardware.

Disable hardware acceleration under Options > General.
