### ISSUE TITLE
Weird framerate, speeded up recording 

### ISSUE THREAD

**Issue by Kotoru** [NickeManarin/ScreenToGif#818]
So, since there's no sound recording I was using Audacity and then Filmora to match the recording with the audio and NOTICED that it had a slightly altered framerate. I ended up slowing the video down to 72% in order to get the perfect match. I was exporting in 30 FPS which I considered a standard. What's the problem then?
P.S. 
I still would love to see some simplistic integration of the audio recording, haven't found any decent alternatives to this program, all the others hurt my framerate and quality :(  
P.P.S. I know it's not easy :D

**Comment by NickeManarin** [comment]
With the next version, the options for exporting videos with FFmpeg will be easier to understand (also, it will be possible to control framerate and vsync, etc.).

Currently vsync is set o "2" in all cases, maybe that's the issue.

**Comment by NickeManarin** [comment]
Check v2.28.
