### ISSUE TITLE
FFMpeg integration\Scaling

### ISSUE THREAD

**Issue by Kotoru** [NickeManarin/ScreenToGif#819]
I've decided to try import and scale my footage(by nearest neighbor) using FFMpeg:
![image](https://user-images.githubusercontent.com/81743173/113277921-8ca73f80-92e1-11eb-9a18-0482aafcdb91.png)
but got this error:

   _en ScreenToGif.Windows.Other.Encoder.EncodeWithFfmpeg(String name, List`1 listFrames, Int32 id, Parameters param, CancellationTokenSource tokenSource, String processing)
   en ScreenToGif.Windows.Other.Encoder.<Encode>d__26.MoveNext()

Command:

-vsync 2 -safe 0 -f concat -i "file:C:\Users\almaz\AppData\Local\Temp\ScreenToGif\Recording\2021-04-01 09-28-21\Encode 2021-04-01 11-58-33-64\concat.txt" ffmpeg -i <input> -vf 'scale=iw*3:ih*3' -sws_flags neighbor <output> -y "C:\Users\almaz\Desktop\3.avi"

Result:

ffmpeg version 4.3.2-2021-02-27-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, concat, from 'file:C:\Users\almaz\AppData\Local\Temp\ScreenToGif\Recording\2021-04-01 09-28-21\Encode 2021-04-01 11-58-33-64\concat.txt':
  Duration: 00:00:14.50, start: 0.000000, bitrate: 23 kb/s
    Stream #0:0: Video: png, rgba(pc), 1273x717 [SAR 3779:3779 DAR 1273:717], 25 tbr, 25 tbn, 25 tbc
<input>: Invalid argument_

Is there something wrong with my code or maybe I haven't integrated the exe file correctly?
I've used this file?.
![image](https://user-images.githubusercontent.com/81743173/113278170-dee86080-92e1-11eb-9452-9562143ab128.png)

**Comment by NickeManarin** [comment]
> -vsync 2 -safe 0 -f concat -i "file:C:\Users\almaz\AppData\Local\Temp\ScreenToGif\Recording\2021-04-01 09-28-21\Encode 2021-04-01 11-58-33-64\concat.txt" ffmpeg -i -vf 'scale=iw3:ih3' -sws_flags neighbor -y "C:\Users\almaz\Desktop\3.avi"

Currently, the FFmpeg command is cannot be fully customized.
I'm changing that for v2.28.

As you can see the parameters are a subset of the whole command.
You can try removing "ffmpeg -i" from the parameter text box.

**Comment by Kotoru** [comment]
I see! Glad to hear that!

**Comment by NickeManarin** [comment]
@Kotoru You can try out the beta for v2.28: https://github.com/NickeManarin/ScreenToGif/issues/826

**Comment by NickeManarin** [comment]
Checkout v2.28, it's available already.
