### ISSUE TITLE
Load GIF in Editor : only first frame is good

### ISSUE THREAD

**Issue by payne911** [NickeManarin/ScreenToGif#824]
Try loading this GIF in the Editor: https://thumbs.gfycat.com/BlackImmaterialClumber-size_restricted.gif

First frame:

![image](https://user-images.githubusercontent.com/38117856/114322915-ca317700-9af0-11eb-89c1-2be87e07a6bb.png)

Second frame:

![image](https://user-images.githubusercontent.com/38117856/114322918-cf8ec180-9af0-11eb-9328-72b3c5e4f845.png)

Third frame: 

![image](https://user-images.githubusercontent.com/38117856/114322926-d61d3900-9af0-11eb-8043-fce70b35c65a.png)

It gets progressively worse... Last frame:

![image](https://user-images.githubusercontent.com/38117856/114322932-e1706480-9af0-11eb-80f2-3a1406b409b9.png)

**Comment by NickeManarin** [comment]
Fixed, ready for next version, v2.28.

![image](https://user-images.githubusercontent.com/14798947/115333353-e926ad80-a16f-11eb-831c-9d12d27139f5.png)
