### ISSUE TITLE
Suggestion: Delete All Previous/Next should consider range selection

### ISSUE THREAD

**Issue by pawlos** [NickeManarin/ScreenToGif#825]
Doing some editing in the program I've noticed that "Delete All Previous/Next" does take into an account only the one selected frame when performing the operation. 

I think it should take the range selection into an account. So if we have 5 frame selected "Delete All Next" should delete all the frames that are after the 5th one (last in the range). Similarly "Delete All Previous" should delete all prior to the first frame in the range selection.

After this change it will wok in a similar fashion for single frame selection and range selection.

I'm happy to provide PR for such change, just before doing so I wanted to run this idea by core maintainers.

**Comment by NickeManarin** [comment]
Makes sense, thank you reaching out.
You are welcome to start working on a fix for this issue. :)

**Comment by pawlos** [comment]
The PR fixes this issue. I've noticed some other quirks (selection after command executes) but I guess it's better to fix them in a separate PRs.

**Comment by NickeManarin** [comment]
Yes, I also found that the commands where still executing when the selection is at the start and end.
It was a simple fix (the CanExecute actions needed to be updated too).
