### ISSUE TITLE
Miscellaneous in GUI and translation

### ISSUE THREAD

**Issue by wvxwxvw** [NickeManarin/ScreenToGif#832]
~~1. A short field for the text, as you can see there is a lot of space there~~
2. Not translated
![2021 04 21_182347](https://user-images.githubusercontent.com/13194155/115580073-6d437700-a2cf-11eb-8741-140d2fd37bde.png)

**Comment by wvxwxvw** [comment]
Regarding point 1, hang up. It was a jamb in translation.

**Comment by NickeManarin** [comment]
Thanks! I just fixed that.
An update will be available in a few hours.
