### ISSUE TITLE
Updating the app maintains the previous version entry in windows "Programs and Features"

### ISSUE THREAD

**Issue by darkred** [NickeManarin/ScreenToGif#833]
I had ScreenToGif 2.28.0 installed via `ScreenToGif.2.28.Setup.msi` installed in win10 x64 20h2.

Today, I wanted to update to the new version, 2.28.1 .
So I tried: 
- downloading `ScreenToGif.2.28.1.Setup` and running it,
- (uninstalling+reinstalling 2.28.0 and) updating via the program itself,

and in both cases, 
in windows "Programs and Features": the old `2.28.0` entry remained and an additional `2.28.1`  created:
![2021-04-21_183441](https://user-images.githubusercontent.com/723651/115582017-353d3380-a2d1-11eb-8eab-955d72b79931.jpg)

This shouldn't occur because the updated program still has the same `ScreenToGif` directory:
![2021-04-21_183611](https://user-images.githubusercontent.com/723651/115581750-f7d8a600-a2d0-11eb-89ae-b4742789ecbe.jpg)

Thank you

**Comment by NickeManarin** [comment]
Did you install with the option to "all users" ticked or not?

**Comment by darkred** [comment]
There's only one local account in my Windows 10 installation, `Administrator` [[screenshot](https://user-images.githubusercontent.com/723651/115681444-3451e380-a35d-11eb-8501-c91e8c5e1732.jpg)]

And, during ScreenToGif install/update,
the only option I got related to "all users" was `Add the shortcut to all users`, and yes, it was ticked (already, by default) : 

<details>
<summary>screenshots</summary>

![2021-04-22_111840](https://user-images.githubusercontent.com/723651/115681028-cd342f00-a35c-11eb-877f-f6ed6f69d604.jpg)
![2021-04-22_112000](https://user-images.githubusercontent.com/723651/115681045-d02f1f80-a35c-11eb-9182-311340e884d9.jpg)


</details>

**Comment by NickeManarin** [comment]
Ok, this issue is related to a flag (ALLUSERS) used in the installer.
When the option to install the app to all users is ticked and later in an update is not ticked, it is treated as another separated app.
So it creates another entry in the App list.

One way to go would be to run a custom action removing the current version before installing it on top.

**Comment by NickeManarin** [comment]
I'm going to close this issue because I'm tracking it via #721.

I have a working solution for stopping this issue, but you'll need to uninstall the broken version before installing the new version.

**Comment by NickeManarin** [comment]
I managed to make it to work, you don't need to uninstall manually the previous version.
The installer detects that a previous version was installed on the same folder, but with a different access mode (per-user / per-machine) and it uninstalls before installing the new version.

**Comment by darkred** [comment]
Thank you for fixing this.
