### ISSUE TITLE
Version 2.28.1 killed all the settings and didn't want to save them anymore

### ISSUE THREAD

**Issue by wvxwxvw** [NickeManarin/ScreenToGif#835]
By the way, you need to add the option to backup the program settings.

**Comment by NickeManarin** [comment]
Do you mean the export settings or the whole app's settings?

**Comment by wvxwxvw** [comment]
Applications. To avoid such misunderstandings.

**Comment by NickeManarin** [comment]
I just tested with a previous version settings file, the app loaded the settings (except the export settings, which are not compatible with the new release) and it was able to save it again when closing the app.

Can you check if there's any log file that was created?

**Comment by wvxwxvw** [comment]
There are  
[21_04_21____ch19-17__MyDoc.zip](https://github.com/NickeManarin/ScreenToGif/files/6353166/21_04_21____ch19-17__MyDoc.zip)
[21_04_21____ch20-18__port.zip](https://github.com/NickeManarin/ScreenToGif/files/6353167/21_04_21____ch20-18__port.zip)
  
I initially deleted this version and returned 2.28.0, there are no problems with it. But now, during the test, it turned out that with the new settings file created in 2.28.0, everything seems to be fine, so far.

**Comment by NickeManarin** [comment]
So, you were using v2.27.3, downloaded and used v2.28 and when starting to use v2.28.1 the settings were lost?

**Comment by NickeManarin** [comment]
I changed the way how the settings are parsed, by adding some other validation steps before trying to parse.

I also fixed the second issue (about not being able to save the settings).
One or more settings were set to null and the settings exporter wis not able to determine the type of the property when saving.

**Comment by wvxwxvw** [comment]
> So, you were using v2.27.3, downloaded and used v2.28 and when starting to use v2.28.1 the settings were lost?

Yes. Moreover, one or more times 2.28.1 loaded the settings. More precisely, I do not remember, probably it is in the logs.
