### ISSUE TITLE
Save as: Filename formatters / template variables: Removed in 2.28.0?

### ISSUE THREAD

**Issue by tony** [NickeManarin/ScreenToGif#837]
Hi!  Thank you for the application @NickeManarin! 

Regarding [2.28](https://github.com/NickeManarin/ScreenToGif/releases/tag/2.28), I currently format via this:

`?yyyy-MM-dd HH-mm-ss? - PR number - my mesage`

In 2.27, this works.

In 2.28, there's still a tooltip ([src](https://github.com/NickeManarin/ScreenToGif/blob/10e7eacc432a6153d69a5f613aeacc4098d3fbf4/ScreenToGif/Resources/Localization/StringResources.en.xaml#L1694)), but trying to use these will produce an error:

![image](https://user-images.githubusercontent.com/26336/115609297-fac19f80-a2ac-11eb-8b0c-041d72bf36f6.png)

![image](https://user-images.githubusercontent.com/26336/115609437-25135d00-a2ad-11eb-8100-5ef43a38d0fe.png)

> The output file name contains one or more invalid characters. Please, select a valid file name. (via `S.SaveAs.Warning.Filename.Invalid`)

```xml
    <s:String x:Key="S.SaveAs.Warning.Filename.Invalid">The output file name contains one or more invalid characters. Please, select a valid file name.</s:String>
```

See also: #282

**Comment by NickeManarin** [comment]
Thanks for the feedback!
The validation was moved to before the filename was properly resolved.

A new release should be available in a few hours.

**Comment by tony** [comment]
Thank you @NickeManarin !
