### ISSUE TITLE
[Feature Request] Retain output and filename among presets

### ISSUE THREAD

**Issue by tony** [NickeManarin/ScreenToGif#838]
Hi! Thank you again for the application @NickeManarin!  This is a tiny one, but wanted to document it for posterity in case anyone else would like it.

(Not sure if this is my own personal habit or the expectation of the common user!)

My intuition expects to "Save as" with the same file name and destination folder in different file types/presets.

In 2.27 and at least 2.28.1, switching the dialog resets / uses the file name for that file type/preset rather than keeping the filename consistent.

I feel surprised when file name changes simply from switching the output types. 

For instance:

![image](https://user-images.githubusercontent.com/26336/115610726-df579400-a2ae-11eb-81b9-c151549185e6.png)

Switching the "file type" wouldn't reset the filename or the destination folder.

### Step 1
![image](https://user-images.githubusercontent.com/26336/115610066-f9dd3d80-a2ad-11eb-9f1f-a4ed0f48a480.png)

### Step 2: Switch filetype / preset

![image](https://user-images.githubusercontent.com/26336/115611154-5bea7280-a2af-11eb-934f-245d190dba08.png)

#### current behavior

Below: I would expect the "File" to be the same with the exception of the `.mp4` file extension

![image](https://user-images.githubusercontent.com/26336/115610178-2002dd80-a2ae-11eb-9cf1-ec2fde2884ee.png)

#### desired behavior

![image](https://user-images.githubusercontent.com/26336/115610324-52143f80-a2ae-11eb-930f-e43ead71dadb.png)

**Comment by NickeManarin** [comment]
The file name and folder are stored in each preset, I could create an option to persist the filename to all presets.

**Comment by tony** [comment]
@NickeManarin I think that would make sense

The file name and the file destination/folder, right?

We can leave this thread open to see if anyone agrees / disagrees, as well.  So far I think I'm the only one who mentioned it.

**Comment by byzod** [comment]
This is bothering me too

I need a "Set Working Directory" option

**Comment by NickeManarin** [comment]
Idea:

Create two options (Options > Application) to persist output path and filename to all presets.

- [ ] Persist the output path to other presets.
    - [ ] Persist the filename to other presets.
    - [x] Persist only to presets of the same file type.

When the output path or filename of a preset changes, the other presets will receive the same data.

**Comment by byzod** [comment]
Idea fragments I can think of

* Automatically optional suffix like `filename_gifski_present1.gif`
* Add a default working directory, all modes use its own path but add an option `use default directory`
* Same working directory, all modes use subfolders by default but can be changed by user. For example all gifs in `wd/gifs` and apng in `wd/apng`. User can change it to `whatever/apng2` and stg will remember it until user click `set as default` button

**Comment by NickeManarin** [comment]
The second idea can be implemented in another time, but by opening another issue ticket.

The first and third ideas I didn't properly understand. 
Looks like it wouldn't be easy to present that functionality for the user.
(Think that this app needs to easy to understand as possible)

**Comment by tony** [comment]
Thank you for looking into this @NickeManarin !

(Purely a UX bikeshed) Another angle of why the current output/filename handling is odd for me:

Since it's the same recording project, why would filenames and outputs be different between presets?

Right now - switching presets gives us the last project's filename for that preset, even when you just saved with a new filename for the project, which I think can be confusing to users.

People pick filenames based on the project, usually, I assume?

**Comment by NickeManarin** [comment]
I added some options to control this behavior.

![image](https://user-images.githubusercontent.com/14798947/124368438-7b9b0100-dc37-11eb-88b2-6591458a4917.png)

**Comment by NickeManarin** [comment]
@tony Ahh, yes. The behavior that you are referring to is something that want to implement. 
I'm reworking the editor from scratch, changing the UX (one of the things that I want to change is that).

The editor will work on top of projects, so to edit something, the app will create a project based on the type of file, locations, etc.

**Comment by tony** [comment]
@NickeManarin I'm excited to try these new settings out!

> @tony Ahh, yes. The behavior that you are referring to is something that want to implement.
> I'm reworking the editor from scratch, changing the UX (one of the things that I want to change is that).

Look forward to seeing this!  The UX you have already is excellent!  Wondering what the rework will look like.
