### ISSUE TITLE
"Save as project too" not saving file name

### ISSUE THREAD

**Issue by dfmore** [NickeManarin/ScreenToGif#849]
When using this feature in the new version I always seem to get an `.stg` file without a name. 

This is my config:
![image](https://user-images.githubusercontent.com/21298559/116159087-8ee59980-a6e7-11eb-9e50-12c33c9a2dd3.png)

And the result:
![image](https://user-images.githubusercontent.com/21298559/116158883-30b8b680-a6e7-11eb-89fe-ceb00c8d9b8b.png)

I use the software pretty much daily and it was working ok in the last version.

**Comment by NickeManarin** [comment]
- [ ] Ignoring filename.
- [ ] Not using only the option to save to disk.
