### ISSUE TITLE
[feature request] save selected frames only

### ISSUE THREAD

**Issue by joekingTheThird3** [NickeManarin/ScreenToGif#850]
If I have 100 frames I sometimes can make 2 or more gifs out of them. I'd like to just select any arbitrary list of frames and just export them as a gif. 

I'd also like some sort of loop points on playback. I try to make smoother looping gifs by selecting close seeming image frames.  Maybe you could select a list of frames and say, loop selected. A loop selected button?

**Comment by NickeManarin** [comment]
1) This option was released with v2.28, when saving open Export options and tick the option "Export partially".

2) You can use the Transition feature. Select the last frame, click on the Transition tab and apply a 2-3 frames transition.
