### ISSUE TITLE
Support arrows to move the recorder

### ISSUE THREAD

**Issue by Drarig29** [NickeManarin/ScreenToGif#86]
Hi!

Could you support arrow keys to easily move the recorder's window? And maybe Shift+Arrow to move quicker (5 pixel by 5 pixel for instance ^^)

**Comment by NickeManarin** [comment]
I just noticed that you can do that already, by pressing <kbd>Alt + Space</kbd> , selecting _Move_ and using your arrows combined with <kbd>Ctrl</kbd> to move 1 pixel.

**Comment by Drarig29** [comment]
Ok :)
