### ISSUE TITLE
Missing Translations

### ISSUE THREAD

**Issue by shenzhiming88** [NickeManarin/ScreenToGif#862]
Hello!
When I open the Recorder selection area, these translations are missing and the strings cannot be found in the language resource file, even in the English file. As shown in the picture.
Thanks!
![动画](https://user-images.githubusercontent.com/66902050/116672293-98674e00-a9d4-11eb-98c9-66c6a2c68736.gif)

**Comment by NickeManarin** [comment]
Thanks!
