### ISSUE TITLE
Pressing Enter to save doesn't take introduced name in consideration

### ISSUE THREAD

**Issue by duarteframos** [NickeManarin/ScreenToGif#87]
When saving a GIF file from the editor with `Ctrl+S`, pressing enter so save in the dialog doesn't take the newly typed name into consideration, it always saves with the last used file name instead.

Say I saved a file named GIF1.gif previously, that name will show up in the name text box as the last used file name, if I type GIF2.gif and press enter to save it will still save as GIF1.gif, unintentionally overwriting the previous file if it still there leading to potentially data loss. If I save as GIF3.gif next and press enter it will save GIF2.gif instead.

Pressing Save the button with a mouse click works as expected.

**Comment by NickeManarin** [comment]
Fixed. I got the same issue and was able to fix it, or at least I'm not able to reproduce anymore.

**Comment by duarteframos** [comment]
Thanks for the fix :)
