### ISSUE TITLE
Updates generates two installation files.

### ISSUE THREAD

**Issue by aserralta** [NickeManarin/ScreenToGif#879]
I received an update today an when updating and installing I noticed that now I have to STG installed in my machine.

![image](https://user-images.githubusercontent.com/44881213/116917344-25e4b100-ac14-11eb-84c6-6e1999d7872b.png)

If I go ahead and uninstall the older one, the new one it's also uninstalled.

**Comment by shenzhiming88** [comment]
Hello!
It might be duplicate.
https://github.com/NickeManarin/ScreenToGif/issues/833

**Comment by aserralta** [comment]
@shenzhiming88 ah you are right! I will close this one.
