### ISSUE TITLE
Playback buttons are disabled after "Save as"

### ISSUE THREAD

**Issue by pawlos** [NickeManarin/ScreenToGif#881]
I've noticed a weird behavior of the editor. After saving an animation all of the Replay buttons are disabled (they were enabled before ofc).

Did some checking and the responsible for this is the `_applyAction == null` in the following code

    private void Playback_CanExecute(object sender, CanExecuteRoutedEventArgs e)
    {
        e.CanExecute = Project != null && Project.Frames.Count > 1 && !IsLoading && _applyAction == null;
    }

as when Save is executed the `_applyAction` is set to `_applyAction = SaveAsButton_Click;` in the `finally` of `SaveAsButton_Click` . After that apparently it never gets nullified again. I guess this is done to prevent playing the video while saving/encoding is performed (although  my simple/quick test with commenting out this line didn't show any issues of playing while saving).

I guess the fix would be to set `_applyAction` to `null` when encoding is done, but not sure if that's possible in the current architecture of the system?

**Comment by pawlos** [comment]
@NickeManarin I could work on a fix for this, but as mentioned not sure if there's a clean way to do this with the current architecture of the app. Don't see it's doable without rewriting the big chunk of code. Any guidelines how you would try to solve this?

**Comment by NickeManarin** [comment]
The `_applyAction` should be set to null when the side panels are closed.
Like this, I believe:

```cs
if (await Task.Run(() => SaveAsync(preset)))
    ClosePanel(false, true);
```

I want to rework the Editor, with a new architecture in mind. 
The current codebase is slow and hard to change.

Some of the behaviors (like this one that we are discussing, for example) made a bit of sense back then, but I believe that it can be removed with little adverse consequences.

And yes, this `_applyAction` is being used in a `CanExecute` to prevent the playback of the preview when a panel is open. But the primary use is to allow the user to press Apply/Save.

**Comment by NickeManarin** [comment]
I'm planning a redesign for the editor for v3. 
I think that it's going to take a while for me to finish it.

---------------------

> Thanks for the info. I think it wont be that easy as ClosePanel(false, true); as in this case ClosePanel(false, true); is called before setting the _applyAction in the finally block. But I'll look around more anyway.

Ahh, sorry. I didn't see that.

**Comment by pawlos** [comment]
@NickeManarin I've created a PR. It's not the fix I was expecting to do, but I went through the code and I think this check for `_applyAction` in Playback was unnecessary in the first place (maybe before it looked differently). Did the testing and I don't see any unwanted behavior w/o this check. The playback is disabled as long as the side panel is opened and get enabled when it's being closed.

Please feel free to comment if you see something's not being right.

**Comment by NickeManarin** [comment]
Thanks. I merged the PR. 

I could not find any other issue with it too.
