### ISSUE TITLE
Weird behavior when importing an image

### ISSUE THREAD

**Issue by Overdrivr** [NickeManarin/ScreenToGif#882]
There is definitely something strange when importing an image onto a recording. I have a PNG image of size 1786x995. I try to import it on a recording that looks like to be the same size. I've checked this by right-clicking on the first slide and checking files details of the image :

![image](https://user-images.githubusercontent.com/1294805/117448789-75421e80-af3f-11eb-8f12-c138d2372614.png)

This is what happens when I try to import, the size of the recording appears to be different :

![image](https://user-images.githubusercontent.com/1294805/117448696-5774b980-af3f-11eb-9f39-9e976d0d82df.png)

When I try to change the size of the imported image to match the one in ScreenToGif import menu (1777x990), it still displays the old image size on the bottom left part of the interface. I even tried changing image name and importing and size is still not correct.

It looks like the entire flow is broken. I feel there are multiple different issues at play here, so it's difficult to offer a clear repro, and I cannot share the images they're for work.

Let me know what I can do to help debug this.

**Comment by pawlos** [comment]
I can see, the values are taken from the `Image` component and not from the image (that the component displays) itself. So it doesn't really show dimensions in px. 

It gets even weirder with HighDPI displays. 

Image dimentions: `560x314`
Size in S2Gif: `248.9x139.6`

I guess, at least for HighDPI, it might be the case of different units: px/points, but I guess the expectations here would be to see size in px.

**Comment by NickeManarin** [comment]
This looks like an issue with the DPI of the captured content.

Can you share the Statistics tab?
For the base recording and for just the image that you tried to import (open an empty editor and load the image).

![image](https://user-images.githubusercontent.com/14798947/117555588-d698e900-b036-11eb-90ef-e03049678309.png)

------------------------

This "Insert" UI will be removed in a near future release.
The insertion of images is going to more fluid, without that step.

**Comment by pawlos** [comment]
@NickeManarin if the request was for me (wasn't sure ;)), here's the data

Captured content:
![image](https://user-images.githubusercontent.com/1296768/117844118-b740cc80-b27f-11eb-9ca0-d991990bbd1e.png)

Static image:
![image](https://user-images.githubusercontent.com/1296768/117844152-be67da80-b27f-11eb-8b27-ac91b600a9ad.png)

Inserting:
![image](https://user-images.githubusercontent.com/1296768/117844227-c9bb0600-b27f-11eb-9f9a-2c0a2694146a.png)


Observe strange values in the last screenshot.

**Comment by Overdrivr** [comment]
@pawlos Just to confirm if you're seeing the same issue as me, both images in the OS have the same pixel count right ?

Below is the dimensions of the video's first frame, both from ScreenToGif and from OS:

![image](https://user-images.githubusercontent.com/1294805/118598737-da530b00-b7ae-11eb-80f3-d15bfb76e284.png)

And then I build a cover image with inkscape, that is exactly the same size (1804x1005) at 96DPI.

![image](https://user-images.githubusercontent.com/1294805/118599111-58afad00-b7af-11eb-927c-db9f93321257.png)

EDIT

By using the size of the image in ScreenToGif Statistics menu and not the one in the import menu, I can successfully import images correctly. So it looks like the size issue really lies in the import menu and not anywhere else:

![image](https://user-images.githubusercontent.com/1294805/118599371-b17f4580-b7af-11eb-9bee-b654ddef6a54.png)

**Comment by pawlos** [comment]
@Overdrivr I think I have a bit different issue, but I think they are connected in the fact that the Import editor is not taking the image dimensions (in pixels) but rather the Canvas that the image is displayed on (from my short analysis of this part of the code).

**Comment by NickeManarin** [comment]
@Overdrivr There are two issues here.

1) Your images have a different DPI. Basically 500px at 96dpi is not the same as 500px at 144dpi.
2) The Insert window is not displaying properly the sizes.

**Comment by NickeManarin** [comment]
I believe that I fixed the issues.

I'm inserting a 96dpi image into a 120dpi recording:

![image](https://user-images.githubusercontent.com/14798947/120910899-144e5900-c659-11eb-8eda-927651d489a0.png)

![image](https://user-images.githubusercontent.com/14798947/120910921-3ea01680-c659-11eb-8a93-62984c87d5da.png)

The insert window will now display the correct pixel size of the recording (the same that the Editor displays).

![image](https://user-images.githubusercontent.com/14798947/120910936-57a8c780-c659-11eb-943c-4d5317661d8b.png)
