### ISSUE TITLE
dual monitor bug

### ISSUE THREAD

**Issue by winner106** [NickeManarin/ScreenToGif#884]
can not record  gif on the second monitor

**Comment by NickeManarin** [comment]
Which version do you have?

Lastest is v2.29.1.

**Comment by NickeManarin** [comment]
Hi, can you give me more details of what's happening?

Current ScreenToGif version?
OS version?
Were you trying to record using DirectX or Bitblt (Options > Recorder)?

**Comment by winner106** [comment]
Lastest Version , Very Good UX! thanks
