### ISSUE TITLE
Separate recording window with no border so content can be recorded on edge of screen

### ISSUE THREAD

**Issue by lysylbn** [NickeManarin/ScreenToGif#89]
Recording window can't be placed on top or any edge of the screen, because window frame is limiting it.
Separate window for controls, and semi-opaque box that would become transparent when recording starts would resolve this.

**Comment by NickeManarin** [comment]
Working on it: https://github.com/NickeManarin/ScreenToGif/blob/master/ScreenToGif/Controls/GhostWindow.cs

**Comment by kwinz** [comment]
Will this also fix #109?

**Comment by NickeManarin** [comment]
Yes.

**Comment by kwinz** [comment]
Awesome. Great work!

**Comment by NickeManarin** [comment]
Almost finished:

![region](https://cloud.githubusercontent.com/assets/14798947/26708539/c5013a7a-4722-11e7-8aa4-c16cc80cd0b7.gif)

![window](https://cloud.githubusercontent.com/assets/14798947/26708544/c78eab1a-4722-11e7-8c51-abc1b469a6ac.gif)

**Comment by NickeManarin** [comment]
Done. To enable, head over to Options > Application.
