### ISSUE TITLE
[Feature idea] Add stopwatch text to animation

### ISSUE THREAD

**Issue by pawlos** [NickeManarin/ScreenToGif#896]
# Idea
I very often use the tool to record other applications running and to show that something takes (too) long time. Currently I was either record just the app (if the sluggishness is obvious) or place a stopwatch next to the recorded app to show the progress of time. 
I was thinking it could be nice idea to have ability to add stopwatch text on the animation, the same way as it's now possible to add keystrokes or progress. 

Haven't check if it's possible to calculate time for each frame but assuming there's a frame duration and delay it could be possible to do it.

@NickeManarin  I could work on this feature if it makes sense to be included in the application unless there's already something like that or you know that that's not possible to do for some reason.

**Comment by pawlos** [comment]
Ok, this can be done by Progress of type Text. Didn't know that one ;)

**Comment by NickeManarin** [comment]
Sorry to not being able to answer in time. :)

**Comment by pawlos** [comment]
No worries ;)
