### ISSUE TITLE
Does it works on Linux?

### ISSUE THREAD

**Issue by roccomuso** [NickeManarin/ScreenToGif#9]
Does it works on linux?

**Comment by NickeManarin** [comment]
I think that it won't work... There's a few P/Invokes to windows APIs.

**Comment by Weber-D** [comment]
The problem seems to be the WPF framework. I tried it on CentOS7 by installing the mono-complete package as described in the offical mono documentation, but 

```
[user@kube Downloads]$ mono ScreenToGif.exe 
The entry point method could not be loaded due to Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. assembly:PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 type:<unknown type> member:(null) signature:<none>
```
Sad to see that such a great tool doesn't work in 2018 on Linux :(

**Comment by vatterspun** [comment]
> Sad to see that such a great tool doesn't work on Linux in 2018 :(

Agreed.  My impression (based on the number and variety of screen capture tools built on .NET libraries) is that Microsoft spent a lot of time making that easy to do with their and then not much time making them cross-platform as was sort of the point of mono.

**Comment by DMW007** [comment]
Would like to donate if this works on Linux. But I swiched mainly to Linux and only have a single VM for Visual Studio, which I'm not using very often. So I sadly couldn't use ScreenToGif very much, altough it seems to be a great tool itself.
