### ISSUE TITLE
[feature request]self updating

### ISSUE THREAD

**Issue by EMLVIRUS** [NickeManarin/ScreenToGif#90]
Instead check out updates here manually, the apps should be able to check for update and download and install it itself.

**Comment by panther2** [comment]
Well, it does check automatically:

![screentogif_2017-02-20_18-19-39](https://cloud.githubusercontent.com/assets/20812775/23135564/774e163c-f799-11e6-8ee5-1c57d503184d.png)

Though I personally prefer to do it manually...

**Comment by NickeManarin** [comment]
Indeed, it does. But only when the Startup window is opened.

![image](https://cloud.githubusercontent.com/assets/14798947/23136107/eac301ce-f779-11e6-87a1-ae0bdf7964be.png)

![image](https://cloud.githubusercontent.com/assets/14798947/23136118/f79a0ac8-f779-11e6-9798-dba40bd68b5d.png)

Maybe I should add that verification of the editor too?

**Comment by EMLVIRUS** [comment]
Actually I'd prefer a banner noticification (or bubble on Windows 7)

**Comment by panther2** [comment]
As long as it remains to be optional I would be fine with either solution.

**Comment by NickeManarin** [comment]
Yes, optional. I like to be non intrusive too.

**Comment by NickeManarin** [comment]
The app will give a hint that an update is available when opening the editor, if the setting is enabled. 

The hint is non intrusive, it uses the same status band under the ribbon.
