### ISSUE TITLE
Can't find the async recording option, where is it?

### ISSUE THREAD

**Issue by wenfangdu** [NickeManarin/ScreenToGif#902]
![image](https://user-images.githubusercontent.com/28700378/119254202-9a918680-bbe7-11eb-844c-7d64e0b348c0.png)

[Picture Source](https://www.reddit.com/r/screentogif/comments/68obmw/increase_framerate/dh073k3?utm_source=share&utm_medium=web2x&context=3)

Also, how to improve framerates now? Seems a lot of functions have changed.

**Comment by NickeManarin** [comment]
There's no need for that anymore, it's all async now and the capture method were improved.

**Comment by wenfangdu** [comment]
@NickeManarin Thanks, good to hear, does enable "Fixed Framerate" still help to increase framerates?

**Comment by NickeManarin** [comment]
@wenfangdu 

No, it just sets the framerate to a fixed value.
If you want increased framerates, try using the DirectX capture mode, with memory cache enabled.
