### ISSUE TITLE
Missing file extension

### ISSUE THREAD

**Issue by seahindeniz** [NickeManarin/ScreenToGif#913]
Hi,

I'm using the `Export options > Copy to the clipboard > File path` option to save files in a temp folder and copy their paths.

For example, whenever I use `Save as` panel to save a recorded project as MP4 or GIF, I get this looking path
`C:\Users\Sahin\AppData\Local\Temp\f7b437cc-2602-432b-8d2a-6cfecb2a8924`

I expect it should save the file with their extensions, depending on their file type
`C:\Users\Sahin\AppData\Local\Temp\f7b437cc-2602-432b-8d2a-6cfecb2a8924.mp4`
or 
`C:\Users\Sahin\AppData\Local\Temp\f7b437cc-2602-432b-8d2a-6cfecb2a8924.gif`

**Comment by pawlos** [comment]
@NickeManarin if you haven't started I can have a look at this issue.

**Comment by NickeManarin** [comment]
@pawlos It's free, you can take it. I'm not working on this one.
