### ISSUE TITLE
[FR] Option to autoincrement file number if a file with the same name already exists

### ISSUE THREAD

**Issue by wenfangdu** [NickeManarin/ScreenToGif#916]
If the `Overwrite (if already exists)` under `Save the file to a folder of your choice` is not checked, I think it makes sense to add an option to autoincrement the file number instead of manual incrementing, if the proposed option is not checked, people can still have the `same file name` check.

![image](https://user-images.githubusercontent.com/28700378/121970448-29d62800-cda9-11eb-8842-2ad2da1add62.png)
![image](https://user-images.githubusercontent.com/28700378/121970232-aae0ef80-cda8-11eb-927e-485d662b3f6f.png)

**Comment by NickeManarin** [comment]
Ok, I was thinking to add another checkbox that unchecks the Override one when enabled.

**Comment by NickeManarin** [comment]
Btw, you can also use DateTime formats as an automatic file naming scheme.

> ? dd-MM-yyyy HH-mm-ss?

**Comment by wenfangdu** [comment]
> Btw, you can also use DateTime formats as an automatic file naming scheme.
> 
> > ? dd-MM-yyyy HH-mm-ss?

Great, didn't know that.

**Comment by wenfangdu** [comment]
> Btw, you can also use DateTime formats as an automatic file naming scheme.
>
> > ?dd-MM-yyyy HH-mm-ss?

I've tried this, worked really well, maybe an option for turning this on as well? Plus i18n for the time format, e.g. `?yyyy-MM-dd HH_mm_ss?` for Chinese.

**Comment by NickeManarin** [comment]
> maybe an option for turning this on as well

It's already enabled, do you mean an UI for selecting the format?

**Comment by wenfangdu** [comment]
@NickeManarin Yes, just about to edit the comment. The current UI is really hard to find this feature, many people simply don't do the hover. A better UI like a separate tip icon etc. would be better.

**Comment by varKeytrap** [comment]
Hey @NickeManarin , I came here because I didn't unerstand that you were supposed to put this format `?dd-MM-yyyy HH-mm-ss?` to get the filename with a date, I think that maybe the tooltip should be updated so it's more explicit. For now (in french version) it's only:
![image](https://user-images.githubusercontent.com/17864005/157847474-84695393-e61b-4a31-9cdc-65df17bc6e08.png)

**Comment by Combinacijus** [comment]
I propose changing default "save as" file name from `Animation.gif` to `gif_?yyyyMMdd_HHmmss?.gif`. This clearly shows formatting capabilities and that you can add text outside ??. 
Next add tooltip with example (incase person already deleted default one and don't remember correct modifiers) and explanations of available modifiers.

Tooltip example:
```
Name of a file e.g "gif_?yyyyMMdd_HHmmss?"
Text between ?...? are for Date/Time formatting e.g "?yyyyMM_dd?" will be saved as "202209_25.gif"
Available modifiers:
yyyy - current year, MM - month, dd - day, HH - hour, mm - minute, ss - second
```

Bonus feature would be to display formatted string under file name input field so you could see current date as final file name

**Comment by NickeManarin** [comment]
@Combinacijus 

I'm currently working on the next major release. 
Here's the current implementation of the file name automation:

![image](https://user-images.githubusercontent.com/14798947/217964146-6059f52b-be1e-4c5d-b22f-24421f7d3e2d.png)

UI is not final, but basically, it's supposed to be easier to add/edit/remove automated sections of the filename.
And the field tells you which parts are dynamic.

When inserting the dynamic field, you can select the format:

![image](https://user-images.githubusercontent.com/14798947/217964565-43b6271e-15f0-46e9-bd19-4b871dc223cd.png)

Or you can edit it yourself.

**Comment by Combinacijus** [comment]
@NickeManarin Oh wow that's amazing. This is miles beyond my suggestion. Great work 👍

**Comment by NickeManarin** [comment]
It will be available in the next version (v3).

**Comment by NickeManarin** [comment]
> Hi, This looks great. Was a v3 released? I didnt see it. Thanks!

No, it snowballed into something way bigger an I got busy with my full time job.
I hope to release it by the end of the year.
