### ISSUE TITLE
Crashed when trying to add an image to a recording

### ISSUE THREAD

**Issue by tkrytr** [NickeManarin/ScreenToGif#92]
Recorded some screen action. Edited it for a while. Saved the project. Then wanted to overlay a small image on top of a portion of the recording. When I was navigating to the image, ScreenToGif crashed. When I tried to open the project, I did not see it in the expected folder. The only thing I have been able to find is a collection of PNGs in this folder: C:\Users\<user>\AppData\Local\Temp\ScreenToGif\Recording\2017-02-20 15-07-01. Is there any way to restore/recreate the GIF using these images?

**Comment by NickeManarin** [comment]
Oh, do you have the log of that error? You can usually find it on the same folder as the executable.

Currently, the only way to restore the recording would be opening the editor and importing all images at once. :/

**Comment by tkrytr** [comment]
Here is the log file:
[log_20_2_2017.txt](https://github.com/NickeManarin/ScreenToGif/files/788661/log_20_2_2017.txt)

**Comment by NickeManarin** [comment]
Thank you for the log file. It looks like the app failed to get information of the selected frame on the frame list (bottom of the editor window), while importing the frames.

Wait, you said that you saved the project, then it should be there. (at least there's no log of any exception with the export process).

If there was an exception while exporting as project, you could try searching for a folder named "Export" inside this one: "C:\Users<user>\AppData\Local\Temp\ScreenToGif\Recording\2017-02-20 15-07-01".

**Comment by NickeManarin** [comment]
Btw, did the crash happened before or after opening the "Insert frames" window? (pops up asking for details on how to insert the frames).

**Comment by NickeManarin** [comment]
Well, this was fixed a while ago. I forgot to close this ticket.
