### ISSUE TITLE
Frame Export Jpg - not supported exception 

### ISSUE THREAD

**Issue by ltdeta** [NickeManarin/ScreenToGif#928]
If you want to save the frames as single images, this only works if you activate the option "zip the image".

![grafik](https://user-images.githubusercontent.com/1563652/124116292-198f9f80-da6f-11eb-86da-c4bfe8e67974.png)

If you do not select this option you will get an error message

![grafik](https://user-images.githubusercontent.com/1563652/124116345-27452500-da6f-11eb-8458-80671f05de65.png)

![grafik](https://user-images.githubusercontent.com/1563652/124116453-42179980-da6f-11eb-9b11-eefc11e03e8c.png)

**Comment by NickeManarin** [comment]
Thank you for the feedback.
