### ISSUE TITLE
Add option to visually show mouse clicks

### ISSUE THREAD

**Issue by jnachtigall** [NickeManarin/ScreenToGif#93]
Very nice and handy tool. There's just one feature that would be important to me: 

For some screencasts it would be good if the actual mouse clicks are shown, e.g. with a small circle around where the user clicked.

Could this maybe be added?

**Comment by NickeManarin** [comment]
Thank you :D

This feature is already present, but I understand it's a little bit hidden. Right now, to enable, you need to open Options > Application.

![Options](https://cloud.githubusercontent.com/assets/14798947/23257321/0c74673e-f9a2-11e6-97fb-12c6d927e409.png)

This automatically adds a circle on top of the cursor after the recording is done.
In a near future, I want to enable the option to add the mouse clicks _after_ the recording.

**Comment by jnachtigall** [comment]
Thanks, that's perfect.

**Comment by jnachtigall** [comment]
@NickeManarin Is there also a way to capture key strokes? For instance, I would have need one to show the pressing of Ctrl+C as shortcut

**Comment by NickeManarin** [comment]
Yes, but it's a little bit different. You have to record > open the editor > Image tab > Key strokes.

Note that all your keystrokes will be applied to the list of frames. Currently there's no way to remove keystrokes or apply only the selected ones.
