### ISSUE TITLE
[Bug] Focus dialog after using a shortcut to stop recording

### ISSUE THREAD

**Issue by wenfangdu** [NickeManarin/ScreenToGif#930]
Currently, when using a shortcut to stop recording, the "Discard Project" dialog won't be focused, although the "No" button seems to be focused, in fact, it's not, therefore using arrow keys to switch option is not available:

![image](https://user-images.githubusercontent.com/28700378/124371056-b2f9c400-dcb0-11eb-8526-5ca248ea86f7.png)

Meanwhile, _clicking_ the "stop recording" button will focus the "Discard Project" dialog:

![image](https://user-images.githubusercontent.com/28700378/124371368-b93d6f80-dcb3-11eb-8706-01f41bf78303.png)

For accessibility, it'd be great to unify this behavior and to generalize this issue, all dialogs might be checked.

**Comment by NickeManarin** [comment]
Thanks.

Looks like something is stealing the focus when the dialog is opening (or perhaps the dialog needs a force focus to activate properly).

**Comment by pawlos** [comment]
@NickeManarin If you haven't started working on this, I can have a look at this one.

**Comment by pawlos** [comment]
It looks like the issue is that the Window is shown but not Activated. When done the same by mouse click - activates it. Did some initial testing and calling Activate not always works. What works is showing the editor before showing the dialog. I'll test this solution more to see if there aren't any unwanted behavior.

**Comment by wenfangdu** [comment]
@NickeManarin @pawlos Just tried v2.33.1, still reproducible, could you please consider reopening this issue?

**Comment by pawlos** [comment]
I can't but @NickeManarin can reopen.

**Comment by NickeManarin** [comment]
It's working normally for me.
Pressing F8 to stop the recording still gives the focus to the dialog that asks about discarding the previous project.

Can you record your screen to show to us?
Or can you give us a step-by-step guide on how to get the same issue?

**Comment by wenfangdu** [comment]
@NickeManarin @pawlos

https://user-images.githubusercontent.com/28700378/127501006-fd7f506b-5b34-463f-a16f-7527ad7073e8.mp4

**Comment by wenfangdu** [comment]
@NickeManarin @pawlos

Steps:

1. Click "Record".
2. Click the screen being recorded (important, otherwise will return focus to the dialog).
3. Hit `F8`.

**Comment by pawlos** [comment]
@wenfangdu thx for the steps. I'll get back to this issue.
