### ISSUE TITLE
[BUG] mscorlib.ThrowIfExceptional

### ISSUE THREAD

**Issue by YoucanBaby** [NickeManarin/ScreenToGif#932]
One or more errors occurred.

at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at ScreenToGif.ImageUtil.ImageMethods.PaintTransparentAndCut(ExportProject project, Color chroma, Int32 taskId, CancellationTokenSource tokenSource)
   at ScreenToGif.Util.EncodingManager.<Encode>d__27.MoveNext()

Index was outside the bounds of the array.

at ScreenToGif.ImageUtil.ImageMethods.<>c__DisplayClass1_1.<PaintTransparentAndCut>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)

ScreenToGif.<PaintTransparentAndCut>b__0

**Comment by Korb** [comment]
> NickeManarin added duplicated on Jul 6, 2021

Which issue should be considered a duplicate of this one? #933 or #968? I also encountered the "Index was outside the bounds of the array" error when trying to save a screen recording I just made to any format, and I'm looking for a solution.

<details markdown="1">
<summary>Logs</summary>

> ► Title - 
> 	Encode
> ♦ [Version] Date/Hour - 
> 	[2.43.2] 09/05/2026 10:33:19
> ▬ Message - 
> 	Error while encoding the Webm with FFmpeg.
> ○ Type - 
> 	System.Exception
> ▲ Source - 
> 	ScreenToGif
> ▼ TargetSite - 
> 	Void MoveNext()
> ◘ Other - 
> 	Command:
> 
> -hwaccel auto -safe 0 -f concat -i "file:D:\Temp\ScreenToGif\Recording\2026-09-05 00-19-57\Encode 2026-09-05 10-33-18-61\concat.txt" -c:v libvpx -preset fast -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -crf 30 -b:v 0 -f webm -fps_mode passthrough -y "E:\Downloads\test.webm"
> 
> Result:
> 
> ♠ StackTrace - 
> at ScreenToGif.Util.EncodingManager.EncodeWithFfmpeg(ExportPreset preset, List`1 listFrames, Int32 id, CancellationTokenSource tokenSource, String processing) in R:\Source\NickeManarin\ScreenToGif\ScreenToGif\Util\EncodingManager.cs:line 1862
> at ScreenToGif.Util.EncodingManager.Encode(ExportProject project, ExportPreset preset, Int32 id, CancellationTokenSource tokenSource) in R:\Source\NickeManarin\ScreenToGif\ScreenToGif\Util\EncodingManager.cs:line 1057
> 
> ----------------------------------
> 
> ► Title - 
> 	Encode
> ♦ [Version] Date/Hour - 
> 	[2.43.2] 09/05/2026 10:33:37
> ▬ Message - 
> 	Error while encoding the Mkv with FFmpeg.
> ○ Type - 
> 	System.Exception
> ▲ Source - 
> 	ScreenToGif
> ▼ TargetSite - 
> 	Void MoveNext()
> ◘ Other - 
> 	Command:
> 
> -hwaccel auto -safe 0 -f concat -i "file:D:\Temp\ScreenToGif\Recording\2026-09-05 00-19-57\Encode 2026-09-05 10-33-37-01\concat.txt" -c:v libx264 -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -q:v 1 -minrate 0.50M -maxrate 5M -bufsize 1M -pass 1 -passlogfile "E:\Downloads\test.mkv" -f matroska -fps_mode auto -y "E:\Downloads\test.mkv"
> -hide_banner -hwaccel auto -safe 0 -f concat -i "file:D:\Temp\ScreenToGif\Recording\2026-09-05 00-19-57\Encode 2026-09-05 10-33-37-01\concat.txt" -c:v libx264 -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -q:v 1 -minrate 0.50M -maxrate 5M -bufsize 1M -pass 2 -passlogfile "E:\Downloads\test.mkv" -f matroska -fps_mode auto -y "E:\Downloads\test.mkv"
> 
> Result:
> 
> ♠ StackTrace - 
> at ScreenToGif.Util.EncodingManager.EncodeWithFfmpeg(ExportPreset preset, List`1 listFrames, Int32 id, CancellationTokenSource tokenSource, String processing) in R:\Source\NickeManarin\ScreenToGif\ScreenToGif\Util\EncodingManager.cs:line 1862
> at ScreenToGif.Util.EncodingManager.Encode(ExportProject project, ExportPreset preset, Int32 id, CancellationTokenSource tokenSource) in R:\Source\NickeManarin\ScreenToGif\ScreenToGif\Util\EncodingManager.cs:line 1057
> 
> ----------------------------------
> 
> ► Title - 
> 	Encode
> ♦ [Version] Date/Hour - 
> 	[2.43.2] 09/05/2026 10:33:54
> ▬ Message - 
> 	Error while encoding the Avi with FFmpeg.
> ○ Type - 
> 	System.Exception
> ▲ Source - 
> 	ScreenToGif
> ▼ TargetSite - 
> 	Void MoveNext()
> ◘ Other - 
> 	Command:
> 
> -hwaccel auto -safe 0 -f concat -i "file:D:\Temp\ScreenToGif\Recording\2026-09-05 00-19-57\Encode 2026-09-05 10-33-53-66\concat.txt" -c:v mpeg4 -vtag xvid -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -b:v 5M -pass 1 -passlogfile "E:\Downloads\test.avi" -f avi -fps_mode passthrough -y "E:\Downloads\test.avi"
> -hide_banner -hwaccel auto -safe 0 -f concat -i "file:D:\Temp\ScreenToGif\Recording\2026-09-05 00-19-57\Encode 2026-09-05 10-33-53-66\concat.txt" -c:v mpeg4 -vtag xvid -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -b:v 5M -pass 2 -passlogfile "E:\Downloads\test.avi" -f avi -fps_mode passthrough -y "E:\Downloads\test.avi"
> 
> Result:
> 
> ♠ StackTrace - 
> at ScreenToGif.Util.EncodingManager.EncodeWithFfmpeg(ExportPreset preset, List`1 listFrames, Int32 id, CancellationTokenSource tokenSource, String processing) in R:\Source\NickeManarin\ScreenToGif\ScreenToGif\Util\EncodingManager.cs:line 1862
> at ScreenToGif.Util.EncodingManager.Encode(ExportProject project, ExportPreset preset, Int32 id, CancellationTokenSource tokenSource) in R:\Source\NickeManarin\ScreenToGif\ScreenToGif\Util\EncodingManager.cs:line 1057

</details>

However, I don’t have an `R:`-drive.

Result of an export attempt after running a clean default configuration:

<details markdown="1">
<summary>Logs</summary>

> ► Title - 
> 	Encode
> ♦ [Version] Date/Hour - 
> 	[2.43.2] 09/05/2026 10:41:22
> ▬ Message - 
> 	Error while encoding the Mkv with FFmpeg.
> ○ Type - 
> 	System.Exception
> ▲ Source - 
> 	ScreenToGif
> ▼ TargetSite - 
> 	Void MoveNext()
> ◘ Other - 
> 	Command:
> 
> -hwaccel auto -safe 0 -f concat -i "file:D:\Temp\ScreenToGif\Recording\2026-09-05 10-40-43\Encode 2026-09-05 10-41-11-98\concat.txt" -c:v libx264 -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -q:v 1 -minrate 0.50M -maxrate 5M -bufsize 1M -pass 1 -passlogfile "E:\Downloads\test.mkv" -f matroska -fps_mode auto -y "E:\Downloads\test.mkv"
> -hide_banner -hwaccel auto -safe 0 -f concat -i "file:D:\Temp\ScreenToGif\Recording\2026-09-05 10-40-43\Encode 2026-09-05 10-41-11-98\concat.txt" -c:v libx264 -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" -q:v 1 -minrate 0.50M -maxrate 5M -bufsize 1M -pass 2 -passlogfile "E:\Downloads\test.mkv" -f matroska -fps_mode auto -y "E:\Downloads\test.mkv"
> 
> Result:
> 
> ffmpeg version 8.0.1-essentials_build-www.gyan.dev Copyright (c) 2000-2025 the FFmpeg developers
>   built with gcc 15.2.0 (Rev8, Built by MSYS2 project)
>   configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-openal --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
>   libavutil      60.  8.100 / 60.  8.100
>   libavcodec     62. 11.100 / 62. 11.100
>   libavformat    62.  3.100 / 62.  3.100
>   libavdevice    62.  1.100 / 62.  1.100
>   libavfilter    11.  4.100 / 11.  4.100
>   libswscale      9.  1.100 /  9.  1.100
>   libswresample   6.  1.100 /  6.  1.100
> Input #0, concat, from 'file:D:\Temp\ScreenToGif\Recording\2026-09-05 10-40-43\Encode 2026-09-05 10-41-11-98\concat.txt':
>   Duration: 00:00:51.40, start: 0.000000, bitrate: 8 kb/s
>   Stream #0:0: Video: png, rgba(pc, gbr/bt709/iec61966-2-1), 1145x1436 [SAR 3779:3779 DAR 1145:1436], 25 fps, 25 tbr, 25 tbn
> Stream mapping:
>   Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
> Press [q] to stop, [?] for help
> [libx264 @ 00000246cd6cc100] -qscale is ignored, -crf is recommended.
> [libx264 @ 00000246cd6cc100] using SAR=1145/1144
> [libx264 @ 00000246cd6cc100] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
> [libx264 @ 00000246cd6cc100] profile Main, level 4.0, 4:2:0, 8-bit
> [libx264 @ 00000246cd6cc100] 264 - core 165 r3223 0480cb0 - H.264/MPEG-4 AVC codec - Copyleft 2003-2025 - http://www.videolan.org/x264.html - options: cabac=1 ref=1 deblock=1:0:0 analyse=0x1:0 me=dia subme=2 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=0 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=12 lookahead_threads=4 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=23.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 vbv_maxrate=5000 vbv_bufsize=1000 crf_max=0.0 nal_hrd=none filler=0 ip_ratio=1.40 aq=1:1.00
> Output #0, matroska, to 'E:\Downloads\test.mkv':
>   Metadata:
>     encoder         : Lavf62.3.100
>   Stream #0:0: Video: h264 (H264 / 0x34363248), yuv420p(tv, unknown/bt709/iec61966-2-1, progressive), 1144x1436 [SAR 1145:1144 DAR 1145:1436], q=2-31, 25 fps, 1k tbn
>     Metadata:
>       encoder         : Lavc62.11.100 libx264
>     Side data:
>       cpb: bitrate max/min/avg: 5000000/0/0 buffer size: 1000000 vbv_delay: N/A
> frame=    0 fps=0.0 q=0.0 size=       0KiB time=N/A bitrate=N/A speed=N/A elapsed=0:00:00.52    
> frame=    0 fps=0.0 q=0.0 size=       0KiB time=N/A bitrate=N/A speed=N/A elapsed=0:00:01.02    
> frame=    6 fps=3.9 q=25.0 size=       1KiB time=00:00:00.36 bitrate=  13.6kbits/s speed=0.233x elapsed=0:00:01.54    
> frame=   30 fps= 15 q=25.0 size=       1KiB time=00:00:02.76 bitrate=   1.8kbits/s speed=1.34x elapsed=0:00:02.05    
> frame=   60 fps= 23 q=26.0 size=     212KiB time=00:00:05.76 bitrate= 300.9kbits/s speed=2.23x elapsed=0:00:02.57    
> frame=   89 fps= 29 q=26.0 size=     212KiB time=00:00:08.64 bitrate= 200.6kbits/s speed= 2.8x elapsed=0:00:03.08    
> frame=  117 fps= 32 q=26.0 size=     512KiB time=00:00:11.44 bitrate= 366.6kbits/s speed=3.17x elapsed=0:00:03.61    
> frame=  145 fps= 35 q=26.0 size=     512KiB time=00:00:14.24 bitrate= 294.5kbits/s speed=3.46x elapsed=0:00:04.11    
> frame=  170 fps= 37 q=26.0 size=     768KiB time=00:00:16.76 bitrate= 375.4kbits/s speed=3.61x elapsed=0:00:04.64    
> frame=  199 fps= 39 q=26.0 size=     768KiB time=00:00:19.64 bitrate= 320.3kbits/s speed=3.81x elapsed=0:00:05.15    
> frame=  228 fps= 40 q=26.0 size=    1024KiB time=00:00:22.56 bitrate= 371.8kbits/s speed=3.98x elapsed=0:00:05.67    
> frame=  256 fps= 41 q=25.0 size=    1024KiB time=00:00:25.36 bitrate= 330.8kbits/s speed= 4.1x elapsed=0:00:06.18    
> frame=  286 fps= 43 q=25.0 size=    1024KiB time=00:00:28.36 bitrate= 295.8kbits/s speed=4.23x elapsed=0:00:06.70    
> frame=  316 fps= 44 q=25.0 size=    1280KiB time=00:00:31.36 bitrate= 334.4kbits/s speed=4.34x elapsed=0:00:07.22    
> frame=  343 fps= 44 q=26.0 size=    1280KiB time=00:00:34.04 bitrate= 308.0kbits/s speed=4.41x elapsed=0:00:07.72    
> frame=  374 fps= 45 q=26.0 size=    1792KiB time=00:00:37.16 bitrate= 395.1kbits/s speed= 4.5x elapsed=0:00:08.25    
> frame=  402 fps= 46 q=26.0 size=    1792KiB time=00:00:39.96 bitrate= 367.4kbits/s speed=4.56x elapsed=0:00:08.75    
> frame=  433 fps= 47 q=26.0 size=    2048KiB time=00:00:43.04 bitrate= 389.8kbits/s speed=4.64x elapsed=0:00:09.28    
> [out#0/matroska @ 00000246cd6c69c0] video:2739KiB audio:0KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: 0.156519%
> frame=  515 fps= 53 q=-1.0 Lsize=    2743KiB time=00:00:51.24 bitrate= 438.6kbits/s speed=5.27x elapsed=0:00:09.71    
> [libx264 @ 00000246cd6cc100] frame I:3     Avg QP:14.57  size: 87962
> [libx264 @ 00000246cd6cc100] frame P:131   Avg QP:14.31  size: 18022
> [libx264 @ 00000246cd6cc100] frame B:381   Avg QP:21.50  size:   471
> [libx264 @ 00000246cd6cc100] consecutive B-frames:  0.8%  1.2%  1.7% 96.3%
> [libx264 @ 00000246cd6cc100] mb I  I16..4: 71.7%  0.0% 28.3%
> [libx264 @ 00000246cd6cc100] mb P  I16..4:  6.2%  0.0%  0.0%  P16..4:  8.5%  0.0%  0.0%  0.0%  0.0%    skip:85.3%
> [libx264 @ 00000246cd6cc100] mb B  I16..4:  0.2%  0.0%  0.0%  B16..8:  2.2%  0.0%  0.0%  direct: 0.1%  skip:97.5%  L0:49.7% L1:48.4% BI: 1.9%
> [libx264 @ 00000246cd6cc100] coded y,uvDC,uvAC intra: 34.5% 34.4% 28.9% inter: 1.0% 0.8% 0.5%
> [libx264 @ 00000246cd6cc100] i16 v,h,dc,p: 60% 34%  5%  1%
> [libx264 @ 00000246cd6cc100] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 35% 31% 17%  2%  3%  3%  3%  3%  3%
> [libx264 @ 00000246cd6cc100] i8c dc,h,v,p: 70% 11% 19%  1%
> [libx264 @ 00000246cd6cc100] Weighted P-Frames: Y:0.0% UV:0.0%
> [libx264 @ 00000246cd6cc100] kb/s:435.75
> 
> Input #0, concat, from 'file:D:\Temp\ScreenToGif\Recording\2026-09-05 10-40-43\Encode 2026-09-05 10-41-11-98\concat.txt':
>   Duration: 00:00:51.40, start: 0.000000, bitrate: 8 kb/s
>   Stream #0:0: Video: png, rgba(pc, gbr/bt709/iec61966-2-1), 1145x1436 [SAR 3779:3779 DAR 1145:1436], 25 fps, 25 tbr, 25 tbn
> Stream mapping:
>   Stream #0:0 -> #0:0 (png (native) -> h264 (libx264))
> Press [q] to stop, [?] for help
> [libx264 @ 0000014675fdc180] -qscale is ignored, -crf is recommended.
> [libx264 @ 0000014675fdc180] using SAR=1145/1144
> [libx264 @ 0000014675fdc180] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
> [libx264 @ 0000014675fdc180] CRF/CQP is incompatible with 2pass.
> [vost#0:0/libx264 @ 0000014675fd71c0] [enc:libx264 @ 0000014675fab540] Error while opening encoder - maybe incorrect parameters such as bit_rate, rate, width or height.
> [vf#0:0 @ 0000014675ffd7c0] Error sending frames to consumers: Generic error in an external library
> [vf#0:0 @ 0000014675ffd7c0] Task finished with error code: -542398533 (Generic error in an external library)
> [vf#0:0 @ 0000014675ffd7c0] Terminating thread with return code -542398533 (Generic error in an external library)
> [vost#0:0/libx264 @ 0000014675fd71c0] [enc:libx264 @ 0000014675fab540] Could not open encoder before EOF
> [vost#0:0/libx264 @ 0000014675fd71c0] Task finished with error code: -22 (Invalid argument)
> [vost#0:0/libx264 @ 0000014675fd71c0] Terminating thread with return code -22 (Invalid argument)
> [out#0/matroska @ 0000014675fd6a40] Nothing was written into output file, because at least one of its streams received no packets.
> frame=    0 fps=0.0 q=0.0 Lsize=       0KiB time=N/A bitrate=N/A speed=N/A elapsed=0:00:00.07    
> Conversion failed!
> ♠ StackTrace - 
>    at ScreenToGif.Util.EncodingManager.EncodeWithFfmpeg(ExportPreset preset, List`1 listFrames, Int32 id, CancellationTokenSource tokenSource, String processing) in R:\Source\NickeManarin\ScreenToGif\ScreenToGif\Util\EncodingManager.cs:line 1862
>    at ScreenToGif.Util.EncodingManager.Encode(ExportProject project, ExportPreset preset, Int32 id, CancellationTokenSource tokenSource) in R:\Source\NickeManarin\ScreenToGif\ScreenToGif\Util\EncodingManager.cs:line 1057

</details>

--- 

ScreenToGif 2.43.2 (Jul 28, 2026)
Microsoft Windows 10.0.26200.9278
