### ISSUE TITLE
Sell commercially

### ISSUE THREAD

**Issue by tony** [NickeManarin/ScreenToGif#934]
Stay open source, but the builds, installer, etc. can be commercial

IMO it'd make most sense to package this on Microsoft Store + Steam

Similar: https://github.com/aseprite/aseprite, https://store.steampowered.com/app/431730/Aseprite/

This assures you get compensated for the project and can continue updates, features, bug fixes, being active on the tracker, etc. 

This is app comprehensive enough of an application it's worth $14.99+ per seat IMO.

IMO the fair value for this apps of this level are $24.99-$74.99. Same for @dacap's Aseprite. His app is $19.99 ($14.99 on sale) but the apps go for double that ([example](https://store.steampowered.com/app/671190/Pro_Motion_NG/))

**Comment by NickeManarin** [comment]
Hi, Tony.

I do plan in releasing the app on Steam for a price (just so people can support the app).
But I still want to distribute the app for free on here and screentogif.com.

For the Microsoft Store, the app is currently free, but I may create a paid add-on or a paid package.

**Comment by tony** [comment]
@NickeManarin the door is always open to! !

I have a few tiny open source projects, none of them are anywhere near as end-to-end or comprehensive as ScreenToGif.  ScreenToGif even has an self updater.

I will close this for now so this doesn't take up any room on the tracker.
