### ISSUE TITLE
[Feature Request] Discard button while capturing?

### ISSUE THREAD

**Issue by AlexRoberts** [NickeManarin/ScreenToGif#936]
When I'm recording something sometimes I'll need to do 2 or 3 retakes to get it perfect.
As-is, I need to pause, click discard, then confirm on the dialog to get back to recording another take.
It would be nice to have the discard button available while capturing, and it could just pause and discard in one action.
Additionally, it would be great to have an option for "Don't show again" on the confirm discard dialog.

Thanks for this amazing tool, and I'm requesting this out of the love I have for the app!

**Comment by NickeManarin** [comment]
Hi, it's available in here:

![image](https://user-images.githubusercontent.com/14798947/124957225-3c7dfe80-dfef-11eb-858c-6773f59d64f9.png)

:)

**Comment by AlexRoberts** [comment]
Wow that was fast! 😂 Sorry I didn't notice! Keep up the great work, this app is incredible!

**Comment by NickeManarin** [comment]
Oh, thank you :)
