### ISSUE TITLE
Frame selection is broken several versions already

### ISSUE THREAD

**Issue by zoulja** [NickeManarin/ScreenToGif#939]
**Scenario:**
1. Click one frame
2. Press Shift + Left or Right to select next frames
3. Select as much as you need

**Expected result:**
Selection is extended is much as you need to edit your record

**Actual result:**
After few frames selection is lost, need to reselect again, usually just about 10 frames can work properly

This was worked fine several versions before, I dunno what happend

**Comment by pawlos** [comment]
Hey @zoulja can you see if I'm doing something different than you? I'm holding shift while pressing left/right and I don't see such behavior on version 2.32.1.
![selection_of_frames](https://user-images.githubusercontent.com/1296768/125512453-fc42f102-c55b-4386-bd52-cf787ef826da.gif)

**Comment by zoulja** [comment]
Not sure what and how goes wrong but I observe this issue every time 😔

**Comment by pawlos** [comment]
@zoulja you do anything different than on the above video?

**Comment by NickeManarin** [comment]
There's something wrong with the virtualization of the list (as seen in another issue ticket).
Maybe it's the same reason behind the bug that you people found.

**Comment by zoulja** [comment]
> @zoulja you do anything different than on the above video?

Nope, scenario is the same.
And it seems in some cases backward selection works better than forward

**Comment by NickeManarin** [comment]
@zoulja Can you try it with v2.34?

**Comment by zoulja** [comment]
Hello @NickeManarin!
It seems to be ok now, thanks a lot for your efforts!
