### ISSUE TITLE
Keystrokes clash with progressbar

### ISSUE THREAD

**Issue by sirtet** [NickeManarin/ScreenToGif#94]
![image](https://cloud.githubusercontent.com/assets/3509308/23261766/214a206e-f9d8-11e6-9d85-34bcee005ae0.png)
There's no way to add a margin, so it would not clash.
Nicest solution would be, it's auto-detected...
easyer to do would be a H and V margin setting.

**Comment by NickeManarin** [comment]
A external margin indeed is the easiest.

**Comment by NickeManarin** [comment]
I added a margin to that element and it's configurable. This will be available with v2.12.
