### ISSUE TITLE
Shift+End will not select the last two frames

### ISSUE THREAD

**Issue by rogeriodec** [NickeManarin/ScreenToGif#942]
1) Open a recent project in the editor (or create and record a new one)
2) The 1st frame will be selected as default. Press Shift+End to select to the last frame

![image](https://user-images.githubusercontent.com/11199752/125631021-19be578f-bf48-4b0b-b6f4-95147057a39a.png)

**Comment by NickeManarin** [comment]
Hi, I could reproduce this issue.
It only happens once per execution.

**Comment by NickeManarin** [comment]
I fixed this issue (or at least it's not happening for me anymore after my changes).

**Comment by rogeriodec** [comment]
Here the problem remains the same, at least with 2.33.1

**Comment by NickeManarin** [comment]
Yeah, I'm going to launch v2.34 in a few minutes.

**Comment by NickeManarin** [comment]
@rogeriodec It's available now.

**Comment by rogeriodec** [comment]
Solved. Thanks.
