### ISSUE TITLE
Editor doesn't remember its last used screen (when maximized, with dual-monitor)

### ISSUE THREAD

**Issue by fireattack** [NickeManarin/ScreenToGif#952]
I have two monitors. They are attached to each other horizontally. My main screen (no.2) is on the right.
![image](https://user-images.githubusercontent.com/4130991/126726112-aae00185-f2de-45ef-b671-b626c75e3045.png)

When I quit the editor on my main (right) screen **maximized**, and restart it, it will start on the left screen maximized.

Exiting the editor in window mode doesn't have this issue, and can start at the correct last used position (and size).

**Comment by NickeManarin** [comment]
Done, it will be available with v2.33.1
