### ISSUE TITLE
How to manually check updates?

### ISSUE THREAD

**Issue by wenfangdu** [NickeManarin/ScreenToGif#954]
If I turn off "Check for updates on startup", is there a way to manually check updates?

**Comment by pawlos** [comment]
From what I can see there's no such option ATM. I guess it could a nice feature to have a 'Check for updates' button on About screen.

**Comment by MaledongGit** [comment]
HI all:

I'm interested in it and fixing it now, but I wonder to know how to change my version of app locally so as to a "upgration test" to verify my logic is right.....?

**Comment by MaledongGit** [comment]
@NickeManarin

**Comment by pawlos** [comment]
@MaledongGit There's already a piecie of code that does the check `CheckForUpdates` - just use it. It might require to be extracted to be able to reuse it in the right place.

**Comment by MaledongGit** [comment]
@pawlos : Thanks, but it's not only to use CheckForUpdates, that's the inner logic codes we need to check updates and decide whether to download or not. What we need in fact is a Download dialog if we need, just like startup. Here's my feat.
