### ISSUE TITLE
[Feature Request] Set the color for click highlights

### ISSUE THREAD

**Issue by claudiojs** [NickeManarin/ScreenToGif#956]
Currently there is no possibility to set a custom color for left and right clicks. This option would be great!

**Comment by NickeManarin** [comment]
Which version are you using? That feature was implemented recently.

**Comment by claudiojs** [comment]
> Which version are you using? That feature was implemented recently.
2.33.1 (I've downloaded and installed the program today). I've searched for this option more than once and I didn't find it (maybe my mistake, could you please tell me where I can change the colors?).

**Comment by pawlos** [comment]
@claudiojs You can either set the colors directly when you add mouse clicks in the Editor via Image -> Mouse clicks. On the side panel you have the ability to pick colors.
![image](https://user-images.githubusercontent.com/1296768/127215511-455899b7-5967-41a3-b343-8ab23fcc3d92.png)

Or if you use automatic tasks, then go to Options -> Tasks and hit "Edit selected item" (selecting first the Mouse clicks task) and you will be able to edit the colors for that automatic task. 
![image](https://user-images.githubusercontent.com/1296768/127215631-17c1e642-6e91-493d-8a4a-8b203eb015b8.png)

**Comment by claudiojs** [comment]
@pawlos thank you very much!
