### ISSUE TITLE
Record Keystrokes and Record Mouse have very different UI

### ISSUE THREAD

**Issue by sirtet** [NickeManarin/ScreenToGif#96]
They seem to be very similar features, but the settings are in completely different places...

I guess there are technical reasons for that, but
should/could this not be made similar?

To have mouse in settings seems more comfortable, as it does not need to be applied after the recording. That saves a lot of time.
Same would go for the progressbar, but obviously this can not be done before the recording is ended.

**Comment by NickeManarin** [comment]
I want to add more options for customization for the Cursor recorder too, to be a pair for the KeyStrokes feature. So my plan is to move the options to add cursor and mouse clicks feature to the editor.

**Comment by nzbart** [comment]
My vote would be to be able to add mouse clicks as a post-recording editing feature like keystrokes, so I can just record my screencast and then later decide whether to add visible mouse clicks or not. This means I don't have to think too much in advance or potentially have to come back and re-record the screencast if I get a setting wrong.

**Comment by NickeManarin** [comment]
@nzbart Done.
