### ISSUE TITLE
Cannot save as gif files with "Gifski"

### ISSUE THREAD

**Issue by MaledongGit** [NickeManarin/ScreenToGif#962]
When choosing the "Gifski" formation to save the recorded snippets to gif, an error dialog pops up:

Reproduction (Follow the step of numbers from 1 to 4):
![Err](https://user-images.githubusercontent.com/52018749/128280855-19c98271-fe07-4291-9fd1-dafb3db68186.JPG)

![ErrMsg](https://user-images.githubusercontent.com/52018749/128280912-5f2686a3-ad7b-43af-b0c1-fb5b9ddf96b5.png)

I've also attached some logs to detect with:

[21_08_04.txt](https://github.com/NickeManarin/ScreenToGif/files/6935500/21_08_04.txt)

**Comment by MaledongGit** [comment]
Ref: https://github.com/NickeManarin/ScreenToGif/issues/462
I'll check whether the current platform belongs to x86 / x64 to decide whether we need it or not....
I'll fix it if free.

**Comment by pein0saga** [comment]
If you located to  Gifski.exe instead of Gifski.dll, this would happen.
