### ISSUE TITLE
Can't cancel frames processing right after capturing a gif

### ISSUE THREAD

**Issue by DmitriyYukhanov** [NickeManarin/ScreenToGif#971]
Hey there!

Sometimes I would like to cancel recorded frames processing which happens right after capture. I see red cross icon, press it but it still keeps processing and cancels only when processing is finished.

I'm using version 2.33.1

**Comment by pawlos** [comment]
I'll have a look at this

**Comment by pawlos** [comment]
What I could find that was not working was that the first processing action didn't update the UI (so no progress - fixed that) but it was correctly responding to the cancel. What was not working correctly was in the automated tasks (mouse click, key stokes, etc.) and I've added a check to stop them when the request was made.
