### ISSUE TITLE
Is this project later considered to support linux?

### ISSUE THREAD

**Issue by wordhui** [NickeManarin/ScreenToGif#975]

**Comment by MaledongGit** [comment]
@wordhui: There's a plan about this by refactoring it with .NET 5 on Linux, please see: https://github.com/NickeManarin/ScreenToGif/issues/579

**Comment by NickeManarin** [comment]
Perhaps with .NET MAUI once it's released and Linux support is added.

**Comment by NickeManarin** [comment]
Perhaps with .NET MAUI once it's released and linux support is added.

**Comment by itpropro** [comment]
Hey @NickeManarin,
did you ever reconsider releasing it for Linux? This application is actually one of the very few ones I am missing after switching to Linux and although there are some tools that support a little feature here and there, there is nothing that comes close to the full package that is ScreenToGif.
