### ISSUE TITLE
"New release available" text doesn't update when changing language

### ISSUE THREAD

**Issue by Leftiezi** [NickeManarin/ScreenToGif#978]
I noticed the blue underlined text notifying the user of a new release in the startup window does not change when switching to a different language. It instead remains in the language that the application was originally started in.

Reproduction: 
-Open app in non-latest version (I used 2.33) so that a new release will be found.
-Change language through the Options window

Example: Started the app in Greek and switched to English
![stgissue](https://user-images.githubusercontent.com/25777792/131846133-614cf372-4327-44f9-af60-11a4c0e94977.png)

**Comment by NickeManarin** [comment]
Thanks, it was fixed.
