### ISSUE TITLE
When having two editors open at the same time, length gets overwritten

### ISSUE THREAD

**Issue by hediet** [NickeManarin/ScreenToGif#980]
When having two editors open at the same time, the length of the gif recorded later overwrites the length of the earlier gif :(
    
Steps:
* Open ScreenToGif
* Record something
* Open the editor  (and keep it open)
* Open a new instance of ScreenToGif
* Record something (longer or shorter)
* Open the editor
* Observe that the recording in the previously opened editor now has the same length as the new recording. When the new recording is longer, out of bound exceptions are thrown when editing the added frames.

**Comment by NickeManarin** [comment]
Hi, thanks for the feedback! 
Looks like the editor instances are sharing unwanted data.
