### ISSUE TITLE
[Question] Enable the keystrokes

### ISSUE THREAD

**Issue by Tox86** [NickeManarin/ScreenToGif#99]
Hi that is my question, i can't enable this option.

**Comment by NickeManarin** [comment]
The keystroke recording isn't a enable/disable feature yet. It always record the keystrokes when recording the screen.

To apply the keystrokes to the animation, you can open the  Image tab > Keystrokes. It only works if your recording has any keystrokes.

**Comment by NickeManarin** [comment]
Did you manage to apply the keystrokes to your recording? If so, please close this question.
If not, I can give further assistance.

**Comment by math2001** [comment]
> Did you manage to apply the keystrokes to your recording?

How do you do that? I guess I need to update to `2.7` (I'm on the `2.4` right now).
