### ISSUE TITLE
save error v2.34

### ISSUE THREAD

**Issue by szmabcd** [NickeManarin/ScreenToGif#993]
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at ScreenToGif.ImageUtil.ImageMethods.PaintTransparentAndCut(ExportProject project, Color chroma, Int32 taskId, CancellationTokenSource tokenSource)
   at ScreenToGif.Util.EncodingManager.<Encode>d__27.MoveNext()

![image](https://user-images.githubusercontent.com/38176269/135451456-0788f1e4-a638-4fd4-b9e6-d5fdeeb1d5ef.png)

**Comment by NickeManarin** [comment]
Can you share with me the project?

**Comment by szmabcd** [comment]
请问下如何分享项目给你？项目怎么分享？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NickeManarin/ScreenToGif"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月30日(星期四) 晚上8:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NickeManarin/ScreenToGif] save error v2.34 (#993)





 
Can you share with me the project?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NickeManarin** [comment]
1) 
![image](https://user-images.githubusercontent.com/14798947/135476420-a1e85d62-5681-4c4d-8082-69007ad98d0a.png)

2) 
![image](https://user-images.githubusercontent.com/14798947/135476467-0a8daaf3-aa0c-4361-bb49-5fff005cbf11.png)

3)
![image](https://user-images.githubusercontent.com/14798947/135476572-096f3bf4-2915-42e1-b28e-fe107a8bf928.png)

**Comment by szmabcd** [comment]
请尽快解决，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NickeManarin/ScreenToGif"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月30日(星期四) 晚上10:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NickeManarin/ScreenToGif] save error v2.34 (#993)





  

  

  

  

  

  

 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NickeManarin** [comment]
You didn't send me the project file.

**Comment by szmabcd** [comment]
我已发送过了


 
---Original---
From: "Nicke ***@***.***&gt;
Date: 2021/11/8 00:02:09
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [NickeManarin/ScreenToGif] save error v2.34 (#993)




 
You didn't send me the project file.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by NickeManarin** [comment]
Closing as duplicated.
